### PR TITLE
DHFPROD-7861: Irrelevant Delete feature when adding thresholds, rules…

### PR DESCRIPTION
**Pull request by AkshayBajajML**
#### Checklist: 
```diff
- Note: do not change the below
```

-  ##### Owner:

- [x] JIRA_ID included in all the commit messages
- [x] PR title is in the format JIRA_ID:Title
- [x] Rebase the branch with upstream
- [x] Squashed all commits into a single commit
- [x] Code passes ESLint tests
- [x] Added Tests
- [x] Run UI tests
  

- ##### Reviewer:

- [x] Reviewed Tests

### CODE REVIEW

**Comment by AkshayBajajML** [comment]
UI changes reviewed and approved by @jbelonoj .
PR is ready to be reviewed.

**Review by briantang — CHANGES_REQUESTED** [review]
Can we briefly add two lines to verify when the Trash icon is and is not there in all the respect .test RTL files.

**Comment by AkshayBajajML** [comment]
> Looks good! Can we briefly add two lines to verify when the Trash icon is and is not there in all the respective .test RTL files?

@briantang Thanks for the comment.. Added missing tests and PR is ready to be reviewed again

**Review by briantang — APPROVED** [review]
Nice!

**Review by xnikhil08 — APPROVED** [review]

**Pull request merged**
