### PR TITLE
DHFPROD-5502: Clicking on the hostname to get to the export modal is …

### PR DESCRIPTION
**Pull request by briantang**
…not intuitive

### Description

- Service name in header now replaced by info icon
- Info icon shows hub version, marklogic version, and service name on hover
- Added copy icon and 'copy to clipboard' functionality on service name in system info modal (from clicking info icon)
- Included minor cypress test adjustments
- Ran ESLint on affected files.

#### Checklist: 
```diff
- Note: do not change the below
```

-  ##### Owner:

- [x] JIRA_ID included in all the commit messages
- [x] PR title is in the format JIRA_ID:Title
- [x] Rebase the branch with upstream
- [x] Squashed all commits into a single commit
- [x] Added Tests
  

- ##### Reviewer:

- [x] Reviewed Tests

### CODE REVIEW

**Comment by briantang** [comment]
Design verified by UX, video here: https://drive.google.com/file/d/1HKBnSMCzVC92Wm9BQqScAoinaAiNuA94/view?usp=sharing

**Review by wooldridge — CHANGES_REQUESTED** [review]
Minor consistency issue, we use "Version" in the mouseover popup and "version" in the dialog. I think it should be capitalized both places.

**Comment by briantang** [comment]
> Minor consistency issue, we use "Version" in the mouseover popup and "version" in the dialog. I think it should be capitalized both places.

Fixed, thanks for catching that @wooldridge.

**Review by wooldridge — APPROVED** [review]
Looks good, I'm seeing unit tests pass.

**Review by timur-isangulov — APPROVED** [review]

**Review by brucean52 — APPROVED** [review]

**Pull request merged**
