### PR TITLE
DHFPROD-5941: Fix for creating structure types with property names, D…

### PR DESCRIPTION
**Pull request by brucean52**
…HFPROD-5560: updated save entities text

#### Checklist: 
```diff
- Note: do not change the below
```

-  ##### Owner:

- [x] JIRA_ID included in all the commit messages
- [x] PR title is in the format JIRA_ID:Title
- [x] Rebase the branch with upstream
- [x] Squashed all commits into a single commit
- [x] Added Tests
  

- ##### Reviewer:

- [x] Reviewed Tests

### CODE REVIEW

**Review by xnikhil08 — APPROVED** [review]
Works as expected.

**Comment by timur-isangulov** [comment]
I see 500 error when using the case from DHFPROD-5941. https://drive.google.com/file/d/1TuZ_2oKXrhenDhybWrHgULU3rPRZgJFh/view

**Review by timur-isangulov — CHANGES_REQUESTED** [review]
I still see 500 error using the case from the DHFPROD-5941. https://drive.google.com/file/d/1TuZ_2oKXrhenDhybWrHgULU3rPRZgJFh/view

**Review by xnikhil08 — CHANGES_REQUESTED** [review]
I am also getting the 500 error in the scenario mentioned by @timur-isangulov. Rest other validation errors(Given in the ticket https://project.marklogic.com/jira/browse/DHFPROD-5941) seems to be showing up fine.
The 500 error comes only when you use same name for both the property and the associated structured property and then hit Save All.

**Comment by brucean52** [comment]
Add fix and e2e test case for issue found.

**Review by timur-isangulov — APPROVED** [review]

**Review by xnikhil08 — APPROVED** [review]

**Pull request merged**
