### PR TITLE
DHFPROD-9416: Fixing graph in modeling when properties include -

### PR DESCRIPTION
**Pull request by aniamy**
#### Checklist: 
```diff
- Note: do not change the below
```

- ##### Owner:

- [x] JIRA_ID included in all the commit messages
- [x] PR title is in the format JIRA_ID:Title
- [x] Rebase the branch with upstream
- [x] Squashed all commits into a single commit
- [x] Code passes ESLint tests
- [x] Added Tests
  

- ##### Reviewer:

- [x] Reviewed Tests
- [x] Added to Release Wiki

### CODE REVIEW

**Comment by ngodugu-marklogic** [comment]
@aniamy I tried to create entity, add property with "-", edit and then delete it, the right panel shows no data even when I am able to see the property in graph view. Can you please take a look.

https://user-images.githubusercontent.com/74939216/196830236-0f9512bb-eea9-41aa-baeb-6753e8d2bf03.mov

**Review by ngodugu-marklogic — CHANGES_REQUESTED** [review]
@aniamy  I tried to create entity, add property with "-", edit and then delete it, the right panel shows no data e

https://user-images.githubusercontent.com/74939216/196831240-35fff270-9fc3-48d5-b605-39025f4f8134.mov

ven when I am able to see the property in graph view. Can you please take a look.

**Comment by aniamy** [comment]
@xnikhil08 Nice bug you found! I can reproduce it in nightly as well. Does not seem related to the scope of this ticket. Can you open a new ticket?

**Review by ngodugu-marklogic — APPROVED** [review]
Created https://project.marklogic.com/jira/browse/DHFPROD-9596 for the issue reported. Rest Looks good to me

**Review by iveyMarklogic — APPROVED** [review]

**Review by lucianaabc-ml — APPROVED** [review]

**Pull request merged**
