### PR TITLE
DHFPROD-6316: Inconsistent/incorrect UI when no access for Match and …

### PR DESCRIPTION
**Pull request by AkshayBajajML**
#### Checklist: 
```diff
- Note: do not change the below
```

-  ##### Owner:

- [x] JIRA_ID included in all the commit messages
- [x] PR title is in the format JIRA_ID:Title
- [x] Rebase the branch with upstream
- [x] Squashed all commits into a single commit
- [x] Added Tests
  

- ##### Reviewer:

- [x] Reviewed Tests

### CODE REVIEW

**Comment by AkshayBajajML** [comment]
Added pending tests reported in https://project.marklogic.com/jira/browse/DHFPROD-6294.

**Review by briantang — APPROVED** [review]
Looks good. Seeing tests pass locally as well.

**Review by wooldridge — CHANGES_REQUESTED** [review]
Nice work! One minor issue, the Add New tooltip appears at the top for Curate but at the bottom for Load. Can we make those consistent? What does UX prefer? I think the bottom is preferable since at the top the tooltip interferes with clicking the tabs. I've added a note about this and a screencap in the ticket. FYI: @jbelonoj

**Review by wooldridge — APPROVED** [review]
Looks great, here's a screencast of the Add New tooltips:
https://drive.google.com/file/d/1___QVoJQBQTwzfOPLExVQ7HpnfEreAyQ/view

In discussing with @AkshayBajajML and @jbelonoj, there are issues with pacing the tooltip at the bottom for the Curate cards so we're putting them consistently at the top and Akshay has done a nice job with the CSS so that everything is centered. Test pass.

**Review by briantang — APPROVED** [review]

**Pull request merged**
