### PR TITLE
DHFPROD-7913: Hovering over entity type shouldn't show placeholder text

### PR DESCRIPTION
**Pull request by AkshayBajajML**
#### Checklist: 
```diff
- Note: do not change the below
```

-  ##### Owner:

- [x] JIRA_ID included in all the commit messages
- [x] PR title is in the format JIRA_ID:Title
- [x] Rebase the branch with upstream
- [x] Squashed all commits into a single commit
- [x] Code passes ESLint tests
- [x] Added Tests
- [x] Run UI tests
  

- ##### Reviewer:

- [x] Reviewed Tests

### CODE REVIEW

**Review by briantang — CHANGES_REQUESTED** [review]
Seeing a related RTL test failure in graph-view.test

Screen Shot 2021-09-29 at 10 31 22 PM

**Comment by AkshayBajajML** [comment]
> Seeing a related RTL test failure in graph-view.test
> 
> Screen Shot 2021-09-29 at 10 31 22 PM

All tests pass now

**Comment by xnikhil08** [comment]
@AkshayBajajML - This needs a rebase.

**Comment by AkshayBajajML** [comment]
> @AkshayBajajML - This needs a rebase.

Done!!

**Review by briantang — CHANGES_REQUESTED** [review]
Seeing empty tooltips when the page is first loaded. Maybe it is empty when it should be null sometimes?

https://watch.screencastify.com/v/5n46hry0feOigytwRotG

**Review by wooldridge — CHANGES_REQUESTED** [review]
I'm seeing the same thing:

https://watch.screencastify.com/v/RZdl115BCIuvKZIRThaj

You can fix by removing the always-defined title property definition and adding the following before tmp is returned:
```
        if (getDescription(e.entityName) && getDescription(e.entityName).length > 0) {
          tmp.title = getDescription(e.entityName);
        }
```

**Comment by AkshayBajajML** [comment]
> Seeing empty tooltips when the page is first loaded. Maybe it is empty when it should be null sometimes?
> 
> https://watch.screencastify.com/v/5n46hry0feOigytwRotG

Fixed it

**Comment by AkshayBajajML** [comment]
> I'm seeing the same thing:
> 
> https://watch.screencastify.com/v/RZdl115BCIuvKZIRThaj
> 
> You can fix by removing the always-defined title property definition and adding the following before tmp is returned:
> 
> ```
>         if (getDescription(e.entityName) && getDescription(e.entityName).length > 0) {
>           tmp.title = getDescription(e.entityName);
>         }
> ```

Awesome!! That worked

**Review by briantang — APPROVED** [review]
Looks good now.

**Review by xnikhil08 — APPROVED** [review]
Looks good now.

**Review by wooldridge — APPROVED** [review]

**Pull request merged**
