### PR TITLE
DHFPROD-5800: Info Popup: Missing keyboard nav to copy functionality

### PR DESCRIPTION
**Pull request by amejiaq**
#### Checklist: 
```diff
- Note: do not change the below
```

- ##### Owner:

- [x] JIRA_ID included in all the commit messages
- [x] PR title is in the format JIRA_ID:Title
- [x] Rebase the branch with upstream
- [x] Squashed all commits into a single commit
- [n/a] Added Tests
- [x] Ran cypress tests on firefox locally
  

- ##### Reviewer:

- [x] Reviewed Tests
- [n/a] Added to Release Wiki

### CODE REVIEW

**Review by littlecherro — APPROVED** [review]

**Comment by aniamy** [comment]
@amejiaq I can open the dropdowns in"Clear All User Data" but I cannot select options with keyboard navigation only.
Also check with @littlecherro I believe we might also have some UX improvements to identify where the focus it. (Very subtle in the buttons but hard to notice on the radiob buttons, the copy icon amd the X)

**Comment by amejiaq** [comment]
> @amejiaq I can open the dropdowns in"Clear All User Data" but I cannot select options with keyboard navigation only. Also check with @littlecherro I believe we might also have some UX improvements to identify where the focus it. (Very subtle in the buttons but hard to notice on the radiob buttons, the copy icon amd the X)

Fixed 🛠

**Comment by aniamy** [comment]
Talked with Andres. Is looking better but there seems to be an issue accessing the tooltips and marking the dropdown option that is being selected/targeted.

**Review by aniamy — APPROVED** [review]

**Review by briantang — APPROVED** [review]
Looks good.

**Pull request merged**
