### PR TITLE
DHFPROD-10122: Latest Palamida Vulnerabilities Fix

### PR DESCRIPTION
**Pull request by littlecherro**
### Description

OLD:
https://jenkins.marklogic.com/view/Security_Palamida/job/palamida-branch-dhf/18/artifact/ML-DHF-REPORT_on_DHFPROD-10122.json/*view*/

vs

NEW:
https://jenkins.marklogic.com/view/Security_Palamida/job/palamida-branch-dhf/19/artifact/ML-DHF-REPORT_on_DHFPROD-10122.json/*view*/

The vulnerabilities are at the bottom of the json file under "vulnerabilities". If you check the link you would notice there's none.

#### Checklist: 
```diff
- Note: do not change the below
```

- ##### Owner:

- [x] JIRA_ID included in all the commit messages
- [x] PR title is in the format JIRA_ID:Title
- [x] Rebase the branch with upstream
- [x] Squashed all commits into a single commit
- n/a Added Tests
- [x] Ran newly added/edited cypress tests on Firefox locally
  

- ##### Reviewer:

- n/a Reviewed Tests
- n/a Added to Release Wiki

### CODE REVIEW

**Review by Sanjeevani19 — COMMENTED** [review]
@littlecherro  Are we not using these libraries anywhere in our current code ?
We have to verify if any previous data hub versions are using this library ?

**Comment by littlecherro** [comment]
> @littlecherro Are we not using these libraries anywhere in our current code ? We have to verify if any previous data hub versions are using this library ?

@Sanjeevani19 It was odd to me too, but apparently not. The first run even tells you where its being used and its only on those NOTICE.txt. I also checked if there's any other project within the repo but no, at least v3.3.1 on the ui we have v4+.
I wanted to test if only deleting the mention of that bootstrap version fixes it and it does. You can check that on the second link.

**Comment by Sanjeevani19** [comment]
> > @littlecherro Are we not using these libraries anywhere in our current code ? We have to verify if any previous data hub versions are using this library ?
> 
> @Sanjeevani19 It was odd to me too, but apparently not. The first run even tells you where its being used and its only on those NOTICE.txt. I also checked if there's any other project within the repo but no, at least v3.3.1 on the ui we have v4+. I wanted to test if only deleting the mention of that bootstrap version fixes it and it does. You can check that on the second link.

So it means we are using version 4+ in our project right ? In that case we have to update the notice.txt file with that latest version

**Comment by littlecherro** [comment]
> > > @littlecherro Are we not using these libraries anywhere in our current code ? We have to verify if any previous data hub versions are using this library ?
> > 
> > 
> > @Sanjeevani19 It was odd to me too, but apparently not. The first run even tells you where its being used and its only on those NOTICE.txt. I also checked if there's any other project within the repo but no, at least v3.3.1 on the ui we have v4+. I wanted to test if only deleting the mention of that bootstrap version fixes it and it does. You can check that on the second link.
> 
> @littlecherro So it means we are using version 4+ in our project right ? In that case we have to update the notice.txt file with that latest version

Okay, perfect. I'll do that :) @Sanjeevani19

**Review by iveyMarklogic — APPROVED** [review]

**Pull request merged**
