### PR TITLE
DHFPROD-8252: Removing ant lib dependency from hub central repo

### PR DESCRIPTION
**Pull request by lucianaabc-ml**
#### Checklist: 
```diff
- Note: do not change the below
```

-  ##### Owner:

- [x] JIRA_ID included in all the commit messages
- [x] PR title is in the format JIRA_ID:Title
- [x] Rebase the branch with upstream
- [x] Squashed all commits into a single commit
- [x] Code passes ESLint tests
- [x] Added Tests
- [x] Run UI tests
  

- ##### Reviewer:

- [x] Reviewed Tests

### CODE REVIEW

**Review by Sanjeevani19 — COMMENTED** [review]
@lucianaabc-ml Looks like the build is failing on this PR https://jenkins.marklogic.com/blue/organizations/jenkins/Datahub_CI/detail/PR-6420/2/pipeline/, Please look into it

**Review by Sanjeevani19 — COMMENTED** [review]
@lucianaabc-ml Looks like the build is still failing, Could you please look into it ?

**Comment by lucianaabc-ml** [comment]
> @lucianaabc-ml Looks like the build is still failing, Could you please look into it ?

yes, the build will continue failing until all the ant components are removed, this prhttps://github.com/marklogic/marklogic-data-hub/pull/6423 still needs to be merged.

**Review by iveyMarklogic — DISMISSED** [review]

**Review by briantang — COMMENTED** [review]
@lucianaabc-ml These tests actually do not pass locally as well. The issue is that one of the packages we removed in this PR is causing the cascader dropdown to look entirely different, i.e. our cascader is dependent on something you removed to work properly. I think we need to find that particular package to solve this.

**Review by iveyMarklogic — APPROVED** [review]

**Review by yubiselmarklogic — APPROVED** [review]

**Review by Sanjeevani19 — APPROVED** [review]

**Pull request merged**
