### PR TITLE
DHFPROD-4308: add/modify test cases for mapping artifact api

### PR DESCRIPTION
**Pull request by hao1st**

### CODE REVIEW

**Comment by hao1st** [comment]
@rjrudin I planned creating test case before I knew you will ask it... 👍

**Comment by rjrudin** [comment]
Looks like something went amiss here - there are 112 commits in this now, think it needs to be rebased.

**Comment by hao1st** [comment]
@SameeraPriyathamTadikonda I did rebase and forcily pushed it in the last push b045e6a.  why said conflict here?

**Comment by SameeraPriyathamTadikonda** [comment]
Can I close this PR and Re-open a new one?

**Pull request closed without merging**
