### PR TITLE
DHFPROD-8013: Flow replacement

### PR DESCRIPTION
**Pull request by yubiselmarklogic**
#### Checklist: 
```diff
- Note: do not change the below
```

-  ##### Owner:

- [x] JIRA_ID included in all the commit messages
- [x] PR title is in the format JIRA_ID:Title
- [x] Rebase the branch with upstream
- [x] Squashed all commits into a single commit
- [x] Code passes ESLint tests
- [x] Added Tests
- [x] Run UI tests
  

- ##### Reviewer:

- [x] Reviewed Tests

### CODE REVIEW

**Review by iveyMarklogic — DISMISSED** [review]

**Review by briantang — CHANGES_REQUESTED** [review]
Looks good, but can the New Flow Dialog be thinner? The width looks much larger than before.

PR: 
Screen Shot 2021-11-04 at 2 54 00 PM

Nightly:
Screen Shot 2021-11-04 at 2 53 53 PM

**Comment by yubiselmarklogic** [comment]
@briantang done

**Review by iveyMarklogic — DISMISSED** [review]

**Comment by briantang** [comment]
@yubiselmarklogic Looks a lot better. Can we now also adjust the 'X' in the top right? It looks a little low and not sitting in the corner but below it.

Screen Shot 2021-11-05 at 10 18 59 AM

**Comment by yubiselmarklogic** [comment]
@briantang done

**Review by briantang — APPROVED** [review]
Looks good

**Review by iveyMarklogic — APPROVED** [review]

**Pull request merged**
