### PR TITLE
Docs develop

### PR DESCRIPTION
**Pull request by grechaw**
A couple of things to go into docs-develop for 3.1

### CODE REVIEW

**Comment by grechaw** [comment]
Hi @kcoleman-marklogic I've updated side nav and the content with two new commits here.  Please see what you think

**Comment by kcoleman-marklogic** [comment]
A couple minor nits in architecture.md I must have missed first time around (sorry). Otherwise it's fine. If you at least fix the 2nd bullet below, you can commit it as far as I'm concerned.

* Under "In General", 2 bullets end in a period, one doesn't. Pick one way.
* Under "Databases" and "Application Servers", I think the table markdown is wrong. They don't render properly. You're missing the leading and trialing pipes on each row.
* Under "REST Extensions", it says "Much of this code finds itself in REST API extensions". Sounds very existential. What does "finds itself" mean? "Is implemented as"? "Is driven by"?

**Comment by grechaw** [comment]
Too funny that third mistake is a Russian translation.  I didn't know I was vulnerable to that!

**Comment by grechaw** [comment]
Made edits, merging now.

**Pull request merged**
