### PR TITLE
DHFPROD-4358: UI: Hookup the middle-tier end point for upload project

### PR DESCRIPTION
**Pull request by hao1st**
https://project.marklogic.com/jira/browse/DHFPROD-4358

1. Fix button layout problem;
2. Make the upload button disable for unauthorized users;
3. Show warning message under the upload button
4. has a dependency on https://github.com/marklogic/marklogic-data-hub/pull/3639

### CODE REVIEW

**Comment by hao1st** [comment]
[datahub-project.zip](https://github.com/marklogic/marklogic-data-hub/files/4294172/datahub-project.zip)

@wooldridge @xnikhil08 The attached zip file works for me. Could you send me your zip file by email? I tried to reproduce and find the root causes.

**Comment by wooldridge** [comment]
FYI, I'm seeing the type error issue that is described here on my local build of this current branch: https://project.marklogic.com/jira/browse/DHFPROD-4568

(I can fix this locally but I hope we can understand/fix this soon.)

**Comment by wooldridge** [comment]
@hao1st, when I try to upload using the provide project .zip, I get a server error message:

https://drive.google.com/file/d/1gUGDjJMUPUKEllpKxaWj8U8RZVL6Tqir/view

In trying to do this several times, after unsuccessfully trying to upload, I've seen 1. the ML server crash and 2. the Data Hub UI asking me to reinstall upon logging in again.

**Comment by hao1st** [comment]
@wooldridge @xnikhil08 I just created a new PR for upload middle-tier enhancement. It should deal with different zip files.

**Comment by hao1st** [comment]
@wooldridge I've never seen the error before when I tried to upload. Please send me the one-ui server log if possible. thanks!

**Comment by bsrikan** [comment]
@hao1st  I am getting following error when trying to Upload a project. When uninstalling you are also removing the users and so the user is not available anymore in ML.
image

You might have tried to upload as an admin. Try using a user with data-hub-environment-manager role.

**Comment by hao1st** [comment]
@bsrikan I could not reproduce, and what user do you use to login? Did you use the latest develop branch?

**Comment by bsrikan** [comment]
> @bsrikan I could not reproduce, and what user do you use to login? Did you use the latest develop branch?

Create a user with data-hub-environment-manager role and try. Hope you are not using admin to test. If you create a user with just manage-admin and security roles directly in ML, then you wont run into this error, since the user.json file is not in the project. We cannot assume that users will be created directly in ML.

I am on latest develop with commits from this PR: 
image

**Comment by hao1st** [comment]
@bsrikan @wooldridge Now i can reproduce the problem when login as "data-hub-environment-manager-user" rather than "admin". The reason is that first we uninstall datahub (include roles and DH users) from ML database. The runas user "data-hub-environment-manager-use" will lose his roles (e.g. two important roles - manage-admin and security). @rjrudin @ryanjdew How do we deal with the situation? Actually you can run the testUploadProjectWithArchiveFolder in EnvironmentControllerTest to reproduce the problem without UI. I used "admin" to run the case, it works as expect. The following errors occur in the uninstall data hub phase. 

```
2020-03-11 23:39:48.062  INFO 12537 --- [           main] com.marklogic.mgmt.ManageClient          : Sending JSON POST request as user 'data-hub-environment-manager-user' (who should have the 'manage-admin' and 'security' roles) to path: /manage/v3
2020-03-11 23:39:48.067 ERROR 12537 --- [           main] c.m.mgmt.cma.ConfigurationManager        : Error occurred while sending POST request to /manage/v3; logging request body to assist with debugging: {}
2020-03-11 23:39:48.070  INFO 12537 --- [           main] c.m.a.c.s.DeployPrivilegesCommand        : Processing file: /var/folders/4j/fmt8dpg54_g48_hg1l29gck8k5tl91/T/one-ui-hub-project16706116241641571981/src/main/hub-internal-config/security/privileges/dhf-internal-data-hub.json
2020-03-11 23:39:48.074  INFO 12537 --- [           main] c.m.a.c.s.DeployPrivilegesCommand        : Processing file: /var/folders/4j/fmt8dpg54_g48_hg1l29gck8k5tl91/T/one-ui-hub-project16706116241641571981/src/main/hub-internal-config/security/privileges/dhf-internal-entities.json
2020-03-11 23:39:48.077  INFO 12537 --- [           main] c.m.a.c.s.DeployPrivilegesCommand        : Processing file: /var/folders/4j/fmt8dpg54_g48_hg1l29gck8k5tl91/T/one-ui-hub-project16706116241641571981/src/main/hub-internal-config/security/privileges/dhf-internal-mappings.json
2020-03-11 23:39:48.083  INFO 12537 --- [           main] c.m.a.c.s.DeployPrivilegesCommand        : Processing file: /var/folders/4j/fmt8dpg54_g48_hg1l29gck8k5tl91/T/one-ui-hub-project16706116241641571981/src/main/hub-internal-config/security/privileges/dhf-internal-trace-ui.json
2020-03-11 23:39:48.086  INFO 12537 --- [           main] c.m.a.c.s.DeployPrivilegesCommand        : Processing files in directory: /var/folders/4j/fmt8dpg54_g48_hg1l29gck8k5tl91/T/one-ui-hub-project16706116241641571981/src/main/ml-config/security/privileges
2020-03-11 23:39:48.086  INFO 12537 --- [           main] c.m.mgmt.cma.ConfigurationManager        : Checking to see if Configuration Management API is available at: /manage/v3
2020-03-11 23:39:48.086  INFO 12537 --- [           main] com.marklogic.mgmt.ManageClient          : Sending JSON POST request as user 'data-hub-environment-manager-user' (who should have the 'manage-admin' and 'security' roles) to path: /manage/v3
2020-03-11 23:39:48.092 ERROR 12537 --- [           main] c.m.mgmt.cma.ConfigurationManager        : Error occurred while sending POST request to /manage/v3; logging request body to assist with debugging: {}
2020-03-11 23:39:48.092  INFO 12537 --- [           main] c.m.a.c.s.DeployPrivilegesCommand        : Merging payloads that reference the same resource
2020-03-11 23:39:48.097  INFO 12537 --- [           main] c.m.mgmt.cma.ConfigurationManager        : Checking to see if Configuration Management API is available at: /manage/v3
2020-03-11 23:39:48.097  INFO 12537 --- [           main] com.marklogic.mgmt.ManageClient          : Sending JSON POST request as user 'data-hub-environment-manager-user' (who should have the 'manage-admin' and 'security' roles) to path: /manage/v3
2020-03-11 23:39:48.104 ERROR 12537 --- [           main] c.m.mgmt.cma.ConfigurationManager        : Error occurred while sending POST request to /manage/v3; logging request body to assist with debugging: {}
2020-03-11 23:39:48.106  INFO 12537 --- [           main] c.m.m.r.security.PrivilegeManager        : Checking for existence of resource: dhf-internal-data-hub
2020-03-11 23:39:48.106  INFO 12537 --- [           main] com.marklogic.mgmt.ManageClient          : Sending XML GET request as user 'data-hub-environment-manager-user' (who should have the 'manage-admin' and 'security' roles) to path: /manage/v2/privileges
2020-03-11 23:39:48.109 ERROR 12537 --- [           main] c.m.rest.util.MgmtResponseErrorHandler   : Logging HTTP response body to assist with debugging: {"errorResponse": 
  {"statusCode":403,
   "status":"Forbidden",
   "message":"403 Forbidden"
  }
}

```

**Comment by rjrudin** [comment]
Uninstalling any ML application as a user with roles that are included in that application is an invalid use case - that's impossible for us to support. An ML application should only be uninstalled as the admin user, or via some theoretical user that has the manage-admin/security roles but no roles that are part of the application being uninstalled. I say "theoretical user" because I don't think anyone creates a user like that, they just use the admin user to uninstall applications.

**Comment by hao1st** [comment]
@bsrikan What do you think, can we get the PR get merged at this time?

**Comment by bsrikan** [comment]
@hao1st unfortunately this PR isnt addressing the AC of the story. The story requires existing user configurations(flows,entities,mappings etc and probably all the settings under src/main/ml-config) to be replaced with those in the uploaded project. If uninstall is not the way, then we have to find another way to do it.

**Comment by hao1st** [comment]
@bsrikan Uninstallatiion works should be fine with "admin". Shannon modified the story and created another story which will address "Upload" authorized user. And also the PR is UI-related and future changes will be backend.

**Comment by bsrikan** [comment]
@hao1st fair enough. It still doesnt meet the AC.

1. Only admin user should be allowed to upload per recent updates. We still have the code in place which checks for manage-admin and security and so a user with data-hub-environment-manager role or manage-admin & security is still able to Upload
2. Upload says successful but it doesnt really upload user artifacts. I can pardon that for this PR since we have a bug open for this DHFPROD-4570

This maybe a PR for a JIRA ticket that is created for UI development, nonetheless the feature as a whole should work as expected. Merging this PR would still render the story incomplete.

**Comment by bsrikan** [comment]
@hao1st As mentioned today in the standup my earlier comment states, this is not done yet. A user with manage-admin & security is able to Upload. The requirement is that only an admin can Upload. So this PR cannot be merged until we take care of that requirement.

**Comment by bsrikan** [comment]
> @hao1st As mentioned today in the standup my earlier comment states, this is not done yet. A user with manage-admin & security is able to Upload. The requirement is that only an admin can Upload. So this PR cannot be merged until we take care of that requirement.

I pulled the latest changes and this looks ok now. My bad, sorry.

**Comment by bsrikan** [comment]
As an admin:
image


As a data-hub-environment-manager user who has manage-admin & security role:
image

**Pull request merged**
