### PR TITLE
DHFPROD-7961: View Instance tab in graph view

### PR DESCRIPTION
**Pull request by federicoRufrancosMarklogic**
#### Checklist: 
```diff
- Note: do not change the below
```

-  ##### Owner:

- [X] JIRA_ID included in all the commit messages
- [X] PR title is in the format JIRA_ID:Title
- [X] Rebase the branch with upstream
- [X] Squashed all commits into a single commit
- [X] Code passes ESLint tests
- [x] Added Tests
- [x] Run UI tests
  

- ##### Reviewer:

- [x] Reviewed Tests

### CODE REVIEW

**Comment by AkshayBajajML** [comment]
Needs rebase!

**Review by Sanjeevani19 — CHANGES_REQUESTED** [review]
@federicoRufrancosMarklogic Here are couple of issues I noticed.

- When clicking on a particular node, the instance tab details, uri doesn't match with the node selected
-  When a particular node is selected and instance icon is clicked, it navigates to detail view but the respective node info is not displayed in the detail view page,Also clicking on back to results throws an error
https://watch.screencastify.com/v/hh1z0p5hjJH5Iw8aFFnN

**Comment by federicoRufrancosMarklogic** [comment]
> @federicoRufrancosMarklogic Here are couple of issues I noticed.
> 
> * When clicking on a particular node, the instance tab details, uri doesn't match with the node selected
> * When a particular node is selected and instance icon is clicked, it navigates to detail view but the respective node info is not displayed in the detail view page,Also clicking on back to results throws an error
>   https://watch.screencastify.com/v/hh1z0p5hjJH5Iw8aFFnN

I had to mock uri as it's not returned by the backend. For both cases, the details page and the instance tab it showing the information from uri = "/json/orders/10248.json (you can see it in graph-explore-side-panel.tsx). 
This is the endpoint been updated: /api/entitySearch/graph?database=
Sorry do not specify at PR details.

**Review by Sanjeevani19 — COMMENTED** [review]
@federicoRufrancosMarklogic Still see undefined error when navigating back from detail page, Please look into it

**Comment by federicoRufrancosMarklogic** [comment]
> @federicoRufrancosMarklogic Still see undefined error when navigating back from detail page, Please look into it

Fixed, you can check it now if work

**Review by Sanjeevani19 — COMMENTED** [review]
- @federicoRufrancosMarklogic the property, value table columns seems to be so close together when compared to the table under snippet view. https://watch.screencastify.com/v/XdN9uQ0av2usolzid0A1
Please confirm if it is reviewed by UX, I can go ahead give an approval

- @xnikhil08 Please confirm if we have a separate story to tie up with actual end points, because this story only works with dummy data

**Comment by aniamy** [comment]
I'm adding the docURI as a response from the backend on this PR: https://github.com/marklogic/marklogic-data-hub/pull/6395 (currently in draft)
If this one is good and gets merged today I can wait and add the real data connection from the backen on PR 6395.

**Comment by xnikhil08** [comment]
> 

@federicoRufrancosMarklogic - The columns shouldn't overlap at all. It should behave more or less like the properties tab in the side panel in Modeling graph view.
@Sanjeevani19  - Just FYI.

**Review by xnikhil08 — CHANGES_REQUESTED** [review]
Since the backend code related PR(#6395 ) is already approved and might merge soon. It's better to use the actual endpoint instead of mock-data here.
@federicoRufrancosMarklogic @aniamy

**Comment by federicoRufrancosMarklogic** [comment]
@xnikhil08 @Sanjeevani19  mocked data was removed and code was updated with endpoint develop by Aniela
About table columns rendering, there are some issues with the new table that are been taken in consideration, I spoke with Mathias, and he is aware of column width and nested columns spacing error. There is a bug on defining first level expand, You'll notice that padding is much bigger than other nested children. Here he explain to me that there is a bug on renderRow method inside HCTable. So with all this I think we can continue with this ticket and merge it to develop. I take a look at Modeling and is behaving same way, the difference is that Modeling panel is wider and has more space to render columns  
The table's issue is this: 
https://project.marklogic.com/jira/browse/DHFPROD-8300

**Review by Sanjeevani19 — CHANGES_REQUESTED** [review]
@federicoRufrancosMarklogic I see that there are BE changes on this PR, So I did a clean build but I don't see related instance details for the selected node. Also when navigating to detail view it is being redirected to  table view https://watch.screencastify.com/v/thA41YLYWCKEwBdICwvf

**Comment by federicoRufrancosMarklogic** [comment]
> @federicoRufrancosMarklogic I see that there are BE changes on this PR, So I did a clean build but I don't see related instance details for the selected node. Also when navigating to detail view it is being redirected to snippet view https://watch.screencastify.com/v/thA41YLYWCKEwBdICwvf

Fix bug, I see that it's working the endpoint and is loading data inside the table? Did you run gradlew mlLoadModules?
Here is a video
https://watch.screencastify.com/v/HWyipVlJB3YEfMn4J2zG

**Comment by aniamy** [comment]
@Sanjeevani19 To confirm you have the latest backend changes check that the response of the graph search includes docURI for each node. If it is missing in your response the backend is not returning the latest data.

**Review by Sanjeevani19 — COMMENTED** [review]
@federicoRufrancosMarklogic Looks good, works as expected. 

When a node is selected and navigating back from detail view should selected node be highlighted, not sure if it a part of AC ?

**Comment by federicoRufrancosMarklogic** [comment]
@Sanjeevani19 I checked the ticket, no AC about highlight selected node
https://project.marklogic.com/jira/browse/DHFPROD-7961

**Review by Sanjeevani19 — APPROVED** [review]

**Review by AkshayBajajML — APPROVED** [review]
Good Work!!

**Comment by AkshayBajajML** [comment]
@federicoRufrancosMarklogic I see some backend and e2e test cases failing, not sure if these are intermittent ones.

**Comment by federicoRufrancosMarklogic** [comment]
@AkshayBajajML Thanks
I just restart test to see if it fails again. I don't see any relation with the functionality implemented

**Review by xnikhil08 — APPROVED** [review]

**Pull request merged**
