### PR TITLE
DHFPROD-10368: Unmerge nodes that aren't part of core search results

### PR DESCRIPTION
**Pull request by ryanjdew**
### Description

Also handles JSON null properties in the new JavaScript code and no longer applies the archived collection to merged documents that are merged multiple times.

#### Checklist: 
```diff
- Note: do not change the below
```

- ##### Owner:

- [x] JIRA_ID included in all the commit messages
- [x] PR title is in the format JIRA_ID:Title
- [x] Rebase the branch with upstream
- [x] Squashed all commits into a single commit
- [x] Added Tests
- N/A Ran newly added/edited cypress tests on Firefox locally
  

- ##### Reviewer:

- N/A Reviewed Tests
- N/A Added to Release Wiki

### CODE REVIEW

**Comment by ngodugu-marklogic** [comment]
@ryanjdew Now we are able to see unmerge option for all the merged documents but when I unmerge Nuno in video1 the unmerge doc do not show up. When I search Nuno I see those unmerge docs showing up but the relations do not show up. Later, In video2 I unmerge Drindy node but the merged node keep showing up with merge icon and it does not actually unmerge. Not sure if they are related to this PR.

https://github.com/marklogic/marklogic-data-hub/assets/74939216/5cef26b2-9a09-46d2-bfb5-7c5689b693fb

https://github.com/marklogic/marklogic-data-hub/assets/74939216/343f4e9f-9b6e-46a7-a1e3-77a5e084b046

**Comment by ryanjdew** [comment]
@ngodugu-marklogic When merges occur multiple times, it is expected that unmerge will only unmerge the last document merged into the record.

**Comment by ngodugu-marklogic** [comment]
@ryanjdew I re-validated the scenarios, I see Unmerge icon for Nuno when I search Drindy but unmerge doesn't work on Nuno node. Then when I unmerge Drindy it unmerges Data but there are relations missing for one of the node. When I search Nuno and unmerge, the Nunos are getting unmerged but again similar to Drindy there is one isolated Nuno node with missing relationships

https://github.com/marklogic/marklogic-data-hub/assets/74939216/3948bbdc-5f0b-4898-b9d1-cd5bbfa3c1a1
Screenshot 2023-07-20 at 11 43 21 PM

**Comment by aniamy** [comment]
@ngodugu-marklogic On the first video after Drindy is unmerged I believe that one Drindy node should have no relationships with any Nuno. MemberID is related to PrimaryInsureId.
That Drindy node has PrimaryInsureId as 1632255 and all relationships (Drindy and Nuno) are with 10045373723596171140 (which are the other 3 Drindy nodes). That's why all other Drindy nodes connect as memeberID to themselves. 

I haven't checked the data for Nuno yet. That was my plan for today. Could be something similar.

**Review by ngodugu-marklogic — APPROVED** [review]

**Pull request merged**
