### PR TITLE
DHFPROD-6589: Fix Failing explore cypress e2e test

### PR DESCRIPTION
**Pull request by ngodugu-marklogic**
#### Checklist: 
```diff
- Note: do not change the below
```

-  ##### Owner:

- [x] JIRA_ID included in all the commit messages
- [x] PR title is in the format JIRA_ID:Title
- [x] Rebase the branch with upstream
- [x] Squashed all commits into a single commit
- [x] Code passes ESLint tests
- [x] Added Tests
  

- ##### Reviewer:

- [x] Reviewed Tests

### CODE REVIEW

**Review by wooldridge — CHANGES_REQUESTED** [review]
I see a failed test when I run scenarios.queries.tsx on this PR branch, here is some of the stack trace:
```
<testsuite name="manage queries modal scenarios on detail page" timestamp="2021-01-27T07:32:45" tests="3" failures="1" time="49.041">
    <testcase name="manage queries modal scenarios on detail page verify manage queries modal visibility and removing query scenario on the detail page" time="20.543" classname="verify manage queries modal visibility and removing query scenario on the detail page">
      <failure message="Timed out retrying: `cy.click()` failed because this element is not visible:

`&lt;div class=&quot;exploreIcon ml-tooltip-container&quot; aria-label=&quot;tool-explore&quot; tabindex=&quot;-1&quot; style=&quot;color: rgb(55, 111, 99); cursor: pointer;&quot;&gt;...&lt;/div&gt;`

This element `&lt;div.exploreIcon.ml-tooltip-container&gt;` is not visible because it has CSS property: `position: fixed` and it&apos;s being covered by another element:

`&lt;div tabindex=&quot;-1&quot; class=&quot;ant-modal-wrap &quot; role=&quot;dialog&quot; aria-labelledby=&quot;rcDialogTitle0&quot;&gt;...&lt;/div&gt;`

Fix this problem, or use `{force: true}` to disable error checking.

https://on.cypress.io/element-cannot-be-interacted-with" type="CypressError"><![CDATA[CypressError: Timed out retrying: `cy.click()` failed because this element is not visible:

`<div class="exploreIcon ml-tooltip-container" aria-label="tool-explore" tabindex="-1" style="color: rgb(55, 111, 99); cursor: pointer;">...</div>`

This element `<div.exploreIcon.ml-tooltip-container>` is not visible because it has CSS property: `position: fixed` and it's being covered by another element:

`<div tabindex="-1" class="ant-modal-wrap " role="dialog" aria-labelledby="rcDialogTitle0">...</div>`

Fix this problem, or use `{force: true}` to disable error checking.

https://on.cypress.io/element-cannot-be-interacted-with
    at $Cy.ensureVisibility (http://localhost:8080/__cypress/runner/cypress_runner.js:161157:24)
    at runAllChecks (http://localhost:8080/__cypress/runner/cypress_runner.js:150120:14)
    at retryActionability (http://localhost:8080/__cypress/runner/cypress_runner.js:150163:16)
    at tryCatcher (http://localhost:8080/__cypress/runner/cypress_runner.js:10325:23)
    at Function.Promise.attempt.Promise.try (http://localhost:8080/__cypress/runner/cypress_runner.js:7599:29)
    at tryFn (http://localhost:8080/__cypress/runner/cypress_runner.js:165556:21)
    at whenStable (http://localhost:8080/__cypress/runner/cypress_runner.js:165594:12)
    at http://localhost:8080/__cypress/runner/cypress_runner.js:165089:16
    at tryCatcher (http://localhost:8080/__cypress/runner/cypress_runner.js:10325:23)
    at Promise._settlePromiseFromHandler (http://localhost:8080/__cypress/runner/cypress_runner.js:8260:31)
    at Promise._settlePromise (http://localhost:8080/__cypress/runner/cypress_runner.js:8317:18)
    at Promise._settlePromise0 (http://localhost:8080/__cypress/runner/cypress_runner.js:8362:10)
    at Promise._settlePromises (http://localhost:8080/__cypress/runner/cypress_runner.js:8442:18)
    at Promise._fulfill (http://localhost:8080/__cypress/runner/cypress_runner.js:8386:18)
    at http://localhost:8080/__cypress/runner/cypress_runner.js:10000:46
From Your Spec Code:
    at Context.eval (http://localhost:8080/__cypress/tests?p=cypress/integration/explore/scenarios.queries.tsx:803:87)]]></failure>
    </testcase>
    <testcase name="manage queries modal scenarios on detail page verify query selection from All Data view page, doesn&apos;t stay on card view" time="14.295" classname="verify query selection from All Data view page, doesn&apos;t stay on card view">
    </testcase>
    <testcase name="manage queries modal scenarios on detail page verify applying previously saved query scenario on the detail page" time="14.203" classname="verify applying previously saved query scenario on the detail page">
    </testcase>
  </testsuite>
</testsuites>
```

**Review by wooldridge — CHANGES_REQUESTED** [review]
@ngodugu-marklogic, I'm still seeing the same error when I run scenarios.queries:
```
  <testsuite name="manage queries modal scenarios on detail page" timestamp="2021-01-27T09:15:07" tests="3" failures="1" time="50.681">
    <testcase name="manage queries modal scenarios on detail page verify manage queries modal visibility and removing query scenario on the detail page" time="20.894" classname="verify manage queries modal visibility and removing query scenario on the detail page">
      <failure message="Timed out retrying: `cy.click()` failed because this element is not visible:

`&lt;div class=&quot;exploreIcon ml-tooltip-container&quot; aria-label=&quot;tool-explore&quot; tabindex=&quot;-1&quot; style=&quot;color: rgb(55, 111, 99); cursor: pointer;&quot;&gt;...&lt;/div&gt;`

This element `&lt;div.exploreIcon.ml-tooltip-container&gt;` is not visible because it has CSS property: `position: fixed` and it&apos;s being covered by another element:

`&lt;div tabindex=&quot;-1&quot; class=&quot;ant-modal-wrap &quot; role=&quot;dialog&quot; aria-labelledby=&quot;rcDialogTitle0&quot;&gt;...&lt;/div&gt;`

Fix this problem, or use `{force: true}` to disable error checking.

https://on.cypress.io/element-cannot-be-interacted-with" type="CypressError"><![CDATA[CypressError: Timed out retrying: `cy.click()` failed because this element is not visible:

`<div class="exploreIcon ml-tooltip-container" aria-label="tool-explore" tabindex="-1" style="color: rgb(55, 111, 99); cursor: pointer;">...</div>`

This element `<div.exploreIcon.ml-tooltip-container>` is not visible because it has CSS property: `position: fixed` and it's being covered by another element:

`<div tabindex="-1" class="ant-modal-wrap " role="dialog" aria-labelledby="rcDialogTitle0">...</div>`

Fix this problem, or use `{force: true}` to disable error checking.

https://on.cypress.io/element-cannot-be-interacted-with
    at $Cy.ensureVisibility (http://localhost:8080/__cypress/runner/cypress_runner.js:161157:24)
    at runAllChecks (http://localhost:8080/__cypress/runner/cypress_runner.js:150120:14)
    at retryActionability (http://localhost:8080/__cypress/runner/cypress_runner.js:150163:16)
    at tryCatcher (http://localhost:8080/__cypress/runner/cypress_runner.js:10325:23)
    at Function.Promise.attempt.Promise.try (http://localhost:8080/__cypress/runner/cypress_runner.js:7599:29)
    at tryFn (http://localhost:8080/__cypress/runner/cypress_runner.js:165556:21)
    at whenStable (http://localhost:8080/__cypress/runner/cypress_runner.js:165594:12)
    at http://localhost:8080/__cypress/runner/cypress_runner.js:165089:16
    at tryCatcher (http://localhost:8080/__cypress/runner/cypress_runner.js:10325:23)
    at Promise._settlePromiseFromHandler (http://localhost:8080/__cypress/runner/cypress_runner.js:8260:31)
    at Promise._settlePromise (http://localhost:8080/__cypress/runner/cypress_runner.js:8317:18)
    at Promise._settlePromise0 (http://localhost:8080/__cypress/runner/cypress_runner.js:8362:10)
    at Promise._settlePromises (http://localhost:8080/__cypress/runner/cypress_runner.js:8442:18)
    at Promise._fulfill (http://localhost:8080/__cypress/runner/cypress_runner.js:8386:18)
    at http://localhost:8080/__cypress/runner/cypress_runner.js:10000:46
From Your Spec Code:
    at Context.eval (http://localhost:8080/__cypress/tests?p=cypress/integration/explore/scenarios.queries.tsx:803:87)]]></failure>
    </testcase>
    <testcase name="manage queries modal scenarios on detail page verify query selection from All Data view page, doesn&apos;t stay on card view" time="15.221" classname="verify query selection from All Data view page, doesn&apos;t stay on card view">
    </testcase>
    <testcase name="manage queries modal scenarios on detail page verify applying previously saved query scenario on the detail page" time="14.566" classname="verify applying previously saved query scenario on the detail page">
    </testcase>
  </testsuite>
</testsuites>
```

**Comment by ngodugu-marklogic** [comment]
> @ngodugu-marklogic, I'm still seeing the same error when I run scenarios.queries:
> 
> ```
>   <testsuite name="manage queries modal scenarios on detail page" timestamp="2021-01-27T09:15:07" tests="3" failures="1" time="50.681">
>     <testcase name="manage queries modal scenarios on detail page verify manage queries modal visibility and removing query scenario on the detail page" time="20.894" classname="verify manage queries modal visibility and removing query scenario on the detail page">
>       <failure message="Timed out retrying: `cy.click()` failed because this element is not visible:
> 
> `&lt;div class=&quot;exploreIcon ml-tooltip-container&quot; aria-label=&quot;tool-explore&quot; tabindex=&quot;-1&quot; style=&quot;color: rgb(55, 111, 99); cursor: pointer;&quot;&gt;...&lt;/div&gt;`
> 
> This element `&lt;div.exploreIcon.ml-tooltip-container&gt;` is not visible because it has CSS property: `position: fixed` and it&apos;s being covered by another element:
> 
> `&lt;div tabindex=&quot;-1&quot; class=&quot;ant-modal-wrap &quot; role=&quot;dialog&quot; aria-labelledby=&quot;rcDialogTitle0&quot;&gt;...&lt;/div&gt;`
> 
> Fix this problem, or use `{force: true}` to disable error checking.
> 
> https://on.cypress.io/element-cannot-be-interacted-with" type="CypressError"><![CDATA[CypressError: Timed out retrying: `cy.click()` failed because this element is not visible:
> 
> `<div class="exploreIcon ml-tooltip-container" aria-label="tool-explore" tabindex="-1" style="color: rgb(55, 111, 99); cursor: pointer;">...</div>`
> 
> This element `<div.exploreIcon.ml-tooltip-container>` is not visible because it has CSS property: `position: fixed` and it's being covered by another element:
> 
> `<div tabindex="-1" class="ant-modal-wrap " role="dialog" aria-labelledby="rcDialogTitle0">...</div>`
> 
> Fix this problem, or use `{force: true}` to disable error checking.
> 
> https://on.cypress.io/element-cannot-be-interacted-with
>     at $Cy.ensureVisibility (http://localhost:8080/__cypress/runner/cypress_runner.js:161157:24)
>     at runAllChecks (http://localhost:8080/__cypress/runner/cypress_runner.js:150120:14)
>     at retryActionability (http://localhost:8080/__cypress/runner/cypress_runner.js:150163:16)
>     at tryCatcher (http://localhost:8080/__cypress/runner/cypress_runner.js:10325:23)
>     at Function.Promise.attempt.Promise.try (http://localhost:8080/__cypress/runner/cypress_runner.js:7599:29)
>     at tryFn (http://localhost:8080/__cypress/runner/cypress_runner.js:165556:21)
>     at whenStable (http://localhost:8080/__cypress/runner/cypress_runner.js:165594:12)
>     at http://localhost:8080/__cypress/runner/cypress_runner.js:165089:16
>     at tryCatcher (http://localhost:8080/__cypress/runner/cypress_runner.js:10325:23)
>     at Promise._settlePromiseFromHandler (http://localhost:8080/__cypress/runner/cypress_runner.js:8260:31)
>     at Promise._settlePromise (http://localhost:8080/__cypress/runner/cypress_runner.js:8317:18)
>     at Promise._settlePromise0 (http://localhost:8080/__cypress/runner/cypress_runner.js:8362:10)
>     at Promise._settlePromises (http://localhost:8080/__cypress/runner/cypress_runner.js:8442:18)
>     at Promise._fulfill (http://localhost:8080/__cypress/runner/cypress_runner.js:8386:18)
>     at http://localhost:8080/__cypress/runner/cypress_runner.js:10000:46
> From Your Spec Code:
>     at Context.eval (http://localhost:8080/__cypress/tests?p=cypress/integration/explore/scenarios.queries.tsx:803:87)]]></failure>
>     </testcase>
>     <testcase name="manage queries modal scenarios on detail page verify query selection from All Data view page, doesn&apos;t stay on card view" time="15.221" classname="verify query selection from All Data view page, doesn&apos;t stay on card view">
>     </testcase>
>     <testcase name="manage queries modal scenarios on detail page verify applying previously saved query scenario on the detail page" time="14.566" classname="verify applying previously saved query scenario on the detail page">
>     </testcase>
>   </testsuite>
> </testsuites>
> ```

**Comment by ngodugu-marklogic** [comment]
@wooldridge The script seems to go fine in my local and I am not sure how to reproduce this error.

**Comment by wooldridge** [comment]
@ngodugu-marklogic, OK, we can look into this tomorrow. Er, later today. :-)

**Comment by ngodugu-marklogic** [comment]
> @ngodugu-marklogic, OK, we can look into this tomorrow. Er, later today. :-)

Done fixed it!

**Review by Sanjeevani19 — APPROVED** [review]
Looks good,Tests passed in the latest build

**Review by timur-isangulov — APPROVED** [review]

**Comment by wooldridge** [comment]
I'm still seeing the same error when I run the following: 
`npm run cy:run -- --spec "cypress/integration/explore/scenarios.queries.tsx"`

**Review by wooldridge — APPROVED** [review]
Will approve for now to move things forward for the e2e fixes.

**Pull request merged**
