### PR TITLE
DHFPROD-10318: Start Time facet value does not reset after clearing he selection

### PR DESCRIPTION
**Pull request by amejiaq**
…he selection

#### Checklist: 
```diff
- Note: do not change the below
```

- ##### Owner:

- [x] JIRA_ID included in all the commit messages
- [x] PR title is in the format JIRA_ID:Title
- [x] Rebase the branch with upstream
- [x] Squashed all commits into a single commit
- [x] Added Tests
- [x] Ran newly added/edited cypress tests on Firefox locally
  

- ##### Reviewer:

- [x] Reviewed Tests
- [n/a] Added to Release Wiki

### CODE REVIEW

**Comment by littlecherro** [comment]
@amejiaq Hey! On explore page its working nice, but the same issue is also happening on monitor. Could you take a look?

**Comment by amejiaq** [comment]
> @amejiaq Hey! On explore page its working nice, but the same issue is also happening on monitor. Could you take a look?

Fixed! 🛠🛠

**Review by littlecherro — DISMISSED** [review]

**Review by ngodugu-marklogic — DISMISSED** [review]

**Review by vmendez-marklogic — CHANGES_REQUESTED** [review]
image


Please address these comments on monitorTableValidations

**Review by vmendez-marklogic — CHANGES_REQUESTED** [review]
image

It is failing exactly were the test was updated

**Review by aniamy — DISMISSED** [review]

**Review by vmendez-marklogic — APPROVED** [review]

**Review by aniamy — APPROVED** [review]

**Pull request merged**
