### PR TITLE
DHFPROD-2011: Refactor Step and Run Dialog to use FormBuilder

### PR DESCRIPTION
**Pull request by brucean52**

### CODE REVIEW

**Comment by alexsmr** [comment]
@brucean52 looks fine to merge. How many dialogs have you covered and many yet to go?

**Comment by brucean52** [comment]
Sure, I will work on the mastering dialogs next.

**Comment by wooldridge** [comment]
@alexsmr and @brucean52 fyi, dialogs in the mastering branch use form builder already, I think we're OK there. Current work is here:

https://github.com/marklogic/marklogic-data-hub/tree/feature/DHFPROD-1678-merging-config

What needs to be implemented across mastering in the add/edit dialogs is validation.

**Comment by ayuwono** [comment]
And I also, if I create a new flow with new steps, then click on Run, all the labels are missing. I'm not sure if it should work for Mock API only

**Comment by ayuwono** [comment]
The bugs mentioned by @wooldridge and me are fixed. I think you need to restart the PR on CI PR merge once its approved

**Comment by brucean52** [comment]
Closing this and opening a new PR that is based on latest develop.

**Pull request closed without merging**
