### PR TITLE
DHFPROD-7471: Show page size menu in mapping UI pagination (source an…

### PR DESCRIPTION
**Pull request by briantang**
…d entity)

### Description

- Added page size menu for source and entity tables
- https://drive.google.com/file/d/1ESfMQGWdA4ESc9ZFjRa4W6HT25oZbrgj/view

#### Checklist: 
```diff
- Note: do not change the below
```

-  ##### Owner:

- [x] JIRA_ID included in all the commit messages
- [x] PR title is in the format JIRA_ID:Title
- [x] Rebase the branch with upstream
- [x] Squashed all commits into a single commit
- [x] Code passes ESLint tests
- [x] Added Tests
  

- ##### Reviewer:

- [x] Reviewed Tests

### CODE REVIEW

**Review by wooldridge — CHANGES_REQUESTED** [review]
@briantang, this is great, thanks for getting it in co quickly.

I think we want to set hideOnSinglePage to false since, if we don't, there's no way for user to set the page size to 1 (to limit the rows to possibly improve performance with lots of deep properties) if, say, there are only 10 top level rows and the default is 20. @sbayatpur @jbelonoj

**Comment by briantang** [comment]
> @briantang, this is great, thanks for getting it in co quickly.
> 
> I think we want to set hideOnSinglePage to false since, if we don't, there's no way for user to set the page size to 1 (to limit the rows to possibly improve performance with lots of deep properties) if, say, there are only 10 top level rows and the default is 20. @sbayatpur @jbelonoj

Good point @wooldridge, pushed a fix.

**Review by Sanjeevani19 — APPROVED** [review]
Looks good, tests pass on pipeline. https://jenkins.marklogic.com/blue/organizations/jenkins/Datahub_CI/detail/PR-5775/2/pipeline

**Comment by briantang** [comment]
Updated pagination options size to "small", as requested by @wooldridge and @jbelonoj

**Review by wooldridge — APPROVED** [review]
Looks great, and I'm seeing the updated test pass locally.

**Review by Sanjeevani19 — APPROVED** [review]

**Review by AkshayBajajML — APPROVED** [review]

**Pull request merged**
