### PR TITLE
DHFPROD-8765: Add new concept class from Graph view in Modeling screen

### PR DESCRIPTION
**Pull request by xnikhil08**
### Description
Functionality to add concepts in the Modeling screen.
Unit and Integration tests added in RTL. E2E will be added as part of future stories when delete/edit capabilities will be added.

#### Checklist: 
```diff
- Note: do not change the below
```

- ##### Owner:

- [x] JIRA_ID included in all the commit messages
- [x] PR title is in the format JIRA_ID:Title
- [x] Rebase the branch with upstream
- [x] Squashed all commits into a single commit
- [x] Code passes ESLint tests
- [x] Added Tests
- [x] Ran cypress tests on firefox locally
  

- ##### Reviewer:

- [x] Reviewed Tests
- [x] Added to Release Wiki

### CODE REVIEW

**Comment by xnikhil08** [comment]
Will add reviewers after few test runs.

**Review by prolonMarkLogic — APPROVED** [review]
I created several concept classes and also tried validations related to them. everything looks well!

**Review by iveyMarklogic — APPROVED** [review]

**Review by iveyMarklogic — CHANGES_REQUESTED** [review]
@xnikhil08 I found an issue when you create a concept and try to go to the concept settings modal. The app crash on the explore when you click on the gear.

https://user-images.githubusercontent.com/88790827/178356527-bc17c2f0-627f-401e-a890-c7bdb2b3e89a.mp4

**Comment by xnikhil08** [comment]
> @xnikhil08 I found an issue when you create a concept and try to go to the concept settings modal. The app crash on the explore when you click on the gear.
> 
>  issue.mp4

@iveyMarklogic - Fixed the issue. Another review ?

**Review by iveyMarklogic — DISMISSED** [review]

**Review by prolonMarkLogic — APPROVED** [review]

**Review by prolonMarkLogic — DISMISSED** [review]

**Review by iveyMarklogic — DISMISSED** [review]

**Review by iveyMarklogic — APPROVED** [review]

**Review by prolonMarkLogic — APPROVED** [review]

**Review by Sanjeevani19 — COMMENTED** [review]
@xnikhil08 Looks like the Entity Modeling: Graph View test is failing in two subsequent runs, please look into that. Converting this to a draft until that is fixed

**Comment by xnikhil08** [comment]
@Sanjeevani19 - The graph edit related test is fixed and passed now. Can we merge this PR manually now, since the other failing tests seems to be intermittent ?

**Pull request merged**
