### PR TITLE
DHFPROD-2561: Add Collections field to all steps (Quickstart)

### PR DESCRIPTION
**Pull request by brucean52**

### CODE REVIEW

**Comment by wooldridge** [comment]
@brucean52 I'm not seeing collections saved correctly for a mapping, here are my steps:

1. Create a mapping step after ingestion ("TestIngest").
2. For mapping step, Source Collection: TestIngest, Target Entity: Customer.
3. Add additional target collection: AddedColl

Look at saved flow file:

"collections" : [ "AddedColl", "" ],

Expected: 

"collections" : [ "TestIngest", "Customer", "AddedColl" ],

**Comment by wooldridge** [comment]
@brucean52 I'm seeing something similar to the above mapping situation with mastering:

1. Create a mastering step ("TestMaster") after mapping ("TestMap").
2. For mapping step, Source Collection: TestMap, Target Entity: Customer.
3. Add additional target collection: AddedColl2

Look at saved flow file:

"collections" : [ "AddedColl2" ],

Expected:

"collections" : [ "TestMaster", "Customer", "AddedColl2" ],

**Comment by brucean52** [comment]
@ayuwono I'll look into fixing issue #1 in this PR. For #2, I think it can be a separate issue to handle duplicates and collection name validation.

**Comment by wooldridge** [comment]
@brucean52 I think we can handle most of the issues that @ayuwono brought up with judicious use of lodash, something like:

let collections = _.without(_.uniq(collections), "");

???

**Comment by brucean52** [comment]
@ayuwono @wooldridge I added the proper collections values to custom step, fixed editing, and fixed issue 1 and 2.

**Pull request merged**
