### PR TITLE
DHFPROD-5654: Load Table Not Accessible Using Keyboard

### PR DESCRIPTION
**Pull request by MSBrignoni**
### Description
Load Table Not Accessible Using Keyboard

#### Checklist: 
```diff
- Note: do not change the below
```

- ##### Owner:

- [x] JIRA_ID included in all the commit messages
- [x] PR title is in the format JIRA_ID:Title
- [x] Rebase the branch with upstream
- [x] Squashed all commits into a single commit
- [x] Added Tests
- [x] Ran cypress tests on firefox locally
  

- ##### Reviewer:

- [x] Reviewed Tests
- [x] Added to Release Wiki

### CODE REVIEW

**Review by littlecherro — COMMENTED** [review]
I think it should be nice to be able to change between tabs here. As of now i cant, even with arrow keys :(

image

**Review by littlecherro — CHANGES_REQUESTED** [review]
image

3 issues here: 

1.  there's an extra tab index in both "add step to..." and the select that doesnt do anything on ENTER or SPACE.
2. i cannot open the select with Enter and this is on the AC of similar tickets (not yours, check the one ivey's working on) but we should follow ONE criterion (maybe someone forgot to add it to yours? idk)
3. Popover should close when it lost focus or user TAB/SHIFT+TABS out of it not only on pressing ESC

**Comment by MSBrignoni** [comment]
> I think it should be nice to be able to change between tabs here. As of now i cant, even with arrow keys :(
> 
> image
 
Thanks, fixed. Was added the "Tab" behavior, but, note that when the button is in focus a new "tabIndex" is added by the library itself.

**Comment by MSBrignoni** [comment]
> image
> 
> 3 issues here:
> 
>     1. there's an extra tab index in both "add step to..." and the select that doesnt do anything on ENTER or SPACE.
> 
>     2. i cannot open the select with Enter and this is on the AC of similar tickets (not yours, check the one ivey's working on) but we should follow ONE criterion (maybe someone forgot to add it to yours? idk)
> 
>     3. Popover should close when it lost focus or user TAB/SHIFT+TABS out of it not only on pressing ESC

Thanks for the catch.
1) Removed.
2) 3) I added a new property, so, when the component dropdown is in focus, will open itself, is possible to use the "Tab", "arrows" and "Enter" to select between the elements, and close this using "Esc" to move with "Tab" to the next element (trash icon).

**Review by littlecherro — APPROVED** [review]

**Review by amejiaq — APPROVED** [review]

**Pull request merged**
