### PR TITLE
DHFPROD-5915: Deploying search options when model is created

### PR DESCRIPTION
**Pull request by rahulvudutala**
#### Checklist: 
```diff
- Note: do not change the below
```

-  ##### Owner:

- [x] JIRA_ID included in all the commit messages
- [x] PR title is in the format JIRA_ID:Title
- [x] Rebase the branch with upstream
- [x] Squashed all commits into a single commit
- [x] Added Tests
  

- ##### Reviewer:

- [x] Reviewed Tests

### CODE REVIEW

**Review by rjrudin — APPROVED** [review]

**Review by akshaysonvane — COMMENTED** [review]
After our discussion on this @rahulvudutala, I realized that since the explorer options are so integral to the app, I think we should generate and deploy them during data hub installation.

Currently, EntityManagerImpl (as part of LoadUserModulesCommand) will not deploy the options if there aren't any entities. I think we can get rid of this optimization and always generate and deploy the options.

An additional advantage here would be to not waste cycles in generating and deploying empty options when we hit the createModel endpoint.

@rjrudin, @ryanjdew do you see any issues if we always generate the options file?

**Comment by rjrudin** [comment]
@akshaysonvane That sounds good to me

**Comment by rahulvudutala** [comment]
will es.searchOptionsGenerate(model) generate search options when there are no entityModels?

**Comment by akshaysonvane** [comment]
> will es.searchOptionsGenerate(model) generate search options when there are no entityModels?

Yes, we can pass in an empty map.

**Review by ryanjdew — APPROVED** [review]

**Pull request merged**
