### PR TITLE
DHFPROD-5653: Help icons on forms aren't accessible using keyboard

### PR DESCRIPTION
**Pull request by AkshayBajajML**
Note: Testing strategy will be included in separate ticket.
#### Checklist: 
```diff
- Note: do not change the below
```

-  ##### Owner:

- [x] JIRA_ID included in all the commit messages
- [x] PR title is in the format JIRA_ID:Title
- [x] Rebase the branch with upstream
- [x] Squashed all commits into a single commit
- [x] Code passes ESLint tests
- N/A Added Tests
- [x] Run UI tests
  

- ##### Reviewer:

- N/A Reviewed Tests

### CODE REVIEW

**Comment by AkshayBajajML** [comment]
@wooldridge Fixed HCInput as well now.

**Comment by wooldridge** [comment]
@AkshayBajajML, in the Load dialog, I can select the Help icons under Advanced and open the tooltips (by pressing Enter), but the Help icons under Basic are not opening when selected. Screencast:

https://watch.screencastify.com/v/PEptTnw8NVKpALOQwqVq

**Comment by wooldridge** [comment]
As part of this PR, can we make this minor fix? See this line:

https://github.com/marklogic/marklogic-data-hub/blob/develop/marklogic-data-hub-central/ui/src/components/entities/merging/merging-card.tsx#L378

```
<HCTooltip id="delete-tootlip" text={"Delete"} placement="bottom">
```

Change `id="delete-tootlip"` to `id="delete-tooltip"`.

I don't see this id value currently referenced anywhere in the code, so it shouldn't affect anything.

**Comment by wooldridge** [comment]
@AkshayBajajML, in the following file:

https://github.com/marklogic/marklogic-data-hub/blob/32829148cd88692c889e7643dc8a76365ce8b995/marklogic-data-hub-central/ui/src/components/load/create-edit-load/create-edit-load.tsx

I see the following code (and the pattern I describe appears multiple places in that file):

```
<OverlayTrigger overlay={<Tooltip id="button-tooltip12">{keyboardNavigationTooltips.dropdownUserInfo}</Tooltip>} placement="left" show={selectTooltipVisible}>
    <span className={styles.toot} tabIndex={0} ref={srcFormatSelectRef} style={{width: "100%"}} onKeyDown={(e) => serviceNameKeyDownHandler(e, "sourceFormatSelect")}>
      <Select
        id="sourceFormat-select-wrapper"
        inputId="sourceFormat"
        tabIndex={0}
        placeholder="Enter source format"
        value={sourceFormatSelectOptions.find(oItem => oItem.value === srcFormat)}
        onChange={handleSrcFormat}
        isDisabled={props.canReadOnly && !props.canReadWrite}
        aria-label="sourceFormat-select"
        onBlur={sendPayload}
        options={sourceFormatSelectOptions}
        styles={reactSelectThemeConfig}
        className={styles.toot}
        onKeyDown={(e) => serviceNameKeyDownHandler(e, "sourceFormatSelectInner")}
      />
    </span>
  </OverlayTrigger>
```

I see `className={styles.toot}` on both the wrapping span and the Select element. Does it need to be both places? 

When I look at similar code in advanced-settings.tsx, I only see a className applied to the wrapping span, for example:

https://github.com/marklogic/marklogic-data-hub/blob/32829148cd88692c889e7643dc8a76365ce8b995/marklogic-data-hub-central/ui/src/components/advanced-settings/advanced-settings.tsx#L840

**Review by wooldridge — CHANGES_REQUESTED** [review]
See my comments.

**Comment by AkshayBajajML** [comment]
@wooldridge Thank you for your comments. I have addressed those and PR is ready for review for again

**Review by wooldridge — CHANGES_REQUESTED** [review]
@AkshayBajajML, the previous issues look fixed, great! I noticed a couple other behaviors, what are your thoughts?

1. Open Load Step Settings and go to the Advanced tab using keyboard navigation.
2. From the Advanced tab, tab once to select the Select menu. No tooltip appears.
3. Tab once. Shift tab back to the Select menu. Tooltip appears.

I would expect the tooltip to appear in step #2, consistent with step #3. ???

1. Make the tooltip appear on the Select menu. 
2. Click somewhere else in the browser to remove menu focus. Tooltip remains visible and is difficult to make disappear. I have to tab back to the menu somehow and then tab away to make it disappear.

I would expect the tooltip to disappear when the menu element loses focus. ???

You can see both behaviors in the following screencast:

https://watch.screencastify.com/v/4RajtIMWV7Ix4xiSmyrQ

**Comment by AkshayBajajML** [comment]
> @AkshayBajajML, the previous issues look fixed, great! I noticed a couple other behaviors, what are your thoughts?
> 
> 1. Open Load Step Settings and go to the Advanced tab using keyboard navigation.
> 2. From the Advanced tab, tab once to select the Select menu. No tooltip appears.
> 3. Tab once. Shift tab back to the Select menu. Tooltip appears.
> 
> I would expect the tooltip to appear in step #2, consistent with step #3. ???
> 
> 1. Make the tooltip appear on the Select menu.
> 2. Click somewhere else in the browser to remove menu focus. Tooltip remains visible and is difficult to make disappear. I have to tab back to the menu somehow and then tab away to make it disappear.
> 
> I would expect the tooltip to disappear when the menu element loses focus. ???
> 
> You can see both behaviors in the following screencast:
> 
> https://watch.screencastify.com/v/4RajtIMWV7Ix4xiSmyrQ

@wooldridge For the tooltip not appearing for first select is expected as there is not event handler for firstly tabbed element.
I have handled the scenario for closing the tooltips when user clicks outside anywhere in form.

**Review by wooldridge — CHANGES_REQUESTED** [review]
Is there a way to widen the container for the Interceptors tooltip under Advanced? In my browser, I couldn't see the entirety of this massive tooltip, widening the container would help. Looks like this will work in advanced-settings.scss:
```
#interceptors-tooltip .tooltip-inner {
    max-width: 400px;
}
```
Screen Shot 2022-01-13 at 4 27 13 PM

Also, there are links inside the Interceptor tooltip that, because of their purple color, are unreadable against the black background. We can fix this (make all links inside tooltips white) by adding the following to App.scss:
```
.tooltip .tooltip-inner a {
  color: white;
}
```

**Comment by AkshayBajajML** [comment]
> Is there a way to widen the container for the Interceptors tooltip under Advanced? In my browser, I couldn't see the entirety of this massive tooltip, widening the container would help. Looks like this will work in advanced-settings.scss:
> 
> ```
> #interceptors-tooltip .tooltip-inner {
>     max-width: 400px;
> }
> ```
> 
> Screen Shot 2022-01-13 at 4 27 13 PM
> 
> Also, there are links inside the Interceptor tooltip that, because of their purple color, are unreadable against the black background. We can fix this (make all links inside tooltips white) by adding the following to App.scss:
> 
> ```
> .tooltip .tooltip-inner a {
>   color: white;
> }
> ```

Done! PR is ready for review again

**Review by wooldridge — APPROVED** [review]

**Review by briantang — APPROVED** [review]

**Comment by briantang** [comment]
Looks like a couple RTL failures need to be fixed @AkshayBajajML

**Comment by AkshayBajajML** [comment]
@wooldridge @briantang 
Tests passing!!

**Review by briantang — APPROVED** [review]

**Comment by AkshayBajajML** [comment]
@wooldridge @briantang 
Rebased!! and all tests passing except 2 intermittent ones.

**Review by briantang — APPROVED** [review]

**Comment by briantang** [comment]
One failure looks weird but unrelated. Let's give it one more run.

**Review by briantang — APPROVED** [review]

**Review by wooldridge — APPROVED** [review]

**Pull request merged**
