### PR TITLE
DHFPROD-9597: Condition Concepts search on compatible ML version

### PR DESCRIPTION
**Pull request by ryanjdew**
### Description
9563 is also inlcuded as a part of this ticket

#### Checklist: 
```diff
- Note: do not change the below
```

- ##### Owner:

- [x] JIRA_ID included in all the commit messages
- [x] PR title is in the format JIRA_ID:Title
- [x] Rebase the branch with upstream
- [x] Squashed all commits into a single commit
- [x] Code passes ESLint tests
- [x] Added Tests
- [x] Ran cypress tests on firefox locally
  

- ##### Reviewer:

- [x] Reviewed Tests
- N/A Added to Release Wiki

### CODE REVIEW

**Review by lucianaabc-ml — APPROVED** [review]

**Comment by ngodugu-marklogic** [comment]
@ryanjdew Seems like the Concept toggle is not showing the expanded concept while turning it on 

https://user-images.githubusercontent.com/74939216/197635989-1ee12d81-1458-41c0-9b63-c1d1339ae3dd.mov

**Review by ngodugu-marklogic — CHANGES_REQUESTED** [review]
Also, here I searched Kettle which should be a concept I was able to expand a node which displayed Jeans as concept, I right clicked on a node which has category Kettle but I do not see expand option displayed for it.

https://user-images.githubusercontent.com/74939216/197638254-630b3778-32a2-475c-a597-c3a61be576b3.mov

**Comment by ryanjdew** [comment]
@ngodugu-marklogic I just pushed a fix for the "Show Related" not appearing for Concept relationships pre-10.0-7.

Since the Concepts toggle resubmits the search, I can't do much there. I believe that will be resolved by the separate front-end ticket we have for this scenario.

**Comment by ngodugu-marklogic** [comment]
@ryanjdew The collapse isn’t working properly, not sure if it is related to this PR. If not please let me know will create a seperate ticket

https://user-images.githubusercontent.com/74939216/197716024-a2221961-86e5-4c55-b85d-b109136bd4a1.mov

**Comment by ngodugu-marklogic** [comment]
@ryanjdew Using ML-11.0.20221024 I created a new concept class and when I try to filter using the related entity, the concepts do not show up. They do not show up even when I click show related.

**Review by aniamy — CHANGES_REQUESTED** [review]
Looking at the pipeline there seems to be a line in the wrong place in the e2e code.
"Cannot call `cy.get()` outside a running test.  This usually happens when you accidentally write commands outside an `it(...)` test."

**Comment by aniamy** [comment]
> @ryanjdew Using ML-11.0.20221024 I created a new concept class and when I try to filter using the related entity, the concepts do not show up. They do not show up even when I click show related. Also the graph is showing some nodes to have related records but when I try to expand it doesn't show any expanded records(ML 10.0-20221025)
> 
>  Screen.Recording.2022-10-25.at.3.04.53.AM.mov

@ngodugu-marklogic This PR is the backend work related to concepts. The video seems to be a UI issue since in the latest call you show that the BE actually returns the data. Seems like we need a ticket to handle that bug separately.

**Review by aniamy — DISMISSED** [review]

**Comment by ngodugu-marklogic** [comment]
@ryanjdew Seems like Leaf nodes E2E test is still failing.

**Comment by ngodugu-marklogic** [comment]
@ryanjdew The Related Concepts Facet just shows one Concept though we have more concepts present in Graph which is causing the E2E scripts to fail.. Can you please take a look at it

image

**Review by ngodugu-marklogic — APPROVED** [review]

**Review by briantang — APPROVED** [review]

**Pull request merged**
