### PR TITLE
DHFPROD-4935: Fixing bad paths in 9-rewriter.xml

### PR DESCRIPTION
**Pull request by rjrudin**
For testing, I used a script that's attached to 4935

#### Checklist: 
```diff
- Note: do not change the below
```

-  ##### Owner:

- [x] JIRA_ID included in all the commit messages
- [x] PR title is in the format JIRA_ID:Title
- [x] Rebase the branch with upstream
- [x] Squashed all commits into a single commit
- [x] Added Tests
  

- ##### Reviewer:

- [ ] Reviewed Tests

### CODE REVIEW

**Comment by bsrikan** [comment]
@rjrudin is this related to the support ticket MLSSUPPORT #29101

**Comment by rjrudin** [comment]
It's not - this was reported in Slack recently. Support 29101 is related to a bug that's already fixed in 5.2.0. But I think we should knock this out if we're going to do a 5.2.2.

**Comment by SameeraPriyathamTadikonda** [comment]
@rjrudin  Can I merge this? Pipeline will not merge automatically to feature branches.

**Comment by rjrudin** [comment]
@SameeraPriyathamTadikonda  Yes, please merge.

**Pull request merged**
