### PR TITLE
DHFPROD-4614:Apply button for any unapplied facet selection, DHFPROD-4629:Visual indicator for unapplied facet selections

### PR DESCRIPTION
**Pull request by Sanjeevani19**
#### Checklist: 
```diff
- Note: do not change the below
```

-  ##### Owner:

- [x] JIRA_ID included in all the commit messages
- [x] PR title is in the format JIRA_ID:Title
- [x] Rebase the branch with upstream
- [x] Squashed all commits into a single commit
- [x] Added Tests
  

- ##### Reviewer:

- [x] Reviewed Tests

### CODE REVIEW

**Comment by Sanjeevani19** [comment]
> Select facets, apply the facets, and then deselect the facets. The apply facets button disappears.
> https://drive.google.com/file/d/1nSJzG4ThW-4Tf1vQXkkIBO-oVCGcfRn_/view
> Hey bruce I made the necessary changes for this and pushed them.

> Clicking the grey, unapplied facet buttons can cause the app the crash
> https://drive.google.com/file/d/1D90LmvAetKCD2V_ROmD44ifQW2Oiv-bT/view
The above issue will be handled as a part of this story, https://project.marklogic.com/jira/browse/DHFPROD-4630, for now I disabled the on-click for the app to not crash.

**Comment by Sanjeevani19** [comment]
> When navigating off browse view and then back, applied facets are lost when another facet is checked.
> https://drive.google.com/file/d/1NJNnW7q8GixignAr5WbJX1C7MYjsW99Z/view

- @brucean52 the above bug already exists in the current develop branch, I created a separate JIRA ticket to handle this. 
https://project.marklogic.com/jira/browse/DHFPROD-4740

**Comment by Sanjeevani19** [comment]
> The apply all button stays after facets are applied
> https://drive.google.com/file/d/1dgXfvBkMV6oRselQz4_S-lSbUSACJOyK/view

- @brucean52 - I have made the necessary changes for this and pushed them, please review it

**Comment by rahulvudutala** [comment]
Previously unapplied facets are also applied when something some facet which is unapplied is applied.
Discussed this with Sanjeevani Vishaka and it will be handled by Sanjeevani as part of DHFPROD-4630 story. So approving this PR

**Pull request merged**
