### PR TITLE
DHFPROD-4733: Navigate to the Detail view for JSON and XML documents

### PR DESCRIPTION
**Pull request by xnikhil08**
### Description
Adding the new detail view for non-entity instance document(All Data option).

#### Checklist: 
```diff
- Note: do not change the below
```

-  ##### Owner:

- [x] JIRA_ID included in all the commit messages
- [x] PR title is in the format JIRA_ID:Title
- [x] Rebase the branch with upstream
- [x] Squashed all commits into a single commit
- [x] Added Tests
  

- ##### Reviewer:

- [x] Reviewed Tests

### CODE REVIEW

**Review by timur-isangulov — DISMISSED** [review]
Looks good.

**Review by briantang — CHANGES_REQUESTED** [review]
@xnikhil08 It looks like there may be a cypress test failing on the pipeline. The Jenkins link is not working sometimes so you can track it down manually visiting this link: 
https://jenkins.marklogic.com/blue/organizations/jenkins/Datahub_CI/detail/PR-4806/1/pipeline

**Comment by xnikhil08** [comment]
> @xnikhil08 It looks like there may be a cypress test failing on the pipeline. The Jenkins link through Github is not working sometimes so you can track it down manually visiting this link:
> https://jenkins.marklogic.com/blue/organizations/jenkins/Datahub_CI/detail/PR-4806/1/pipeline

@briantang - Thanks for pointing out. Just pushed a fix.

**Review by Sanjeevani19 — APPROVED** [review]
Functionality and tests looks good, One core unit test related to mapping is failing but not related to this PR.

**Review by rahulvudutala — APPROVED** [review]

**Review by briantang — APPROVED** [review]

**Review by timur-isangulov — APPROVED** [review]

**Pull request merged**
