### PR TITLE
DHFPROD-2192: Enable Polling on Flow run and change the status to stop

### PR DESCRIPTION
**Pull request by brucean52**
I'm getting the following error in the back end terminal when I try and run the flow.

2019-04-17 17:27:59.682  WARN 48934 --- [pool-5-thread-2] c.m.c.d.impl.WriteBatcherImpl            : Error writing batch: com.marklogic.client.FailedRequestException: Local message: failed to apply resource at documents: Internal Server Error. Server Message: XDMP-CAST: (err:FORG0001) xs:int(fn:subsequence($error-data, 1, 1)) -- Invalid cast: "The specified flow flow-me is missing." cast as xs:int
17:27:59.682 [pool-5-thread-2] WARN  c.m.c.d.impl.WriteBatcherImpl - Error writing batch: com.marklogic.client.FailedRequestException: Local message: failed to apply resource at documents: Internal Server Error. Server Message: XDMP-CAST: (err:FORG0001) xs:int(fn:subsequence($error-data, 1, 1)) -- Invalid cast: "The specified flow flow-me is missing." cast as xs:int

### CODE REVIEW

**Comment by srinathgit** [comment]
@brucean52 ,
After creating the flow, did you deploy it to the server ? Can you look in data-hub-STAGING in QC and see if /flows/flow-me.flow.json is present ?

**Comment by brucean52** [comment]
@srinathgit I'm having issues getting it deployed to the server. Here's the error I'm getting

```
2019-04-17 21:01:57.111  INFO 50084 --- [nio-8080-exec-8] c.m.h.d.c.DeployHubDatabaseCommand       : Forest creation is disabled, so not creating any forest
21:01:57.111 [http-nio-8080-exec-8] INFO  c.m.h.d.c.DeployHubDatabaseCommand - Forest creation is disabled, so not creating any forests
```

**Comment by srinathgit** [comment]
This seems like an issue during installation. Are you trying to reinstall the hub ? you can just deploy user artifacts without having to run installation again. Also is this with latest code of 2096 feature branch ?

**Comment by brucean52** [comment]
Yeah this is latest code on 2096, clean install of data hub using ML server 9.09

**Comment by aebadirad** [comment]
There's just no way your changes affected this. So it's got to be a problem deeper or a config issue.

**Comment by ayuwono** [comment]
@brucean52 , this error that you first posted is because you are using 4200. Try to run java jar on war file and use port 8080

**Comment by brucean52** [comment]
@ayuwono Do I need to build the war file? I'm not familiar with using port 8080

**Pull request merged**
