### PR TITLE
DHFPROD-7943: Component Replacement: Input Group 2

### PR DESCRIPTION
**Pull request by MSBrignoni**
### Description
Input Group 2

#### Checklist: 
```diff
- Note: do not change the below
```

-  ##### Owner:

- [x] JIRA_ID included in all the commit messages
- [x] PR title is in the format JIRA_ID:Title
- [x] Rebase the branch with upstream
- [x] Squashed all commits into a single commit
- [x] Code passes ESLint tests
- [x] Added Tests
- [x] Run UI tests
  

- ##### Reviewer:

- [x] Reviewed Tests

### CODE REVIEW

**Review by briantang — CHANGES_REQUESTED** [review]
@MSBrignoni The Batch size field width has increased to match the others - but I checked with UX and it should remain a small field.
PR: 
Screen Shot 2021-11-04 at 2 22 31 PM

Nightly:
Screen Shot 2021-11-04 at 2 22 47 PM

**Comment by MSBrignoni** [comment]
> 
> 
> @MSBrignoni The Batch size field width has increased to match the others - but I checked with UX and it should remain a small field. PR: Screen Shot 2021-11-04 at 2 22 31 PM
> 
> Nightly: Screen Shot 2021-11-04 at 2 22 47 PM

Thank you Brian, done
FIX INPUT
.

**Review by briantang — APPROVED** [review]

**Review by iveyMarklogic — DISMISSED** [review]

**Review by briantang — CHANGES_REQUESTED** [review]
@MSBrignoni This needs a linting fix.

**Comment by MSBrignoni** [comment]
> 
> 
> @MSBrignoni This needs a linting fix.

Thank You Brian, was one white space in create-edit-space.tsx.

**Review by iveyMarklogic — DISMISSED** [review]

**Review by briantang — APPROVED** [review]

**Review by briantang — CHANGES_REQUESTED** [review]
Actually @MSBrignoni I'm also seeing the same issue from Input Group 4 now in this PR as well for create-edit-step.tsx. After creating a step, the next time you create a step, it is not cleaned and still contains the name from the previous dialog.

**Comment by MSBrignoni** [comment]
> 
> 
> Actually @MSBrignoni I'm also seeing the same issue from Input Group 4 now in this PR as well for create-edit-step.tsx. After creating a step, the next time you create a step, it is not cleaned and still contains the name from the previous dialog.

Thank you Brian, i was checking the New Loading Step too, was fixed.

**Review by iveyMarklogic — APPROVED** [review]

**Review by briantang — APPROVED** [review]

**Pull request merged**
