### PR TITLE
DHFPROD-2350: Do not save map on initial loading

### PR DESCRIPTION
**Pull request by wooldridge**
For details, see: https://project.marklogic.com/jira/browse/DHFPROD-2350

### CODE REVIEW

**Comment by hao1st** [comment]
Just did quick test. After the change, it seems auto-saving does not work if we edit any setting from a step...

**Comment by wooldridge** [comment]
@hao1st can you describe the steps you are taking to test? This change should only affect the mapping step. 

I'm seeing mapping changes persisted:

1. Create a new flow.
2. Create a new ingestion step, ingest docs.
3. Create a new mapping step with ingestion step as source.
4. Define mapping properties via menus.
5. After defining mapping properties, switch steps, reload page, or go back to Manage Flows and then back to mapping step. Mapping settings are persisted in all cases.

**Comment by bsrikan** [comment]
Will look into it today

**Comment by bsrikan** [comment]
> I still see the following:
> From Console tab
> 
> ```
> GET /api/flows/mapping-only main.91e8eef6bb0cdf1afbd5.js:1:1006893
> flow by id response 
> Object { id: "mapping-only", name: "mapping-only", description: "", batchSize: 100, threadCount: 4, stopOnError: false, options: {}, steps: (1) […], jobs: (1) […], latestJob: {…} }
> main.91e8eef6bb0cdf1afbd5.js:1:3095715
> GET /api/flows/mapping-only/steps main.91e8eef6bb0cdf1afbd5.js:1:1007465
> mapping-only main.91e8eef6bb0cdf1afbd5.js:1:1007507
> save mapping 
> Object { language: "zxx", name: "mapping-only-map-test", description: "", version: 7, targetEntityType: "http://example.com/Order-0.0.1/Order", sourceContext: "//", sourceURI: "/ingestion-flow/json/json/orders/10255.json", properties: {…} }
> main.91e8eef6bb0cdf1afbd5.js:1:2771276
> PUT api/flows/mapping-only/steps/map-test-mapping
> ```
> 
> From Network Tab:
> 
> ```
> 200  GET    mapping-only-map-test   json
> 200  GET    mapping-only-map-test   json
> 200  POST  mapping-only-map-test   xml
> ```

My bad. Earlier build was running on port 8080. Will update shortly

**Comment by wooldridge** [comment]
@bsrikan thanks. @ayuwono can you test?

**Pull request merged**
