### PR TITLE
DHFPROD-1951: ingest step feature commits

### PR DESCRIPTION
**Pull request by alexsmr**

### CODE REVIEW

**Comment by wooldridge** [comment]
@alexsmr I'm seeing compilation with warnings:

WARNING in Circular dependency detected:
src/main/ui/app/components/common/common.module.ts -> src/main/ui/app/components/common/index.ts -> src/main/ui/app/components/common/common.module.ts

WARNING in Circular dependency detected:
src/main/ui/app/components/common/index.ts -> src/main/ui/app/components/common/common.module.ts -> src/main/ui/app/components/common/index.ts
｢wdm｣: Compiled with warnings.]

**Comment by wooldridge** [comment]
@alexsmr When I load the ingestion configuration view ("Order Flow 01" from the online-store project), I see this as the Input File Path:

../../../../../marklogic-data-hub/examples/healthcare

If I navigate up a directory ("..") to:

../../../../../marklogic-data-hub/examples

I see no folders in the examples directory listed. I only see a "..". I think this is a bug since I have many subdirectories inside examples? online-store, etc.

**Comment by wooldridge** [comment]
@alexsmr Should the ingestion config view be saving? I'm not seeing any endpoint calls made upon form changes or Save button clicks.

**Comment by ayuwono** [comment]
When using the folder browser, I can't navigate to the child folders

Should the style guide follow the form/table like in Mastering step?

**Comment by ayuwono** [comment]
Now I can navigate to child/sub folders after creating the ingest step. But after clicking on Save, it seems that the folder path is not saved (After clicking on Save, go back to Manage Flows page, click on the flow and go to the ingest step)

There is a bug on creating ingest step, it seems that after selecting Ingestion as the type, the Target Entity drop down menu disappears
- Click on New Step
- On new step dialog, select Ingestion as the type
The Target Entity drop down menu is gone

**Comment by alexsmr** [comment]
> There is a bug on creating ingest step, it seems that after selecting Ingestion as the type, the Target Entity drop down menu disappears.
@ayuwono this is by design. See: https://wiki.marklogic.com/display/ENGINEERING/Flow+UI+Design?preview=/102766514/102971079/Edit%20Flow%20v10%20(New%20Step%20Ingestion).png

**Comment by alexsmr** [comment]
Will open a new pull request.

**Pull request closed without merging**
