### PR TITLE
DHFPROD-6276: Update card footer icons

### PR DESCRIPTION
**Pull request by AkshayBajajML**
#### Checklist: 
```diff
- Note: do not change the below
```

-  ##### Owner:

- [x] JIRA_ID included in all the commit messages
- [x] PR title is in the format JIRA_ID:Title
- [x] Rebase the branch with upstream
- [x] Squashed all commits into a single commit
- [x] Added Tests
  

- ##### Reviewer:

- [x] Reviewed Tests

### CODE REVIEW

**Comment by briantang** [comment]
@AkshayBajajML @wooldridge @jbelonoj With the settings and step details icons being changed, should/can they also be updated in the respective modals below? 

Screen Shot 2020-12-10 at 1 48 16 PM
Screen Shot 2020-12-10 at 1 48 27 PM

**Comment by jbelonoj** [comment]
Absolutely, @briantang. Good catch! Do we need another Jira for those or can be fixed as part of this one?

**Comment by briantang** [comment]
> Absolutely, @briantang. Good catch! Do we need another Jira for those or can be fixed as part of this one?

Thanks @jbelonoj. @AkshayBajajML do you think the change is simple enough to include in this PR? Another Jira may not be needed.

**Comment by AkshayBajajML** [comment]
> > Absolutely, @briantang. Good catch! Do we need another Jira for those or can be fixed as part of this one?
> 
> Thanks @jbelonoj. @AkshayBajajML do you think the change is simple enough to include in this PR? Another Jira may not be needed.

Yeah I think it should not be a problem.

**Review by briantang — CHANGES_REQUESTED** [review]
Requesting changes for icons in modals to be updated as well.

**Comment by AkshayBajajML** [comment]
> Requesting changes for icons in modals to be updated as well.

Thank you for the finding.. Updated it

**Review by briantang — APPROVED** [review]
Looks good now!

**Review by Sanjeevani19 — APPROVED** [review]

**Pull request merged**
