### PR TITLE
DHFPROD-5231: Validate and Save ruleset for multiple properties form

### PR DESCRIPTION
**Pull request by xnikhil08**
### Description
Below changes are addressed in this PR.
1. The ruleset with multiple properties can be saved now. The result can be seen on the match scale. Cypress tests added for the same.
2. Most of the validation & Integration tests exists in RTL. More scenarios will definitely be added further as we progress with other stories related to individual match types.
3. Saving the ruleset works for all the match types. However, the e2e test cases, if not done here already, will be added in their respective stories. e2e have been added for Zip and Exact match types.

All UI changes are approved by @jbelonoj.

#### Checklist: 
```diff
- Note: do not change the below
```

-  ##### Owner:

- [x] JIRA_ID included in all the commit messages
- [x] PR title is in the format JIRA_ID:Title
- [x] Rebase the branch with upstream
- [x] Squashed all commits into a single commit
- [x] Code passes ESLint tests
- [x] Added Tests
  

- ##### Reviewer:

- [x] Reviewed Tests

### CODE REVIEW

**Comment by AkshayBajajML** [comment]
property names deselection on Match on: not working consistently.
Screencast: https://drive.google.com/file/d/1WcVK67Fq3xtyARZELfKmG3fMfMFWNAae/view?usp=sharing

**Comment by xnikhil08** [comment]
> -Property names deselection on Match on: not working consistently.
> Screencast: https://drive.google.com/file/d/1WcVK67Fq3xtyARZELfKmG3fMfMFWNAae/view?usp=sharing
> 
> -Info related to match type is not reset/cleared on deselecting the property.
> Screencast: https://drive.google.com/file/d/1oXkpdt7RZH-OBPwNOW6kltaRFCrIzYo_/view?usp=sharing

@AkshayBajajML - The "Match on: " feature is out-of-scope for this story and not completed yet. It will be picked up as part of its own dedicated JIRA ticket.
Fixed the second issue in my latest commit.
Another review ?

**Review by AkshayBajajML — DISMISSED** [review]
-- Info related to match type is not reset/cleared on deselecting the property : **Resolved now**

-- Exact and Zip match type are working as expected.

**Review by Sanjeevani19 — APPROVED** [review]
Looks good, works as expected.

**Review by AkshayBajajML — APPROVED** [review]

**Review by wooldridge — APPROVED** [review]
Looks good to me, tests pass.

General question about the mastering sliders, there is a CSS pointer for "grabbing":

https://www.w3schools.com/cssref/playit.asp?filename=playcss_cursor&preval=grabbing

I think we should use that for all the slider cursor interactions since it is a grab and drag interaction, not a point and click. I will file a bug for this so UX can review.

**Review by ngodugu-marklogic — APPROVED** [review]

**Pull request merged**
