### PR TITLE
DHFPROD-2575: Add 404 Route and exception handling for invalid routes

### PR DESCRIPTION
**Pull request by brucean52**

### CODE REVIEW

**Comment by brucean52** [comment]
@ayuwono we are displaying the status code and status text that the server side returns as an error response. The status is different depending on if it's the job details view or edit flow view

**Comment by wooldridge** [comment]
@brucean52 looks like there are conflicts to fix before merging.

**Comment by brucean52** [comment]
@wooldridge thanks. Fixed the conflicts.

**Comment by brucean52** [comment]
I'm not sure why this is failing CI/CD pipeline. @SameeraPriyathamTadikonda

**Comment by SameeraPriyathamTadikonda** [comment]
> I'm not sure why this is failing CI/CD pipeline. @SameeraPriyathamTadikonda

There are some conflicts when it tries to Rebase and merge

**Pull request closed without merging**
