### PR TITLE
DHFPROD-7890: Introduce entity-specific side panel

### PR DESCRIPTION
**Pull request by federicoRufrancosMarklogic**
#### Checklist: 
```diff
- Note: do not change the below
```

-  ##### Owner:

- [X] JIRA_ID included in all the commit messages
- [X] PR title is in the format JIRA_ID:Title
- [X] Rebase the branch with upstream
- [X] Squashed all commits into a single commit
- [X] Code passes ESLint tests
- [X] Added Tests
- [x] Run UI tests
  

- ##### Reviewer:

- [x] Reviewed Tests

### CODE REVIEW

**Review by xnikhil08 — CHANGES_REQUESTED** [review]

**Comment by xnikhil08** [comment]
Cursor should change to a pointer when hovering over any entity type rectangle in the main side panel and entity type squares in the grey side panel (collapsed view of main side panel). Currently the cursor remains the same no matter where the user hovers over.

**Review by xnikhil08 — DISMISSED** [review]
Looks good.
Sine we would be taking care of the portion of hooking up to the actual endpoints as part of separate ticket i.e DHFPROD-8269, I don't mind moving forward with this one to get few pieces of the puzzle in place.
(Assuming the UX approval is already in place.)

**Comment by federicoRufrancosMarklogic** [comment]
> are of the portion of hooking up to the actual endpoints as part of separate ticket i.e DHFPROD-8269, I don't mind moving forward with this one to get few pieces of the puzzle in place.

Yes, UI  was reviewed with Jamie and some updates had been made some time ago. They were already push to the branch

**Review by Sanjeevani19 — COMMENTED** [review]
@federicoRufrancosMarklogic Linting seems to be fail on the pipeline, Please run 
npm run lint . -- --fix

**Review by Sanjeevani19 — CHANGES_REQUESTED** [review]
@federicoRufrancosMarklogic Functionality Looks good.

There is no longer zero state explore button and one of the e2e test failure is related to that https://jenkins.marklogic.com/blue/organizations/jenkins/Datahub_CI/detail/PR-6374/30/tests, Please fix it

**Comment by federicoRufrancosMarklogic** [comment]
> @federicoRufrancosMarklogic Functionality Looks good.
> 
> There is no longer zero state explore button and one of the e2e test failure is related to that https://jenkins.marklogic.com/blue/organizations/jenkins/Datahub_CI/detail/PR-6374/30/tests, Please fix it

yes I just find it and push changes, also one test was expecting to navigate throw zero state page, everything updated

**Review by Sanjeevani19 — APPROVED** [review]

**Review by briantang — APPROVED** [review]
Cool! This looks great @federicoRufrancosMarklogic

**Pull request merged**
