### PR TITLE
DHFPROD-2019: Update UI to work with new JSON payload changes

### PR DESCRIPTION
**Pull request by brucean52**

### CODE REVIEW

**Comment by brucean52** [comment]
OK, that seems to fix it.

**Comment by brucean52** [comment]
Should I also change config to options? I think it would make the terminology more consistent across the entire stack.

**Comment by alexsmr** [comment]
@brucean52 yes, that will be great. It is more work though than ingestion.

**Comment by brucean52** [comment]
I think I got all the changes done. Please check.

**Pull request merged**
