### PR TITLE
DHFPROD-7435: View Entity Type tab in the Graph view except color and…

### PR DESCRIPTION
**Pull request by AkshayBajajML**
… icon

#### Checklist: 
```diff
- Note: do not change the below
```

-  ##### Owner:

- [x] JIRA_ID included in all the commit messages
- [x] PR title is in the format JIRA_ID:Title
- [x] Rebase the branch with upstream
- [x] Squashed all commits into a single commit
- [x] Code passes ESLint tests
- [x] Added Tests
  

- ##### Reviewer:

- [x] Reviewed Tests

### CODE REVIEW

**Comment by AkshayBajajML** [comment]
UI changes reviewed and approved by Jamie

**Review by briantang — CHANGES_REQUESTED** [review]
Screen Shot 2021-07-07 at 3 57 11 PM

Looks good @AkshayBajajML! Small alignment suggestion, looks like the Prefix tooltip icon is a little below the center line. Could that be shifted up so it's centered?

**Comment by AkshayBajajML** [comment]
> Screen Shot 2021-07-07 at 3 57 11 PM
> 
> Looks good @AkshayBajajML! Small alignment suggestion, looks like the Prefix tooltip icon is a little below the center line. Could that be shifted up so it's centered?

fixed it!

**Review by briantang — DISMISSED** [review]

**Comment by AkshayBajajML** [comment]
Resolved Merge conflicts

**Review by briantang — APPROVED** [review]

**Review by Sanjeevani19 — APPROVED** [review]

**Pull request merged**
