### PR TITLE
DHFPROD-6544: Function search bar is not getting displayed properly in Map Step

### PR DESCRIPTION
**Pull request by devinnicholson**
#### Checklist: 
```diff
- Note: do not change the below
```

-  ##### Owner:

- [x] JIRA_ID included in all the commit messages
- [x] PR title is in the format JIRA_ID:Title
- [x] Rebase the branch with upstream
- [x] Squashed all commits into a single commit
- [x] Code passes ESLint tests
- [x] Added Tests
  

- ##### Reviewer:

- [x] Reviewed Tests

### CODE REVIEW

**Comment by devinnicholson** [comment]
Mike caught an issue with the fix and this PR needs a slight edit-- not ready for review yet.

**Review by wooldridge — APPROVED** [review]
I am seeing function menus for mapping definitions for all of the entities in the reference project behaving correctly now whereas they are not on the develop branch (e.g., properties for the NamespacedCustomer entity). Linting and unit tests pass.

**Review by jyangML — APPROVED** [review]

**Comment by wooldridge** [comment]
This PR is showing e2e failures. 

4 of the 5 e2e failures are failures that @SameeraPriyathamTadikonda noted as common due to the cypress upgrade. 

The remaining failure is the following:
```
tests / cypresse2e / manage queries modal scenarios, developer role manage queries, edit, apply, delete query – manage queries, edit, apply, delete query
Error
Timed out retrying: Unable to find an element by: [data-testid="/json/persons/last-name-dob-custom1.json-detailOnSeparatePage"]
Stacktrace
TestingLibraryElementError: Timed out retrying: Unable to find an element by: [data-testid="/json/persons/last-name-dob-custom1.json-detailOnSeparatePage"]
    at Object.getElementError (http://localhost:8080/__cypress/tests?p=cypress/support/index.js:89:27068)
    at eval (http://localhost:8080/__cypress/tests?p=cypress/support/index.js:89:35130)
    at eval (http://localhost:8080/__cypress/tests?p=cypress/support/index.js:89:34742)
    at eval (http://localhost:8080/__cypress/tests?p=cypress/support/index.js:89:35405)
    at eval (http://localhost:8080/__cypress/tests?p=cypress/support/index.js:89:19920)
    at c (http://localhost:8080/__cypress/tests?p=cypress/support/index.js:89:19950)
    at y (http://localhost:8080/__cypress/tests?p=cypress/support/index.js:89:20236)
    at x (http://localhost:8080/__cypress/tests?p=cypress/support/index.js:89:20590)
```
This appears to have nothing to do with the changes made in this PR. The PR is a minor CSS fix applied to the mapping UI, and this e2e is a Manage Queries test.

**Comment by timur-isangulov** [comment]
> manage queries modal scenarios, developer role manage queries

@wooldridge, I'm looking into Explorer e2e failures.

**Review by wooldridge — APPROVED** [review]

**Review by jyangML — APPROVED** [review]

**Review by timur-isangulov — APPROVED** [review]

**Pull request merged**
