### PR TITLE
DHFPROD-5311: Fix file type circles in Run Tile

### PR DESCRIPTION
**Pull request by AkshayBajajML**
#### Checklist: 
```diff
- Note: do not change the below
```

-  ##### Owner:

- [x] JIRA_ID included in all the commit messages
- [x] PR title is in the format JIRA_ID:Title
- [x] Rebase the branch with upstream
- [x] Squashed all commits into a single commit
- [x] Added Tests
  

- ##### Reviewer:

- [x] Reviewed Tests

### CODE REVIEW

**Comment by jbelonoj** [comment]
Sure, would look nicer all boxes with the same height, @wooldridge. I guess one thing to test as we are making that change would be a long step name that wraps to the next line.

**Comment by wooldridge** [comment]
@jbelonoj, good point about the long text. Would you prefer we use CSS to add ellipses for long names that hit the end of the enclosing container?

**Comment by jbelonoj** [comment]
@wooldridge I think we have to truncate and add "..." for the names that don't have space and we wrap to the next line for the ones that have. What do you think?

**Comment by wooldridge** [comment]
Interesting point, @jbelonoj. I can't recall any other places where we've distinguished between long names with spaces and long names without spaces, and applied different formatting. The ellipses would come with a mouseover that shows the entire name text. I think having the ellipsis truncation for all long text is best as it keeps the containers a consistent size and is much, much easier to implement and much less complicated.

**Comment by jbelonoj** [comment]
Sure, @wooldridge. That works, especially for these cards with a pretty rigid spacing. I think generally it's better usability - wise to wrap text with spaces in the tables, for example. We want to the user to see the actual data rather than a bunch of "...". If the text doesn't have spaces, we have no choice but truncate. Does this make sense?

**Comment by wooldridge** [comment]
@jbelonoj, here's what I currently see:

Screen Shot 2020-08-04 at 3 02 16 PM

I will move the truncation issue to a separate ticket since it's not trivial and is different from what @AkshayBajajML fixed, here's the issue I created: https://project.marklogic.com/jira/browse/DHFPROD-5683

**Pull request merged**
