### PR TITLE
DHFPROD-7640: Improve tooltips for interceptors

### PR DESCRIPTION
**Pull request by AkshayBajajML**
Note: Also fixed the line break issue for Add merge rules description. 

#### Checklist: 
```diff
- Note: do not change the below
```

-  ##### Owner:

- [x] JIRA_ID included in all the commit messages
- [x] PR title is in the format JIRA_ID:Title
- [x] Rebase the branch with upstream
- [x] Squashed all commits into a single commit
- [x] Code passes ESLint tests
- N/A Added Tests
- [x] Run UI tests
  

- ##### Reviewer:

- N/A Reviewed Tests

### CODE REVIEW

**Comment by AkshayBajajML** [comment]
UI changes reviewed and approved by @jbelonoj

**Review by wooldridge — CHANGES_REQUESTED** [review]
Comments about the Interceptors help text:
1. In other help content (e.g., Target Permissions tooltip), we use monospace type to distinguish code. In the Interceptors tooltip, we use green text. Can we use monospace in the Interceptors tooltip as well?
2. We don't use the distinguishing text (green color) throughout the help content for code. In the PR, we don't use it for instances of "path", "when", "beforeMain", and "beforeContentPersisted". We also don't have the starting and ending brace/bracket in green. Let's mark up all the code in green (or as monospace, whatever style we decide).
3. There are two instances where we use single quotes instead of the more prevalent double quotes, 'beforeMain' and 'beforeContentPersisted'. Let's be consistent and use double quotes throughout.
4. Let's add a space between "vars" and "(optional)". 
5. The PR content ends with two links. The first doesn't work (typo), the second works. The first references the master version of the example project and the second references the develop version. I think we should be referencing the master version. I think we should show a single link and link "Example" text since linking the entire URL is messy.
6. I also think we should make the "xdmp.invoke function" text a link and get rid of the extra URL link.
@sbayatpur thoughts?
interceptors

**Comment by sbayatpur** [comment]
I agree with Mike's recommendations

**Comment by AkshayBajajML** [comment]
Made the changes and pushed again.
PR is ready for review again

**Review by briantang — APPROVED** [review]
Looks good. Also seeing Mike's comments addressed.

**Review by wooldridge — APPROVED** [review]

**Pull request merged**
