### PR TITLE
DHFPROD-2018: Implement payload changes in Mocking & Swagger layers

### PR DESCRIPTION
**Pull request by clockworked247**
Reflect changes in mocking server and Swagger doc.
https://wiki.marklogic.com/display/ENGINEERING/DHF+Web+Service+REST+API+Data+Model

Includes pathing interactive mocking changes in DHFPROD-1996.

### CODE REVIEW

**Comment by alexsmr** [comment]
@clockworked247 so does these PR brakes UI? Do we need to do additional work to fix it?

**Comment by clockworked247** [comment]
@alexsmr yes. DHFPROD-2019 tracks the UI changes required.  DHFPROD-2032 tracks the QA changes required.  All changes were as discussed on the call yesterday.  The changes reflect the final plan of record for the REST APIs for Banana.

**Comment by clockworked247** [comment]
FYI, build is successful locally.

**Comment by alexsmr** [comment]
@clockworked247 Thanks, Scott. Can you please create a feature branch based on story name and open this PR against it. If we need to add more UI work to comply with the new schema, we better off with common feature branch and work against it until UI and QA are stable. The "fix" I mean is to continue the work to finish the stories you created.

**Comment by clockworked247** [comment]
Closing in favor of new feature branch @alexsmr requested:  https://github.com/marklogic/marklogic-data-hub/pull/2091

**Pull request closed without merging**
