### PR TITLE
Feature: Swagger powered mock api framework

### PR DESCRIPTION
**Pull request by clockworked247**
Swagger + Express powered API mocking

- Proxy 4200 Angular calls to 8081
- Express Server on 8081: if a mock for the requested path exists, return mock, otherwise pass through to 8080 Java API endpoints
- Raw Swagger doc at: http://localhost:4200/api/swagger/doc/
- Bruce inspired Swagger UI rendering of mocked API: http://localhost:4200/api/swagger-ui/
- Sample Mock API Swagger document created with paths: GET http://localhost:4200/api/samples & GET/DELETE http://localhost:4200/api/samples/{id} 
- Quick Start still working at:  http://localhost:4200

### CODE REVIEW

**Comment by aebadirad** [comment]
@clockworked247 can we get a rebase on this from develop (or just npm audit fix and correct the karma version like we did in dev)? then I'll bring it in

**Comment by clockworked247** [comment]
@ableasdale branch has been rebased off latest develop

**Comment by clockworked247** [comment]
@aebadirad  I'm also requesting a compliance review on the new 3rd party libs, before we merge this change.  Let's wait to merge till we have approvals.  Thx.

**Comment by clockworked247** [comment]
Compliance has approved.  Ready to merge!

**Comment by aebadirad** [comment]
Sweet, merging.

**Pull request merged**
