### PR TITLE
DHFPROD-6613: Query dropdown changes its position with a flicker

### PR DESCRIPTION
**Pull request by devinnicholson**
#### Checklist: 
```diff
- Note: do not change the below
```

-  ##### Owner:

- [x] JIRA_ID included in all the commit messages
- [x] PR title is in the format JIRA_ID:Title
- [x] Rebase the branch with upstream
- [x] Squashed all commits into a single commit
- [x] Code passes ESLint tests
- N/A Added Tests
  

- ##### Reviewer:

- N/A Reviewed Tests

### CODE REVIEW

**Review by timur-isangulov — CHANGES_REQUESTED** [review]
Hi @devinnicholson, the issue with the explorer query dropdown is fixed but I noticed the issue with mapping DropDownWithSearch component. The list closes if I click search field. https://drive.google.com/file/d/1ZE2pZB-U936kXlW0g4XQoSyckZy6MkIr/view

**Review by brucean52 — APPROVED** [review]

**Comment by brucean52** [comment]
> Hi @devinnicholson, the issue with the explorer query dropdown is fixed but I noticed this change causes the issue with mapping DropDownWithSearch component. The list closes if I click search field. https://drive.google.com/file/d/1ZE2pZB-U936kXlW0g4XQoSyckZy6MkIr/view

I see the same issue.

**Review by wooldridge — APPROVED** [review]
I'm seeing the bug fixed and the function menu working correctly now.

Query menu fixed: https://drive.google.com/file/d/1j7P87QrW-Nnv6F_PH2hnDsC2D9dCGfog/view

Function menu working correctly: https://drive.google.com/file/d/1foPU2lkacBYY5JBalWCg0PIHZIO2B_xc/view

**Review by timur-isangulov — APPROVED** [review]
Looks good.

**Pull request merged**
