### PR TITLE
DHFPROD-7794: Add final modeling Graph UI text

### PR DESCRIPTION
**Pull request by AkshayBajajML**
#### Checklist: 
```diff
- Note: do not change the below
```

-  ##### Owner:

- [x] JIRA_ID included in all the commit messages
- [x] PR title is in the format JIRA_ID:Title
- [x] Rebase the branch with upstream
- [x] Squashed all commits into a single commit
- [x] Code passes ESLint tests
- N/A Added Tests
- [x] Run UI tests
  

- ##### Reviewer:

- N/A Reviewed Tests

### CODE REVIEW

**Comment by AkshayBajajML** [comment]
Jamie reviewed and approved UI related changes

**Review by xnikhil08 — DISMISSED** [review]

**Review by wooldridge — APPROVED** [review]
Looks great!

**Comment by wooldridge** [comment]
@AkshayBajajML, the E2E failures on this PR should be fixed by the following PR, which was merged to develop: https://github.com/marklogic/marklogic-data-hub/pull/6073

Rebase this branch to develop and you should be OK.

**Comment by AkshayBajajML** [comment]
> @AkshayBajajML, the E2E failures on this PR should be fixed by the following PR, which was merged to develop: #6073
> 
> Rebase this branch to develop and you should be OK.

Rebased!!

**Review by wooldridge — APPROVED** [review]

**Review by briantang — APPROVED** [review]

**Review by xnikhil08 — APPROVED** [review]

**Pull request merged**
