### PR TITLE
DHFPROD-4777: Adding ESLint into Data Hub Central UI project

### PR DESCRIPTION
**Pull request by saarimrahman**
### Description
See description from https://github.com/marklogic/marklogic-data-hub/pull/4701. This is a new PR for the 5.4-develop branch as the previous PR was reverted. 

#### Checklist: 
```diff
- Note: do not change the below
```

-  ##### Owner:

- [x] JIRA_ID included in all the commit messages
- [x] PR title is in the format JIRA_ID:Title
- [x] Rebase the branch with upstream
- [x] Squashed all commits into a single commit
- n/a Added Tests
  

- ##### Reviewer:

- n/a Reviewed Tests

### CODE REVIEW

**Review by wooldridge — APPROVED** [review]
Looks good, runs fine:

Screen Shot 2020-10-14 at 3 48 25 PM

**Review by briantang — APPROVED** [review]

**Review by briantang — COMMENTED** [review]
Looks like there are some merge conflicts. Can you look into resolving those? @saarimrahman

**Review by wooldridge — APPROVED** [review]
Reviewed tile functionality, looks good. Unit tests pass. Approved!

**Comment by wooldridge** [comment]
@saarimrahman, looks like another conflict resolution/rebase is needed. :-(

**Review by Sanjeevani19 — APPROVED** [review]

**Review by timur-isangulov — DISMISSED** [review]

**Review by Sanjeevani19 — APPROVED** [review]

**Review by timur-isangulov — APPROVED** [review]

**Pull request merged**
