### PR TITLE
DHFPROD-5757:Ensure the flow panel scrolled upon adding a step to a flow in Run

### PR DESCRIPTION
**Pull request by chriskellyml**
### Description

DHFPROD-5757: Ensure the flow panel scrolled upon adding a step to a flow in Run

- When the user adds a step from any interface, the flow panel is opened and scrolled to the right.

#### Checklist: 
```diff
- Note: do not change the below
```

-  ##### Owner:

- [x] JIRA_ID included in all the commit messages
- [x] PR title is in the format JIRA_ID:Title
- [x] Rebase the branch with upstream
- [x] Squashed all commits into a single commit
- [x] Added Tests: Checked affected tests are passing but did feel an additional automated test was required
  

- ##### Reviewer:

- [x] Reviewed Tests

### CODE REVIEW

**Review by srinathgit — CHANGES_REQUESTED** [review]
1. I rebased your branch locally and added a step to a flow that has horizontal scrollbar, I don't see the scrollbar scrolled to the far right and showing the newly added step.
https://drive.google.com/file/d/1BZJqhoXra2MXLv5b67aOpkyJTKpQDDSV/view
2. Once you fix the functionality, please rebase against feature/5.4-develop and push to your feature branch

**Comment by chriskellyml** [comment]
> 1. I rebased your branch locally and added a step to a flow that has horizontal scrollbar, I don't see the scrollbar scrolled to the far right and showing the newly added step.

@srinathgit This is not what the fix does. When a user adds a new step it should scroll to the right if it does not fit on the page so the user can see the step they just added. The steps should not be scrolled to the right by default or when you load the page as you showed in your screen capture.

**Comment by srinathgit** [comment]
> > 1. I rebased your branch locally and added a step to a flow that has horizontal scrollbar, I don't see the scrollbar scrolled to the far right and showing the newly added step.
> 
> @srinathgit This is not what the fix does. When a user adds a new step it should scroll to the right if it does not fit on the page so the user can see the step they just added. The steps should not be scrolled to the right by default or when you load the page as you showed in your screen capture.

When a user adds a step, he is automatically redirected to “Run” tile and the flow to which the step was added is opened. My understanding as per AC in the story is that when this happens, the scrollbar is automatically scrolled to far right to display the step which I don’t see happening

**Comment by srinathgit** [comment]
I misunderstood the scope of the ticket. For DHFPROD-5757, we can restrict the scope to only adding steps from the Run tile(as described in the ticket) and consider scrolling to far right  when adding steps from Load, Curate tile in a separate ticket
I tried adding step from Run tile and see some scenarios where it’s not working correctly

https://drive.google.com/file/d/146f9ALmDXoNM8VWudGlc4dmA_B2JmNGt/view

**Review by srinathgit — CHANGES_REQUESTED** [review]
1. Looks like it needs a rebase
2. Commit message should be of format,(DHFPROD-####:<msg>) e.g. DHFPROD-5757:Ensure the flow panel scrolled upon adding a step to a flow in Run

**Review by Sanjeevani19 — APPROVED** [review]

**Comment by srinathgit** [comment]
Tests are handled in separate task.

**Review by srinathgit — APPROVED** [review]

**Comment by Sanjeevani19** [comment]
> Tests are handled in separate task.

Tests will be added as a part of https://project.marklogic.com/jira/browse/DHFPROD-6157

**Pull request merged**
