### PR TITLE
DHFPROD-7949: Search box in the sidebar

### PR DESCRIPTION
**Pull request by AkshayBajajML**
Screencast: https://drive.google.com/file/d/1Ze5dIxV0mRm5LB9XiWzIHzFmjoCUXn_J/view?usp=sharing.

#### Checklist: 
```diff
- Note: do not change the below
```

-  ##### Owner:

- [x] JIRA_ID included in all the commit messages
- [x] PR title is in the format JIRA_ID:Title
- [x] Rebase the branch with upstream
- [x] Squashed all commits into a single commit
- [x] Code passes ESLint tests
- [x] Added Tests
- [x] Run UI tests
  

- ##### Reviewer:

- [x] Reviewed Tests
- [x] Added Release Notes

### CODE REVIEW

**Comment by AkshayBajajML** [comment]
@briantang Added respective release notes to 5.7 release.

**Review by briantang — APPROVED** [review]
Looks good to me.

**Review by briantang — CHANGES_REQUESTED** [review]
There are some e2e and ui test failures though @AkshayBajajML

**Comment by AkshayBajajML** [comment]
> There are some e2e and ui test failures though @AkshayBajajML

Looking into them

**Review by iveyMarklogic — APPROVED** [review]

**Review by briantang — APPROVED** [review]

**Review by xnikhil08 — DISMISSED** [review]
Looks good.

**Review by briantang — APPROVED** [review]

**Review by iveyMarklogic — DISMISSED** [review]

**Review by briantang — DISMISSED** [review]

**Review by xnikhil08 — APPROVED** [review]

**Review by briantang — APPROVED** [review]
Pushed an e2e fix.

**Review by iveyMarklogic — APPROVED** [review]

**Review by xnikhil08 — APPROVED** [review]

**Review by briantang — APPROVED** [review]

**Pull request merged**
