### PR TITLE
DHFPROD-9292: Nodes with IRI by different properties.

### PR DESCRIPTION
**Pull request by aniamy**
#### Checklist: 
```diff
- Note: do not change the below
```

- ##### Owner:

- [x] JIRA_ID included in all the commit messages
- [x] PR title is in the format JIRA_ID:Title
- [x] Rebase the branch with upstream
- [x] Squashed all commits into a single commit
- [x] Code passes ESLint tests
- [x] Added Tests
- N/A Ran cypress tests on firefox locally
  

- ##### Reviewer:

- [ ] Reviewed Tests
- [ ] Added to Release Wiki

### CODE REVIEW

**Review by Sanjeevani19 — COMMENTED** [review]
@aniamy one of the related core test is failing, http://jenkins1.marklogic.com/blue/organizations/jenkins/Datahub_CI/detail/PR-7213/14/tests, please look into it

**Comment by ryanjdew** [comment]
Just pushed an update for the core test and there was some UI changes that were missing from the previous commit I pushed that I'm hoping will resolve the e2e failures.

**Review by prolonMarkLogic — CHANGES_REQUESTED** [review]
Hello, I see that the "open related Product records in a table"  is not working, I attached a short video

https://user-images.githubusercontent.com/92050414/190653242-ee32cb9e-25ce-43d8-901d-d8680e8e3661.mp4

**Comment by prolonMarkLogic** [comment]
Hello, when I try to expand a group node, this error occurs and the graph stops working:

**Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'parentDocUri')**
    at handleGroupNodeExpand (graph-vis-explore.tsx:610:1)
    at handleMenuClick (graph-vis-explore.tsx:859:1)
    at HTMLUnknownElement.callCallback (react-dom.development.js:188:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:237:1)
    at invokeGuardedCallback (react-dom.development.js:292:1)
    at invokeGuardedCallbackAndCatchFirstError (react-dom.development.js:306:1)
    at executeDispatch (react-dom.development.js:389:1)
    at executeDispatchesInOrder (react-dom.development.js:414:1)
    at executeDispatchesAndRelease (react-dom.development.js:3278:1)
    at executeDispatchesAndReleaseTopLevel (react-dom.development.js:3287:1)
    at forEachAccumulated (react-dom.development.js:3259:1)
    at runEventsInBatch (react-dom.development.js:3304:1)

**Comment by aniamy** [comment]
@ryanjdew I am testing the latest changes in node expand and I found that nodeExpand is still having issues.
When I double clicked the node disappeared. And when right click for menu and expand 3 nodes it freezes in the UI (you can see the UI issue in the video)
https://watch.screencastify.com/v/Xr1LcEKrxswROnOyEOUk

**Comment by csilva-ml** [comment]
> @csilva-ml Could you look into the e2e test failures, let's make sure to get this merged by EOD today http://jenkins1.marklogic.com/blue/organizations/jenkins/Datahub_CI/detail/PR-7213/31/tests

Yes Sanjeevani I am on it right now

**Comment by csilva-ml** [comment]
@Sanjeevani19 @aniamy This is still failing
image
2|1|

**Review by ryanjdew — APPROVED** [review]

**Comment by aniamy** [comment]
Closing as we are handling all graph related code in this branch https://github.com/marklogic/marklogic-data-hub/tree/graph-beta-changes

**Pull request closed without merging**
