### PR TITLE
MLUI-143: search.component.ts

### PR DESCRIPTION
**Pull request by clockworked247**
Search Component complete + Search Viewer Component reorg & fixes.

### CODE REVIEW

**Comment by clockworked247** [comment]
@alexsmr This has been rebased off the latest mlui-integration branch.  I don't see any updates to the repo since I last rebased, so everything appears current.   Let me know if I'm missing something.

**Comment by alexsmr** [comment]
OK. Can you please push some change to trigger the build? Thanks.

**Comment by clockworked247** [comment]
@alexsmr I saw https://github.com/marklogic/marklogic-data-hub/pull/1539 was merged, so I rebased this off the latest.

**Comment by clockworked247** [comment]
Appears to be more test churn on this failure.  https://jenkins.marklogic.com/job/dhf-QS-develop-rh7-Commit/300/testReport  At a glance, Search does not appear to be related to these flows, jobs and mapping failures.

**Comment by clockworked247** [comment]
Rebased off latest mlui-integration branch

**Pull request merged**
