### PR TITLE
Assigning the modified string to "ampCall"

### PR DESCRIPTION
**Pull request by srinathgit**
Assigning the modified string to "ampCall"

### CODE REVIEW

**Comment by grechaw** [comment]
attention @akshaysonvane

**Comment by srinathgit** [comment]
@grechaw ,

I spoke with @akshaysonvane  and since it looks like Alex has made the modules db name changes in this "DHFPROD-1192-upgrade" branch, he will delete his PR.

**Comment by grechaw** [comment]
alex actually made the change in his PR and may have made the change to this file too,but probably missed your actual bugfix.

**Comment by srinathgit** [comment]
yeah and I have rebased against his latest commit , so  I think this PR can be merged

**Pull request merged**
