### PR TITLE
DHFPROD-7640: Improve tooltips for interceptors

### PR DESCRIPTION
**Pull request by AkshayBajajML**
Note: Also fixed minor CSS changes along-
- Fixed the extra padding issue on viewing bulb icon popover in HC overview page.
- Fixed bottom padding in Model tile for https://project.marklogic.com/jira/browse/DHFPROD-7893

#### Checklist: 
```diff
- Note: do not change the below
```

-  ##### Owner:

- [x] JIRA_ID included in all the commit messages
- [x] PR title is in the format JIRA_ID:Title
- [x] Rebase the branch with upstream
- [x] Squashed all commits into a single commit
- [x] Code passes ESLint tests
- N/A Added Tests
- [x] Run UI tests
  

- ##### Reviewer:

- N/A Reviewed Tests

### CODE REVIEW

**Review by briantang — CHANGES_REQUESTED** [review]
Looks good @AkshayBajajML . I see part of the AC is to change the arrow on this tooltip to white. Will/Did you address this? It still looks blue to me.

Screen Shot 2021-09-23 at 1 02 13 PM

**Comment by AkshayBajajML** [comment]
> Looks good @AkshayBajajML . I see part of the AC is to change the arrow on this tooltip to white. Will/Did you address this? It still looks blue to me.
> 
> Screen Shot 2021-09-23 at 1 02 13 PM

Fixed the issue and PR is ready for review again

**Review by briantang — DISMISSED** [review]
Looks good now

**Review by wooldridge — CHANGES_REQUESTED** [review]
Still seeing extra padding on the bottom of graph view in Modeling, should that be gone with this PR? 
Screen Shot 2021-09-27 at 10 41 08 AM

**Comment by AkshayBajajML** [comment]
> Still seeing extra padding on the bottom of graph view in Modeling, should that be gone with this PR? Screen Shot 2021-09-27 at 10 41 08 AM

Resolved and pushed the changes

**Review by wooldridge — APPROVED** [review]

**Review by briantang — APPROVED** [review]

**Pull request merged**
