### PR TITLE
DHFPROD-7656: Allow selecting top-level property for merge rule

### PR DESCRIPTION
**Pull request by ryanjdew**
#### Checklist: 
```diff
- Note: do not change the below
```

-  ##### Owner:

- [x] JIRA_ID included in all the commit messages
- [x] PR title is in the format JIRA_ID:Title
- [x] Rebase the branch with upstream
- [x] Squashed all commits into a single commit
- [x] Code passes ESLint tests
- [x] Added Tests
- N/A Run UI tests
  

- ##### Reviewer:

Added to https://wiki.marklogic.com/display/ENGINEERING/Data+Hub+5.7.0 

- [x] Reviewed Tests
- [x] Added to Release Wiki

### CODE REVIEW

**Review by yubiselmarklogic — COMMENTED** [review]
@ryanjdew  The user should continue be able to select individual structured type properties under the top-level structured types.

When select one top-level structured type all the properties below it should also be highlighted.
image

**Comment by ryanjdew** [comment]
Thanks, @yubiselmarklogic. I've added styling to the children of selected structured properties.

selectedAddress

**Comment by yubiselmarklogic** [comment]
@ryanjdew  Looks good now

**Review by yubiselmarklogic — APPROVED** [review]

**Review by aniamy — DISMISSED** [review]

**Comment by ryanjdew** [comment]
Fixed the e2e test to add the Details property to the proper entity

**Review by aniamy — DISMISSED** [review]

**Review by yubiselmarklogic — DISMISSED** [review]

**Review by yubiselmarklogic — APPROVED** [review]

**Review by briantang — APPROVED** [review]

**Pull request merged**
