### PR TITLE
DHFPROD-7334: Fixed staging rewriter; no longer forking REST modules

### PR DESCRIPTION
**Pull request by rjrudin**
### Description

Deleted all of the forked REST modules. 

Removed a bunch of Java code for determining the staging rewriter to use based on server version. That's no longer needed now that the staging rewriter is generated dynamically when DHF modules are loaded. 

Added tests for ml:hubversion, ml:flow, and ml:sjsFlow to ensure they work. 

#### Checklist: 
```diff
- Note: do not change the below
```

-  ##### Owner:

- [x] JIRA_ID included in all the commit messages
- [x] PR title is in the format JIRA_ID:Title
- [x] Rebase the branch with upstream
- [x] Squashed all commits into a single commit
- [x] Code passes ESLint tests
- [x] Added Tests
  

- ##### Reviewer:

- [x] Reviewed Tests

### CODE REVIEW

**Comment by rjrudin** [comment]
Not assigning reviewers yet, as I need for the 7256 PR to be merged to develop first.

**Comment by rjrudin** [comment]
Most of this is file deletions and file renaming (for amp files; I renamed them so we have a consistent approach there).

**Review by ryanjdew — APPROVED** [review]

**Review by srinathgit — CHANGES_REQUESTED** [review]
Couple of test failures
https://jenkins.marklogic.com/blue/organizations/jenkins/Datahub_CI/detail/PR-5666/3/tests

**Comment by rjrudin** [comment]
Fixed a couple tests that expected amp files to have previous filenames

**Review by srinathgit — APPROVED** [review]

**Review by akshaysonvane — APPROVED** [review]

**Pull request merged**
