### PR TITLE
DHFPROD-8004: Query managing replacement

### PR DESCRIPTION
**Pull request by yubiselmarklogic**
#### Checklist: 
```diff
- Note: do not change the below
```

-  ##### Owner:

- [x] JIRA_ID included in all the commit messages
- [x] PR title is in the format JIRA_ID:Title
- [x] Rebase the branch with upstream
- [x] Squashed all commits into a single commit
- [x] Code passes ESLint tests
- [x] Added Tests
- [x] Run UI tests
  

- ##### Reviewer:

- [ ] Reviewed Tests

### CODE REVIEW

**Review by briantang — CHANGES_REQUESTED** [review]
@yubiselmarklogic Looks good, but I think it is a little strange that there are two cancellation buttons ("No" & "Cancel"). This is on the nightly as well, but can we just choose one to keep with this PR? FYI @jbelonoj . And if we choose to keep "No" instead of "Cancel", do we follow the same theme of positioning both buttons in the center of the modal?

Screen Shot 2021-11-16 at 11 31 24 AM
s choose one to keep?
Screen Shot 2021-11-16 at 11 31 06 AM

**Comment by jbelonoj** [comment]
> @yubiselmarklogic Looks good, but I think it is a little strange that there are two cancellation buttons ("No" & "Cancel"). This is on the nightly as well, but can we just choose one to keep with this PR? FYI @jbelonoj . And if we choose to keep "No" instead of "Cancel", do we follow the same theme of positioning both buttons in the center of the modal?

Thanks, @briantang. Yes, we should definitely have two buttons, No and Yes. They should be centered, just like on all the other Yes/No confirmations.

**Comment by yubiselmarklogic** [comment]
@jbelonoj, @briantang  The format for yes/no dialog don't use title, in this case I should keep it?

**Comment by jbelonoj** [comment]
@yubiselmarklogic I think we can keep the "Existing Query" title. We don't need the "Confirmation" title, let's remove it. Thanks!

**Comment by yubiselmarklogic** [comment]
Close the pr to create new one when complete all modals related to query process in tasks 8004, 8005 and 8047.

**Pull request closed without merging**
