### PR TITLE
DHFPROD-7451: Add spinner for entity properties load in mapping

### PR DESCRIPTION
**Pull request by briantang**
#### Checklist: 
```diff
- Note: do not change the below
```

-  ##### Owner:

- [x] JIRA_ID included in all the commit messages
- [x] PR title is in the format JIRA_ID:Title
- [x] Rebase the branch with upstream
- [x] Squashed all commits into a single commit
- [x] Code passes ESLint tests
- [x] Added Tests
  

- ##### Reviewer:

- [x] Reviewed Tests

### CODE REVIEW

**Review by srinathgit — DISMISSED** [review]

**Comment by srinathgit** [comment]
@briantang 
I tested out the PR. It looks good. I think we don't want this PR to be merged until 5.5.0 release branch is created. Can you convert it to "Draft" state ?

**Comment by briantang** [comment]
@srinathgit Thanks, I thought so. Curious about the rest of this jenkins run though, so I'll convert it to Draft as soon as it's done.

**Comment by briantang** [comment]
Looking into an e2e failure...will convert this PR out of draft state once it is ready.

**Review by srinathgit — APPROVED** [review]

**Review by wooldridge — CHANGES_REQUESTED** [review]
Can we make the two spinners on the mapping details page the same size? 

DHFPROD-7451-spinners-mapping


Make the entity spinner large just like the existing source spinner:
```
<MLSpin size={"large"} data-testid="spinner"/>
```

**Review by wooldridge — APPROVED** [review]
Looks good!

**Review by srinathgit — APPROVED** [review]

**Review by xnikhil08 — APPROVED** [review]

**Pull request merged**
