### PR TITLE
DHFPROD-7258: Set namespaces for structured properties

### PR DESCRIPTION
**Pull request by ryanjdew**
#### Checklist: 
```diff
- Note: do not change the below
```

-  ##### Owner:

- [x] JIRA_ID included in all the commit messages
- [x] PR title is in the format JIRA_ID:Title
- [x] Rebase the branch with upstream
- [x] Squashed all commits into a single commit
- [x] Code passes ESLint tests
- [x] Added Tests
- [x] Run UI tests
  

- ##### Reviewer:

- [x] Reviewed Tests

### CODE REVIEW

**Review by briantang — COMMENTED** [review]
@ryanjdew  I think the **package-lock.json** is probably not necessary in the commit

**Comment by ryanjdew** [comment]
@briantang Good catch. I just reverted it.

**Review by aniamy — DISMISSED** [review]

**Review by briantang — CHANGES_REQUESTED** [review]
Placeholder text is no longer apparent, and seems like some UI tests failing. Probably some issues with the 5.6 code and the newly replaced code in 5.7. I can try to assist when I get the chance

**Review by briantang — APPROVED** [review]
This looks good to go. The remaining mappingWithCustomHeader.spec failure is intermittent

**Review by Sanjeevani19 — APPROVED** [review]
Looks good

**Pull request merged**
