### PR TITLE
DHFPROD-5961: Add run icon and 'run in flow' menu to all steps

### PR DESCRIPTION
**Pull request by briantang**
### Description

- Added option to run a Load/Curate step in a new flow or run in an existing flow from Card view via Run icon
- Added RTL and Cypress tests for the respective scenarios
- Design reviewed by @jbelonoj, note: Run tooltip will briefly cover the Run menu, but discussed that this is the best option for now.
- note: There is a known bug with adding/running a same step to an existing flow where job details get corrupted. @srinathgit is working on a fix.

#### Checklist: 
```diff
- Note: do not change the below
```

-  ##### Owner:

- [x] JIRA_ID included in all the commit messages
- [x] PR title is in the format JIRA_ID:Title
- [x] Rebase the branch with upstream
- [x] Squashed all commits into a single commit
- [x] Added Tests
  

- ##### Reviewer:

- [x] Reviewed Tests

### CODE REVIEW

**Comment by briantang** [comment]
I will wait to make sure this PR is approved before creating the same one towards the develop branch.

**Review by Sanjeevani19 — CHANGES_REQUESTED** [review]
@briantang two cypress tests are failing on the pipeline, https://jenkins.marklogic.com/blue/organizations/jenkins/Datahub_CI/detail/PR-4798/1/tests, Please fix them

**Review by wooldridge — CHANGES_REQUESTED** [review]
Looks great, here's a screencast of some manual tests:

https://drive.google.com/file/d/11urilK84o19dfrOeyQtSSuqgrHQBdhv-/view

One minor UI inconsistency issue. The new Run button (Load and Curate views) has a rollover effect whereas the existing Run button (Run view) does not. I think these should be consistent and I like the rollover. @jbelonoj  what do you think, is there a UX guideline for this?

**Comment by briantang** [comment]
> @briantang two cypress tests are failing on the pipeline, https://jenkins.marklogic.com/blue/organizations/jenkins/Datahub_CI/detail/PR-4798/1/tests, Please fix them

Cypress tests pass in pipeline now.

**Review by Sanjeevani19 — APPROVED** [review]

**Comment by briantang** [comment]
> Looks great, here's a screencast of some manual tests:
> 
> https://drive.google.com/file/d/11urilK84o19dfrOeyQtSSuqgrHQBdhv-/view
> 
> One minor UI inconsistency issue. The new Run button (Load and Curate views) has a rollover effect whereas the existing Run button (Run view) does not. I think these should be consistent and I like the rollover. @jbelonoj what do you think, is there a UX guideline for this?
> 
> FWIW, here's a screencast showing the hover effects for all the card footer icons: https://drive.google.com/file/d/12dJsfPMZxWfADuFwwXJJVpUljGlFumYZ/view

Also added rollover effect on the Run button so it is consistent with buttons in the Run tile. Approved by Julia, screencast here: https://drive.google.com/file/d/1d7l9t5dQ-6FCMIW2hfClOGA_iMzU7DP8/view

**Comment by briantang** [comment]
Thanks @wooldridge , addressed the spacings.

**Review by wooldridge — APPROVED** [review]

**Review by Sanjeevani19 — APPROVED** [review]

**Pull request merged**
