### PR TITLE
DHFPROD-6064: Added testDhsTests to core project

### PR DESCRIPTION
**Pull request by rjrudin**
### Description

You'll need to add the following properties to gradle-local.properties, as the test plumbing will read properties in that file and in gradle-local.properties:

mlHost=changeme
mlUsername=changeme
mlPassword=changeme
mlSecurityUsername=same as mlUsername
mlSecurityPassword=same as mlUsername
hubDhs=true
hubSsl=true

Also deleted gradle-dhs.properties, which has no bearing on anything. 

Removed "ssl" and "certauth" support from build.gradle, as those were unused. Also removed testBootstrap, as there are not any tests in the "com.marklogic.hub.bootstrap" package. Removed references to that from Jenkinsfile as well. 

#### Checklist: 
```diff
- Note: do not change the below
```

-  ##### Owner:

- [x] JIRA_ID included in all the commit messages
- [x] PR title is in the format JIRA_ID:Title
- [x] Rebase the branch with upstream
- [x] Squashed all commits into a single commit
- [x] Added Tests
  

- ##### Reviewer:

- [x] Reviewed Tests

### CODE REVIEW

**Review by srinathgit — DISMISSED** [review]

**Review by akshaysonvane — APPROVED** [review]

**Review by ryanjdew — APPROVED** [review]

**Comment by rjrudin** [comment]
Had to rebase and fix an issue in build.gradle

**Review by srinathgit — APPROVED** [review]

**Review by akshaysonvane — DISMISSED** [review]

**Comment by SameeraPriyathamTadikonda** [comment]
Looks like datahub is not installed and tests are failing.

**Comment by rjrudin** [comment]
Fixed testAcceptance task

**Review by ryanjdew — APPROVED** [review]

**Review by akshaysonvane — APPROVED** [review]

**Comment by SameeraPriyathamTadikonda** [comment]
TestAcceptance Works fine but testDhsTests fails on dhs instance

**Review by akshaysonvane — APPROVED** [review]

**Review by srinathgit — APPROVED** [review]

**Review by SameeraPriyathamTadikonda — APPROVED** [review]

**Review by ryanjdew — APPROVED** [review]

**Pull request merged**
