### PR TITLE
DHFPROD-926 fix QuickStart UI style issues

### LINKED ISSUE #1030: QuickStart UI is not rendered correctly
QuickStart v3.0.0 develop branch
MacOS on Chrome

Some UIs are broken. They are across the application. Here are some examples:

screen shot 2018-05-23 at 2 52 21 pm

screen shot 2018-05-23 at 2 54 30 pm

screen shot 2018-05-23 at 2 55 21 pm

screen shot 2018-05-23 at 2 56 06 pm

┆Status: Closed

### PR DESCRIPTION
**Pull request by wooldridge**
These issues occurred after upgrading to Angular 6. Our MDL library does not currently support Angular 6.

- Remove extra spacing on sides of folder browser
- Adjust bottom border in selected text fields

Fixes #1030

### CODE REVIEW

**Comment by ayuwono** [comment]
@wooldridge, it looks good. There are still a couple of ui issues that you might do a quick fix on this PR?

1) On the dialog box, it seems that there is a blue border around the button:
screen shot 2018-06-08 at 10 12 25 am

screen shot 2018-06-08 at 10 29 44 am

2) When creating a new Harmonize flow, there is a double line on the name field

screen shot 2018-06-08 at 10 31 38 am

**Comment by wooldridge** [comment]
The blue border is just the default button having user focus. At least that's what I'm seeing. I don't see that as a bug, but it's interesting if that wasn't happening before. 

I'm seeing the textbox line issue fixed on Create Harmonize Flow.

**Comment by wooldridge** [comment]
I'm checking this on Chrome and Firefox (Mac).

**Comment by ayuwono** [comment]
After re-test, the double lines are not displayed on the text boxes. The blue border line on the dialog box button is fine

**Pull request merged**
