### PR TITLE
DHFPROD-8348: Change tooltips with links to white background to make the links readable

### PR DESCRIPTION
**Pull request by MSBrignoni**
### Description

Tooltip Background and Popovers

#### Checklist: 
```diff
- Note: do not change the below
```

-  ##### Owner:

- [x] JIRA_ID included in all the commit messages
- [x] PR title is in the format JIRA_ID:Title
- [x] Rebase the branch with upstream
- [x] Squashed all commits into a single commit
- [x] Code passes ESLint tests
- [x] Added Tests
- [x] Run UI tests
  

- ##### Reviewer:

- [x] Reviewed Tests
- [N/A] Added Release Notes

### CODE REVIEW

**Comment by MSBrignoni** [comment]
In the video of the [sprint 60](https://wiki.marklogic.com/display/ENGINEERING/Data+Hub+Sprint+60+Review) I show where the popovers are

**Comment by AkshayBajajML** [comment]
I see changes to package-lock.json file is also pushed.
Is that intended?

**Comment by MSBrignoni** [comment]
> I see changes to package-lock.json file is also pushed. Is that intended?

Was changed in the "npm install", removed just in case.

**Review by AkshayBajajML — APPROVED** [review]
Looks Good

**Review by yubiselmarklogic — APPROVED** [review]

**Pull request merged**
