### PR TITLE
DHFPROD-6098: Create endpoint for fetching source document for mapping UI

### PR DESCRIPTION
**Pull request by brent-hartwig**
### Description
Replacement PR for https://github.com/marklogic/marklogic-data-hub/pull/4804 and https://github.com/marklogic/marklogic-data-hub/pull/4835.  This PR only has one commit, and is compatible with both ML 9 and ML 10.

Offer the `/api/steps/mapping/{stepName}/testingDoc` endpoint where the intent is to enable the mapping UI to retrieve a source document associated to a step.

Supports XML and JSON formatted source documents but only ever returns a JSON representation. The implementation relies on fast-xml-parser to convert XML to JSON. Version v3.17.1 thereof was introduced to the backend. The frontend is already set up to use version ^3.16.0.

`/api/steps/mapping/{stepName}/testingDoc` is to replace `/api/steps/mapping/{stepName}/doc`.  A separate PR is expected to remove the latter.

#### Checklist: 
```diff
- Note: do not change the below
```

-  ##### Owner:

- [ ] JIRA_ID included in all the commit messages
- [ ] PR title is in the format JIRA_ID:Title
- [ ] Rebase the branch with upstream
- [ ] Squashed all commits into a single commit
- [ ] Added Tests
  

- ##### Reviewer:

- [ ] Reviewed Tests

### CODE REVIEW

**Review by srinathgit — CHANGES_REQUESTED** [review]
The endpoint looks good. There are couple of changes that I think needs to be done. For http://localhost:3000/api/steps/mapping/mapCustomersXML/testingDoc?docUri=/Customer/CustXMLDoc1.xml, I am seeing the following response 

```
{
	"data": {
		"entity-services:envelope": {
			"entity-services:headers": {
				"createdOn": "2020-11-10T12:19:35.375056-08:00",
				"createdBy": "admin"
			},
			"entity-services:triples": "",
			"entity-services:instance": {
				"custOrderInfo:CustOrders": {
					"custOrderInfo:CustomerID": 201,
					"custOrderInfo:Name": {
						"@type": "preferred",
						"custOrderInfo:FirstName": "Randolph",
						"custOrderInfo:LastName": "Gonzales"
					},
					"custOrderInfo:Nicknames": {
						"custOrderInfo:nickname": [
							"Ran",
							"",
							"Gonz"
						]
					},
					"custOrderInfo:Email": "randolphgonzales@nutralab.com",
					"custOrderInfo:Address": {
						"custOrderInfo:Shipping": {
							"custOrderInfo:Street": "Village Road",
							"custOrderInfo:City": "Genoa",
							"custOrderInfo:State": "Connecticut",
							"custOrderInfo:Postal": "56150-3633"
						},
						"custOrderInfo:Billing": {
							"custOrderInfo:Street": "Mermaid Avenue",
							"custOrderInfo:City": "Glenshaw",
							"custOrderInfo:State": "Northern Mariana Islands",
							"custOrderInfo:Postal": "37125-7458"
						}
					},
					"custOrderInfo:Phone": "(973) 559-3861",
					"custOrderInfo:PIN": 5427,
					"custOrderInfo:Created": "2015-01-02T15:49:17",
					"custOrderInfo:SSN": "111-11-1111"
				}
			},
			"entity-services:attachments": ""
		}
	},
	"namespaces": {
		"entity-services": "http://marklogic.com/entity-services",
		""
		""
		"custOrderInfo": "custOrderInfo"
	},
	"format": "XML"
}
```
1. The spurious quotes in namespaces should be removed.
2. "data" should just contain the source document instance ("entity-services:instance" ). More like
```
{
	"data": {
		"custOrderInfo:CustOrders": {
			"custOrderInfo:CustomerID": 201,
			"custOrderInfo:Name": {
				"@type": "preferred",
				"custOrderInfo:FirstName": "Randolph",
				"custOrderInfo:LastName": "Gonzales"
			},
			"custOrderInfo:Nicknames": {
				"custOrderInfo:nickname": [
					"Ran",
					"",
					"Gonz"
				]
			},
			"custOrderInfo:Email": "randolphgonzales@nutralab.com",
			"custOrderInfo:Address": {
				"custOrderInfo:Shipping": {
					"custOrderInfo:Street": "Village Road",
					"custOrderInfo:City": "Genoa",
					"custOrderInfo:State": "Connecticut",
					"custOrderInfo:Postal": "56150-3633"
				},
				"custOrderInfo:Billing": {
					"custOrderInfo:Street": "Mermaid Avenue",
					"custOrderInfo:City": "Glenshaw",
					"custOrderInfo:State": "Northern Mariana Islands",
					"custOrderInfo:Postal": "37125-7458"
				}
			},
			"custOrderInfo:Phone": "(973) 559-3861",
			"custOrderInfo:PIN": 5427,
			"custOrderInfo:Created": "2015-01-02T15:49:17",
			"custOrderInfo:SSN": "111-11-1111"
		}
	},
	"namespaces": {
		"entity-services": "http://marklogic.com/entity-services",
		"custOrderInfo": "custOrderInfo"
	},
	"format": "XML"
}
```

**Comment by xnikhil08** [comment]
Looks good, except the changes mentioned by @srinathgit. We can have only the instance within data as we are not using the other portions(headers, triples) of the envelope anyway within the mapping step details.

**Comment by xnikhil08** [comment]
@brent-hartwig - Please check all the required checkboxes in the checklist within the PR description, except "Reviewed Tests"

**Comment by brent-hartwig** [comment]
This PR's feedback was addressed in https://github.com/marklogic/marklogic-data-hub/pull/4848.  Closing this one.

**Pull request closed without merging**
