### PR TITLE
DHFPROD-9864: Fix latest E2E failures on 5.8-develop nightly

### PR DESCRIPTION
**Pull request by ngodugu-marklogic**
#### Checklist: 
```diff
- Note: do not change the below
```

- ##### Owner:

- [x] JIRA_ID included in all the commit messages
- [x] PR title is in the format JIRA_ID:Title
- [x] Rebase the branch with upstream
- [x] Squashed all commits into a single commit
- [N/A] Added Tests
- [x] Ran cypress tests on firefox locally
  

- ##### Reviewer:

- [x] Reviewed Tests
- [N/A] Added to Release Wiki

### CODE REVIEW

**Review by Sanjeevani19 — COMMENTED** [review]
@ngodugu-marklogic looks like there are two test failures consistently failing on two consecutive runs http://jenkins1.marklogic.com/blue/organizations/jenkins/Datahub_CI/detail/PR-7573/3/pipeline, Please look into them

**Comment by ngodugu-marklogic** [comment]
@Sanjeevani19 Seems like exploreUnmerge.cy.tsx is failing constantly due to an issue from application 
image
The other seems intermittent and were stabilized in dev by upgrade.

**Comment by briantang** [comment]
I pushed a bugfix for the application error. Let's see how the run goes. @ngodugu-marklogic

**Comment by briantang** [comment]
@ngodugu-marklogic the unmerge spec has been fixed now. Remaining one looks like e2e?

**Review by eeduardo-marklogic — APPROVED** [review]

**Review by aniamy — APPROVED** [review]

**Pull request merged**
