### PR TITLE
DHFPROD-7022: Retain state when navigating away and back to the Map /…

### PR DESCRIPTION
**Pull request by devinnicholson**
… Match / Merge Step Details

### Description
This PR preserves the step details page, it does not preserve Curate expanded rows.
I had 2 major bugs with this PR - issues creating match and merge steps and a problem with infinite looping if a user refreshed the step details page for map/match/merge. They should be fixed but please check for these bugs when reviewing.
#### Checklist: 
```diff
- Note: do not change the below
```

-  ##### Owner:

- [x] JIRA_ID included in all the commit messages
- [x] PR title is in the format JIRA_ID:Title
- [x] Rebase the branch with upstream
- [x] Squashed all commits into a single commit
- [x] Code passes ESLint tests
- [x] Added Tests
  

- ##### Reviewer:

- [x] Reviewed Tests

### CODE REVIEW

**Review by jyangML — DISMISSED** [review]

**Review by Sanjeevani19 — COMMENTED** [review]
There are few tests related to persistence, https://jenkins.marklogic.com/blue/organizations/jenkins/Datahub_CI/detail/PR-5483/5/tests, Could you please check ?

**Comment by devinnicholson** [comment]
> There are few tests related to persistence, https://jenkins.marklogic.com/blue/organizations/jenkins/Datahub_CI/detail/PR-5483/5/tests, Could you please check ?

They aren't failing locally

**Review by Sanjeevani19 — COMMENTED** [review]
@devinnicholson Looks like there are few conflicts, Please rebase

**Review by Sanjeevani19 — DISMISSED** [review]

**Review by jyangML — APPROVED** [review]

**Review by wooldridge — APPROVED** [review]
Looks good. I added a separate story for persisting the entity tab state: https://project.marklogic.com/jira/browse/DHFPROD-7180

**Review by Sanjeevani19 — DISMISSED** [review]

**Review by timur-isangulov — DISMISSED** [review]

**Review by timur-isangulov — APPROVED** [review]

**Review by jyangML — APPROVED** [review]

**Pull request merged**
