### PR TITLE
DHFPROD-10569:Update PULL_REQUEST_TEMPLATE.md

### PR DESCRIPTION
**Pull request by Sanjeevani19**
#### Checklist: 
```diff
- Note: do not change the below
```

- ##### Owner:

- [x] JIRA_ID included in all the commit messages
- [x] PR title is in the format JIRA_ID:Title
- [x] Rebase the branch with upstream
- [x] Squashed all commits into a single commit
- [N/A] Added Tests
- [N/A] Ran newly added/edited cypress tests on Firefox locally
  

- ##### Reviewer:

- [N/A] Reviewed Tests
- [N/A] Added to Release Wiki

### CODE REVIEW

**Review by ngodugu-marklogic — APPROVED** [review]

**Review by SameeraPriyathamTadikonda — COMMENTED** [review]
Should we add the same thing under reviewer checklist as well?

**Comment by Sanjeevani19** [comment]
> Should we add the same thing under reviewer checklist as well?

It would be repetitive to add in two places, We can split like this if needed **Remove any PII info and customer data** under owner section and **Review any PII info and customer data** under review section, Any thoughts ?

**Comment by SameeraPriyathamTadikonda** [comment]
> > Should we add the same thing under reviewer checklist as well?
> 
> It would be repetitive to add in two places, We can split like this if needed **Remove any PII info and customer data** under owner section and **Review any PII info and customer data** under review section, Any thoughts ?

Yes, that's what I meant remove for developers and review for reviewers. That's better

**Review by SameeraPriyathamTadikonda — APPROVED** [review]
Looks good.

**Review by ngodugu-marklogic — APPROVED** [review]

**Pull request merged**
