### PR TITLE
DHFPROD-5710: Mapping: Keyboard Navigation

### PR DESCRIPTION
**Pull request by briantang**
### Description
- Test plan for this story here: https://project.marklogic.com/jira/browse/DHFPROD-5710
- Includes minor e2e fix for https://project.marklogic.com/jira/browse/DHFPROD-9832

#### Checklist: 
```diff
- Note: do not change the below
```

- ##### Owner:

- [x] JIRA_ID included in all the commit messages
- [x] PR title is in the format JIRA_ID:Title
- [x] Rebase the branch with upstream
- [x] Squashed all commits into a single commit
- [x] Added Tests
- [x] Ran cypress tests on firefox locally
  

- ##### Reviewer:

- [x] Reviewed Tests
- [x] Added to Release Wiki

### CODE REVIEW

**Comment by briantang** [comment]
Addressed @aniamy's comments, adding keyboard navigation for all popover searches and table paginations, along with focus highlighting on column options checkboxes

**Comment by iveyMarklogic** [comment]
@briantang this popover is not accessible using  the keyboard navigation 
image

**Review by iveyMarklogic — CHANGES_REQUESTED** [review]
@briantang the same thing happens in this one, I can select the icon but I couldn't navigate inside the popover
image

**Comment by briantang** [comment]
@iveyMarklogic I fixed the issue with edit URI in the top left. For the popovers, we discussed that those should be part of a larger ticket to handle popovers across the app.

**Review by iveyMarklogic — DISMISSED** [review]

**Review by littlecherro — APPROVED** [review]

**Review by littlecherro — CHANGES_REQUESTED** [review]
im unable to reach child chevrons :( 

image

**Review by littlecherro — CHANGES_REQUESTED** [review]
this should close if we tab out of it

image

**Comment by littlecherro** [comment]
image

select opens only on SPACE press, but on ivey's ticket AC was to have SPACE and ENTER for triggering stuff 🤔 or did i miss sth?

**Review by littlecherro — CHANGES_REQUESTED** [review]
unable to reach these 

image

**Comment by briantang** [comment]
@littlecherro fixed!

**Review by littlecherro — CHANGES_REQUESTED** [review]
Hey, im still unable to reach these from Source Data :(


image

**Comment by briantang** [comment]
> Hey, im still unable to reach these from Source Data :(
> 
> image

Oops missed the source table in a different component. Fixed now!

**Review by littlecherro — APPROVED** [review]

**Review by aniamy — APPROVED** [review]

**Pull request merged**
