### PR TITLE
DHFPROD-7617: Add stacking functionality to merge slider

### PR DESCRIPTION
**Pull request by AkshayBajajML**
#### Checklist: 
```diff
- Note: do not change the below
```

-  ##### Owner:

- [x] JIRA_ID included in all the commit messages
- [x] PR title is in the format JIRA_ID:Title
- [x] Rebase the branch with upstream
- [x] Squashed all commits into a single commit
- [x] Code passes ESLint tests
- [x] Added Tests
- [x] Run UI tests
  

- ##### Reviewer:

- [x] Reviewed Tests

### CODE REVIEW

**Comment by AkshayBajajML** [comment]
PR is ready to be reviewed.

**Comment by AkshayBajajML** [comment]
Resolved conflicts
PR is ready to be reviewed!

**Review by Sanjeevani19 — COMMENTED** [review]
@AkshayBajajML here are the couple of changes I noticed :
- When changes are made in edit strategy modal and cancel button is clicked, A modal shows up, yes button is clicked which deletes both length and personJson from the timeline, instead it should leave the changes where they are. 
https://watch.screencastify.com/v/MUiu747sKk0E91XqNQ2i
- The timestamp option shouldn't be draggable inside the edit strategy modal
- A question mark is missing in the delete pop up modal, check with UX on what info needs to be shown there
- I see that delete modals code is written in two places, both of them can be handled in one modal with a conditional statement, see matching delete modal component for reference
- We can delete the entire codebase related to multi-slider component since we replaced all of it with visjs timeline
- Discard changes modal doesn't work consistently, I see a ticket to handle that seperately https://project.marklogic.com/jira/browse/DHFPROD-8160, I marked it for 5.6.2, Please make sure to pick it up next sprint

**Comment by AkshayBajajML** [comment]
PR is ready to be reviewed!

**Review by Sanjeevani19 — APPROVED** [review]

**Review by briantang — APPROVED** [review]

**Pull request merged**
