### PR TITLE
DHFPROD-6948: Removing spring-beans dependency from mlcp-util

### PR DESCRIPTION
**Pull request by rjrudin**
#### Checklist: 
```diff
- Note: do not change the below
```

-  ##### Owner:

- [x] JIRA_ID included in all the commit messages
- [x] PR title is in the format JIRA_ID:Title
- [x] Rebase the branch with upstream
- [x] Squashed all commits into a single commit
- [x] Code passes ESLint tests
- [x] Added Tests
  

- ##### Reviewer:

- [x] Reviewed Tests

### CODE REVIEW

**Review by Sanjeevani19 — COMMENTED** [review]
@rjrudin There is seperate ticket to solve spring beans palamida scan failure, https://project.marklogic.com/jira/browse/DHFPROD-6740, Can this closed if this is merged ?

**Review by akshaysonvane — APPROVED** [review]

**Review by srinathgit — APPROVED** [review]

**Comment by srinathgit** [comment]
> @rjrudin There is seperate ticket to solve spring beans palamida scan failure, https://project.marklogic.com/jira/browse/DHFPROD-6740, Can this closed if this is merged ?

@Sanjeevani19 , I closed the ticket. This PR addresses the issue

**Review by Sanjeevani19 — COMMENTED** [review]
@rjrudin Looks like there is merge conflict, please look into it

**Comment by rjrudin** [comment]
Rebased, fixed merge conflict

**Review by srinathgit — APPROVED** [review]

**Review by Sanjeevani19 — APPROVED** [review]

**Review by fsnow — APPROVED** [review]

**Pull request merged**
