### PR TITLE
DHFPROD-6651: Include reduce queries in threshold combos

### PR DESCRIPTION
**Pull request by ryanjdew**
#### Checklist: 
```diff
- Note: do not change the below
```

-  ##### Owner:

- [x] JIRA_ID included in all the commit messages
- [x] PR title is in the format JIRA_ID:Title
- [x] Rebase the branch with upstream
- [x] Squashed all commits into a single commit
- [x] Code passes ESLint tests
- [x] Added Tests
  

- ##### Reviewer:

- [x] Reviewed Tests

### CODE REVIEW

**Comment by ngodugu-marklogic** [comment]
@ryanjdew When I add just the Reduce ruleset alone, the ruleset doesn't show up under Possible Combinations of Matched Rulesets. It shows up when I add another ruleset. And the ruleset shows as exact instead of reduce. Is this expected? Please refer: https://drive.google.com/file/d/1RJbBZlnLNO4MO6EDwcNnPc2lYMXI_wy6/view

**Comment by ryanjdew** [comment]
@ngodugu-marklogic It is expected that the ruleset wouldn't show up until another was added since it is a negative weight for the reduce type.  How the rule was displayed was not expected. I've since fixed that issue.

**Comment by ngodugu-marklogic** [comment]
> @ngodugu-marklogic It is expected that the ruleset wouldn't show up until another was added since it is a negative weight for the reduce type. How the rule was displayed was not expected. I've since fixed that issue.

@ryanjdew I am seeing NOT getting added before Reduce ruleset
Screen Shot 2021-02-09 at 3 34 36 PM

**Comment by ryanjdew** [comment]
@ngodugu-marklogic I intentionally added that to indicate that the query must be false.

**Review by ngodugu-marklogic — APPROVED** [review]
LGTM!

**Review by Sanjeevani19 — APPROVED** [review]

**Pull request merged**
