### PR TITLE
DHFPROD-8740: Create relationship between Entity type and Concept class node via Add relationship button

### PR DESCRIPTION
**Pull request by xnikhil08**
#### Checklist: 
```diff
- Note: do not change the below
```

- ##### Owner:

- [x] JIRA_ID included in all the commit messages
- [x] PR title is in the format JIRA_ID:Title
- [x] Rebase the branch with upstream
- [x] Squashed all commits into a single commit
- [x] Code passes ESLint tests
- [x] Added Tests
- [x] Ran cypress tests on firefox locally
  

- ##### Reviewer:

- [x] Reviewed Tests
- [x] Added to Release Wiki

### CODE REVIEW

**Review by ryanjdew — APPROVED** [review]

**Review by ryanjdew — APPROVED** [review]

**Comment by iveyMarklogic** [comment]
@xnikhil08  when i create a new concept and a new relationship if i try to edit that new relationship instead of editing a new relationship is created

https://user-images.githubusercontent.com/88790827/181648058-3aa957cc-e9a5-431f-acfb-3778f4a88ae2.mp4

**Review by iveyMarklogic — CHANGES_REQUESTED** [review]
@xnikhil08  when I create a new concept and a new relationship if i try to edit that new relationship instead of editing a new relationship is created

https://user-images.githubusercontent.com/88790827/181648058-3aa957cc-e9a5-431f-acfb-3778f4a88ae2.mp4

**Comment by xnikhil08** [comment]
> 

@iveyMarklogic  - Its fixed in previous commit. Can you review again ?

**Review by iveyMarklogic — CHANGES_REQUESTED** [review]
@xnikhil08 the previous issue was solved but with @rolonPablo we found another issue. when I created a relationship and it sets an expression value, the value of the expression needs to be cleared. That is not happening. 

https://user-images.githubusercontent.com/88790827/181790054-fa52e5b3-439e-4761-a6f2-1cf69165fd88.mp4

**Comment by xnikhil08** [comment]
> @xnikhil08 the previous issue was solved but with @rolonPablo we found another issue. when I created a relationship and it sets an expression value, the value of the expression needs to be cleared. That is not happening.
> 
>  relationExpression.mp4

@iveyMarklogic - Fixed it. Another review?

**Review by ryanjdew — APPROVED** [review]

**Review by iveyMarklogic — APPROVED** [review]

**Pull request merged**
