### PR TITLE
DHFPROD-2362: E2E UI automation scenario with simple json data

### PR DESCRIPTION
**Pull request by ayuwono**
This is a simple scenario of E2E with simple json data to get regression going:
- Create a flow
- Create an ingestion step and ingest json docs
- Create a mapping step and run the mapping
- Create a mastering step and run the mastering

Add some test data for mastering (that's why the number of files changed are > 1000)

Add and update some page objects

Modify the framework so that we use our specific qa-project directory (will be cleaned up after the tests run) rather than generating random directory name

### CODE REVIEW

**Comment by ayuwono** [comment]
@aebadirad , @bsrikan , @timur-isangulov , if you some times, please review this so we can run QS regression on jenkins. Thanks!

**Comment by kkanthet** [comment]
@ayuwono  are the tests running consistently without fail?

**Comment by ayuwono** [comment]
> @ayuwono are the tests running consistently without fail?

@kkanthet , yes on my laptop

**Comment by aebadirad** [comment]
So, locally, these pass for me with no timeout, but jenkins keeps timing out everytime.

**Comment by ayuwono** [comment]
@aebadirad , the jenkins look green. I pushed a commit to retrigger the build

**Comment by ayuwono** [comment]
@

> @aebadirad , the jenkins look green. I pushed a commit to retrigger the build

it seems that only gradle tests...somehow the flow menu options element get stuck on jenkins, will try to add more check on this. On local machine its fine
https://jenkins.marklogic.com/job/dhf-QS-develop-rh7-Commit/1659/artifact/web/e2e/reports/screenshots/152c75e773b9be5b8fc63442582ed3dd.png

**Comment by ayuwono** [comment]
OK, re-trigger the build...with some fixes

**Comment by aebadirad** [comment]
Hey, that seemed to work!

**Comment by ayuwono** [comment]
> Hey, that seemed to work!

Nah...that's the gradle unit tests...gave me false hope. Okay, let's try it again...nth time is a charm

**Comment by ayuwono** [comment]
@aebadirad , @kkanthet : it should be fine now, the last failure is an invalid verification that I fixed

@timur-isangulov also testing on his machine and it's fine.

If you all (at least two) can re-approve this. Thanks!

**Comment by ayuwono** [comment]
Oh finally...
Screen Shot 2019-05-02 at 2 07 31 PM

**Pull request merged**
