### PR TITLE
DHFPROD-6127: Date facets replace the most recent selected facet, when still greyed out.

### PR DESCRIPTION
**Pull request by timur-isangulov**
#### Checklist: 
```diff
- Note: do not change the below
```

-  ##### Owner:

- [x] JIRA_ID included in all the commit messages
- [x] PR title is in the format JIRA_ID:Title
- [x] Rebase the branch with upstream
- [x] Squashed all commits into a single commit
- [x] Added Tests
  

- ##### Reviewer:

- [x] Reviewed Tests

### CODE REVIEW

**Review by Sanjeevani19 — CHANGES_REQUESTED** [review]
@timur-isangulov Hub properties grey facets are being removed when entity properties are selected.
https://drive.google.com/file/d/1VEtwCdMSTRkBrkXv_wpfT3HDvi5xNETa/view

Also the date facets bug happens in 5.3 too, Please check with yash if this should go into 5.3.

**Comment by timur-isangulov** [comment]
> @timur-isangulov Hub properties grey facets are being removed when entity properties are selected.
> https://drive.google.com/file/d/1VEtwCdMSTRkBrkXv_wpfT3HDvi5xNETa/view
> 
> Also the date facets bug happens in 5.3 too, Please check with yash if this should go into 5.3.

Hi @Sanjeevani19, this pr fixes the case described in the jira ticket. The case on the video is different and reproducible on the develop branch as well. Can you please open a separate Jira ticket for the case you discovered.

**Comment by Sanjeevani19** [comment]
> > @timur-isangulov Hub properties grey facets are being removed when entity properties are selected.
> > https://drive.google.com/file/d/1VEtwCdMSTRkBrkXv_wpfT3HDvi5xNETa/view
> > Also the date facets bug happens in 5.3 too, Please check with yash if this should go into 5.3.
> 
> Hi @Sanjeevani19, this pr fixes the case described in the jira ticket. The case on the video is different and reproducible on the develop branch as well. Can you please open a separate Jira ticket for the case you discovered.

@timur-isangulov  I created a seperate JIRA ticket and added it to the sprint, https://project.marklogic.com/jira/browse/DHFPROD-6148.

**Review by Sanjeevani19 — APPROVED** [review]

**Review by xnikhil08 — APPROVED** [review]
Works fine.

**Pull request merged**
