### PR TITLE
DHFPROD-7168: Select Structured Property in Single ruleset form

### PR DESCRIPTION
**Pull request by xnikhil08**
### Description
Support for Structured property in single ruleset form.

#### Checklist: 
```diff
- Note: do not change the below
```

-  ##### Owner:

- [x] JIRA_ID included in all the commit messages
- [x] PR title is in the format JIRA_ID:Title
- [x] Rebase the branch with upstream
- [x] Squashed all commits into a single commit
- [x] Code passes ESLint tests
- [x] Added Tests
  

- ##### Reviewer:

- [x] Reviewed Tests

### CODE REVIEW

**Review by AkshayBajajML — APPROVED** [review]
Looks Good!

**Review by AkshayBajajML — CHANGES_REQUESTED** [review]
Modal position is not consistent on expanding structured properties as can be seen in https://drive.google.com/file/d/1FqkICw41HB3E_g2nFBzij_kVXr3eqQdn/view?usp=sharing

**Comment by xnikhil08** [comment]
> Modal position is not consistent on expanding structured properties as can be seen in https://drive.google.com/file/d/1FqkICw41HB3E_g2nFBzij_kVXr3eqQdn/view?usp=sharing

Issue is fixed. Another review?

**Review by AkshayBajajML — APPROVED** [review]
Looks Good!!

**Review by Sanjeevani19 — APPROVED** [review]

**Pull request merged**
