### PR TITLE
DHFPROD-2264: Documents weren't being mastered through UI

### PR DESCRIPTION
**Pull request by ryanjdew**

### CODE REVIEW

**Comment by ryanjdew** [comment]
@wooldridge I think the last time you checked it was due to not targeting the right collection. I added another commit that on the creation of a step if collections aren't specified it will default to the name of the step for mapping and mastering like ingestion is already doing. You'll need to delete and recreate your mapping step after pulling down the latest.

**Comment by wooldridge** [comment]
With help from @ayuwono, I just figured out the problem. I was setting the source collection for my mastering to the name of the previous mapping step. But it looks like (in my current branch, anyway) data that is being mapped is only having the tag "default-mapping" applied and not a tag corresponding to the step name. When I master to a default-mapping source instead, I'm seeing mastering work. Great!

Sounds like maybe you addressed this issue per your last comment?

**Comment by ryanjdew** [comment]
@wooldridge Yes. The last commit addresses the issue. Now documents should end up in a collection matching the step name.

**Comment by ayuwono** [comment]
I don't see the documents being merged? I got new mastering and mdm collections, but the docs are all the same @ryanjdew

**Pull request merged**
