### PR TITLE
DHFPROD-4714:Browse page goes blank on DHS Service

### PR DESCRIPTION
**Pull request by Sanjeevani19**
#### Checklist: 
```diff
- Note: do not change the below
```

-  ##### Owner:

- [x] JIRA_ID included in all the commit messages
- [x] PR title is in the format JIRA_ID:Title
- [x] Rebase the branch with upstream
- [x] Squashed all commits into a single commit
- [x] Added Tests
  

- ##### Reviewer:

- [x] Reviewed Tests

### CODE REVIEW

**Comment by bsrikan** [comment]
@Sanjeevani19 JIRA ID was not included in the commit message so I unchecked that checklist item.

**Comment by Sanjeevani19** [comment]
> @Sanjeevani19 JIRA ID was not included in the commit message so I unchecked that checklist item.

@bsrikan, I have just added the JIRA ID, Thank you

**Comment by Sanjeevani19** [comment]
> Fix looks good, not sure if it requires any automated tests.

@akshaysonvane, I am not planning on adding any automated tests for this.

**Comment by akshaysonvane** [comment]
> > Fix looks good, not sure if it requires any automated tests.
> 
> @akshaysonvane, I am not planning on adding any automated tests for this.

Since this does not require any tests ticking the checkboxes for tests to move this forward in the pipeline.

**Pull request merged**
