### PR TITLE
DHFPROD-5624: Load + Curate: Keyboard navigation within Cards

### PR DESCRIPTION
**Pull request by iveyMarklogic**
#### Checklist: 
```diff
- Note: do not change the below
```

- ##### Owner:

- [x] JIRA_ID included in all the commit messages
- [x] PR title is in the format JIRA_ID:Title
- [x] Rebase the branch with upstream
- [x] Squashed all commits into a single commit
- [x] Added Tests
- [x] Ran cypress tests on firefox locally
  

- ##### Reviewer:

- [x] Reviewed Tests
- [n/a] Added to Release Wiki

### CODE REVIEW

**Review by littlecherro — CHANGES_REQUESTED** [review]
@iveyMarklogic i think we should have an outline here, because as a user im not really sure where i am after tabing out from the "close" icon :( 

image

**Review by littlecherro — COMMENTED** [review]
If I'm not wrong, i think we should be able to open the select with ENTER too. @briantang is that correct? At least in my PR i did it that way, if it's not necessary I'm changing it. AC from this tickets contemplates ENTER/SPACE to open things 👀

image

here i'm only able to open the dropdown with SPACE

**Review by littlecherro — CHANGES_REQUESTED** [review]
im unable to navigate to this part, but if i click it, it opens a modal.

image

**Comment by littlecherro** [comment]
> @iveyMarklogic i think we should have an outline here, because as a user im not really sure where i am after tabing out from the "close" icon on Load :(
> 
> image

NVM this, Martin tackled it in his PR :)

**Comment by littlecherro** [comment]
> If I'm not wrong, i think we should be able to open the select with ENTER too. @briantang is that correct? At least in my PR i did it that way, if it's not necessary I'm changing it. AC from this tickets contemplates ENTER/SPACE to open things 👀
> 
> image
> 
> here i'm only able to open the dropdown with SPACE

Hey @iveyMarklogic, from what we stated yesterday, we are going to open the select when focused (when we tab into it) and i think that's missing in these new changes.

**Review by littlecherro — CHANGES_REQUESTED** [review]
Check the component from the comment above on load screen :)

**Review by littlecherro — APPROVED** [review]
NICE :D

**Review by littlecherro — APPROVED** [review]

**Review by amejiaq — APPROVED** [review]

**Pull request merged**
