### PR TITLE
DHFPROD-835, DHFPROD-827 

### PR DESCRIPTION
**Pull request by kcoleman-marklogic**
Cleaned up of tutorial screenshots (shrinking,trimming, dropping) and text. I also dumped a number of unnecessary screenshots and the cutesy hand icon everywhere we tell users to click something. 

Updated non-UI portions of docs to reflect trace and jobs db merge. There's still some screenshot work required for DHFPROD-827, but it is blocked on DHFPROD-920.

Some of the screenshots that were not replaced will require editing before 3.1 because they still reflect the modeling UI pre-PII, but I left them because I wasn't working specifically on PII.

I'm not sure who should review this. I tapped Mike and Kasey. Feel free to recuse yourself. You'll probably have a hard time groking most of this without standing up a personal doc site with the changes.

### CODE REVIEW

**Comment by grechaw** [comment]
Hi @wooldridge this PR really needs review from someone familiar with the UI.

**Comment by wooldridge** [comment]
@grechaw, thanks, I am reviewing this.

**Comment by wooldridge** [comment]
I created a Jekyll server and reviewed the current Tutorial pages. Here are comments, I'm happy to make the changes...

---
Make the callouts in the screens consistent. 

- 12 screens have the new red callouts.
- 23 have the pink callouts. 

I don't have a strong preference for either. In the interest of time, I can update the red-version screens to have the pink callouts.

Red callouts:

/images/3x/create-product-entity/entities-select.png
/images/3x/create-product-entity/create-product-entity.png
/images/3x/create-product-input-flow/select-flows.png
/images/3x/create-product-input-flow/create-load-product-flow.png
/images/3x/load-products-as-is/configure-load-products.png
/images/3x/load-products-as-is/select-jobs.png
/images/3x/load-products-as-is/jobs-view.png
/images/3x/load-products-as-is/mlcp-output.png
/images/3x/load-products-as-is/click-lightning-bolt.png
/images/3x/browse-understand-product-data/select-browse.png
/images/3x/create-order-input-flow/create-load-order-flow.png
/images/3x/modeling-order-entity/edit-order-entity.png

---
http://127.0.0.1:4000/marklogic-data-hub/tutorial/create-order-input-flow/

The Data Format in the screen is XML. Should be JSON, the default.

---
http://127.0.0.1:4000/marklogic-data-hub/tutorial/install/

All-caps button labels should be bolded (example: "Click NEXT.").

Need to update tbe bottom screen based on merging of Jobs and Traces databases and updating of the Dashboard view (as Kim has pointed out: DHFPROD-920).

---
http://127.0.0.1:4000/marklogic-data-hub/tutorial/create-product-entity/

Step 4, bold "No".

Move the final screen shot up to under the steps it describes. Currently we show the final result and then show the user what already happened, this was odd for me.

---
http://127.0.0.1:4000/marklogic-data-hub/tutorial/load-products-as-is/

I would remove the ragged edging on the long screen shot. I found it distracting and out of place since we don't use it anywhere else. Maybe there is another way to communicate this or maybe we can just separate the screens.

In: "You should see a view similar to the following, reflecting the load products job we just completed:"

Change to "Load Products job" to match name.

In Jobs screen shot, use sentence casing to match similar screens elsewhere.

Add unlabeled callout to point out "x" in screenshot to help with the step that follows.

"To view the trace output from your load products job, click the lightning bolt icon ([icon]) on the far right of the job row. Alternatively, you can click Traces in the top navigation bar to see all traces."

Bold "lightning bolt" and "Traces" in the text above.

---
http://127.0.0.1:4000/marklogic-data-hub/tutorial/browse-understand-product-data/

"Click the first search result to see the raw document."

Has a hand icon preceding it. Looks like we've removed all these on previous pages so let's remove the rest.

Add thin CSS borders to all screenshots to avoid white space bordering white space in browser because that looks messy.

---
http://127.0.0.1:4000/marklogic-data-hub/tutorial/modeling-product-entity/

In steps, bold "pencil" in "pencil icon" and add actual pencil in parens. (Consistent with previous icon references.)
In steps, bold "key" in "key icon" and add actual key in parens.
(Check if there other instances of this.)

---
http://127.0.0.1:4000/marklogic-data-hub/tutorial/harmonizing-product-data/

Add cropped screen for "click Flows" step, similar to other pages.

Unbold "Product" in "documents in the Product collection".

Change: "Verify the harmonization job appears in the list and has finished."

To: "Verify the harmonization job appears in the list and has a <bold>FINISHED</bold> status."

---
http://127.0.0.1:4000/marklogic-data-hub/tutorial/create-order-entity/

Add cropped screen for "Click Entities" step, similar to other pages. Split that sentence appropriately.

Change "Click and Drag" to "Click and drag".

---
http://127.0.0.1:4000/marklogic-data-hub/tutorial/load-orders-as-is/

Add a screenshot (or screenshots) similar to:

http://127.0.0.1:4000/marklogic-data-hub/tutorial/load-products-as-is/

I know the above is a repeat of similar step but I think a typical user isn't familiar with the process and can use the hand holding.

Step 6, all caps for "Run Import".

---
http://127.0.0.1:4000/marklogic-data-hub/tutorial/modeling-order-entity/

Can we add padding to the modeling info table?

Add a screen for this step:

"To begin, click Entities in the top navigation bar, and then open the entity editor by clicking on the pencil icon in the upper right corner of the Order entity."

I think hand holding is appropriate.

For key and lightning bolt icons, bold the text and add the in-line icon in parens as in previous notes.

---
http://127.0.0.1:4000/marklogic-data-hub/tutorial/harmonizing-order-data/

Looks like more hand icons are here. Remove them to be consistent with other pages.

Two places: we have a "Click SAVE" where "SAVE" is an in-line button. Replace button with bold "SAVE" text to be consistent. Do the same with the "RUN HARMONIZE" button.

Under "View the Harmonized Orders", change to: "Make sure the job has a FINISHED status." Bold the "FINISHED".

---
http://127.0.0.1:4000/marklogic-data-hub/tutorial/wrapping-up/

Under "Uninstalling QuickStart", bold "Settings" and bold and all-cap "Uninstall Hub".

**Comment by kcoleman-marklogic** [comment]
Wow, thanks, @wooldridge. This is terrific feedback. I do have one question from a quick skim. You said:

>Add thin CSS borders to all screenshots to avoid white space bordering white space in browser because that looks messy.

I have not the slightest idea how to do that in our wonderful world of markdown and jekyll. Can you point me in the right direction? (I might be able to just add it to the images with my screencap editor, but I'll have to see.)

Also, you mentioned:

>In the interest of time, I can update the red-version screens to have the pink callouts.

I think there are better uses of your time and skills than faffing about with screenshots. :) I'll take on that task. The inconsistency is something I was aware of and planned to circle back to.

**Comment by wooldridge** [comment]
I did work on the above list, see: kcoleman-marklogic#2

Here is what is left:

http://127.0.0.1:4000/marklogic-data-hub/tutorial/install/

Need to update the bottom screen based on merging of Jobs and Traces databases and updating of the Dashboard view (as Kim has pointed out: DHFPROD-920).

**Comment by wooldridge** [comment]
@grechaw, I'm updating the QuickStart tutorial content to address the fact that the Traces database has been folded into the Jobs database. Here's what I have now:

> The following are the three databases and what they store:

> Staging: incoming data
> Final: harmonized data
> Jobs: data about the jobs run and debugging data about each harmonized document

Is that accurate?

**Comment by grechaw** [comment]
Yes, looks good from here.

**Comment by wooldridge** [comment]
I addressed all the items in my above comment list in the following PR: https://github.com/kcoleman-marklogic/marklogic-data-hub/pull/2

The following issue has been fixed so I was able to add an updated Dashboard screenshot: https://project.marklogic.com/jira/browse/DHFPROD-920

I also updated two screenshots that were missing the PII elements in the entity edit view.

@kcoleman-marklogic, if these updates look OK, I would go ahead and:

1. Merge my PR with your docs-develop branch.
2. Rebase and merge this PR.

**Pull request merged**
