### PR TITLE
DHFPROD-5652: added focus and focus indicator to close buttons

### PR DESCRIPTION
**Pull request by jyangML**
### Description
See comment for full list of buttons affected by this PR.
#### Checklist: 
```diff
- Note: do not change the below
```

-  ##### Owner:

- [x] JIRA_ID included in all the commit messages
- [x] PR title is in the format JIRA_ID:Title
- [x] Rebase the branch with upstream
- [x] Squashed all commits into a single commit
- [x] Code passes ESLint tests
- [N/A] Added Tests
  

- ##### Reviewer:

- [N/A] Reviewed Tests

### CODE REVIEW

**Comment by jyangML** [comment]
List of "Close" buttons in this PR (ordered by tile):

load
* load tile header
* add new loading step
* advanced step settings
* edit loading step
* delete step

model
* model tile header
* add entity type
* edit entity type
* edit (entity type) property
* delete property
* add structured type property

curate
* curate tile header
* (all) add new step
* (map, match) step details
* (all) step settings
* (all) delete step

run
* run tile header
* create flow
* edit flow
* remove flow
* add (new, existing) step
* remove step

explore
* explore tile header
* manage queries
* edit query
* export query
* delete query

**Review by wooldridge — CHANGES_REQUESTED** [review]
@jyangML, I'm seeing minor linting issues, can you fix and force-push?
```
/Users/mwooldri/projects/marklogic-data-hub/marklogic-data-hub-central/ui/src/components/entities/matching/ruleset-single-modal/ruleset-single-modal.tsx
  248:6  error  Trailing spaces not allowed  no-trailing-spaces

/Users/mwooldri/projects/marklogic-data-hub/marklogic-data-hub-central/ui/src/components/tiles/tiles.tsx
  142:1  error  Expected indentation of 14 spaces but found 12  indent

✖ 2 problems (2 errors, 0 warnings)
  2 errors and 0 warnings potentially fixable with the `--fix` option.
```

**Comment by jyangML** [comment]
Ran lint through entire code base.  This PR now has a unrelated few style changes too

**Review by briantang — APPROVED** [review]
All close buttons have prominent keyboard focus now. Looks good.

**Review by xnikhil08 — APPROVED** [review]

**Review by wooldridge — APPROVED** [review]

**Pull request merged**
