### PR TITLE
DHFPROD-4743:Entity table is skewed when the error from XPATH expression is longer

### PR DESCRIPTION
**Pull request by srinathgit**
### Description
Entity table is skewed when the error from XPATH expression is longer. This PR also fixes the issue of 'Type' not displaying fully in entity table. I am not sure if this requires test and if so please provide suggestions as to what kind of tests to add
#### Checklist: 
```diff
- Note: do not change the below
```

-  ##### Owner:

- [x] JIRA_ID included in all the commit messages
- [x] PR title is in the format JIRA_ID:Title
- [x] Rebase the branch with upstream
- [x] Squashed all commits into a single commit
- [x] Added Tests
  

- ##### Reviewer:

- [x] Reviewed Tests

### CODE REVIEW

**Comment by bsrikan** [comment]
@srinathgit can you pls add a screenshot of the fix to understand what to expect as it might help understand how to unit test this.

**Comment by srinathgit** [comment]
> @srinathgit can you pls add a screenshot of the fix to understand what to expect as it might help understand how to unit test this.

image

**Comment by bsrikan** [comment]
> > @srinathgit can you pls add a screenshot of the fix to understand what to expect as it might help understand how to unit test this.
> 
>     1. 'Type' in entity table is fixed
> 
>     2. The xpath expression error doesn't spill over (see bug for how it was earlier)
>        image

Can you try and verify that error and expression text box have same width given xpath expression in the image?

**Comment by srinathgit** [comment]
> > > @srinathgit can you pls add a screenshot of the fix to understand what to expect as it might help understand how to unit test this.
> > 
> > 
> > ```
> > 1. 'Type' in entity table is fixed
> > 
> > 2. The xpath expression error doesn't spill over (see bug for how it was earlier)
> >    image
> > ```
> 
> Can you try and verify that error and expression text box have same width given xpath expression in the image?

There are no tests for the "Test/Clear" button feature. Once the tests for those go in, I can add a line to verify the width of the 2 are equal.

**Comment by bsrikan** [comment]
Needs a rebase.

**Pull request merged**
