### PR TITLE
DHFPROD-5975: Screen corruption after Select Flow on Load Screen

### PR DESCRIPTION
**Pull request by AkshayBajajML**
#### Checklist: 
```diff
- Note: do not change the below
```

-  ##### Owner:

- [x] JIRA_ID included in all the commit messages
- [x] PR title is in the format JIRA_ID:Title
- [x] Rebase the branch with upstream
- [x] Squashed all commits into a single commit
- N/A Added Tests
  

- ##### Reviewer:

- N/A Reviewed Tests

### CODE REVIEW

**Review by wooldridge — DISMISSED** [review]
Looks good, I see it fixed in both the Load and Mapping tiles:

https://drive.google.com/file/d/1wAfDjv-OOj2HgzcBZfNDOtcxeCanS1NN/view

Also checked in Windows.

**Review by briantang — APPROVED** [review]
Nice!

**Review by timur-isangulov — DISMISSED** [review]

**Comment by AkshayBajajML** [comment]
Fixed test case failure

**Review by briantang — APPROVED** [review]

**Review by wooldridge — APPROVED** [review]
I'm seeing unit tests pass. Approved!

**Pull request merged**
