### PR TITLE
DHFPROD-5878:Stop table scrolling in Explorer

### PR DESCRIPTION
**Pull request by Sanjeevani19**
This reverts commit cc6c322ce87e879adac2d433054ed55e98ef1bb7, please refer DHFPROD-5878 ticket for reasons to revert this commit.
Reverting this commit also fixes some explorer e2e tests(https://project.marklogic.com/jira/browse/DHFPROD-6004) failing on DHS

#### Checklist: 
```diff
- Note: do not change the below
```

-  ##### Owner:

- [x] JIRA_ID included in all the commit messages
- [x] PR title is in the format JIRA_ID:Title
- [x] Rebase the branch with upstream
- [x] Squashed all commits into a single commit
- [x] Added Tests
  

- ##### Reviewer:

- [x] Reviewed Tests

### CODE REVIEW

**Review by rjrudin — CHANGES_REQUESTED** [review]
The JIRA ticket is for 5.4, but this is pointed at develop. Should be 5.4-develop, right?

**Comment by Sanjeevani19** [comment]
> The JIRA ticket is for 5.4, but this is pointed at develop. Should be 5.4-develop, right?

@rjrudin Initially it was planned for 5.3, I changed it to 5.4 this morning since the fix needs a lot of changes(https://project.marklogic.com/jira/browse/DHFPROD-5878).This PR is only to revert the commit which already got merged to develop as part of the other PR (https://github.com/marklogic/marklogic-data-hub/pull/4570) and to get it back to the original state where it was working.

**Review by timur-isangulov — APPROVED** [review]
Revert commit for 5.3 looks good.

**Review by rjrudin — APPROVED** [review]
Sorry, I missed the part about a revert

**Review by wooldridge — APPROVED** [review]

**Pull request merged**
