### PR TITLE
DHFPROD-7574: Create relationship via Add relationship button

### PR DESCRIPTION
**Pull request by briantang**
### Description

- Can now create relationships via dragging edges between nodes or clicking on a node with edit mode
- Demo here: https://drive.google.com/file/d/1-q9HPD2c7YoJ1I8GYNbMm20IEn-PtbGR/view
- UX approved by Jamie

#### Checklist: 
```diff
- Note: do not change the below
```

-  ##### Owner:

- [x] JIRA_ID included in all the commit messages
- [x] PR title is in the format JIRA_ID:Title
- [x] Rebase the branch with upstream
- [x] Squashed all commits into a single commit
- [x] Code passes ESLint tests
- [x] Added Tests
- [x] Run UI tests
  

- ##### Reviewer:

- [x] Reviewed Tests

### CODE REVIEW

**Review by xnikhil08 — DISMISSED** [review]
Looks good.

**Comment by briantang** [comment]
Briefly added some missing styling/functionality across graph view for when no edit permissions are present. Ready for re-review

**Review by xnikhil08 — APPROVED** [review]

**Comment by briantang** [comment]
@wooldridge The asterick was requested by Jamie and Matthew to show that the field is required. It is to be consistent with the relationship field placeholder which also has an asterick towards the end because it is a required field.

**Comment by wooldridge** [comment]
> @wooldridge The asterick was requested by Jamie and Matthew to show that the field is required. It is to be consistent with the relationship field placeholder which also has an asterick towards the end because it is a required field.

If we have asterisked content, I would expect that asterisk to reference a legend (or whatever you want to call it) describing why the asterisk is there. I know an asterisk is common for required form fields, perhaps to the point where it is generally understood that it means, but in this case we're not dealing with a standard form and I was confused looking for what the asterisk meant.

**Review by wooldridge — CHANGES_REQUESTED** [review]
Looks like if I don't select a Join Property I get an error in the browser? Is that being handled separately?

https://drive.google.com/file/d/1FpL2g94H6TcVmooT41582DFkn9_6eYLc/view

**Comment by briantang** [comment]
@wooldridge Correct, there is no BE support for that yet, so it will be handled with DHFPROD-7575.

**Comment by briantang** [comment]
Added footnote for asterick clarification, approved by UX.

**Review by wooldridge — APPROVED** [review]

**Review by Sanjeevani19 — APPROVED** [review]

**Pull request merged**
