### PR TITLE
DHFPROD-4520: Refactored explorer ui into one ui codebase

### PR DESCRIPTION
**Pull request by brucean52**

### CODE REVIEW

**Comment by bsrikan** [comment]
Looks good to me. It should be safe to move over explorer-ui/e2e under one-ui/ui/e2e and the cypress.json files. 
Might have to carefully pick some dev-dependencies from package.json

**Comment by brucean52** [comment]
I can move the folder and files over, but I'm not familiar enough with it to get it working. Do you want me to do another commit?

**Comment by bsrikan** [comment]
@timur-isangulov can you try fetching Bruce's commits in this PR, copy over the cypress folder and related config files and see if cypress tests continue to run?

**Comment by timur-isangulov** [comment]
> @timur-isangulov can you try fetching Bruce's commits in this PR, copy over the cypress folder and related config files and see if cypress tests continue to run?

Hi @bsrikan cypress e2e has it's own package.json and doesn't depend on explorer-ui project.

**Comment by bsrikan** [comment]
@brucean52 can you pls make another commit moving over e2e under one-ui/ui/src. @timur-isangulov can then verify if tests run ok

**Comment by timur-isangulov** [comment]
@bsrikan I was able to build and run cypress tests at the new directory marklogic-data-hub/one-ui/ui/e2e

**Comment by brucean52** [comment]
> * Also the search bar and sidebar facets needs to be fixed when scrolling

They are currently fixed, but I removed margin-top for it. We will probably need to tweak the CSS more once the tiles are ready.

**Comment by bsrikan** [comment]
@timur-isangulov @Sanjeevani19 is it looking good now after Bruce's recent push. Whenever you can get to it, pls update the story or this PR with latest findings. Thanks!

**Comment by Sanjeevani19** [comment]
> @timur-isangulov @Sanjeevani19 is it looking good now after Bruce's recent push. Whenever you can get to it, pls update the story or this PR with latest findings. Thanks!

Apart from few CSS tweaks which can be handled later, everything looks good to me

**Comment by timur-isangulov** [comment]
I pushed fix for e2e, please review.

**Pull request merged**
