### PR TITLE
DHFPROD-6002: Refactoring manage query component to be available in Explore tile header

### PR DESCRIPTION
**Pull request by xnikhil08**
### Description
Fixing the bugs mentioned in the ticket DHFPROD-6002 and DHFPROD-6347.

#### Checklist: 
```diff
- Note: do not change the below
```

-  ##### Owner:

- [x] JIRA_ID included in all the commit messages
- [x] PR title is in the format JIRA_ID:Title
- [x] Rebase the branch with upstream
- [x] Squashed all commits into a single commit
- [x] Added Tests
  

- ##### Reviewer:

- [x] Reviewed Tests

### CODE REVIEW

**Review by timur-isangulov — CHANGES_REQUESTED** [review]
Hi @xnikhil08, I see three extra requests when applying saved query from the Browse view. I attached the screenshots of the current develop and this pr
Develop
pr 4979

.

**Review by timur-isangulov — CHANGES_REQUESTED** [review]
Clear Query icon doesn't open Explore Zero State page if the manage query dialog was opened from the detail view. Please see video https://drive.google.com/file/d/1hCbrgmb2pD8E2pjALGof-ixDbbJVvRPi/view

**Comment by timur-isangulov** [comment]
I see the database parameter to be undefined on the Browse page after applying the previously saved query on the detail view. https://drive.google.com/file/d/1ljw3nwQXt0cNRAioGrcWQm0yXa93Fb_I/view

**Comment by timur-isangulov** [comment]
> Click on Clear Query icon doesn't open Explore Zero State page if the manage query dialog was opened from the detail view. Please see video https://drive.google.com/file/d/1hCbrgmb2pD8E2pjALGof-ixDbbJVvRPi/view

I can reproduce this issue on recent develop, as well. Opened a regression bug  https://project.marklogic.com/jira/browse/DHFPROD-6348.

**Comment by timur-isangulov** [comment]
> I see the database parameter to be undefined on the Browse page after applying the previously saved query on the detail view. https://drive.google.com/file/d/1ljw3nwQXt0cNRAioGrcWQm0yXa93Fb_I/view

Opened a separate bug for this issue https://project.marklogic.com/jira/browse/DHFPROD-6347 since it's reproducible on  develop.

**Comment by xnikhil08** [comment]
> Hi @xnikhil08, I see three extra requests when applying saved query from the Browse view. I attached the screenshots of the current develop and this pr
> Develop:
> Develop
> PR:
> pr 4979
> 
> .

@timur-isangulov - Now that the manage query modal is out of the browse component, it doesn't render unless user clicks on the manage query button on top right of explore tile. As discussed the behavior seems to be appropriate.

**Comment by xnikhil08** [comment]
> Click on Clear Query icon doesn't open Explore Zero State page if the manage query dialog was opened from the detail view. Please see video https://drive.google.com/file/d/1hCbrgmb2pD8E2pjALGof-ixDbbJVvRPi/view

@timur-isangulov - As discussed, this is a regression bug in develop as well. It will be taken care of in a separate ticket as given below.
https://project.marklogic.com/jira/browse/DHFPROD-6348

**Review by timur-isangulov — APPROVED** [review]
Looks good.

**Review by Sanjeevani19 — APPROVED** [review]

**Review by brucean52 — APPROVED** [review]

**Pull request merged**
