### PR TITLE
DHFPROD-5923: Updated Relationship to Related Entities

### PR DESCRIPTION
**Pull request by brucean52**
#### Checklist: 
```diff
- Note: do not change the below
```

-  ##### Owner:

- [x] JIRA_ID included in all the commit messages
- [x] PR title is in the format JIRA_ID:Title
- [x] Rebase the branch with upstream
- [x] Squashed all commits into a single commit
- [x] Added Tests
  

- ##### Reviewer:

- [x] Reviewed Tests

### CODE REVIEW

**Comment by rjrudin** [comment]
One nit - let's only say "refactor" when the changes result in no change in functionality that is visible to the client of the software being changed, whether the client is a human or some other piece of software.

**Review by xnikhil08 — APPROVED** [review]
Looks good.

**Review by akshaysonvane — APPROVED** [review]

**Comment by SameeraPriyathamTadikonda** [comment]
one cypress test is failing.

**Comment by brucean52** [comment]
> one cypress test is failing.

The cypress failure isn't related to this PR.

**Pull request merged**
