### PR TITLE
DHFPROD-6098: Create endpoint for fetching source document for mapping UI

### PR DESCRIPTION
**Pull request by brent-hartwig**
### Description
Replacement PR for https://github.com/marklogic/marklogic-data-hub/pull/4804.  This PR only has one commit.

Offer the `/api/steps/mapping/{stepName}/testingDoc` endpoint where the intent is to enable the mapping UI to retrieve a source document associated to a step.

Supports XML and JSON formatted source documents but only ever returns a JSON representation. The implementation relies on fast-xml-parser to convert XML to JSON. Version v3.17.1 thereof was introduced to the backend. The frontend is already set up to use version ^3.16.0.

`/api/steps/mapping/{stepName}/testingDoc` is to replace `/api/steps/mapping/{stepName}/doc`.  A separate PR is expected to remove the latter.

#### Checklist: 
```diff
- Note: do not change the below
```

-  ##### Owner:

- [x] JIRA_ID included in all the commit messages
- [ ] PR title is in the format JIRA_ID:Title
- [ ] Rebase the branch with upstream
- [ ] Squashed all commits into a single commit
- [ ] Added Tests
  

- ##### Reviewer:

- [ ] Reviewed Tests

### CODE REVIEW

**Review by rjrudin — APPROVED** [review]

**Review by srinathgit — CHANGES_REQUESTED** [review]
When I use the endpoint to fetch doc  /Customer/CustXMLDoc1.xml with step mapCustomersXML from reference-entity-model project(http://localhost:3000/api/steps/mapping/mapCustomersXML/testingDoc?docUri=/Customer/CustXMLDoc1.xml), I get the following error
```
2020-11-09 23:07:09.430 Notice: JS-JAVASCRIPT: for (let [key, value] of Object.entries(jsonIn)) { -- Error running JavaScript request: TypeError: Object.entries(...)[Symbol.iterator] is not a function
2020-11-09 23:07:09.430 Notice:+in /data-hub/5/data-services/mapping/xmlToJsonForMapping.sjs, at 99:34, in _transform() [javascript]
2020-11-09 23:07:09.430 Notice:+in /data-hub/5/data-services/mapping/xmlToJsonForMapping.sjs, at 308:10, in transform() [javascript]
2020-11-09 23:07:09.430 Notice:+in /data-hub/5/data-services/mapping/getDocumentForTesting.sjs, at 51:63 [javascript]
2020-11-09 23:07:09.430 Notice:+in /data-hub/5/data-services/mapping/getDocumentForTesting.sjs [javascript]
2020-11-09 23:07:09.432 Info: Status 500: JS-JAVASCRIPT: for (let [key, value] of Object.entries(jsonIn)) { -- Error running JavaScript request: TypeError: Object.entries(...)[Symbol.iterator] is not a function
```

**Comment by rjrudin** [comment]
@srinathgit  What version of ML is that? @brent-hartwig That looks like an SJS feature that isn't supported on ML 9, and DHF still has to support the latest version of 9.

**Comment by brent-hartwig** [comment]
Roger that.  Will test on 9 today.  Thank you.

**Comment by srinathgit** [comment]
> Roger that. Will test on 9 today. Thank you.

I forgot to mention the server version. It is indeed 9.0-x (9.0-12 to be precise).

**Comment by brent-hartwig** [comment]
Replaced by https://github.com/marklogic/marklogic-data-hub/pull/4844

**Pull request closed without merging**
