### PR TITLE
DHFPROD-9135: Merge documents modal icons

### PR DESCRIPTION
**Pull request by briantang**
### Description

- Added merge icon setup for merge notifications in Explore (only in All Data Card view)
- Includes @AkshayBajajML 's backend changes
- Reference:
Screen Shot 2022-07-29 at 11 22 09 AM

#### Checklist: 
```diff
- Note: do not change the below
```

- ##### Owner:

- [x] JIRA_ID included in all the commit messages
- [x] PR title is in the format JIRA_ID:Title
- [x] Rebase the branch with upstream
- [x] Squashed all commits into a single commit
- [x] Code passes ESLint tests
- [x] Added Tests
- [x] Ran cypress tests on firefox locally
  

- ##### Reviewer:

- [x] Reviewed Tests
- [x] Added to Release Wiki

### CODE REVIEW

**Review by AkshayBajajML — CHANGES_REQUESTED** [review]
Icon appears in correct documents.
It has missing hover color.
Screen Shot 2022-07-29 at 4 18 32 PM

**Comment by briantang** [comment]
Added hover effects.

**Comment by briantang** [comment]
This is ready for review again.

**Review by AkshayBajajML — DISMISSED** [review]
Looks Good!!

**Review by ryanjdew — DISMISSED** [review]

**Review by ryanjdew — APPROVED** [review]

**Review by AkshayBajajML — APPROVED** [review]

**Pull request merged**
