### PR TITLE
DHFPROD-9382: Does not correctly work the initial view in curate.

### PR DESCRIPTION
**Pull request by senumulapally**
#### Checklist: 
```diff
- Note: do not change the below
```

- ##### Owner:

- [x] JIRA_ID included in all the commit messages
- [x] PR title is in the format JIRA_ID:Title
- [x] Rebase the branch with upstream
- [x] Squashed all commits into a single commit
- [x] Code passes ESLint tests
- [x] Ran cypress tests on firefox locally
  

- ##### Reviewer:

- [x] Reviewed Tests
- [x] Added to Release Wiki

### CODE REVIEW

**Review by littlecherro — CHANGES_REQUESTED** [review]
Hey, i was testing you changes and this came up:

with clean qa project, i created a new entity, published and went to curate

image

**Review by littlecherro — APPROVED** [review]
Looks good :)

**Review by Sanjeevani19 — COMMENTED** [review]
@senumulapally let's add a test to cover this scenario, see if it can be added as a part of RTL

**Comment by littlecherro** [comment]
hey @senumulapally let fix the text "This functionality implemented yet." to a clearer one :)

**Comment by senumulapally** [comment]
Added a cypress e2e test case and I also changed the text to 'This functionality is not implemented yet.'

**Review by littlecherro — APPROVED** [review]

**Comment by briantang** [comment]
Needs an RTL test fix since one of the tests are failing.

**Review by briantang — APPROVED** [review]

**Pull request merged**
