### PR TITLE
DHFPROD-6645: Front-end: Each after match save, call validation API a…

### PR DESCRIPTION
**Pull request by AkshayBajajML**
…nd display warnings if they exist

#### Checklist: 
```diff
- Note: do not change the below
```

-  ##### Owner:

- [x] JIRA_ID included in all the commit messages
- [x] PR title is in the format JIRA_ID:Title
- [x] Rebase the branch with upstream
- [x] Squashed all commits into a single commit
- [x] Code passes ESLint tests
- [x] Added Tests
  

- ##### Reviewer:

- [x] Reviewed Tests

### CODE REVIEW

**Comment by AkshayBajajML** [comment]
Got UI changes reviewed by @jbelonoj

**Comment by ngodugu-marklogic** [comment]
@AkshayBajajML The E2E scripts are failing due to below reasons
1. When we create a duplicate match step, the new match step modal disappears and an error message saying it is a duplicate step gets displayed and when we click on okay it closes, But the create new match step modal is still displayed on the screen
2. When we create a new map step and save, it should automatically open the step details modal. This is not happening.

Can confirm if these changes are expected.

**Comment by AkshayBajajML** [comment]
> @AkshayBajajML The E2E scripts are failing due to below reasons
> 
> 1. When we create a duplicate match step, the new match step modal disappears and an error message saying it is a duplicate step gets displayed and when we click on okay it closes, But the create new match step modal is still displayed on the screen
> 2. When we create a new map step and save, it should automatically open the step details modal. This is not happening.
> 
> Can confirm if these changes are expected.

Yeah I can reproduce and these issues need to be fixed. 
Working on them and thanks for the comments

**Comment by AkshayBajajML** [comment]
> > @AkshayBajajML The E2E scripts are failing due to below reasons
> > 
> > 1. When we create a duplicate match step, the new match step modal disappears and an error message saying it is a duplicate step gets displayed and when we click on okay it closes, But the create new match step modal is still displayed on the screen
> > 2. When we create a new map step and save, it should automatically open the step details modal. This is not happening.
> > 
> > Can confirm if these changes are expected.
> 
> Yeah I can reproduce and these issues need to be fixed.
> Working on them and thanks for the comments

Resolved the mentioned issues and now integration tests pass.

**Review by ngodugu-marklogic — APPROVED** [review]
LGTM!

**Review by Sanjeevani19 — APPROVED** [review]

**Pull request merged**
