### PR TITLE
DHFPROD-5597: Show search link when facets > 20

### PR DESCRIPTION
**Pull request by wooldridge**
### Description

Popover search link only shown for a facet when number of facet items is great than a limit (20).

#### Checklist: 
```diff
- Note: do not change the below
```

-  ##### Owner:

- [x] JIRA_ID included in all the commit messages
- [x] PR title is in the format JIRA_ID:Title
- [x] Rebase the branch with upstream
- [x] Squashed all commits into a single commit
- [x] Added Tests
  

- ##### Reviewer:

- [x] Reviewed Tests

### CODE REVIEW

**Review by xnikhil08 — DISMISSED** [review]
Working as expected.

**Review by Sanjeevani19 — APPROVED** [review]

**Comment by SameeraPriyathamTadikonda** [comment]
@wooldridge Please rebase the branch

**Comment by wooldridge** [comment]
@SameeraPriyathamTadikonda, rebased, ready for re-review.

**Comment by bsrikan** [comment]
@SameeraPriyathamTadikonda this PR has a test refactored and so there is a difference in what we have here in 5.4-develop vs develop.. Do you anticipate any issues given the difference.

**Review by bsrikan — APPROVED** [review]

**Review by briantang — APPROVED** [review]

**Comment by SameeraPriyathamTadikonda** [comment]
> @SameeraPriyathamTadikonda this PR has a test refactored and so there is a difference in what we have here in 5.4-develop vs develop.. Do you anticipate any issues given the difference.

It shouldn't be a problem.

**Pull request merged**
