### PR TITLE
DHFPROD-7532: Add new entity type from graph UI

### PR DESCRIPTION
**Pull request by wooldridge**
### Description

Screencast here: https://drive.google.com/file/d/1e4wdlhIGGY4Hm4-RhigH8efHlsdcLtA4/view

E2E test added in new graph.spec.tsx file. 

#### Checklist: 
```diff
- Note: do not change the below
```

-  ##### Owner:

- [x] JIRA_ID included in all the commit messages
- [x] PR title is in the format JIRA_ID:Title
- [x] Rebase the branch with upstream
- [x] Squashed all commits into a single commit
- [x] Code passes ESLint tests
- [x] Added Tests
- [x] Run UI tests
  

- ##### Reviewer:

- [x] Reviewed Tests

### CODE REVIEW

**Comment by wooldridge** [comment]
E2E and unit tests are passing but this just came up, will restart (@ngodugu-marklogic):
Screen Shot 2021-08-05 at 10 11 49 AM
Screen Shot 2021-08-05 at 10 12 14 AM

**Review by AkshayBajajML — CHANGES_REQUESTED** [review]
**Looks Good**!! only one minor issue
- Getting error on deleting the entity from tabular view and switching back to graph view

https://user-images.githubusercontent.com/66277536/128408457-bf136401-1c5c-4037-84b8-4de425b7ca03.mov

**Comment by wooldridge** [comment]
> **Looks Good**!! only one minor issue
> 
> * Getting error on deleting the entity from tabular view and switching back to graph view
> 

Thanks for catching, I will look into it.

**Comment by xnikhil08** [comment]
> > **Looks Good**!! only one minor issue
> > 
> > * Getting error on deleting the entity from tabular view and switching back to graph view
> 
> Thanks for catching, I will look into it.

@wooldridge & @AkshayBajajML - I faced something similar while working on the deletion of entity story. I am refactoring the deletion logic to the parent Modeling component for both, Table view and Graph view, which should resolve this issue as well.

**Comment by wooldridge** [comment]
Fixed conflicts and the deletion error issue but I'm seeing an issue with new-entity selection (not highlighting) so need to investigate that a bit more.

**Review by briantang — CHANGES_REQUESTED** [review]
Functionality looks good. I believe there are just some related UI tests failing in the pipeline now (in Modeling.test.tsx). Looks like there are additional calls being made to the backend on init.

`Error: expect(jest.fn()).toHaveBeenCalledTimes(expected)
Expected number of calls: 1
Received number of calls: 2
`

**Review by briantang — APPROVED** [review]

**Review by ngodugu-marklogic — APPROVED** [review]

**Review by AkshayBajajML — APPROVED** [review]

**Pull request merged**
