### PR TITLE
DHFPROD-6092: Fixing the issue where switching between all data to entity sometimes switches to all entities

### PR DESCRIPTION
**Pull request by xnikhil08**
### Description
Just a fix for the bug described in the associated JIRA ticket. Also, contains fix for few e2e testing edge cases.

#### Checklist: 
```diff
- Note: do not change the below
```

-  ##### Owner:

- [x] JIRA_ID included in all the commit messages
- [x] PR title is in the format JIRA_ID:Title
- [x] Rebase the branch with upstream
- [x] Squashed all commits into a single commit
- [x] Added Tests
  

- ##### Reviewer:

- [x] Reviewed Tests

### CODE REVIEW

**Comment by timur-isangulov** [comment]
HI @xnikhil08, I noticed that switching from All Data to an entity looks slower and the document count changes few times during rendering https://drive.google.com/file/d/1leTGAhnZIrA2CfHakSPHgqjBhIBZTCMN/view

**Review by timur-isangulov — CHANGES_REQUESTED** [review]
HI @xnikhil08, I noticed that switching from All Data to an entity causes page to re-render two times and the document count changes few times https://drive.google.com/file/d/1leTGAhnZIrA2CfHakSPHgqjBhIBZTCMN/view

**Comment by xnikhil08** [comment]
> HI @xnikhil08, I noticed that switching from All Data to an entity causes page to re-render two times and the document count changes few times https://drive.google.com/file/d/1leTGAhnZIrA2CfHakSPHgqjBhIBZTCMN/view

@timur-isangulov - Can you check again? Just pushed a fix.

**Review by timur-isangulov — APPROVED** [review]

**Review by Sanjeevani19 — APPROVED** [review]

**Review by Sanjeevani19 — CHANGES_REQUESTED** [review]
@xnikhil08 This PR needs a rebase.

**Review by Sanjeevani19 — DISMISSED** [review]

**Review by timur-isangulov — CHANGES_REQUESTED** [review]
Hi @xnikhil08 I noticed an issue when applying the facet search for the entity and switching to the All data displays raw card when select cancel on modal https://drive.google.com/file/d/1wxoprDIq3SGlI8o35ENbDW2LGMgBwdVe/view

**Comment by xnikhil08** [comment]
> Hi @xnikhil08 I noticed an issue when applying the facet search for the entity and switching to the All data displays raw card when select cancel on modal https://drive.google.com/file/d/1wxoprDIq3SGlI8o35ENbDW2LGMgBwdVe/view

@timur-isangulov - Can you review again. ? I've pushed a fix for the issue.

**Comment by timur-isangulov** [comment]
> > Hi @xnikhil08 I noticed an issue when applying the facet search for the entity and switching to the All data displays raw card when select cancel on modal https://drive.google.com/file/d/1wxoprDIq3SGlI8o35ENbDW2LGMgBwdVe/view
> 
> @timur-isangulov - Can you review again. ? I've pushed a fix for the issue.

Hi @xnikhil08 the previous issue is fixed but I just noticed one more during testing, it looks like the the props.item.primaryKey is missing on search-result.tsx component if switching to the entity from All Data with snippet view previously enabled. 
Screen Shot 2020-10-14 at 9 34 02 AM

https://drive.google.com/file/d/1RbddjWEFXeKwtX-_M8JBX2dapZ9Ztubr/view

**Comment by xnikhil08** [comment]
> > > Hi @xnikhil08 I noticed an issue when applying the facet search for the entity and switching to the All data displays raw card when select cancel on modal https://drive.google.com/file/d/1wxoprDIq3SGlI8o35ENbDW2LGMgBwdVe/view
> > 
> > 
> > @timur-isangulov - Can you review again. ? I've pushed a fix for the issue.
> 
> Hi @xnikhil08 the previous issue is fixed but I just noticed one more during testing, it looks like the the props.item.primaryKey is missing on search-result.tsx component if switching to the entity from All Data with snippet view previously enabled.
> Screen Shot 2020-10-14 at 9 34 02 AM
> 
> https://drive.google.com/file/d/1RbddjWEFXeKwtX-_M8JBX2dapZ9Ztubr/view

@timur-isangulov - Can you check again?

**Review by timur-isangulov — APPROVED** [review]
Opened a jira ticket for couple of issues noticed in the pr but not related to DHFPROD-6092  https://project.marklogic.com/jira/browse/DHFPROD-6135

**Review by rahulvudutala — APPROVED** [review]

**Pull request merged**
