### PR TITLE
DHFPROD-8011: Page replacement

### PR DESCRIPTION
**Pull request by yubiselmarklogic**
#### Checklist: 
```diff
- Note: do not change the below
```

-  ##### Owner:

- [x] JIRA_ID included in all the commit messages
- [x] PR title is in the format JIRA_ID:Title
- [x] Rebase the branch with upstream
- [x] Squashed all commits into a single commit
- [x] Code passes ESLint tests
- [x] Added Tests
- [x] Run UI tests
  

- ##### Reviewer:

- [x] Reviewed Tests

### CODE REVIEW

**Review by MSBrignoni — DISMISSED** [review]

**Review by iveyMarklogic — APPROVED** [review]

**Review by briantang — CHANGES_REQUESTED** [review]
Have these designs been checked with UX? The alignment looks off.
PR: 
Screen Shot 2021-11-08 at 1 20 08 PM

Nightly:
Screen Shot 2021-11-08 at 1 21 04 PM

**Comment by yubiselmarklogic** [comment]
@briantang done

**Review by iveyMarklogic — APPROVED** [review]

**Review by briantang — CHANGES_REQUESTED** [review]
Couple e2e failures regarding the Modal that appear related.

**Comment by yubiselmarklogic** [comment]
@briantang fixed

**Review by iveyMarklogic — APPROVED** [review]

**Review by mrodrigu-marklogic — APPROVED** [review]

**Review by briantang — APPROVED** [review]

**Pull request merged**
