### PR TITLE
DHFPROD-7871: Populate entity-specific side panel

### PR DESCRIPTION
**Pull request by federicoRufrancosMarklogic**
UX checked the implementation and some updated where done.
Found an issue with the DateRangePicker component, as it's displaying at the bottom of  the facets it's not been fully displayed and I cannot scroll more to the bottom.

#### Checklist: 
```diff
- Note: do not change the below
```

-  ##### Owner:

- [X] JIRA_ID included in all the commit messages
- [X] PR title is in the format JIRA_ID:Title
- [X] Rebase the branch with upstream
- [X] Squashed all commits into a single commit
- [X] Code passes ESLint tests
- [X] Added Tests
- [X] Run UI tests
  

- ##### Reviewer:

- [x] Reviewed Tests

### CODE REVIEW

**Review by AkshayBajajML — CHANGES_REQUESTED** [review]
Nice Work! I have few observations:

- Placeholder for search entity at side panel says "Please select target database". I am thinking it should be something related to selected entity.
- When we select all entities in the dropdown, it does not filter as expected.
- Can we change the cursor to pointer for the red highlighted part of below screenshot. Since it routes user to back screen. Adding some tooltip will help.
Screen Shot 2022-01-17 at 10 52 33 AM
Screen Shot 2022-01-17 at 10 55 00 AM

**Comment by federicoRufrancosMarklogic** [comment]
@AkshayBajajML change requested pushed
* Placeholder for search entity at side panel says "Please select target database". I am thinking it should be something related to selected entity. 
REMOVED, I TALK WITH YUBISEL BECAUSE HE ADD IT, AND HE TOLD ME THAT THERE SHOULDN'T BE PLACEHOLDER AT ALL HERE, BY DEFAULT SHOULD SHOW "ALL ENTITES" SELECTED
* When we select all entities in the dropdown, it does not filter as expected.
THERE WAS A BUG INTRUDUCED ON ANT <SELECT/> REPLACED, SOLVED 
Can we change the cursor to pointer for the red highlighted part of below screenshot. Since it routes user to back screen. Adding some tooltip will help.
* CHANGED!

**Review by AkshayBajajML — CHANGES_REQUESTED** [review]
I cannot see tooltip and pointer cursor. I can see other changes and those look good.

**Review by xnikhil08 — CHANGES_REQUESTED** [review]
Closing the Base entities dropdown, turns back to All Entities option.
https://watch.screencastify.com/v/aJFjW5wcHjNE0AYhOTxt

**Comment by federicoRufrancosMarklogic** [comment]
Can check not the functionality now @AkshayBajajML @xnikhil08.

**Comment by AkshayBajajML** [comment]
> Can check not the functionality now @AkshayBajajML @xnikhil08.

Looks Good!!
I still see same issue as mentioned by @xnikhil08(Closing the Base entities dropdown, turns back to All Entities option).

**Review by AkshayBajajML — APPROVED** [review]

**Review by briantang — APPROVED** [review]

**Review by AkshayBajajML — APPROVED** [review]

**Review by xnikhil08 — APPROVED** [review]

**Pull request merged**
