### PR TITLE
DHFPROD-3614: Provide UI help for finding resources on XPath and available functions

### PR DESCRIPTION
**Pull request by xnikhil08**

### CODE REVIEW

**Comment by xnikhil08** [comment]
> The white box around the question mark seems off to one side in both Chrome and FF. Needs to be fixed.
> 
> Chrome 78:
> image
> 
> FF70:
> image

@bsrikan - This is fixed. Please review again.

**Comment by bsrikan** [comment]
Yes this seems to be fixed now. Only the link for TDE remains to be fixed.

**Comment by xnikhil08** [comment]
> Yes this seems to be fixed now. Only the link for TDE remains to be fixed.

@bsrikan - Gave a comment about extraction functions link in the JIRA story.

**Comment by bsrikan** [comment]
QS test run in Jenkins with the test added for help links.
https://jenkins.marklogic.com/view/DHF-9.0-Server-All/job/5.x/view/quick-start/job/NO_CI_dhf-qs-develop-rh7_10_ReleaseBuild/

Added test passes.. Same 6 failures as before.

TDE link seems to be correct, no change required.

**Pull request merged**
