### PR TITLE
MLUI-130: Jobs Component

### PR DESCRIPTION
**Pull request by clockworked247**

### CODE REVIEW

**Comment by alexsmr** [comment]
Another thing: if it breaks the build, then you have not tested it with DHF. Even though there is no suppose to be any functional changes, we still should at least test if there is no visual problems (alignment, icons, etc.) arise when moving UI out.

**Comment by clockworked247** [comment]
@alexsmr This did not break the build for me.  I run both storybook and Quick Start to verify everything is working before creating a PR.  

The merge issue yesterday was an exception and the first time it happened on my work... not sure what happened there.  Like related to a bad merge.

---
Regarding the error message you mentioned, I don't see it:

Storybook output:

```
macpro-3753:quick-start sbrooks$ npm run storybook

> data-hub-quickstart@3.0.0 storybook /Users/sbrooks/Desktop/learning/marklogic-data-hub/quick-start
> start-storybook -p 6006 -s ./src/main/ui/assets

info @storybook/angular v4.0.0-alpha.23
info 
info => Loading static files from: /Users/sbrooks/Desktop/learning/marklogic-data-hub/quick-start/src/main/ui/assets .
info => Loading presets
info => Loading custom addons config.
info => Using default options for ForkTsCheckerWebpackPlugin
info => Loading angular-cli config.
WARN => Failed to get angular-cli webpack config.
info => Loading custom webpack config (full-control mode).
Starting type checking service...
Using 1 worker with 2048MB memory limit
 10% building modules 2/2 modules 0 activeℹ ｢wdm｣: wait until bundle finished:       
 67% building modules 871/903 modules 32 active ...e-style-prefixer/dynamic/dynamicData.jsℹ ｢wdm｣: wait until bundle finished: /__webpack_hmr
No type errors found                                                                                  
Version: typescript 2.9.2
Time: 10978ms
webpack built a5f5f95e06a972c6f7f0 in 17906ms
ℹ ｢wdm｣: Hash: a5f5f95e06a972c6f7f0
Version: webpack 4.20.2
Time: 17906ms
Built at: 2018-11-01 11:06:56
                                 Asset       Size   Chunks                    Chunk Names
  07c3c549e00186f1c17541f3f7ecfb76.svg   2.34 MiB           [emitted]  [big]  
  674f50d287a8c48dc19ba404d20fe713.eot    162 KiB           [emitted]         
  b06871f281fee6b241d60582ae9369b9.ttf    162 KiB           [emitted]         
af7ae505a9eed503f8b8e6982036873e.woff2   75.4 KiB           [emitted]         
 fee66e712a8a08eef5805a46892932ad.woff   95.7 KiB           [emitted]         
  e79bfd88537def476913f3ed52f4f4b3.eot    140 KiB           [emitted]         
  a37b0c01c0baf1888ca812cc0508f6e2.ttf    125 KiB           [emitted]         
 012cf6a10129e2275d79d6adac7f3b02.woff   56.3 KiB           [emitted]         
570eb83859dc23dd0eec423a49e147fe.woff2   43.3 KiB           [emitted]         
  c28acdf1c1f9c45ff40b25d6719e4c6c.eot    315 KiB           [emitted]  [big]  
  912ec66d7572ff821749319396470bde.svg    434 KiB           [emitted]  [big]  
  a33808e1480bbdc1273cce84ed5c288c.ttf    315 KiB           [emitted]  [big]  
32562ea54b66a048a7d093eb6f595faa.woff2    117 KiB           [emitted]         
 40f483d6f7ef034dee114865ce30a6e3.woff    155 KiB           [emitted]         
               static/iframe.bundle.js   9.83 MiB   iframe  [emitted]  [big]  iframe
              static/manager.bundle.js   5.02 MiB  manager  [emitted]  [big]  manager
                           iframe.html    2.4 KiB           [emitted]         
                            index.html  997 bytes           [emitted]         
           static/iframe.bundle.js.map   9.51 MiB   iframe  [emitted]         iframe
          static/manager.bundle.js.map   5.37 MiB  manager  [emitted]         manager
Entrypoint iframe [big] = static/iframe.bundle.js static/iframe.bundle.js.map
Entrypoint manager [big] = static/manager.bundle.js static/manager.bundle.js.map
[./.storybook/addons.js] 261 bytes {manager} [built]
[./.storybook/config.js] 2.38 KiB {iframe} [built]
[./node_modules/@angular-mdl/popover/popover.css] 1.17 KiB {iframe} [built]
[./node_modules/@angular-mdl/select/select.css] 1.17 KiB {iframe} [built]
[./node_modules/@storybook/core/dist/client/manager/index.js] 366 bytes {manager} [built]
[./node_modules/@storybook/core/dist/server/config/globals.js] 93 bytes {iframe} [built]
[./node_modules/@storybook/core/dist/server/config/polyfills.js] 113 bytes {iframe} {manager} [built]
[./node_modules/font-awesome/css/font-awesome.css] 1.19 KiB {iframe} [built]
[./node_modules/global/window.js] 232 bytes {iframe} {manager} [built]
[0] multi ./node_modules/@storybook/core/dist/server/config/polyfills.js ./node_modules/@storybook/core/dist/server/config/globals.js ./.storybook/config.js ./node_modules/webpack-hot-middleware/client.js?reload=true 64 bytes {iframe} [built]
[1] multi ./.storybook/addons.js ./node_modules/@storybook/core/dist/server/config/polyfills.js ./node_modules/@storybook/core/dist/client/manager/index.js 52 bytes {manager} [built]
[./node_modules/material-design-icons-iconfont/dist/material-design-icons.css] 1.21 KiB {iframe} [built]
[./node_modules/mdi/css/materialdesignicons.css] 1.21 KiB {iframe} [built]
[./node_modules/webpack-hot-middleware/client.js?reload=true] 7.59 KiB {iframe} [built]
[./node_modules/webpack-hot-middleware/process-update.js] 4.26 KiB {iframe} [built]
    + 2215 hidden modules
ℹ ｢wdm｣: Compiled successfully.
info Storybook started on => http://localhost:6006/
info 
```

Quick Start output:

```
macpro-3753:marklogic-data-hub sbrooks$ ./gradlew runUI
Starting a Gradle Daemon, 6 busy Daemons could not be reused, use --status for details

> Task :quick-start:npmInstallUI 
npm WARN ng2-device-detector@1.0.1 requires a peer of @angular/core@^4.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN ng2-device-detector@1.0.1 requires a peer of rxjs@^5.1.0 but none is installed. You must install peer dependencies yourself.

up to date in 13.866s

> Task :quick-start:runUI 

> data-hub-quickstart@3.0.0 start /Users/sbrooks/Desktop/learning/marklogic-data-hub/quick-start
> ng serve --proxy-config proxy.config.json --host 0.0.0.0 --disable-host-check

WARNING: Running a server with --disable-host-check is a security risk. See https://medium.com/webpack/webpack-dev-server-middleware-security-issues-1489d950874a for more information.
** Angular Live Development Server is listening on 0.0.0.0:4200, open your browser on http://localhost:4200/ **
DEPRECATION WARNING on line 1, column 8 of stdin:
Including .css files with @import is non-standard behaviour which will be removed in future versions of LibSass.
Use a custom importer to maintain this behaviour. Check your implementations documentation on how to create a custom importer.

DEPRECATION WARNING on line 2, column 8 of stdin:
Including .css files with @import is non-standard behaviour which will be removed in future versions of LibSass.
Use a custom importer to maintain this behaviour. Check your implementations documentation on how to create a custom importer.


Date: 2018-11-01T18:08:15.355Z
Hash: 75da535b860671e42b92
Time: 43711ms
chunk {main} main.js, main.js.map (main) 14.2 MB [initial] [rendered]
chunk {polyfills} polyfills.js, polyfills.js.map (polyfills) 424 kB [initial] [rendered]
chunk {runtime} runtime.js, runtime.js.map (runtime) 6.22 kB [entry] [rendered]
chunk {styles} styles.js, styles.js.map (styles) 209 kB [initial] [rendered]
chunk {vendor} vendor.js, vendor.js.map (vendor) 7.81 MB [initial] [rendered]
ℹ ｢wdm｣: Compiled successfully.1m 23s]
<==========---> 80% EXECUTING [1m 39s]
> :quick-start:runUI
```

No errors....

---
Looking at: https://jenkins.marklogic.com/view/DHF-9.0-Server-All/job/dhf-QS-develop-rh7-Commit/136/

Regarding the build failure, I believe there is an issue with the build not because of my code, but because there is leftover build files that are causing the build to fail.

I recall seeing a similar error on my machine, but removing node_modules and rerunning npm install within Quick Start fixed the problem.   Does this step need to be added to the Jenkins build?

**Comment by alexsmr** [comment]
@clockworked247 try to run "./gradle build -x test' this what resulted in the build problem. About leftovers, hm... Jenkins machine should remove node_modules and rerun npm install. If this is not happening, then there is a build configuration problem.

**Comment by alexsmr** [comment]
One more thing: I do not see you have removed old html and scss. I usually do rename it with ui suffix, then git getting the operation as refactoring and can track the history.

**Comment by clockworked247** [comment]
Closing in favor of:  https://github.com/marklogic/marklogic-data-hub/pull/1494

**Pull request closed without merging**
