### PR TITLE
DHFPROD-5851: Fix mapping tool namespacing edge case

### PR DESCRIPTION
**Pull request by ryanjdew**
#### Checklist: 
```diff
- Note: do not change the below
```

-  ##### Owner:

- [x] JIRA_ID included in all the commit messages
- [x] PR title is in the format JIRA_ID:Title
- [x] Rebase the branch with upstream
- [x] Squashed all commits into a single commit
- [x] Added Tests
  

- ##### Reviewer:

- [x] Reviewed Tests

### CODE REVIEW

**Comment by xnikhil08** [comment]
> image
> 
> Here, OrderDetails should get **OrderNS** namespace from its parent node, but getting **OD**. This will load incorrect value in the xpath expression field when selected.
> 
> I am using attached file to test it. If the namespace is declared with a prefix to xmlns then the node is assuming the same namespace, even if the prefix is not used in its nodeName.
> 
> [10289.xml.zip](https://github.com/marklogic/marklogic-data-hub/files/5163850/10289.xml.zip)

@ryanjdew - Looks like it was a cache issue for me. I reset my environment and getting **OrderNS** only now for OrderDetails node. 
But all the child nodes of **p:OrderDetail**, except UnitPrice, are getting wrong namespaces as mentioned by @srinathgit . The other OrderDetail node and its children seems to be fine.

**Comment by ryanjdew** [comment]
@xnikhil08 @srinathgit Missed passing the default namespace down recursively in some cases. I'm getting the expected namespaces set for the lower-level elements in the attached XML doc.

**Review by xnikhil08 — APPROVED** [review]
Looks good!

**Review by wooldridge — APPROVED** [review]
Looks good:

Screen Shot 2020-09-02 at 12 09 39 PM

**Review by srinathgit — APPROVED** [review]
Looks good

**Pull request merged**
