### PR TITLE
DHFPROD-1428: Improve the usability of text input elements

### PR DESCRIPTION
**Pull request by brucean52**

### CODE REVIEW

**Comment by ayuwono** [comment]
The input flow UI looks fine after the change.

One thing, I'm not sure if it's affected by the change, the pagination marker (on browser, jobs, and trace page) is changed from a circle to an ellipse?

screen shot 2019-01-21 at 2 22 41 pm

**Comment by ayuwono** [comment]
And the results text seems to have multiple lines
screen shot 2019-01-21 at 2 38 04 pm

**Comment by aebadirad** [comment]
Ooh, let's make sure these haven't changed.

**Comment by brucean52** [comment]
@ayuwono I believe the issues are due to my incorrect css selector. Please check again.

**Comment by ayuwono** [comment]
Okay, looks good now after your recent commit

**Comment by aebadirad** [comment]
@brucean52 can you also create a PR for this to the 4.x line

**Pull request merged**
