### PR TITLE
DHFPROD-8360: Add Lag to All Tooltips

### PR DESCRIPTION
**Pull request by amejiaq**
#### Checklist: 
```diff
- Note: do not change the below
```

- ##### Owner:

- [x] JIRA_ID included in all the commit messages
- [x] PR title is in the format JIRA_ID:Title
- [x] Rebase the branch with upstream
- [x] Squashed all commits into a single commit
- [x] Added Tests
- [x] Ran cypress tests on firefox locally
  

- ##### Reviewer:

- [x] Reviewed Tests
- [n/a] Added to Release Wiki

### CODE REVIEW

**Review by littlecherro — DISMISSED** [review]

**Review by MSBrignoni — COMMENTED** [review]
Looks good, but, I would add a little bit more delay, we need more opinions here. Regarding the popovers will get the same behavior? in that case, would be necessary a new ticket.

**Comment by aniamy** [comment]
Converting to draft while we wait the input from Griffin

**Comment by briantang** [comment]
Received confirmation from Griffin that the implementation in this PR is correct. No need to impact popovers yet as well. We can move forward with reviews as soon as the below conflict is resolved.

**Review by MSBrignoni — APPROVED** [review]

**Review by briantang — DISMISSED** [review]

**Review by briantang — APPROVED** [review]
Tests are passing now.

**Review by MSBrignoni — APPROVED** [review]

**Pull request merged**
