### PR TITLE
Added "stepsPreview" to mocking server JSON in support of Manage Flow UI

### PR DESCRIPTION
**Pull request by clockworked247**
Allows us to render step types under Flow name (colored bars) in Manage Flow UI

### CODE REVIEW

**Comment by alexsmr** [comment]
@clockworked247 if we are going this way, please add then tatgetEntity property, that we derive from entities on flow management page.

**Comment by wooldridge** [comment]
I would suggest the following:

```
steps: [
  { id: "flow-1-step-1", type: "ingestion", targetEntity: ""},
  { id: "flow-1-step-2", type: "mapping", targetEntity: "Customer"},
  { id: "flow-1-step-3", type: "mastering", targetEntity: "Customer"}
]
```

**Comment by alexsmr** [comment]
@wooldridge +1

**Comment by clockworked247** [comment]
@wooldridge @alexsmr Updated.

New API tweaks in support of Manage UI requirements
 - dynamic mocks & Swagger also reflect these changes

Requesting merge.

**Pull request merged**
