### PR TITLE
DHFPROD-7444: Edit color in the Graph View

### PR DESCRIPTION
**Pull request by briantang**
### Description
- Can select colors when adding a new entity type or editing a new entity type in the graph view
- Out of scope but included: Relayed this work in the tabular view as well so color is visible in the table and can also be added/modified too.
- Demo: https://drive.google.com/file/d/1_XD1jmedmtYvrcdSpRoX50wJwF6ndHBt/view

#### Checklist: 
```diff
- Note: do not change the below
```

-  ##### Owner:

- [x] JIRA_ID included in all the commit messages
- [x] PR title is in the format JIRA_ID:Title
- [x] Rebase the branch with upstream
- [x] Squashed all commits into a single commit
- [x] Code passes ESLint tests
- [x] Added Tests
- [x] Run UI tests
  

- ##### Reviewer:

- [x] Reviewed Tests

### CODE REVIEW

**Comment by briantang** [comment]
Fixed conflicts caused by graph positioning PR being merged

**Comment by briantang** [comment]
@wooldridge Had to deal with some conflicts with including my color additions and your graphX, graphY work in the payload. Hope you can review when you get the chance.

**Review by wooldridge — DISMISSED** [review]
I'm seeing some issues with this branch compared to the current develop:

1. Default colors for the example project entities that don't have them defined (AFAIK). Are they supposed to be dark gray?
2. After creating a new entity, I don't see the positions persisted when using the new PR branch.

Here are some screencasts...

develop: https://drive.google.com/file/d/1gesmjVvpufqBpPbkFvSZT6TOepeZpbcp/view

DHFPROD-7444: https://drive.google.com/file/d/1XvYamffxq6VxxkPxm5_zHvCqvW_r9_FN/view

**Comment by briantang** [comment]
Thanks @wooldridge, good catch. Looks like some changes were corrupted during rebase/conflict resolution. I have fixed both issues!

**Review by xnikhil08 — APPROVED** [review]
Looks good.
Noticed few things which can be handled in a separate ticket.
1. There is a lag between choosing the color from the picker and the node being refreshed with the new color. Perhaps a spinner might help here.
2. While the system is trying to save the color in the database, if user clicks on Table view, then user is brought back to the graph view suddenly, as soon as the result comes back from the server. See the screencast below.
https://drive.google.com/file/d/1MGWKXvCZnj9xP7RVIVWtCQe-tZrUYSuD/view
These doesn't seem like a blocker for the release and can be handled in a separate ticket, so approving the PR now.
@sbayatpur - Just FYI.

**Comment by AkshayBajajML** [comment]
Functionality looks Good!! Good work Brian
Screencast: https://drive.google.com/file/d/1aPaQV8Zwuycnd6Y7plEOKdwrVtzWTHkQ/view?usp=sharing

**Review by AkshayBajajML — DISMISSED** [review]

**Comment by briantang** [comment]
Removed somewhere I noticed still using entityMetadata color rather than the latest and greatest color. Needs re-reviews

**Review by AkshayBajajML — APPROVED** [review]

**Review by xnikhil08 — APPROVED** [review]

**Review by wooldridge — APPROVED** [review]
Looks and works great.

**Pull request merged**
