### PR TITLE
DHFPROD-8813: Modeling Graph Entity Physics

### PR DESCRIPTION
**Pull request by briantang**
#### Checklist: 
```diff
- Note: do not change the below
```

-  ##### Owner:

- [x] JIRA_ID included in all the commit messages
- [x] PR title is in the format JIRA_ID:Title
- [x] Rebase the branch with upstream
- [x] Squashed all commits into a single commit
- [x] Code passes ESLint tests
- [N/A]  Added Tests
  

- ##### Reviewer:

- [N/A] Reviewed Tests
- [N/A] Added to Release Wiki

### CODE REVIEW

**Review by prolonMarkLogic — COMMENTED** [review]
@briantang I still see the problem, should I run a special command to reload the frontend or something?

**Review by lucianaabc-ml — APPROVED** [review]

**Review by MSBrignoni — COMMENTED** [review]
Hi @briantang, with the project e2e, the bug was fixed, I see this behavior (chrome and FF), just to double-check  if this is the desired:

https://user-images.githubusercontent.com/89084298/166067992-1f365845-8dd6-456c-b7a2-9599021d1101.mp4

**Comment by briantang** [comment]
@MSBrignoni Yes, for now, that is to be expected.

**Comment by briantang** [comment]
@xnikhil08 updated spring constant looks good.

**Review by xnikhil08 — DISMISSED** [review]

**Review by xnikhil08 — APPROVED** [review]

**Review by Sanjeevani19 — APPROVED** [review]

**Pull request merged**
