### PR TITLE
DHFPROD-2223: moving to absolute path in ingest step

### PR DESCRIPTION
**Pull request by alexsmr**

### CODE REVIEW

**Comment by ayuwono** [comment]
It works on both 4200 and 8080

**Comment by timur-isangulov** [comment]
It doesn't work for me on Windows using the latest fix.

**Comment by aebadirad** [comment]
@ayuwono @alexsmr  verify this on windows please

**Comment by timur-isangulov** [comment]
On the latest develop ingest shows absolute path on Windows. However, when I run it's still returns error "java.lang.RuntimeException: java.lang.RuntimeException: java.util.IllegalFormatConversionException: c != java.util.UUID"

**Comment by aebadirad** [comment]
I think we need to pull in #2289 to correct this, as that's in the java layer. Add the comment there :)

**Pull request merged**
