### PR TITLE
DHFPROD-6710: View helpful icons for related entity, multiple, and st…

### PR DESCRIPTION
**Pull request by timur-isangulov**
…ructured types

### Description
This pr includes only legend, the icons for the table will be added after DHFPROD-6706 is completed.
Screen Shot 2021-03-12 at 9 41 57 AM

#### Checklist: 
```diff
- Note: do not change the below
```

-  ##### Owner:

- [x] JIRA_ID included in all the commit messages
- [x] PR title is in the format JIRA_ID:Title
- [x] Rebase the branch with upstream
- [x] Squashed all commits into a single commit
- [x] Code passes ESLint tests
- [x] Added Tests
  

- ##### Reviewer:

- [x] Reviewed Tests

### CODE REVIEW

**Review by Sanjeevani19 — APPROVED** [review]

**Review by AkshayBajajML — DISMISSED** [review]
Looks Good!! Legend icons are present now.

**Review by wooldridge — CHANGES_REQUESTED** [review]
@timur-isangulov, can we add a little more breathing room between the icons and their labels? This should do it:
```
  .legendText {
    font-size: 14px;
    margin-left: 18px;
    img, svg {
      margin-right: 2px;
    }
  }

**Comment by timur-isangulov** [comment]
> @timur-isangulov, can we add a little more breathing room between the icons and their labels? This should do it:
> 
> ```
>   .legendText {
>     font-size: 14px;
>     margin-left: 18px;
>     img, svg {
>       margin-right: 2px;
>     }
>   }
> ```

Sure, added changes. Thank you.

**Review by wooldridge — APPROVED** [review]
@timur-isangulov, thanks, looks good!

**Review by briantang — APPROVED** [review]

**Review by Sanjeevani19 — APPROVED** [review]

**Pull request merged**
