### PR TITLE
DHFPROD-7427: Add Help info to entity table title in mapping

### PR DESCRIPTION
**Pull request by AkshayBajajML**
#### Checklist: 
```diff
- Note: do not change the below
```

-  ##### Owner:

- [x] JIRA_ID included in all the commit messages
- [x] PR title is in the format JIRA_ID:Title
- [x] Rebase the branch with upstream
- [x] Squashed all commits into a single commit
- [x] Code passes ESLint tests
- [x] Added Tests
  

- ##### Reviewer:

- [ ] Reviewed Tests

### CODE REVIEW

**Review by wooldridge — CHANGES_REQUESTED** [review]
The popup text for this new feature reads: "Map related entities by selecting them from the dropdown below."

Here's a screencast of the functionality I am seeing in the PR: https://drive.google.com/file/d/1P_Nj_H1d3_m5mQMmc2mRKaRTyHgwaiex/view

Customer: NO icon/popup
Order (deliveredTo Customer): YES icon/popup
Product (Order includes): YES icon/popup

Expectation: The "Customer" entity table HAS a related dropdown, so it SHOULD have an icon/popup.
The "Product (Order includes)" entity table DOES NOT HAVE a related dropdown, so it SHOULD NOT have an icon/popup.

The rule is if the entity table is displaying a dropdown for related entity selection, the icon/popup should be there. If not, no icon/popup.

@sbayatpur @jbelonoj please correct me if I'm mistaken.

**Comment by AkshayBajajML** [comment]
> The popup text for this new feature reads: "Map related entities by selecting them from the dropdown below."
> 
> Here's a screencast of the functionality I am seeing in the PR: https://drive.google.com/file/d/1P_Nj_H1d3_m5mQMmc2mRKaRTyHgwaiex/view
> 
> Customer: NO icon/popup
> Order (deliveredTo Customer): YES icon/popup
> Product (Order includes): YES icon/popup
> 
> Expectation: The "Customer" entity table HAS a related dropdown, so it SHOULD have an icon/popup.
> The "Product (Order includes)" entity table DOES NOT HAVE a related dropdown, so it SHOULD NOT have an icon/popup.
> 
> The rule is if the entity table is displaying a dropdown for related entity selection, the icon/popup should be there. If not, no icon/popup.
> 
> @sbayatpur @jbelonoj please correct me if I'm mistaken.

Thanks @wooldridge for clarity and that makes sense too. 
Applied the changes as requested and updated test cases as well.

**Comment by wooldridge** [comment]
Converted to draft as there are still questions about popup content. CC: @jbelonoj @sbayatpur

**Comment by AkshayBajajML** [comment]
> Converted to draft as there are still questions about popup content. CC: @jbelonoj @sbayatpur

No update required for popover content by @jbelonoj and @sbayatpur

**Review by wooldridge — CHANGES_REQUESTED** [review]

**Comment by AkshayBajajML** [comment]
Closing this due to conflicts and would submit new fresh PR.

**Pull request closed without merging**
