### PR TITLE
feature/DHFPROD-1678 Merging configuration for Mastering

### PR DESCRIPTION
**Pull request by wooldridge**
Most of the functionality for merging implemented. Some work on the matching configuration as well.

TODOs:

- Add edit-in-place for weights.
- Need to fine-tune interaction between strategies in Merge Options and Merge Strategies tables.
- Support custom merge options

@brucean52, I will look at how this works with the New Step functionality separately. (I see it errors, as you pointed out in the previous PR.)

### CODE REVIEW

**Comment by ayuwono** [comment]
It's working on Mock API. On adding a new step, the UI is broken
Screen Shot 2019-03-25 at 10 59 15 AM

I can add Merging Strategies and Merging Collections, but can't add Merging Options

**Comment by wooldridge** [comment]
Thanks, @ayuwono. Are you seeing an error with Merge Option creation? What error?

**Comment by ayuwono** [comment]
> Thanks, @ayuwono. Are you seeing an error with Merge Option creation? What error?

No, it just do nothing when I click on Add button

**Comment by alexsmr** [comment]
@ayuwono please open the dev console and copy the error that shows up when you click on Add button.

**Comment by ayuwono** [comment]
> @ayuwono please open the dev console and copy the error that shows up when you click on Add button.

ok, will do

**Comment by brucean52** [comment]
Here's one of the errors I get when trying to create a Mastering step. The other errors are for other missing properties.
```
StepComponent.html:33 ERROR TypeError: Cannot read property 'matchOptions' of undefined
    at Function.push../src/main/ui/app/components/flows-new/edit-flow/mastering/merging/merging.model.ts.Merging.fromConfig (merging.model.ts:30)
    at MergingComponent.push../src/main/ui/app/components/flows-new/edit-flow/mastering/merging/merging.component.ts.MergingComponent.ngOnInit (merging.component.ts:63)
    at checkAndUpdateDirectiveInline (core.js:22000)
    at checkAndUpdateNodeInline (core.js:23264)
    at checkAndUpdateNode (core.js:23226)
    at debugCheckAndUpdateNode (core.js:23860)
    at debugCheckDirectivesFn (core.js:23820)
    at Object.eval [as updateDirectives] (StepComponent.html:34)
    at Object.debugUpdateDirectives [as updateDirectives] (core.js:23812)
    at checkAndUpdateView (core.js:23208)
```

**Comment by ayuwono** [comment]
Here is the error when clicking Add button on Merging Options
```
ERROR TypeError: Cannot read property 'definition' of undefined
    at Object.eval [as handleEvent] (MergeOptionsUiComponent.html:14)
    at handleEvent (core.js:23008)
    at callWithDebugContext (core.js:24078)
    at Object.debugHandleEvent [as handleEvent] (core.js:23805)
    at dispatchEvent (core.js:20457)
    at core.js:20904
    at HTMLButtonElement.<anonymous> (platform-browser.js:993)
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (zone.js:423)
    at Object.onInvokeTask (core.js:17279)
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (zone.js:422)
```

```

  | View_MergeOptionsUiComponent_0 | @ | MergeOptionsUiComponent.html:14
-- | -- | -- | --
  | proxyClass | @ | compiler.js:18234
  | push../node_modules/@angular/core/fesm5/core.js.DebugContext_.logError | @ | core.js:24040
  | push../node_modules/@angular/core/fesm5/core.js.ErrorHandler.handleError | @ | core.js:15766
  | dispatchEvent | @ | core.js:20461
  | (anonymous) | @ | core.js:20904
  | (anonymous) | @ | platform-browser.js:993
  | push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask | @ | zone.js:423
  | onInvokeTask | @ | core.js:17279
  | push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask | @ | zone.js:422
  | push../node_modules/zone.js/dist/zone.js.Zone.runTask | @ | zone.js:195
  | push../node_modules/zone.js/dist/zone.js.ZoneTask.invokeTask | @ | zone.js:498
  | invokeTask | @ | zone.js:1744
  | globalZoneAwareCallback | @ | zone.js:1770


```

**Comment by ayuwono** [comment]
I also get the similar error when clicking on Add button on Match Options
```
MatchOptionsUiComponent.html:14 ERROR TypeError: Cannot read property 'definition' of undefined
    at Object.eval [as handleEvent] (MatchOptionsUiComponent.html:14)
    at handleEvent (core.js:23008)
    at callWithDebugContext (core.js:24078)
    at Object.debugHandleEvent [as handleEvent] (core.js:23805)
    at dispatchEvent (core.js:20457)
    at core.js:20904
    at HTMLButtonElement.<anonymous> (platform-browser.js:993)
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (zone.js:423)
    at Object.onInvokeTask (core.js:17279)
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (zone.js:422)
View_MatchOptionsUiComponent_0 @ MatchOptionsUiComponent.html:14
proxyClass @ compiler.js:18234
push../node_modules/@angular/core/fesm5/core.js.DebugContext_.logError @ core.js:24040
push../node_modules/@angular/core/fesm5/core.js.ErrorHandler.handleError @ core.js:15761
dispatchEvent @ core.js:20461
(anonymous) @ core.js:20904
(anonymous) @ platform-browser.js:993
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask @ zone.js:423
onInvokeTask @ core.js:17279
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask @ zone.js:422
push../node_modules/zone.js/dist/zone.js.Zone.runTask @ zone.js:195
push../node_modules/zone.js/dist/zone.js.ZoneTask.invokeTask @ zone.js:498
invokeTask @ zone.js:1744
globalZoneAwareCallback @ zone.js:1770
MatchOptionsUiComponent.html:14 ERROR CONTEXT DebugContext_ {view: {…}, nodeIndex: 12, nodeDef: {…}, elDef: {…}, elView: {…}}
```

**Comment by wooldridge** [comment]
@brucean52, @ayuwono thanks for the info, I looking into these issues.

**Comment by wooldridge** [comment]
@ayuwono, a Mastering (and Mapping) step is required to be associated with a target entity. The mock data currently has our example Mapping and Mastering steps associated with an "Order" entity. Do you have an "Order" entity set up in your environment? I do because I'm running in the online-store environment. Any thoughts on how to address this from a QA testing perspective?

**Comment by ayuwono** [comment]
> @ayuwono, a Mastering (and Mapping) step is required to be associated with a target entity. The mock data currently has our example Mapping and Mastering steps associated with an "Order" entity. Do you have an "Order" entity set up in your environment? I do because I'm running in the online-store environment. Any thoughts on how to address this from a QA testing perspective? The UI should also address this error condition, obviously.

I don't have Order entity, but I have Product entity. Will try with Order entity. And yes, there should be error message on this

**Comment by ayuwono** [comment]
After trying with Order entity that has properties, adding match options and merging options look okay

**Comment by wooldridge** [comment]
@ayuwono I've added messaging for the missing target entity case. Can you test?

**Comment by ayuwono** [comment]
> @ayuwono I've added messaging for the missing target entity case. Can you test?

sure

**Comment by wooldridge** [comment]
@brucean52 the New Step issue should be fixed with my latest commit. The targetEntity value still needs to be populated from the form. Hoping we can merge this PR for now.

**Comment by ayuwono** [comment]
Tested the message where there is no target entity, it looks good
Adding match and merging options are good too (with Order entity)

There still need some wiring on when:
1) create a new flow
2) new mastering step
3) choose entity other than Order (example: Product)
We still can't add match and merging options. This might be expected as this will work on Mock API only

**Comment by wooldridge** [comment]
@brucean52 I fixed the target entity issue with my latest commit.

**Comment by ayuwono** [comment]
@wooldridge target entity test on new flow and step is good. I can set entity other than Order. I can also add match and merge options on this new mastering step

**Comment by wooldridge** [comment]
OK, I fixed some conflicts earlier but GitHub is still complaining so I may need to rebase and open another PR.

**Pull request closed without merging**
