### PR TITLE
DHFPROD-9385: Return labels in Notification endpoint

### PR DESCRIPTION
**Pull request by rahulvudutala**
#### Checklist: 
```diff
- Note: do not change the below
```

- ##### Owner:

- [x] JIRA_ID included in all the commit messages
- [x] PR title is in the format JIRA_ID:Title
- [x] Rebase the branch with upstream
- [x] Squashed all commits into a single commit
- [x] Added Tests
  

- ##### Reviewer:

- [x] Reviewed Tests
- [x] Added to Release Wiki

### CODE REVIEW

**Review by briantang — CHANGES_REQUESTED** [review]
It seems a bit strange to have individual properties for each matching URI underneath the "extractions" object, but the value is a nested object revealing all matching URIs again. Could we just show one object layer here of all 1:1 (individual uri : label) without the nesting?

Screen Shot 2022-09-15 at 9 34 06 AM

**Review by briantang — DISMISSED** [review]

**Review by ryanjdew — APPROVED** [review]

**Comment by briantang** [comment]
@rahulvudutala Couple conflicts and what appears to be a few related core unit failures as well.

**Review by lucianaabc-ml — DISMISSED** [review]

**Review by aniamy — DISMISSED** [review]

**Review by Sanjeevani19 — COMMENTED** [review]
@briantang  Could you take a look at this PR, it has few e2e failures http://jenkins1.marklogic.com/blue/organizations/jenkins/Datahub_CI/detail/PR-7222/16/tests

**Comment by briantang** [comment]
The e2e should pass on the next run now that my PR has merged.

**Comment by briantang** [comment]
Looking into the remaining failure. UI still seems out of date in the failure so we may want to merge this one after Martin's PR is in.

**Comment by briantang** [comment]
Discussing with Rahul the conflict and a potential issue here.

**Review by briantang — APPROVED** [review]
Looks good now!

**Review by Sanjeevani19 — COMMENTED** [review]
@lucianaabc-ml  Could you please take a look on these test failures http://jenkins1.marklogic.com/blue/organizations/jenkins/Datahub_CI/detail/PR-7222/28/tests,  If you have other things on your plate please spilt between you and @MSBrignoni

**Review by aniamy — DISMISSED** [review]

**Review by lucianaabc-ml — APPROVED** [review]

**Review by briantang — APPROVED** [review]

**Review by ryanjdew — APPROVED** [review]

**Pull request merged**
