### PR TITLE
WIP Mastering tests

### PR DESCRIPTION
**Pull request by karavi1**
Smart Mastering Unit Tests

### CODE REVIEW

**Comment by rjrudin** [comment]
@karavi1 It's difficult to review a PR with so many files in it. I recommend splitting it up into multiple PRs so that each is easier to review, it will make for easier feedback cycles. It looks like the folder name for each suite it a reasonable way to split them up - i.e. a PR for double-metaphone, a PR for match-and-merge, etc.

**Comment by ryanjdew** [comment]
@rjrudin These tests are taken from the smart-mastering-core and updated for marklogic-unit-test 1.0.beta, instead of 0.12.0. I asked @karavi1 to create this work in progress PR to help me investigate some of the assertions are failing. Once we get the code/assertions working as expected, we can look into breaking up the tests into separate PRs.

**Comment by rjrudin** [comment]
@ryanjdew @karavi1 Can this be closed for now? I'd like to get the list of outstanding PRs cleaned up for the 5.0.2 release.

**Comment by ryanjdew** [comment]
@rjrudin I'm fine with closing it for now.

**Pull request closed without merging**
