### PR TITLE
DHFPROD-7944: Input-Group-3

### PR DESCRIPTION
**Pull request by MSBrignoni**
### Description
Input Group 3

#### Checklist: 
```diff
- Note: do not change the below
```

-  ##### Owner:

- [x] JIRA_ID included in all the commit messages
- [x] PR title is in the format JIRA_ID:Title
- [x] Rebase the branch with upstream
- [x] Squashed all commits into a single commit
- [x] Code passes ESLint tests
- [x] Added Tests
- [x] Run UI tests
  

- ##### Reviewer:

- [x] Reviewed Tests

### CODE REVIEW

**Review by briantang — CHANGES_REQUESTED** [review]
@MSBrignoni Looks good. I'm just seeing one difference here - this input needs the placeholder text "Filter". On the nightly it has it.

Screen Shot 2021-11-02 at 10 28 17 AM

**Comment by AkshayBajajML** [comment]
Reviewed it! Apart from what @briantang mentioned; Rest looks Good.

**Comment by MSBrignoni** [comment]
> 
> 
> @MSBrignoni Looks good. I'm just seeing one difference here - this input needs the placeholder text "Filter". On the nightly it has it.
> 
> Screen Shot 2021-11-02 at 10 28 17 AM

Thank you @briantang and @AkshayBajajML , it works fine in FF but not in Chrome, i fixed it adding the placeholder in the input too and not only in the autocomplete (graph-view.tsx, line 97).

**Review by briantang — APPROVED** [review]

**Review by AkshayBajajML — APPROVED** [review]

**Review by iveyMarklogic — APPROVED** [review]

**Review by iveyMarklogic — APPROVED** [review]

**Review by briantang — APPROVED** [review]
Looks good

**Review by iveyMarklogic — APPROVED** [review]

**Pull request merged**
