### PR TITLE
DHFPROD-6526: Fixing job times bug via new DS endpoints

### PR DESCRIPTION
**Pull request by rjrudin**
### Description

The mlJobs endpoint was trying to handle every job operation, and I was having a hard time sorting out how to fix it so that the timestamps were always correct and valid on the Job document. So I replaced it with 4 new DS endpoints and a JobService interface, which I think is a lot easier to understand. And the "RunFlowWithSameJobIdTest" is now passing, which I updated to include multiple steps, as that produced some new problems that  the original fix wasn't handling. 

I removed all the unused stuff as a result of this change - that includes JobDocManager, JobMonitor, and a number of functions in jobs.sjs. 

#### Checklist: 
```diff
- Note: do not change the below
```

-  ##### Owner:

- [x] JIRA_ID included in all the commit messages
- [x] PR title is in the format JIRA_ID:Title
- [x] Rebase the branch with upstream
- [x] Squashed all commits into a single commit
- [x] Code passes ESLint tests
- [x] Added Tests
  

- ##### Reviewer:

- [x] Reviewed Tests

### CODE REVIEW

**Review by fsnow — APPROVED** [review]

**Comment by rjrudin** [comment]
Rebased

**Review by srinathgit — APPROVED** [review]

**Review by fsnow — APPROVED** [review]

**Comment by rjrudin** [comment]
Fixed tests and further simplified things by making jobs.sjs a regular library module

**Review by ryanjdew — DISMISSED** [review]

**Review by srinathgit — DISMISSED** [review]

**Comment by rjrudin** [comment]
Rebased to fix merge conflict

**Review by srinathgit — APPROVED** [review]

**Review by srinathgit — APPROVED** [review]

**Review by ryanjdew — DISMISSED** [review]

**Comment by rjrudin** [comment]
Fixed FlowRunnerTest failures; JobService is no longer a private field, it's in a concurrent map along with other stateful stuff

**Review by ryanjdew — APPROVED** [review]

**Review by fsnow — APPROVED** [review]

**Review by srinathgit — APPROVED** [review]

**Pull request merged**
