### PR TITLE
DHFPROD-6995: FE : Show warnings based on different views

### PR DESCRIPTION
**Pull request by AkshayBajajML**
Test cases will be added by @ngodugu-marklogic as part of https://project.marklogic.com/jira/browse/DHFPROD-7158

#### Checklist: 
```diff
- Note: do not change the below
```

-  ##### Owner:

- [x] JIRA_ID included in all the commit messages
- [x] PR title is in the format JIRA_ID:Title
- [x] Rebase the branch with upstream
- [x] Squashed all commits into a single commit
- [x] Code passes ESLint tests
- N/A Added Tests
  

- ##### Reviewer:

- N/A Reviewed Tests

### CODE REVIEW

**Review by Sanjeevani19 — COMMENTED** [review]
@AkshayBajajML the merge rule warning seems to be persisted, even after setting the max values and max-sources to 1 as suggested in the fix, there is no way to save a merge rule now,  Is that expected ?
https://drive.google.com/file/d/1-XC1JwU52wBYgJowXV_9V60iWng02VUg/view

**Comment by AkshayBajajML** [comment]
> @AkshayBajajML the merge rule warning seems to be persisted, even after setting the max values and max-sources to 1 as suggested in the fix, there is no way to save edited merge rule form changes, Is that expected ?
> https://drive.google.com/file/d/1-XC1JwU52wBYgJowXV_9V60iWng02VUg/view

Yes, it is expected. In order to make that warning go away we need to assign single value strategy for all properties mentioned in warning.

**Comment by Sanjeevani19** [comment]
> > @AkshayBajajML the merge rule warning seems to be persisted, even after setting the max values and max-sources to 1 as suggested in the fix, there is no way to save edited merge rule form changes, Is that expected ?
> > https://drive.google.com/file/d/1-XC1JwU52wBYgJowXV_9V60iWng02VUg/view
> 
> Yes, it is expected. In order to make that warning go away we need to assign single value strategy for all properties mentioned in warning.

@AkshayBajajML Even after setting max-values and max-sources to 1, the warning still persists

**Comment by ngodugu-marklogic** [comment]
@AkshayBajajML There are couple of tests(addMergeStepToFlow, merging, e2eMasteringflow) failing on this PR for 2 reasons:
1. Because the warning message shows up when we create a merge/match step and we need to additionally cancel it for the modal to disappear, we need to fix this in our scripts
2. When we add a merge rule and save the pop does not go away. It persists on screen. Can you please check this at your end and fix/create a bug accordingly

**Comment by AkshayBajajML** [comment]
> @AkshayBajajML There are couple of tests(addMergeStepToFlow, merging, e2eMasteringflow) failing on this PR for 2 reasons:
> 
> 1. Because the warning message shows up when we create a merge/match step and we need to additionally cancel it for the modal to disappear, we need to fix this in our scripts
> 2. When we add a merge rule and save the pop does not go away. It persists on screen. Can you please check this at your end and fix/create a bug accordingly

Fixed Both issues

**Comment by AkshayBajajML** [comment]
Here is the screencast for all the warnings which includes temporal collection related warning https://drive.google.com/file/d/1F8lK-Pr3C9RQDVVaEFx6ZB48WXFtJ_0_/view?usp=sharing.

**Review by Sanjeevani19 — DISMISSED** [review]

**Review by Sanjeevani19 — DISMISSED** [review]

**Review by ngodugu-marklogic — APPROVED** [review]

**Comment by ngodugu-marklogic** [comment]
@AkshayBajajML Seems like there are some lint errors. Can you please fix them

**Comment by AkshayBajajML** [comment]
> @AkshayBajajML Seems like there are some lint errors. Can you please fix them

Fixed the lint issues

**Review by ngodugu-marklogic — APPROVED** [review]

**Review by Sanjeevani19 — APPROVED** [review]

**Pull request merged**
