### PR TITLE
Adding e2e tests using mapping

### PR DESCRIPTION
**Pull request by srinathgit**
Adding tests for DHFPROD-635. There are some tests that fail currently.

### CODE REVIEW

**Comment by srinathgit** [comment]
Tests are failing. working on fixing them

**Comment by aebadirad** [comment]
Did this get already pulled in with the other PR? if not, we need to clean up some conflicts

**Comment by srinathgit** [comment]
Charles had already pulled this into the other PR (dhfprod-386-mapping branch). The code is already in develop branch after the merge today. So, I am closing this PR.

**Comment by softdeciple101** [comment]
Much appreciative please excuse any delays on my behalf.

**Pull request closed without merging**
