### PR TITLE
DHFPROD-7290: Make Test/Clear buttons in Mapping UI always accessible

### PR DESCRIPTION
**Pull request by devinnicholson**
### Description
UI fixes for Mapping UI:
- Test/clear buttons in a fixed location 
- Whitespace reduced
- Only one scroll bar per container 
- Popup on refresh removed

No tests needed.

#### Checklist: 
```diff
- Note: do not change the below
```

-  ##### Owner:

- [x] JIRA_ID included in all the commit messages
- [x] PR title is in the format JIRA_ID:Title
- [x] Rebase the branch with upstream
- [x] Squashed all commits into a single commit
- [x] Code passes ESLint tests

### CODE REVIEW

**Review by wooldridge — CHANGES_REQUESTED** [review]
I'm seeing the content in the view header shifted to the right, no more padding.

GOOD (has padding) on develop:
Screen Shot 2021-05-26 at 3 50 45 PM

BAD (padding gone for Clear/Test and icons) on DHFPROD-7290:

Screen Shot 2021-05-26 at 3 46 50 PM

CSS adjustment?

**Comment by devinnicholson** [comment]
> I'm seeing the content in the view header shifted to the right, no more padding.
> 
> GOOD (has padding) on develop:
> Screen Shot 2021-05-26 at 3 50 45 PM
> 
> BAD (padding gone for Clear/Test and icons) on DHFPROD-7290:
> 
> Screen Shot 2021-05-26 at 3 46 50 PM
> 
> CSS adjustment?

Browser/version/OS?

**Comment by wooldridge** [comment]
> Browser/version/OS?

@devinnicholson MacOS Chrome v90.0.4430.93 (1680px x 875px dimensions)

**Comment by devinnicholson** [comment]
> I'm seeing the content in the view header shifted to the right, no more padding.
> 
> GOOD (has padding) on develop:
> Screen Shot 2021-05-26 at 3 50 45 PM
> 
> BAD (padding gone for Clear/Test and icons) on DHFPROD-7290:
> 
> Screen Shot 2021-05-26 at 3 46 50 PM
> 
> CSS adjustment?

Made adjustments and confirmed with different resolutions/browsers. Let me know if you're seeing a fix.

**Review by wooldridge — CHANGES_REQUESTED** [review]
I'm also seeing padding issues with the entity table and the icons next to Column Options. There's padding there in develop:

Screen Shot 2021-05-27 at 12 56 26 PM

**Comment by wooldridge** [comment]
@devinnicholson, "padding-right: 30px;" on parentContainer might fix it.

**Review by wooldridge — CHANGES_REQUESTED** [review]
Still need to right-pad the entity table:

Screen Shot 2021-05-27 at 3 40 58 PM

**Review by wooldridge — APPROVED** [review]

**Review by xnikhil08 — APPROVED** [review]

**Comment by ngodugu-marklogic** [comment]
@devinnicholson Seems like there are some lint errors. Can you please look into them.

**Review by wooldridge — APPROVED** [review]

**Review by briantang — APPROVED** [review]

**Pull request merged**
