### PR TITLE
DHFPROD-5950: FE-Select database for exploring curated entities

### PR DESCRIPTION
**Pull request by timur-isangulov**
#### Checklist: 
```diff
- Note: do not change the below
```

-  ##### Owner:

- [x] JIRA_ID included in all the commit messages
- [x] PR title is in the format JIRA_ID:Title
- [x] Rebase the branch with upstream
- [x] Squashed all commits into a single commit
- [x] Added Tests
  

- ##### Reviewer:

- [x] Reviewed Tests

### CODE REVIEW

**Comment by rahulvudutala** [comment]
Rebase off the feature/5.4-develop branch and create a PR. You have 26 commits in this PR

**Comment by rahulvudutala** [comment]
Looks good to me

**Review by rahulvudutala — APPROVED** [review]

**Review by Sanjeevani19 — DISMISSED** [review]

**Review by Sanjeevani19 — DISMISSED** [review]

**Review by rahulvudutala — APPROVED** [review]

**Review by xnikhil08 — CHANGES_REQUESTED** [review]
There seems to be a spacing issue on left side of database switch and right side of View as switch on zero page. Please see the screenshot below.
SpacingIssue

**Comment by xnikhil08** [comment]
In Firefox, the text within the database switch buttons doesn't seem to be exactly vertically centered(within the buttons). Looks reasonably fine on chrome though.

image

**Comment by timur-isangulov** [comment]
> There seems to be a spacing issue on left side of database switch and right side of View as switch on zero page. Please see the screenshot below. I've highlighted the space difference in red color.
> SpacingIssue

Hi @xnikhil08, can you please review again, I pushed the fix.

**Comment by timur-isangulov** [comment]
> In Firefox, the text within the database switch buttons doesn't seem to be exactly vertically centered(within the buttons). Looks reasonably fine on chrome though.
> 
> image

This one also. Thanks.

**Review by xnikhil08 — APPROVED** [review]
Looks good now.

**Review by rahulvudutala — APPROVED** [review]

**Review by Sanjeevani19 — APPROVED** [review]

**Review by xnikhil08 — APPROVED** [review]

**Review by SameeraPriyathamTadikonda — APPROVED** [review]

**Pull request merged**
