### PR TITLE
DHFPROD-7576: Publish entity types

### PR DESCRIPTION
**Pull request by xnikhil08**
### Description
Involves both backend(courtesy: @ryanjdew and @aniamy) and front-end changes for the Publish entity types story.
Any missing test cases will be added separately as part of the DHFPROD-7847.

#### Checklist: 
```diff
- Note: do not change the below
```

-  ##### Owner:

- [x] JIRA_ID included in all the commit messages
- [x] PR title is in the format JIRA_ID:Title
- [x] Rebase the branch with upstream
- [x] Squashed all commits into a single commit
- [x] Code passes ESLint tests
- [x] Added Tests
- [x] Run UI tests
  

- ##### Reviewer:

- [x] Reviewed Tests

### CODE REVIEW

**Review by ryanjdew — APPROVED** [review]

**Review by wooldridge — CHANGES_REQUESTED** [review]
I'm noticing that a new property isn't appearing in the side panel after creation. But it does exist, and appears after switching tabs:

https://drive.google.com/file/d/1738rLssR2f8pVDWLxyoQmTT6uWREWyVE/view

Is this expected behavior? I would expect to see the new property on save.

**Comment by xnikhil08** [comment]
> I'm noticing that a new property isn't appearing in the side panel after creation. But it does exist, and appears after switching tabs:
> 
> https://drive.google.com/file/d/1738rLssR2f8pVDWLxyoQmTT6uWREWyVE/view
> 
> Is this expected behavior? I would expect to see the new property on save.

@wooldridge - Looks like your environment is pointing to older backend changes for entity types. Try resetting and publish the changes to local maven.

**Comment by AkshayBajajML** [comment]
I noticed that publish button is always enabled in graph view even when no change is made and is clickable.
It is disabled in tabular view

**Comment by xnikhil08** [comment]
> I noticed that publish button is always enabled in graph view even when no change is made and is clickable.
> It is disabled in tabular view

@AkshayBajajML - Try resetting your environment. Publish the changes to local maven and then start with a clean ML. Looks like you are still pointing to older HC code.

**Review by briantang — DISMISSED** [review]
Functionality looks fantastic on my end. Nice!

**Review by AkshayBajajML — DISMISSED** [review]
Works as expected.
Good Work!!

**Review by wooldridge — APPROVED** [review]

**Review by wooldridge — CHANGES_REQUESTED** [review]
I believe this is a bug, the confirm dialog after clicking Publish always says I have unpublished changes: https://drive.google.com/file/d/1R6s0DUy6stA1PJbmTIfNss78SkK7i2Fr/view

**Comment by xnikhil08** [comment]
> I believe this is a bug, the confirm dialog after clicking Publish always says I have unpublished changes: https://drive.google.com/file/d/1R6s0DUy6stA1PJbmTIfNss78SkK7i2Fr/view

@wooldridge - Not sure if you have pointed to the correct branch (https://github.com/xnikhil08/marklogic-data-hub/tree/feature/DHFPROD-7576). I don't see the updated confirmation modal and Banner texts in the screencast, suggesting that you are probably using a different branch.

**Comment by AkshayBajajML** [comment]
> I believe this is a bug, the confirm dialog after clicking Publish always says I have unpublished changes: https://drive.google.com/file/d/1R6s0DUy6stA1PJbmTIfNss78SkK7i2Fr/view

That happened with me too initially(I was pointing to incorrect branch) but it worked fine once I did mladmin cleandata and start and reinstalled the hc-qa project.

**Review by wooldridge — CHANGES_REQUESTED** [review]
When I add a property and then delete that property (without publishing), there is no net change in the entity. Yet the UI shows the system as having unsaved changes. Was this a conscious design decision? Screencast: https://drive.google.com/file/d/1y95xsTEna1noCA8o7gTYp1qLjFwdN-Wn/view

**Comment by wooldridge** [comment]
> > I believe this is a bug, the confirm dialog after clicking Publish always says I have unpublished changes: https://drive.google.com/file/d/1R6s0DUy6stA1PJbmTIfNss78SkK7i2Fr/view
> 
> @wooldridge - Not sure if you have pointed to the correct branch (https://github.com/xnikhil08/marklogic-data-hub/tree/feature/DHFPROD-7576). I don't see the updated confirmation modal and Banner texts in the screencast, suggesting that you are probably using a different branch.

@xnikhil08, thanks, that was the case, wrong branch.

**Review by ryanjdew — APPROVED** [review]

**Review by AkshayBajajML — APPROVED** [review]

**Review by briantang — DISMISSED** [review]

**Comment by wooldridge** [comment]
> When I add a property and then delete that property (without publishing), there is no net change in the entity. Yet the UI shows the system as having unsaved changes. Was this a conscious design decision? Screencast: https://drive.google.com/file/d/1y95xsTEna1noCA8o7gTYp1qLjFwdN-Wn/view

Discussed this issue with @xnikhil08, this shouldn't block beta and it may not be something worth fixing. Created a ticket to track: https://project.marklogic.com/jira/browse/DHFPROD-7860

**Review by wooldridge — APPROVED** [review]

**Review by briantang — APPROVED** [review]

**Review by AkshayBajajML — DISMISSED** [review]

**Review by briantang — APPROVED** [review]

**Review by AkshayBajajML — APPROVED** [review]

**Pull request merged**
