### PR TITLE
DHFPROD-7689: Component Replacement Layout

### PR DESCRIPTION
**Pull request by iveyMarklogic**
#### Checklist: 
```diff
- Note: do not change the below
```

-  ##### Owner:

- [x] JIRA_ID included in all the commit messages
- [x] PR title is in the format JIRA_ID:Title
- [x] Rebase the branch with upstream
- [x] Squashed all commits into a single commit
- [x] Code passes ESLint tests
- [x] Added Tests
- [x] Run UI tests
  

- ##### Reviewer:

- [x] Reviewed Tests

### CODE REVIEW

**Review by briantang — APPROVED** [review]
Looks good to me.

**Review by briantang — CHANGES_REQUESTED** [review]
Actually seeing one issue, the columns in this view look more confined (only 2 columns) with some empty space compared to the original (3 columns).
PR: 
Screen Shot 2021-11-18 at 1 31 54 PM

Nightly: 
Screen Shot 2021-11-18 at 1 31 48 PM

**Comment by iveyMarklogic** [comment]
I added a fix to solve this issue, can you check again, please?

**Review by briantang — APPROVED** [review]
Looks better now!

**Review by Yubisel — APPROVED** [review]

**Review by yubiselmarklogic — APPROVED** [review]

**Pull request merged**
