### PR TITLE
DHFPROD-9292: and DHFPROD-9291 Graph beta changes

### PR DESCRIPTION
**Pull request by ryanjdew**
#### Checklist: 
```diff
- Note: do not change the below
```

- ##### Owner:

- [x] JIRA_ID included in all the commit messages
- [x] PR title is in the format JIRA_ID:Title
- [x] Rebase the branch with upstream
- [x] Squashed all commits into a single commit
- [x] Code passes ESLint tests
- [x] Added Tests
- [x] Ran cypress tests on firefox locally
  

- ##### Reviewer:

- [x] Reviewed Tests
- [N/A] Added to Release Wiki

### CODE REVIEW

**Review by Sanjeevani19 — COMMENTED** [review]
Two core tests are failing on the latest run, @rahulvudutala @aniamy Please take a look http://jenkins1.marklogic.com/blue/organizations/jenkins/Datahub_CI/detail/PR-7238/3/tests

**Comment by csilva-ml** [comment]
> Two core tests are failing on the latest run, @rahulvudutala @aniamy Please take a look http://jenkins1.marklogic.com/blue/organizations/jenkins/Datahub_CI/detail/PR-7238/3/tests

Also the expand nodes is still failing. Please let me know when I can test it again.

**Comment by Sanjeevani19** [comment]
> Details

@csilva-ml  So all the 4 cypress tests failing are related expand node feature ?

**Review by prolonMarkLogic — CHANGES_REQUESTED** [review]
hello, when trying to expand a group node, it disappears.
https://watch.screencastify.com/v/OIzbHFfs9c0fWvZ5nkFx

**Comment by prolonMarkLogic** [comment]
HI, I found cases when we are writing the edges more than the expected, in this Case babyRegistry 4039 has ownedBy customer 401, I expected one edge but I have 3.
image

**Comment by csilva-ml** [comment]
> > Details
> 
> @csilva-ml So all the 4 cypress tests failing are related expand node feature ?

no, not all 4 of them. 

- graphLeafNodes and graphGroupNodes -> Expand issue
- crudQueriesFromManageQueries -> 400 error
image
- exploreGraphFacetConsistentNavigation and entitiesSidepanel  we're looking into it, I'll push a fix today.

**Comment by ryanjdew** [comment]
@prolonMarkLogic Pushed a change to use URIs as node IDs and sorted the IDs for the edges to remove duplicates.

**Comment by ngodugu-marklogic** [comment]
I am unable to open explore tile using sled project (https://project.marklogic.com/repo/projects/CIVS/repos/sled-envision-mes/browse?at=refs%2Fheads%2Ffeature%2Fmes-NJPOT-HC5.8) FYI @ryanjdew @aniamy. Can anyone please try to test this
image

**Review by Sanjeevani19 — COMMENTED** [review]
@csilva-ml @aniamy @ryanjdew I see the same cypress and core unit test failures even on the latest run http://jenkins1.marklogic.com/blue/organizations/jenkins/Datahub_CI/detail/PR-7238/16/tests, Are they functionality issues or test issues ?

**Review by briantang — DISMISSED** [review]

**Review by ngodugu-marklogic — DISMISSED** [review]

**Review by Sanjeevani19 — COMMENTED** [review]
@rahulvudutala  @ryanjdew Looks like lint UI is failing on the latest run http://jenkins1.marklogic.com/blue/organizations/jenkins/Datahub_CI/detail/PR-7238/41/pipeline/116, Could you push that fix when you have a chance ?

@ngodugu-marklogic  Leaf nodes e2e failure still shows up, please let me know if I can merge this manually ?

**Comment by ryanjdew** [comment]
@Sanjeevani19 Lint change pushed

**Review by briantang — DISMISSED** [review]

**Review by Sanjeevani19 — APPROVED** [review]

**Review by rahulvudutala — APPROVED** [review]

**Comment by briantang** [comment]
Monitoring for next run.

**Review by Sanjeevani19 — APPROVED** [review]

**Review by briantang — APPROVED** [review]

**Review by ngodugu-marklogic — APPROVED** [review]

**Pull request merged**
