### PR TITLE
Able to save an entity with duplicate property names

### PR DESCRIPTION
**Pull request by clockworked247**
Issue #1144 

Validation now checks to ensure property name is not empty, unique & without spaces.  Also, I updated the e2e test where it checks for error message string.

### CODE REVIEW

**Comment by ayuwono** [comment]
@clockworked247 , thanks for changing the e2e test. Actually there is another area of the test that has duplicate property scenario, I've already addressed in this commit on my PR:
https://github.com/marklogic/marklogic-data-hub/pull/1239/commits/5ea2caf201cfb6c8e40d8fb3c066165b122e31d5

**Comment by clockworked247** [comment]
@ayuwono I just updated the check of the error message but did not add logic to the test to attempt to add a duplicate property.

**Comment by clockworked247** [comment]
Hmmm, build failure...  no info on why either...

**Comment by ayuwono** [comment]
Yes, I have to change the test. Before, you can save the entity even they have duplicate prop, but right now, the save button is disabled.

**Comment by clockworked247** [comment]
@grechaw Thanks!

**Pull request merged**
