### PR TITLE
DHFPROD-6494: Matching/merging e2e failures

### PR DESCRIPTION
**Pull request by ngodugu-marklogic**
#### Checklist: 
```diff
- Note: do not change the below
```

-  ##### Owner:

- [x] JIRA_ID included in all the commit messages
- [x] PR title is in the format JIRA_ID:Title
- [x] Rebase the branch with upstream
- [x] Squashed all commits into a single commit
- [x] Code passes ESLint tests
- [x] Added Tests
  

- ##### Reviewer:

- [x] Reviewed Tests

### CODE REVIEW

**Review by Sanjeevani19 — COMMENTED** [review]
@ngodugu-marklogic I see that you did break most of the existing tests into very smaller chunks, which is different from what we have been following for e2e, Any reason for breaking them into very smaller chunks of tests, Should the team keep writing new tests in this way ?

**Review by timur-isangulov — CHANGES_REQUESTED** [review]
Hi @ngodugu-marklogic, I tried to disable one or two tests and run the whole test suite and it failed. I think we should follow Cypress best practices and not to coupling multiple tests together.

**Comment by ngodugu-marklogic** [comment]
> @ngodugu-marklogic I see that you did break most of the existing tests into very smaller chunks, which is different from what we have been following for e2e, Any reason for breaking them into very smaller chunks of tests, Should the team keep writing new tests in this way ?

@Sanjeevani19 The best practice is having your test easily readable. Splitting (even when it is just simple assertions) your tests into separate its, descriptions or even files depending on the section tests helps a lot. Tests are more readable and the results are more clear as well. And it is easier for debugging a failure when occurred.

**Comment by ngodugu-marklogic** [comment]
> Hi @ngodugu-marklogic, I tried to disable one or two tests and run the whole test suite and it failed. I think we should follow Cypress best practices and not to coupling multiple tests together.

@timur-isangulov As we are writing an E2E flow, commenting out the it blocks where we are navigating to particular page would result in failure as we are breaking the flow. I am only dividing the huge block of code with multiple assertions to smaller blocks for better readability and maintainability. I feel debugging a failure is difficult when we have huge blocks.

**Comment by xnikhil08** [comment]
> > @ngodugu-marklogic I see that you did break most of the existing tests into very smaller chunks, which is different from what we have been following for e2e, Any reason for breaking them into very smaller chunks of tests, Should the team keep writing new tests in this way ?
> 
> @Sanjeevani19 The best practice is having your test easily readable. Splitting (even when it is just simple assertions) your tests into separate its, descriptions or even files depending on the section tests helps a lot. Tests are more readable and the results are more clear as well. And it is easier for debugging a failure when occurred.

@ngodugu-marklogic @Sanjeevani19 - Just food for thought here. Splitting a bigger test to smaller chunks is completely fine but let's ensure that we are not compromising on readability and error handling with runtime, exponentially.
Given that we have certain commands/steps in AfterEach and BeforEach blocks which will be associated with every IT block, so finding that optimal line of code modularity is always critical as we don't want the overall run time to increase drastically just because the beforeEach and AfterEach blocks are running against each smaller IT blocks.

**Comment by ngodugu-marklogic** [comment]
> > > @ngodugu-marklogic I see that you did break most of the existing tests into very smaller chunks, which is different from what we have been following for e2e, Any reason for breaking them into very smaller chunks of tests, Should the team keep writing new tests in this way ?
> > 
> > 
> > @Sanjeevani19 The best practice is having your test easily readable. Splitting (even when it is just simple assertions) your tests into separate its, descriptions or even files depending on the section tests helps a lot. Tests are more readable and the results are more clear as well. And it is easier for debugging a failure when occurred.
> 
> @ngodugu-marklogic @Sanjeevani19 - Just food for thought here. Splitting a bigger test to smaller chunks is completely fine but let's ensure that we are not compromising on readability and error handling with runtime, exponentially.
> Given that we have certain commands/steps in AfterEach and BeforEach blocks which will be associated with every IT block, so finding that optimal line of code modularity is always critical as we don't want the overall run time to increase drastically just because the beforeEach and AfterEach blocks are running against each smaller IT blocks.

@xnikhil08 Thank you for bringing this up. In beforeEach and afterEach block we are just re authenticating as Cypress clears the local storage after each it block. I compared the runtime for AddMatchStepToFlow and AddMergeStepToFlow with the older builds and I see the run time improved by few seconds :) Will fix matching and merging accordingly.

**Comment by ngodugu-marklogic** [comment]
> > > > @ngodugu-marklogic I see that you did break most of the existing tests into very smaller chunks, which is different from what we have been following for e2e, Any reason for breaking them into very smaller chunks of tests, Should the team keep writing new tests in this way ?
> > > 
> > > 
> > > @Sanjeevani19 The best practice is having your test easily readable. Splitting (even when it is just simple assertions) your tests into separate its, descriptions or even files depending on the section tests helps a lot. Tests are more readable and the results are more clear as well. And it is easier for debugging a failure when occurred.
> > 
> > 
> > @ngodugu-marklogic @Sanjeevani19 - Just food for thought here. Splitting a bigger test to smaller chunks is completely fine but let's ensure that we are not compromising on readability and error handling with runtime, exponentially.
> > Given that we have certain commands/steps in AfterEach and BeforEach blocks which will be associated with every IT block, so finding that optimal line of code modularity is always critical as we don't want the overall run time to increase drastically just because the beforeEach and AfterEach blocks are running against each smaller IT blocks.
> 
> @xnikhil08 Thank you for bringing this up. In beforeEach and afterEach block we are just re authenticating as Cypress clears the local storage after each it block. I compared the runtime for AddMatchStepToFlow and AddMergeStepToFlow with the older builds and I see the run time improved by few seconds :) Will fix matching and merging accordingly.

Fixed!

**Review by Sanjeevani19 — APPROVED** [review]

**Review by Sanjeevani19 — APPROVED** [review]
I see that the run time has improved and all tests are passing on the latest build.

**Review by xnikhil08 — APPROVED** [review]
Good job.

**Review by timur-isangulov — APPROVED** [review]

**Pull request merged**
