### PR TITLE
DHFPROD-5381: Upon refreshing the explorer page, the query name and description not persist

### PR DESCRIPTION
**Pull request by xnikhil08**
### Description
This PR resolves the bug DHFPROD-5381 and also adds user preferences in explorer.

#### Checklist: 
```diff
- Note: do not change the below
```

-  ##### Owner:

- [x] JIRA_ID included in all the commit messages
- [x] PR title is in the format JIRA_ID:Title
- [x] Rebase the branch with upstream
- [x] Squashed all commits into a single commit
- [x] Added Tests
  

- ##### Reviewer:

- [x] Reviewed Tests

### CODE REVIEW

**Comment by xnikhil08** [comment]
> I see an error when refreshing the Explore page with the selected query https://drive.google.com/file/d/186wyK798WKr7fZYpxZwO1iFaSxVAOnA7/view.
> Snippet, zero state views and page number don't persist when refreshing https://drive.google.com/file/d/1jzHXid-Pw1ZxmM-mvixOlrqhvCypEPlN/view

Fixed these.

**Comment by Sanjeevani19** [comment]
> * If user selects a facet from hub properties and refreshes the page, the hub properties seems to be collpased after reloading instead it should be expanded even if one facet is selected.

@xnikhil08  the first mentioned issue still persists, the second issue is fixed

**Comment by xnikhil08** [comment]
> > * If user selects a facet from hub properties and refreshes the page, the hub properties seems to be collapsed after reloading instead it should be expanded even if one facet is selected.
> 
> @xnikhil08 this issue still persists, the other issue is fixed

@Sanjeevani19 - The issue should be resolved now. Can you check again?

**Comment by timur-isangulov** [comment]
> > I see an error when refreshing the Explore page with the selected query https://drive.google.com/file/d/186wyK798WKr7fZYpxZwO1iFaSxVAOnA7/view.
> > Snippet, zero state views and page number don't persist when refreshing https://drive.google.com/file/d/1jzHXid-Pw1ZxmM-mvixOlrqhvCypEPlN/view
> 
> Fixed these.

I still see the error if save query and refresh the page. 
Screen Shot 2020-08-11 at 9 27 17 AM

**Comment by Sanjeevani19** [comment]
> > > * If user selects a facet from hub properties and refreshes the page, the hub properties seems to be collapsed after reloading instead it should be expanded even if one facet is selected.
> > 
> > 
> > @xnikhil08 this issue still persists, the other issue is fixed
> 
> @Sanjeevani19 - The issue should be resolved now. Can you check again?

@xnikhil08 this above issue is resolved, but I am still seeing the same error as @timur-isangulov described

**Comment by xnikhil08** [comment]
> > > > * If user selects a facet from hub properties and refreshes the page, the hub properties seems to be collapsed after reloading instead it should be expanded even if one facet is selected.
> > > 
> > > 
> > > @xnikhil08 this issue still persists, the other issue is fixed
> > 
> > 
> > @Sanjeevani19 - The issue should be resolved now. Can you check again?
> 
> @xnikhil08 the above issue is resolved, but I am still seeing the same error as @timur-isangulov described

@Sanjeevani19  @timur-isangulov  - Try now. Just pushed the fix.

**Pull request merged**
