### PR TITLE
DHFPROD-7832: Component Replacement: Select (or MLSelect)

### PR DESCRIPTION
**Pull request by yubiselmarklogic**
#### Checklist: 
```diff
- Note: do not change the below
```

-  ##### Owner:

- [x] JIRA_ID included in all the commit messages
- [x] PR title is in the format JIRA_ID:Title
- [x] Rebase the branch with upstream
- [x] Squashed all commits into a single commit
- [x] Code passes ESLint tests
- [x] Added Tests
- [x] Run UI tests
  

- ##### Reviewer:

- [x] Reviewed Tests

### CODE REVIEW

**Comment by mrodrigu-marklogic** [comment]
@yubiselmarklogic it seems there is a rebase needed

**Review by mrodrigu-marklogic — DISMISSED** [review]

**Comment by AkshayBajajML** [comment]
I have few Minor comments:

- Can we change cursor to pointer when user tries to hover over dropdown.
- I see the font is different for dropdown options as compared to nightly. (Is this expected change?) @jbelonoj 
- When dropdown has horizontal scrollbar; the hover color changes partially for the visible part only.(Screenshot below)
Screen Shot 2021-12-17 at 2 13 45 PM
Screen Shot 2021-12-17 at 2 24 02 PM

**Comment by yubiselmarklogic** [comment]
@AkshayBajajML fixed

**Review by AkshayBajajML — APPROVED** [review]

**Comment by AkshayBajajML** [comment]
> @AkshayBajajML fixed

Good work!
Above issues are fixed.

**Review by mrodrigu-marklogic — DISMISSED** [review]
LGTM 
Screen Shot 2021-12-20 at 17 07 24

**Review by AkshayBajajML — DISMISSED** [review]

**Review by AkshayBajajML — APPROVED** [review]

**Review by Sanjeevani19 — APPROVED** [review]

**Pull request merged**
