### PR TITLE
Merging Feature/5.4 develop to develop

### PR DESCRIPTION
**Pull request by SameeraPriyathamTadikonda**
### Description
Merging feature/5.4-develop to develop
#### Checklist: 
```diff
- Note: do not change the below
```

-  ##### Owner:

- [x] JIRA_ID included in all the commit messages
- [x] PR title is in the format JIRA_ID:Title
- [x] Rebase the branch with upstream
- [x] Squashed all commits into a single commit
- [x] Added Tests
  

- ##### Reviewer:

- [x] Reviewed Tests

### CODE REVIEW

**Review by Sanjeevani19 — COMMENTED** [review]
@SameeraPriyathamTadikonda looks like there are few merge conflicts, please look into them

**Comment by SameeraPriyathamTadikonda** [comment]
@Sanjeevani19 I know this is the PR to merge feature branch to develop. We will sync it with develop once all the other PRs get merged.

**Comment by rjrudin** [comment]
@SameeraPriyathamTadikonda  @Sanjeevani19  I think it'd be simpler for someone to reset their local develop branch to the latest 5.4-develop commit, and then do a force push. I don't think a merge commit is buying us anything here.

**Comment by SameeraPriyathamTadikonda** [comment]
@rjrudin Once we rebase 5.4-develop again with develop. I'll do a manual rebase and merge of this PR.

**Review by rjrudin — APPROVED** [review]

**Review by ryanjdew — APPROVED** [review]

**Pull request merged**
