### PR TITLE
DHFPROD-1989: Merge to Develop

### PR DESCRIPTION
**Pull request by brucean52**

### CODE REVIEW

**Comment by bsrikan** [comment]
@brucean52 you might want to rebase with develop. Not sure if it is already. I tried to create a flow by altering the options like batchSize etc and couldnt create a flow. There was a fix merged for this very issue recently

**Comment by ayuwono** [comment]
I thought this is about the steps (hovering, indexing, information, etc)? I approved based on that

**Comment by bsrikan** [comment]
Thats ok. I just wanted to make sure it wasnt breaking anything else.

**Comment by brucean52** [comment]
I agree with @ayuwono. These changes only affect the step functionality. The PR won't break the fixes that @bsrikan mentioned that are already in develop branch.

**Pull request merged**
