### PR TITLE
DHFPROD-9107: Getting com.marklogic.client.FailedRequestException whi…

### PR DESCRIPTION
**Pull request by AkshayBajajML**
…le running Matching step

#### Checklist: 
```diff
- Note: do not change the below
```

- ##### Owner:

- [x] JIRA_ID included in all the commit messages
- [x] PR title is in the format JIRA_ID:Title
- [x] Rebase the branch with upstream
- [x] Squashed all commits into a single commit
- [x] Code passes ESLint tests
- N/A Added Tests
- [x] Ran cypress tests on firefox locally
  

- ##### Reviewer:

- N/A Reviewed Tests
- N/A Added to Release Wiki

### CODE REVIEW

**Comment by AkshayBajajML** [comment]
Pushed the fix... Lets wait for pipeline to execute.

**Comment by AkshayBajajML** [comment]
@Sanjeevani19 @ngodugu-marklogic.. Previous issue is resolved but currently failing due to below mentioned bug.
Screen Shot 2022-07-12 at 2 12 44 PM

**Comment by AkshayBajajML** [comment]
All test pass now. We are expecting now 2 docs as synonyms match function is fixed; We incorporated same change for backend tests as can be seen over (https://github.com/marklogic/marklogic-data-hub/pull/7027/files#diff-77c08cc0fc423bde44f6986c394384561686f594764d45b79d21a41d4ae0ee2aR350).

**Review by Sanjeevani19 — APPROVED** [review]

**Review by briantang — APPROVED** [review]
Thank you @AkshayBajajML !

**Pull request merged**
