### PR TITLE
DHFPROD-9233: Graph Overlap

### PR DESCRIPTION
**Pull request by littlecherro**
#### Checklist: 
```diff
- Note: do not change the below
```

- ##### Owner:

- [x] JIRA_ID included in all the commit messages
- [x] PR title is in the format JIRA_ID:Title
- [x] Rebase the branch with upstream
- [x] Squashed all commits into a single commit
- [x] Code passes ESLint tests
- N/A Added Tests
- [x] Ran cypress tests on firefox locally
  

- ##### Reviewer:

- N/A Reviewed Tests
- N/A Added to Release Wiki

### CODE REVIEW

**Comment by littlecherro** [comment]
To help you guys with the review, im leaving these videos here:

BEFORE CHANGES - SLED
https://user-images.githubusercontent.com/108084664/194957961-3f1d8a36-83c4-485d-b61c-09768064987e.mp4

AFTER CHANGES - SLED
https://user-images.githubusercontent.com/108084664/194958032-3f4a4af6-18b4-409e-ac84-450c6ecdbf68.mp4

**Comment by littlecherro** [comment]
im adding vids for QA project as well :)

BEFORE: 

https://user-images.githubusercontent.com/108084664/195350638-5b898db2-1f89-43a5-9a8e-b7aa1ab02627.mp4

AFTER: 

https://user-images.githubusercontent.com/108084664/195350717-cfca9390-fdb4-42db-9721-62827af0a99b.mp4

**Comment by MSBrignoni** [comment]
We were reviewing with @rolonPablo, looks good! the only thing we noticed, is related to the initial process of stabilization ending at about 1:30 minutes, and, in develop branch, 30 seconds (with the same data and browser).
Is much better at the user´s views, but, takes around 1 minute more to stabilize slowly all the nodes. Is this the desired behavior?

**Comment by littlecherro** [comment]
After reviewing the comment that @rolonPablo and @MSBrignoni left, i changed the config and this is the result:

NEW CONFIG QA project: 
https://user-images.githubusercontent.com/108084664/195663683-d9ca7b5c-b3de-4372-9a3f-ab78a98fbdb4.mp4

**Pull request closed without merging**
