### PR TITLE
DHFPROD-6089: Final Intro page illustrations

### PR DESCRIPTION
**Pull request by AkshayBajajML**
#### Checklist: 
```diff
- Note: do not change the below
```

-  ##### Owner:

- [x] JIRA_ID included in all the commit messages
- [x] PR title is in the format JIRA_ID:Title
- [x] Rebase the branch with upstream
- [x] Squashed all commits into a single commit
- N/A Added Tests
  

- ##### Reviewer:

- N/A Reviewed Tests

### CODE REVIEW

**Comment by AkshayBajajML** [comment]
Confirmed UI changes with @jbelonoj

**Review by wooldridge — CHANGES_REQUESTED** [review]
@AkshayBajajML, can we name the new images more concisely and consistently? I suggest:

load-overview.svg
model-overview.svg
curate-overview.svg
run-overview.svg
explore-overview.svg

**Comment by AkshayBajajML** [comment]
@wooldridge Thanks, I agree with it. I will make those changes.

**Review by wooldridge — APPROVED** [review]
Looks good!

**Review by briantang — APPROVED** [review]

**Pull request merged**
