### PR TITLE
DHFPROD-5024: Browse view in tiles needs CSS fixes

### PR DESCRIPTION
**Pull request by timur-isangulov**
#### Checklist: 
```diff
- Note: do not change the below
```

-  ##### Owner:

- [x] JIRA_ID included in all the commit messages
- [x] PR title is in the format JIRA_ID:Title
- [x] Rebase the branch with upstream
- [x] Squashed all commits into a single commit
- [x] Added Tests
  

- ##### Reviewer:

- [x] Reviewed Tests

### CODE REVIEW

**Comment by timur-isangulov** [comment]
No tests needed, only CSS changed.

**Comment by bsrikan** [comment]
The table header is fixed now. There are other issues. Will leave it upto the team to handle it either with this ticket or another one.

Scroll bar issue: https://www.screencast.com/t/M95YhzfL13Mk

Using qa-project, I had saved the query 
image

then went to another tile. when I came back to explore tile, got the message for existing query:
image

I said Cancel and clicked explore tile again. Selected Customer entity, then hit Explore and got an empty table:
image


Would recommend developers to test in and around their own fix.

**Comment by bsrikan** [comment]
Also, although the bug title might say css fix, its not only that. We can add tests to verify table header is fixed via style property. IIRC, there are some tests in curation you can refer to.

**Comment by timur-isangulov** [comment]
> The table header is fixed now. There are other issues. Will leave it upto the team to handle it either with this ticket or another one.
> 
> Scroll bar issue: https://www.screencast.com/t/M95YhzfL13Mk
> 
> Using qa-project, I had saved the query
> image
> 
> then went to another tile. when I came back to explore tile, got the message for existing query:
> image
> 
> I said Cancel and clicked explore tile again. Selected Customer entity, then hit Explore and got an empty table:
> image
> 
> Would recommend developers to test in and around their own fix.

Hi Srikanth,

This may be a bug with saving queries, can you please open a separate jira for that. 

Thanks.

**Comment by timur-isangulov** [comment]
> @timur-isangulov, the table header is not fixed when scrolling

Yes, there seems to be an issue with MLTable, setting vertical scrolling prop the header doesn't resize when clicking on the properties with structured objects. Opened issue for contractors https://project.marklogic.com/jira/browse/UX-131 .

**Pull request merged**
