### PR TITLE
DHFPROD-9614: Disable Concept Actions Based on ML Version

### PR DESCRIPTION
**Pull request by briantang**
#### Checklist: 
```diff
- Note: do not change the below
```

- Also including undefined check fix for https://project.marklogic.com/jira/browse/DHFPROD-9639

- ##### Owner:

- [x] JIRA_ID included in all the commit messages
- [x] PR title is in the format JIRA_ID:Title
- [x] Rebase the branch with upstream
- [x] Squashed all commits into a single commit
- [x] Code passes ESLint tests
- [x] Added Tests
- [x] Ran cypress tests on firefox locally
  

- ##### Reviewer:

- [x] Reviewed Tests
- [x] Added to Release Wiki

### CODE REVIEW

**Comment by briantang** [comment]
Converting to draft for now to fix version checking.

**Review by littlecherro — COMMENTED** [review]
Hey Brian, we were testing with @iveyMarklogic and @aniamy and on 10.0-9.5 concepts are disabled but on older versions works fine. 
https://www.awesomescreenshot.com/video/12169170?key=1c25e90534d32439eb0520b39fc305f9

**Comment by aniamy** [comment]
@briantang Testing with a ML 11 server I'm getting some errors from backend and UI is showing this message. We should update this message for this error scenarios.
image

**Review by aniamy — APPROVED** [review]

**Review by littlecherro — APPROVED** [review]

**Review by Sanjeevani19 — COMMENTED** [review]
@rolonPablo Looks like core tests are failing due to unauthorized error, not sure if these are related to the changes you made http://jenkins1.marklogic.com/blue/organizations/jenkins/Datahub_CI/detail/PR-7321/15/tests, Could you please look into it ?

**Comment by briantang** [comment]
Remaining e2e is intermittent. This PR can be merged.

**Review by iveyMarklogic — APPROVED** [review]

**Comment by briantang** [comment]
Other PR merge caused a conflict. Pushed a fix. Needs reviews.

**Review by littlecherro — APPROVED** [review]

**Review by aniamy — APPROVED** [review]

**Review by Sanjeevani19 — COMMENTED** [review]
Now that we have a seg fault fix for 11.0.Nightly, Could we also test this PR on that server version ?

**Comment by ngodugu-marklogic** [comment]
E2E test look intermittent, we can merge this PR manually @Sanjeevani19

**Review by iveyMarklogic — APPROVED** [review]

**Pull request merged**
