### PR TITLE
DHFPROD-7296: Home Page: Links not Keyboard Accessible

### PR DESCRIPTION
**Pull request by amejiaq**
#### Checklist: 
```diff
- Note: do not change the below
```

- ##### Owner:

- [x] JIRA_ID included in all the commit messages
- [x] PR title is in the format JIRA_ID:Title
- [x] Rebase the branch with upstream
- [x] Squashed all commits into a single commit
- [n/a] Added Tests
- [x] Ran cypress tests on firefox locally
  

- ##### Reviewer:

- [x] Reviewed Tests
- [x] Added to Release Wiki

### CODE REVIEW

**Review by briantang — CHANGES_REQUESTED** [review]
@amejiaq Couple things, I only see this working for the first card (Load) and not the other 4 cards in the overview page. Also it looks like the "Video Tutorial" link is being skipped when keyboard navigating. Hitting ENTER should also open the links but currently it does not.

**Comment by amejiaq** [comment]
> @amejiaq Couple things, I only see this working for the first card (Load) and not the other 4 cards in the overview page. Also it looks like the "Video Tutorial" link is being skipped when keyboard navigating. Hitting ENTER should also open the links but currently it does not.

Fixed!, I dropped my changes resolving a conflict but now is ready to review

**Review by briantang — DISMISSED** [review]
Looks good now. Potentially we should add this scenario to the manual testing wiki: https://wiki.marklogic.com/display/ENGINEERING/Manual+Testing+Scenarios

**Comment by amejiaq** [comment]
> Looks good now. Potentially we should add this scenario to the manual testing wiki: https://wiki.marklogic.com/display/ENGINEERING/Manual+Testing+Scenarios

Done!

**Review by MSBrignoni — CHANGES_REQUESTED** [review]
The navigation with "tab" looks good!, but, when I hit "enter", is not going properly.

https://user-images.githubusercontent.com/89084298/208500410-7dce9e30-b0f6-4714-9b57-1889524e21fa.mp4

**Comment by amejiaq** [comment]
> The navigation with "tab" looks good!, but, when I hit "enter", is not going properly.
> 
>  Screen_Recording_.12-19-2022_3-24-05_PM.mp4

Fixed! 🛠

**Review by MSBrignoni — APPROVED** [review]

**Review by briantang — APPROVED** [review]

**Pull request merged**
