### PR TITLE
DHFPROD-6531: Mapping properties from first mapping pre-populated on all other mappings

### PR DESCRIPTION
**Pull request by xnikhil08**
### Description
We will revisit any test scenarios for this bug in a separate mini-hardening, in the interest of time. Just the fix for the bug is included in this PR.

#### Checklist: 
```diff
- Note: do not change the below
```

-  ##### Owner:

- [x] JIRA_ID included in all the commit messages
- [x] PR title is in the format JIRA_ID:Title
- [x] Rebase the branch with upstream
- [x] Squashed all commits into a single commit
- [x] Code passes ESLint tests
- [N/A] Added Tests
  

- ##### Reviewer:

- [ N/A] Reviewed Tests

### CODE REVIEW

**Review by Sanjeevani19 — COMMENTED** [review]
Works as expected, @xnikhil08 Do you think it's better we add a e2e scenario for this, Given the time constraint if you think it would take some time, let's create a separate task to cover these scenarios

**Review by Sanjeevani19 — DISMISSED** [review]

**Comment by xnikhil08** [comment]
> Works as expected, @xnikhil08 Do you think it's better we add a e2e scenario for this, Given the time constraint if you think it would take some time, let's create a separate task to cover these scenarios

@Sanjeevani19 - We should definitely include an e2e scenario for this, but given the timing constraint i was thinking if we can take that up as a part of separate ticket, unless this bug is not a blocker anymore.

**Review by srinathgit — CHANGES_REQUESTED** [review]
~~After applying the fix, can you try this, create a new map for entity1 and save it, open entity2 pane , UI breaks~~
The above issue is already present in develop

**Comment by Sanjeevani19** [comment]
> > Works as expected, @xnikhil08 Do you think it's better we add a e2e scenario for this, Given the time constraint if you think it would take some time, let's create a separate task to cover these scenarios
> 
> @Sanjeevani19 - We should definitely include an e2e scenario for this, but given the timing constraint i was thinking if we can take that up as a part of separate ticket, unless this bug is not a blocker anymore.

https://project.marklogic.com/jira/browse/DHFPROD-6521, created this task to handle these test scenarios

**Review by srinathgit — CHANGES_REQUESTED** [review]
I create a step 'map1', add a property, close it. I create another step 'map2', when I add a property, 'map1' gets overwritten. see
https://drive.google.com/file/d/1FfT4BhPT3pCx3L9vbIpoAaiFP-6doWwz/view

**Comment by xnikhil08** [comment]
> I create a step 'map1', add a property, close it. I create another step 'map2', when I add a property, 'map1' gets overwritten. see
> https://drive.google.com/file/d/1FfT4BhPT3pCx3L9vbIpoAaiFP-6doWwz/view

@srinathgit - Fixed it. Another review ?

**Review by srinathgit — APPROVED** [review]
Looks good

**Review by Sanjeevani19 — APPROVED** [review]

**Review by srinathgit — CHANGES_REQUESTED** [review]
https://jenkins.marklogic.com/blue/organizations/jenkins/Datahub_CI/detail/PR-5125/3/tests 
e2e test failure

**Comment by Sanjeevani19** [comment]
> https://jenkins.marklogic.com/blue/organizations/jenkins/Datahub_CI/detail/PR-5125/3/tests
> e2e test failure

@srinathgit This might be a intermittent test failure, not related to this PR, Could you please remove Changes requested state so that the tests will run again

**Review by srinathgit — APPROVED** [review]

**Pull request merged**
