### PR TITLE
DHFPROD-6119: Ant Design components are fixed to body element

### PR DESCRIPTION
**Pull request by xnikhil08**
### Description
This is just fixing implementation detail for ant design components, to fix the issue where some components like tooltip, popovers etc., were being fixed to the body element. No tests are required here.

#### Checklist: 
```diff
- Note: do not change the below
```

-  ##### Owner:

- [x] JIRA_ID included in all the commit messages
- [x] PR title is in the format JIRA_ID:Title
- [x] Rebase the branch with upstream
- [x] Squashed all commits into a single commit
- [ N/A] Added Tests
  

- ##### Reviewer:

- [ N/A] Reviewed Tests

### CODE REVIEW

**Review by timur-isangulov — CHANGES_REQUESTED** [review]
HI @xnikhil08, I noticed that tooltips on the table view to show processed data and complete json are not centered. 
Screen Shot 2020-10-22 at 9 21 23 AM
Screen Shot 2020-10-22 at 9 20 01 AM

**Comment by xnikhil08** [comment]
@timur-isangulov - Pushed a fix for the tooltips. The tooltips will not be center aligned if they are close to the right toolbar because they cannot overlap the toolbar container so they will look like in the screenshot below.
image

**Review by timur-isangulov — APPROVED** [review]

**Review by brucean52 — APPROVED** [review]

**Comment by Sanjeevani19** [comment]
> @timur-isangulov - Pushed a fix for the tooltips. The tooltips will not be center aligned if they are close to the right toolbar because they cannot overlap the toolbar container so they will look like in the screenshot below.
> image

@xnikhil08 Did UX approve these changes ?

**Comment by xnikhil08** [comment]
Looks like few tests are failing. Keeping this in draft until those are fixed.

**Review by wooldridge — CHANGES_REQUESTED** [review]
I'm seeing the popovers on the Mapping details disconnected: 

https://drive.google.com/file/d/1gAq6oBWKAekHrcMQanMVqLmixpO7S8f_/view

**Comment by xnikhil08** [comment]
> I'm seeing the popovers on the Mapping details disconnected:
> 
> https://drive.google.com/file/d/1gAq6oBWKAekHrcMQanMVqLmixpO7S8f_/view

@wooldridge - Could you please confirm if this is happening in the below 5.4 develop branch as well.
https://github.com/xnikhil08/marklogic-data-hub/tree/DHFPROD-6119-5.4Develop
For some reason it's working fine for me over there.

**Comment by xnikhil08** [comment]
> > @timur-isangulov - Pushed a fix for the tooltips. The tooltips will not be center aligned if they are close to the right toolbar because they cannot overlap the toolbar container so they will look like in the screenshot below.
> > image
> 
> @xnikhil08 Did UX approve these changes ?

@Sanjeevani19 - Yes.

**Comment by xnikhil08** [comment]
> I'm seeing the popovers on the Mapping details disconnected:
> 
> https://drive.google.com/file/d/1gAq6oBWKAekHrcMQanMVqLmixpO7S8f_/view

@wooldridge - The popovers seems to be working fine in 5.4 branch so, per my discussion with both UX and PM, we can move forward with the changes in the PR along with the popover exceptions in mapping as its not a blocker for 5.3.

**Review by timur-isangulov — APPROVED** [review]

**Review by Sanjeevani19 — APPROVED** [review]

**Review by wooldridge — APPROVED** [review]

**Pull request merged**
