### PR TITLE
DHFPROD-7744: Component Replacement: Create a theme on bootstrap 

### PR DESCRIPTION
**Pull request by iveyMarklogic**
#### Checklist: 
```diff
- Note: do not change the below
```

-  ##### Owner:

- [x] JIRA_ID included in all the commit messages
- [x] PR title is in the format JIRA_ID:Title
- [x] Rebase the branch with upstream
- [x] Squashed all commits into a single commit
- [x] Code passes ESLint tests
- [x] Added Tests
- [x] Run UI tests
  

- ##### Reviewer:

- [x] Reviewed Tests

### CODE REVIEW

**Review by romanlescano — APPROVED** [review]

**Review by mrodrigu-marklogic — APPROVED** [review]
LGTM

**Review by yubiselmarklogic — APPROVED** [review]

**Review by aniamy — APPROVED** [review]

**Review by briantang — APPROVED** [review]

**Review by wooldridge — APPROVED** [review]
Approved. I'm seeing changes in the HCTheme.scss file show up in the app, for example changing $text-color to rgb(255, 0, 0):

Screen Shot 2021-08-24 at 6 19 27 PM

**Comment by SameeraPriyathamTadikonda** [comment]
@iveyMarklogic One cypress E2E test failed on your PR

https://jenkins.marklogic.com/blue/organizations/jenkins/Datahub_CI/detail/PR-6028/3/tests

**Review by yubiselmarklogic — DISMISSED** [review]

**Review by mrodrigu-marklogic — DISMISSED** [review]

**Review by Sanjeevani19 — DISMISSED** [review]

**Comment by wooldridge** [comment]
E2E failing test: relatedEntityMapping.spec.tsx

AssertionError: Timed out retrying after 12000ms: expected '<span>' to have text '444-44-4440', but the text was 'null'

Reviewing video:

Screen Shot 2021-08-27 at 5 11 56 PM

On Jenkins, "SSN" is being typed into the entity mapping fields twice, leading to null values in the Test column. CC: @ngodugu-marklogic

**Review by yubiselmarklogic — DISMISSED** [review]

**Review by yubiselmarklogic — APPROVED** [review]

**Review by yubiselmarklogic — APPROVED** [review]

**Review by briantang — APPROVED** [review]

**Review by aniamy — APPROVED** [review]

**Review by Sanjeevani19 — APPROVED** [review]

**Review by mrodrigu-marklogic — APPROVED** [review]

**Review by yubiselmarklogic — APPROVED** [review]

**Review by romanlescano — APPROVED** [review]

**Pull request merged**
