### PR TITLE
DHFPROD-5229: Save a match ruleset, DHFPROD-5250: Delete a match ruleset

### PR DESCRIPTION
**Pull request by brucean52**
#### Checklist: 
```diff
- Note: do not change the below
```

-  ##### Owner:

- [x] JIRA_ID included in all the commit messages
- [x] PR title is in the format JIRA_ID:Title
- [x] Rebase the branch with upstream
- [x] Squashed all commits into a single commit
- [x] Added Tests
  

- ##### Reviewer:

- [x] Reviewed Tests

### CODE REVIEW

**Review by Sanjeevani19 — CHANGES_REQUESTED** [review]
@brucean52 was able to add two match rule sets with same name and match type, not sure if this is allowed, please look into it
https://drive.google.com/file/d/1utdyTPEqBE0Pq8mBnrG981Cqk4b96O_n/view

Was able to save a match rule set without property name
https://drive.google.com/file/d/1ZtwRi_42OFj5NRjgOlWKUqbIqdgaRse6/view

**Comment by brucean52** [comment]
> @brucean52 was able to add two match rule sets with same name and match type, not sure if this is allowed, please look into it
> https://drive.google.com/file/d/1utdyTPEqBE0Pq8mBnrG981Cqk4b96O_n/view

per @ryanjdew duplicate match rulesets are allowed.

**Comment by brucean52** [comment]
fixed being able to save a ruleset without selecting a property to match.

**Review by Sanjeevani19 — DISMISSED** [review]

**Review by Sanjeevani19 — COMMENTED** [review]
@brucean52 Could you please add unit tests to check for validation error messages ?

**Review by ryanjdew — DISMISSED** [review]

**Comment by brucean52** [comment]
> @brucean52 Could you please add unit tests to check for validation error messages when submitting an empty form or when required fields are missing ?

added tests.

**Review by Sanjeevani19 — APPROVED** [review]

**Review by ryanjdew — APPROVED** [review]

**Pull request merged**
