### PR TITLE
DHFPROD-6167: Correct Column name Entity to Entity Type.

### PR DESCRIPTION
**Pull request by timur-isangulov**
DHFPROD-5599: Don't show pagination controls if 0 or 1 pages.
DHFPROD-6126: Radio Group Switcher Hover State.
DHFPROD-6287: source name and source type facets are rendered in incorect location.

#### Checklist: 
```diff
- Note: do not change the below
```

-  ##### Owner:

- [x] JIRA_ID included in all the commit messages
- [x] PR title is in the format JIRA_ID:Title
- [x] Rebase the branch with upstream
- [x] Squashed all commits into a single commit
- [x] Added Tests
  

- ##### Reviewer:

- [x] Reviewed Tests

### CODE REVIEW

**Review by wooldridge — CHANGES_REQUESTED** [review]
Very nice work, @timur-isangulov. I like the hideOnSinglePage configurability for DHFPROD-5599.

I see an issue with that feature, however. I describe it in detail here:

https://project.marklogic.com/jira/browse/DHFPROD-5599

Let's see what UX thinks.

**Comment by wooldridge** [comment]
UX updated the requirements for DHFPROD-5599. We will show the per-page menu when the number of results is > 10 (but still hide the other navigation elements when there are only one page of results). That will fix the problem I described. Details on the ticket: https://project.marklogic.com/jira/browse/DHFPROD-5599

**Comment by timur-isangulov** [comment]
> Very nice work, @timur-isangulov. I like the hideOnSinglePage configurability for DHFPROD-5599.
> 
> I see an issue with that feature, however. I describe it in detail here:
> 
> https://project.marklogic.com/jira/browse/DHFPROD-5599
> 
> Let's see what UX thinks.

Thanks Mike,  I  added requested changes, would you please review again.

**Review by Sanjeevani19 — APPROVED** [review]

**Review by wooldridge — APPROVED** [review]
Thanks, @timur-isangulov! My manually testing of the pagination passes now: https://drive.google.com/file/d/1QrweQekRhkIAbu3_4lgHpHuSPnTNLIqt/view

I see you added tests and all the unit tests pass, awesome.

**Pull request merged**
