### PR TITLE
MLUI-136: map component

### PR DESCRIPTION
**Pull request by wooldridge**
Refactor map component (logic), create map-ui component (presentation), create story for map-ui.

### CODE REVIEW

**Comment by wooldridge** [comment]
More details about these updates here: https://project.marklogic.com/jira/browse/MLUI-205

**Comment by wooldridge** [comment]
@alexsmr, thanks. My latest commits should fix the problems, I'm now seeing the build test pass locally.

**Comment by alexsmr** [comment]
@wooldridge, There are a bunch of e2e tests failures, can you please investigate them: https://jenkins.marklogic.com/view/DHF-9.0-Server-All/job/dhf-QS-develop-rh7-Commit/209/

**Comment by alexsmr** [comment]
@wooldridge Sorry, I confused it with other PR. This one still fails. Can you please investigate: https://jenkins.marklogic.com/view/DHF-9.0-Server-All/job/dhf-QS-develop-rh7-Commit/211 ?

**Comment by wooldridge** [comment]
@alexsmr, those errors should be fixed with my latest commit.

**Comment by wooldridge** [comment]
I see the following errors when running the e2e tests on my MLUI-136-map-ui branch:

**************************************************
*                    Failures                    *
**************************************************

1) QuickStart mappings Run Mappings should create a mapping for Product entity with sku source
  - Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
  - Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.

2) QuickStart mappings Run Mappings should update MapProduct with SKU source
  - Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.

3) QuickStart mappings Run Mappings should create Harmonize SKU flow on Product
  - Failed: No element found using locator: by.cssContainingText("app-select-list td", "MapProduct")

4) QuickStart mappings Run Mappings should redeploy modules
  - Failed: unknown error: Element <mdl-button _ngcontent-c7="" id="redeploy-button" mdl-button-type="raised" mdl-colored="primary" mdl-ripple="" tooltip="This will clear our your modules database and reload the modules located in the plugins directory. You shouldn't need to do this since modules are automatically deployed." tooltipplacement="top" ng-reflect-mdl-button-type="raised" ng-reflect-mdl-colored-type="primary" ng-reflect-ripple-active="" ng-reflect-content="This will clear our your modul" ng-reflect-placement="top" class="mdl-button mdl-button--raised mdl-button--primary">...</mdl-button> is not clickable at point (149, 1038). Other element would receive the click: <mdl-backdrop-overlay class="dialog-backdrop" style="z-index: 100000;"></mdl-backdrop-overlay>
    (Session info: headless chrome=70.0.3538.102)
    (Driver info: chromedriver=2.43.600229 (3fae4d0cda5334b4f533bede5a4787f7b832d052),platform=Mac OS X 10.11.6 x86_64)

5) QuickStart mappings Run Mappings should run Harmonize SKU flow with mapping
  - Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
  - Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.

6) QuickStart mappings Run Mappings should verify the harmonized SKU data with mappings
  - Failed: unknown error: Element <a _ngcontent-c2="" class="mdl-navigation__link" id="browser-tab" ng-reflect-klass="mdl-navigation__link" ng-reflect-ng-class="[object Object]" ng-reflect-router-link="browse" href="#/browse">...</a> is not clickable at point (1462, 32). Other element would receive the click: <mdl-backdrop-overlay class="dialog-backdrop" style="z-index: 100000;"></mdl-backdrop-overlay>
    (Session info: headless chrome=70.0.3538.102)
    (Driver info: chromedriver=2.43.600229 (3fae4d0cda5334b4f533bede5a4787f7b832d052),platform=Mac OS X 10.11.6 x86_64)

7) QuickStart mappings Run Mappings should rollback to current URI when providing invalid URI
  - Failed: unknown error: Element <a _ngcontent-c2="" class="mdl-navigation__link" id="mappings-tab" ng-reflect-klass="mdl-navigation__link" ng-reflect-ng-class="[object Object]" ng-reflect-router-link="mappings" href="#/mappings">...</a> is not clickable at point (1321, 32). Other element would receive the click: <mdl-backdrop-overlay class="dialog-backdrop" style="z-index: 100000;"></mdl-backdrop-overlay>
    (Session info: headless chrome=70.0.3538.102)
    (Driver info: chromedriver=2.43.600229 (3fae4d0cda5334b4f533bede5a4787f7b832d052),platform=Mac OS X 10.11.6 x86_64)

8) QuickStart mappings Run Mappings should verify the behavior on reset cancel
  - Failed: unknown error: Element <a _ngcontent-c2="" class="mdl-navigation__link" id="mappings-tab" ng-reflect-klass="mdl-navigation__link" ng-reflect-ng-class="[object Object]" ng-reflect-router-link="mappings" href="#/mappings">...</a> is not clickable at point (1321, 32). Other element would receive the click: <mdl-backdrop-overlay class="dialog-backdrop" style="z-index: 100000;"></mdl-backdrop-overlay>
    (Session info: headless chrome=70.0.3538.102)
    (Driver info: chromedriver=2.43.600229 (3fae4d0cda5334b4f533bede5a4787f7b832d052),platform=Mac OS X 10.11.6 x86_64)

9) QuickStart mappings Run Mappings should verify the behavior on reset ok
  - Failed: unknown error: Element <a _ngcontent-c2="" class="mdl-navigation__link" id="mappings-tab" ng-reflect-klass="mdl-navigation__link" ng-reflect-ng-class="[object Object]" ng-reflect-router-link="mappings" href="#/mappings">...</a> is not clickable at point (1321, 32). Other element would receive the click: <mdl-backdrop-overlay class="dialog-backdrop" style="z-index: 100000;"></mdl-backdrop-overlay>
    (Session info: headless chrome=70.0.3538.102)
    (Driver info: chromedriver=2.43.600229 (3fae4d0cda5334b4f533bede5a4787f7b832d052),platform=Mac OS X 10.11.6 x86_64)

10) QuickStart uninstall Uninstall should go to the settings page
  - Failed: unknown error: Element <a _ngcontent-c2="" class="mdl-navigation__link" id="settings-tab" ng-reflect-klass="mdl-navigation__link" ng-reflect-ng-class="[object Object]" ng-reflect-router-link="settings" href="#/settings">...</a> is not clickable at point (1790, 32). Other element would receive the click: <mdl-backdrop-overlay class="dialog-backdrop" style="z-index: 100000;"></mdl-backdrop-overlay>
    (Session info: headless chrome=70.0.3538.102)
    (Driver info: chromedriver=2.43.600229 (3fae4d0cda5334b4f533bede5a4787f7b832d052),platform=Mac OS X 10.11.6 x86_64)

11) QuickStart uninstall Uninstall should click the uninstall button
  - Failed: No element found using locator: by.buttonText("Uninstall Hub")

12) QuickStart uninstall Uninstall should show the uninstall progress bar
  - Failed: EPIPE write EPIPE

13) QuickStart uninstall Uninstall should uninstall the hub
  - Failed: EPIPE write EPIPE

Executed 129 of 129 specs (13 FAILED) in 34 mins 45 secs.
FINISHED: creating xml report
[14:34:06] I/launcher - 0 instance(s) of WebDriver still running
[14:34:06] I/launcher - chrome #01 failed 13 test(s)
[14:34:06] I/launcher - overall: 13 failed spec(s)
[14:34:06] E/launcher - Process exited with error code 1

**Comment by wooldridge** [comment]
FYI, I see the following when I run e2e tests on the mlui-integration branch, so it looks like the "Run Mappings" tests have issues across the board: 

**************************************************
*                    Failures                    *
**************************************************

1) QuickStart mappings Run TypeAhead should create Harmonize WorldBank flow
  - Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
  - Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.

2) QuickStart mappings Run TypeAhead should run Harmonize WorldBank flow with mapping
  - Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
  - Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.

3) QuickStart mappings Run TypeAhead should verify the harmonized data with mappings
  - Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
  - Expected 'Showing Results 1 to 10 of 1857
  <<
  <
  1
  2
  3
  4
  5
  6
  7
  8
  9
  >
  >>' to contain 'Showing Results 1 to 1 of 1'.
  - Expected '/product/private/board_games.csv-0-70?doc=yes&type=foo' to contain '/world_bank.zip-0-100'.

4) QuickStart mappings Run Mappings should create a mapping for Product entity with sku source
  - Failed: stale element reference: element is not attached to the page document
    (Session info: headless chrome=70.0.3538.102)
    (Driver info: chromedriver=2.43.600229 (3fae4d0cda5334b4f533bede5a4787f7b832d052),platform=Mac OS X 10.11.6 x86_64)

5) QuickStart mappings Run Mappings should update MapProduct with SKU source
  - Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
  - Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.

6) QuickStart mappings Run Mappings should create Harmonize SKU flow on Product
  - Failed: No element found using locator: by.cssContainingText("app-select-list td", "MapProduct")

7) QuickStart mappings Run Mappings should redeploy modules
  - Failed: unknown error: Element <mdl-button _ngcontent-c7="" id="redeploy-button" mdl-button-type="raised" mdl-colored="primary" mdl-ripple="" tooltip="This will clear our your modules database and reload the modules located in the plugins directory. You shouldn't need to do this since modules are automatically deployed." tooltipplacement="top" ng-reflect-mdl-button-type="raised" ng-reflect-mdl-colored-type="primary" ng-reflect-ripple-active="" ng-reflect-content="This will clear our your modul" ng-reflect-placement="top" class="mdl-button mdl-button--raised mdl-button--primary">...</mdl-button> is not clickable at point (149, 1038). Other element would receive the click: <mdl-backdrop-overlay class="dialog-backdrop" style="z-index: 100000;"></mdl-backdrop-overlay>
    (Session info: headless chrome=70.0.3538.102)
    (Driver info: chromedriver=2.43.600229 (3fae4d0cda5334b4f533bede5a4787f7b832d052),platform=Mac OS X 10.11.6 x86_64)

8) QuickStart mappings Run Mappings should run Harmonize SKU flow with mapping
  - Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
  - Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.

9) QuickStart mappings Run Mappings should verify the harmonized SKU data with mappings
  - Failed: unknown error: Element <a _ngcontent-c2="" class="mdl-navigation__link" id="browser-tab" ng-reflect-klass="mdl-navigation__link" ng-reflect-ng-class="[object Object]" ng-reflect-router-link="browse" href="#/browse">...</a> is not clickable at point (1462, 32). Other element would receive the click: <mdl-backdrop-overlay class="dialog-backdrop" style="z-index: 100000;"></mdl-backdrop-overlay>
    (Session info: headless chrome=70.0.3538.102)
    (Driver info: chromedriver=2.43.600229 (3fae4d0cda5334b4f533bede5a4787f7b832d052),platform=Mac OS X 10.11.6 x86_64)

10) QuickStart mappings Run Mappings should rollback to current URI when providing invalid URI
  - Failed: unknown error: Element <a _ngcontent-c2="" class="mdl-navigation__link" id="mappings-tab" ng-reflect-klass="mdl-navigation__link" ng-reflect-ng-class="[object Object]" ng-reflect-router-link="mappings" href="#/mappings">...</a> is not clickable at point (1321, 32). Other element would receive the click: <mdl-backdrop-overlay class="dialog-backdrop" style="z-index: 100000;"></mdl-backdrop-overlay>
    (Session info: headless chrome=70.0.3538.102)
    (Driver info: chromedriver=2.43.600229 (3fae4d0cda5334b4f533bede5a4787f7b832d052),platform=Mac OS X 10.11.6 x86_64)

11) QuickStart mappings Run Mappings should verify the behavior on reset cancel
  - Failed: unknown error: Element <a _ngcontent-c2="" class="mdl-navigation__link" id="mappings-tab" ng-reflect-klass="mdl-navigation__link" ng-reflect-ng-class="[object Object]" ng-reflect-router-link="mappings" href="#/mappings">...</a> is not clickable at point (1321, 32). Other element would receive the click: <mdl-backdrop-overlay class="dialog-backdrop" style="z-index: 100000;"></mdl-backdrop-overlay>
    (Session info: headless chrome=70.0.3538.102)
    (Driver info: chromedriver=2.43.600229 (3fae4d0cda5334b4f533bede5a4787f7b832d052),platform=Mac OS X 10.11.6 x86_64)

12) QuickStart mappings Run Mappings should verify the behavior on reset ok
  - Failed: unknown error: Element <a _ngcontent-c2="" class="mdl-navigation__link" id="mappings-tab" ng-reflect-klass="mdl-navigation__link" ng-reflect-ng-class="[object Object]" ng-reflect-router-link="mappings" href="#/mappings">...</a> is not clickable at point (1321, 32). Other element would receive the click: <mdl-backdrop-overlay class="dialog-backdrop" style="z-index: 100000;"></mdl-backdrop-overlay>
    (Session info: headless chrome=70.0.3538.102)
    (Driver info: chromedriver=2.43.600229 (3fae4d0cda5334b4f533bede5a4787f7b832d052),platform=Mac OS X 10.11.6 x86_64)

13) QuickStart uninstall Uninstall should go to the settings page
  - Failed: unknown error: Element <a _ngcontent-c2="" class="mdl-navigation__link" id="settings-tab" ng-reflect-klass="mdl-navigation__link" ng-reflect-ng-class="[object Object]" ng-reflect-router-link="settings" href="#/settings">...</a> is not clickable at point (1790, 32). Other element would receive the click: <mdl-backdrop-overlay class="dialog-backdrop" style="z-index: 100000;"></mdl-backdrop-overlay>
    (Session info: headless chrome=70.0.3538.102)
    (Driver info: chromedriver=2.43.600229 (3fae4d0cda5334b4f533bede5a4787f7b832d052),platform=Mac OS X 10.11.6 x86_64)

14) QuickStart uninstall Uninstall should click the uninstall button
  - Failed: No element found using locator: by.buttonText("Uninstall Hub")

15) QuickStart uninstall Uninstall should show the uninstall progress bar
  - Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
  - Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.

16) QuickStart uninstall Uninstall should uninstall the hub
  - Failed: Wait timed out after 200011ms

Executed 129 of 129 specs (16 FAILED) in 56 mins 50 secs.
FINISHED: creating xml report
[17:18:39] I/launcher - 0 instance(s) of WebDriver still running
[17:18:39] I/launcher - chrome #01 failed 16 test(s)
[17:18:39] I/launcher - overall: 16 failed spec(s)
[17:18:39] E/launcher - Process exited with error code 1

**Comment by alexsmr** [comment]
@wooldridge please trigger one more build by committing some changes.

**Comment by wooldridge** [comment]
@alexsmr, my recent merge should trigger a build.

**Comment by alexsmr** [comment]
@wooldridge please trigger one more build by committing some changes. It had been run on bad machine.

**Comment by wooldridge** [comment]
@alexsmr, that latest commit should trigger a rebuild.

**Comment by wooldridge** [comment]
@alexsmr, merged with latest from mlui-integration.

**Comment by alexsmr** [comment]
@wooldridge Mike, can you please fix the build. Looks like I have messed when fixing conflicts. Thanks.

**Pull request merged**
