### PR TITLE
DHFPROD-7907: Viewing certain entities in Explore breaks UI

### PR DESCRIPTION
**Pull request by federicoRufrancosMarklogic**
#### Checklist: 
```diff
- Note: do not change the below
```

-  ##### Owner:

- [X] JIRA_ID included in all the commit messages
- [X] PR title is in the format JIRA_ID:Title
- [X] Rebase the branch with upstream
- [X] Squashed all commits into a single commit
- [X] Run UI tests
  

- ##### Reviewer:

- [ ] Reviewed Tests

### CODE REVIEW

**Review by wooldridge — APPROVED** [review]

**Comment by wooldridge** [comment]
@briantang FYI, this is working for me. No compile issues.

**Comment by briantang** [comment]
@federicoRufrancosMarklogic @wooldridge Ah, looks like the tests still don't like ML Design System even if it's just this one instance.
Screen Shot 2021-09-28 at 6 33 27 PM

**Comment by federicoRufrancosMarklogic** [comment]
> @federicoRufrancosMarklogic @wooldridge Ah, looks like the tests still don't like ML Design System even if it's just this one instance. Screen Shot 2021-09-28 at 6 33 27 PM

I see the error on my local environment, but I don't follow the source of the error. I switched to develop if I could reproduce and it's working fine there.
I'm guessing that maybe the error comes from the design-system library, right?

**Review by yubiselmarklogic — APPROVED** [review]

**Review by xnikhil08 — APPROVED** [review]
Works for me.

**Comment by wooldridge** [comment]
@federicoRufrancosMarklogic, I discussed this with @briantang and we decided we should not worry about fixing this right now unless it is blocking the replacement work. (Eventually we will need to fix this as part of the Table component replacement, but that will involve using a new component altogether.) So we can close this PR and move the Jira ticket back to the Backlog.

**Pull request closed without merging**
