### PR TITLE
DHFPROD-7768: Threshold and ruleset handle names are not displayed

### PR DESCRIPTION
**Pull request by briantang**
#### Checklist: 
```diff
- Note: do not change the below
```

-  ##### Owner:

- [x] JIRA_ID included in all the commit messages
- [x] PR title is in the format JIRA_ID:Title
- [x] Rebase the branch with upstream
- [x] Squashed all commits into a single commit
- [x] Code passes ESLint tests
- [x] Added Tests
- [x] Run UI tests
  

- ##### Reviewer:

- [x] Reviewed Tests

### CODE REVIEW

**Review by Sanjeevani19 — DISMISSED** [review]

**Review by ngodugu-marklogic — APPROVED** [review]

**Comment by briantang** [comment]
Rebased with latest updates to the branch. Needs re-review

**Review by ngodugu-marklogic — APPROVED** [review]

**Review by wooldridge — APPROVED** [review]
Nice, I see it working again: https://drive.google.com/file/d/1afz2XtBXg4fMtEkbNIw_Hxce5TOxVFCu/view

**Comment by briantang** [comment]
Pushing additional e2e fixes due to ML Design system removal where selectors needed to be reworked. Checking to see if number of failures go down. Explore page seems to be breaking so expecting those related tests to still fail. Will monitor.

**Review by Sanjeevani19 — COMMENTED** [review]
@briantang Looks like still 3 e2e tests are still failing on the pipeline https://jenkins.marklogic.com/blue/organizations/jenkins/Datahub_CI/detail/PR-6009/8/tests, Please look into them

**Review by Sanjeevani19 — APPROVED** [review]

**Pull request merged**
