### PR TITLE
DHFPROD-6444: Removing OBE scaffolding code

### PR DESCRIPTION
**Pull request by rjrudin**
### Description

I noticed this while testing out custom steps and custom step definitions. 

#### Checklist: 
```diff
- Note: do not change the below
```

-  ##### Owner:

- [x] JIRA_ID included in all the commit messages
- [x] PR title is in the format JIRA_ID:Title
- [x] Rebase the branch with upstream
- [x] Squashed all commits into a single commit
- [x] Code passes ESLint tests
- [x] Added Tests
  

- ##### Reviewer:

- [x] Reviewed Tests

### CODE REVIEW

**Review by akshaysonvane — DISMISSED** [review]
+0 −1,085; nice!

**Review by srinathgit — CHANGES_REQUESTED** [review]
There are 3 test failures
https://jenkins.marklogic.com/blue/organizations/jenkins/Datahub_CI/detail/PR-5065/1/tests

**Review by akshaysonvane — DISMISSED** [review]

**Review by ryanjdew — DISMISSED** [review]

**Review by srinathgit — COMMENTED** [review]
Should we delete these since in QS we still allow creation of custom-mapping , custom-mastering steps ?

**Comment by rjrudin** [comment]
@srinathgit  Argh - good point. Yeah, they need to stay then. I'll update the PR and add comments to those files to note that QS still needs them.

**Comment by rjrudin** [comment]
Removed the custom mapping/mastering files per review.

**Review by srinathgit — APPROVED** [review]

**Review by ryanjdew — APPROVED** [review]

**Pull request merged**
