### PR TITLE
DHFPROD-7680: Component Replacement: Avatar

### PR DESCRIPTION
**Pull request by federicoRufrancosMarklogic**
#### Checklist: 
```diff
- Note: do not change the below
```

-  ##### Owner:

- [X] JIRA_ID included in all the commit messages
- [X] PR title is in the format JIRA_ID:Title
- [X] Rebase the branch with upstream
- [X] Squashed all commits into a single commit
- [ ] Code passes ESLint tests
- [X] Added Tests
- [X] Run UI tests
  

- ##### Reviewer:

- [ ] Reviewed Tests

### CODE REVIEW

**Review by Sanjeevani19 — COMMENTED** [review]
@federicoRufrancosMarklogic Looks like the PR title is not matching the JIRA title, Could you please change it to "DHFPROD-7680 : Component Replacement: Avatar" - This is the format we follow "JIRA ID : JIRA Title"
-  Also we run npm run lint . -- --fix from the UI directory on all our PR's so that there are no linting issues, Could you also make sure that is run

**Comment by federicoRufrancosMarklogic** [comment]
@Sanjeevani19 I just update PR title and run eslint on the UI folder, there are no issues related with my changes.

**Comment by SameeraPriyathamTadikonda** [comment]
> @Sanjeevani19 I just update PR title and run eslint on the UI folder, there are no issues related with my changes.

@federicoRufrancosMarklogic  PR Title should be JIRA_ID:<PR_TITLE>

**Comment by Sanjeevani19** [comment]
> @Sanjeevani19 I just update PR title and run eslint on the UI folder, there are no issues related with my changes.

@federicoRufrancosMarklogic there is a semicolon missing in between JIRA_ID and JIRA title

**Review by aniamy — APPROVED** [review]

**Review by romanlescano — DISMISSED** [review]

**Review by wooldridge — CHANGES_REQUESTED** [review]
@federicoRufrancosMarklogic, functionality looks great!

I'm seeing a lot of changes in this PR that are not related to the Avatar component replacement. And my linting shows errors. I think if we tried to merge, there could be problems.

I suggest doing the following:

1. Create a new branch (off of feature/ant-lib-replacement) with just the header.tsx and header.module.tsx updates to support the Avatar component replacement.
2. Create a new PR. 
3. Close this PR.

Sorry for the extra work, once this first PR goes through, we should be looking good!

**Comment by federicoRufrancosMarklogic** [comment]
> @federicoRufrancosMarklogic, functionality looks great!
> 
> I'm seeing a lot of changes in this PR that are not related to the Avatar component replacement. And my linting shows errors. I think if we tried to merge, there could be problems.
> 
> I suggest doing the following:
> 
> 1. Create a new branch (off of feature/ant-lib-replacement) with just the header.tsx and header.module.tsx updates to support the Avatar component replacement.
> 2. Create a new PR.
> 3. Close this PR.
> 
> Sorry for the extra work, once this first PR goes through, we should be looking good!

Thanks @wooldridge for the suggestion, here is the new [PR](https://github.com/marklogic/marklogic-data-hub/pull/6012)

**Pull request closed without merging**
