### PR TITLE
DHFPROD-5878: Stop table scrolling in Explorer

### PR DESCRIPTION
**Pull request by devinnicholson**
### Description
This PR removes the multiple scrollbars in Explore. There should be 1 vertical scrollbar on the Explore tile (the scroll is not on the table anymore). When reducing size of the window, a horizontal scrollbar should appear. The search bar stays fixed in line with table view and snippet view, which now has dynamic width. Sticky header was added in this PR. This PR also fixes the placeholder that appears when scrolling in Modeling.

Reviewers: Please check scrolling in other tiles to make sure no other tile was affected.
#### Checklist: 
```diff
- Note: do not change the below
```

-  ##### Owner:

- [x] JIRA_ID included in all the commit messages
- [x] PR title is in the format JIRA_ID:Title
- [x] Rebase the branch with upstream
- [x] Squashed all commits into a single commit
- [x] Code passes ESLint tests

### CODE REVIEW

**Review by Sanjeevani19 — DISMISSED** [review]
@devinnicholson Here are couple of things I noticed
- There should be a horizontal scroll on the table to make it responsive on different screen widths, otherwise we are not able to get to detail view column when testing on 1024 screen widths and lower
- The top search-bar doesn't align with the table width when we see on 1024 screen widths and lower
https://drive.google.com/file/d/14vf0y3fm4lryQtnsJ24fKy3mImy2OINv/view 
- Since this is a 8 pointer story, it is worth addressing the fixed header also in this story so we can test everything together

**Review by Sanjeevani19 — CHANGES_REQUESTED** [review]
@devinnicholson Couple of things I noticed on latest changes

- There is an extra white space between the table and tile on different screen widths, the space is more on smaller desktop widths of 1024 and the search bar overflows on bigger desktop widths of 2560
 https://drive.google.com/file/d/1VNr7R-PgzgR1ASUi_s4Loa0ICyAKArBF/view
-  Export and column selector icons should be visible for users to click on which is available when you select a particular entity
Screen Shot 2021-07-14 at 4 51 38 PM
- Collapsible side bar icon should be at top right of sidebar, currently it is shifted below
Screen Shot 2021-07-14 at 4 50 52 PM

**Review by briantang — DISMISSED** [review]
Screen Shot 2021-07-15 at 2 28 48 PM

@devinnicholson Nice work! This is such a great improvement. One thing I noticed is that the width of the header does not adjust when the sidebar is collapsed. One solution you can try is giving the header a different className if the sidepanel is collapsed, and the styling of that class should set the width to 100%.

ex: `<div className={collapse? styles. stickyHeaderCollapsed : styles.stickyHeader}>`

**Comment by wooldridge** [comment]
Looking good! I'm seeing the width adjust correctly on different browser widths and the collapse button is sticky. I just see the issue @briantang mentioned.

**Review by briantang — APPROVED** [review]
Looks great!

**Review by Sanjeevani19 — DISMISSED** [review]

**Review by Sanjeevani19 — APPROVED** [review]

**Review by briantang — APPROVED** [review]

**Review by briantang — APPROVED** [review]

**Review by Sanjeevani19 — APPROVED** [review]

**Pull request merged**
