### PR TITLE
MLUI-138: Scoping and story for mlcp.component

### PR DESCRIPTION
**Pull request by pengzhouml**

### CODE REVIEW

**Comment by pengzhouml** [comment]
@alexsmr The latest mlui-integration branch has already been merged.

**Comment by alexsmr** [comment]
@pengzhouml OK. Can you trigger please the build on this PR by pushing something on your branch? Thanks,

**Comment by alexsmr** [comment]
@pengzhouml  Sorry, I got confused with other PR. There are a number of test failures can you please investigate them? https://jenkins.marklogic.com/view/DHF-9.0-Server-All/job/dhf-QS-develop-rh7-Commit/209/

**Comment by alexsmr** [comment]
@pengzhouml There is an error in the build: ERROR in src/main/ui/app/shared/stories/components/flows/flows-ui.compoment.stories.ts(14,33): error TS2307: Cannot find module '../../../../mlcp-ui'.
See: https://jenkins.marklogic.com/view/DHF-9.0-Server-All/job/dhf-QS-develop-rh7-Commit/281/console

**Comment by alexsmr** [comment]
@pengzhouml can you please fix the conflicts and merge latest mlui-integration

**Comment by alexsmr** [comment]
@pengzhouml can you please resolve the conflicts. I want to push everything into integration. Thanks.

**Comment by pengzhouml** [comment]
@alexsmr Sure, I am working on it. I was waiting for the test go Green before I merge to avoid churns.

**Comment by alexsmr** [comment]
@pengzhouml Thanks. Looks like it is still off. Do not wait for the tests. I will push it through to the integration.

**Pull request merged**
