### PR TITLE
Feature/dhfprod 3010

### PR DESCRIPTION
**Pull request by xnikhil08**
Some changes for DHFPROD-3021 and fix for fontAwesome PRO icons.

### CODE REVIEW

**Comment by rjrudin** [comment]
I will try testing these manually locally.

**Comment by srinathgit** [comment]
@xnikhil08 ,
I think we have to create a PR to merge feature/DHFPROD-3010 to develop. This feature branch is getting bloated with too many stories.

**Comment by xnikhil08** [comment]
@srinathgit - I commented out some half cooked changes to keep only the fixes and changes for DHFPROD-3022. Will create a separate PR for other changes.

**Comment by srinathgit** [comment]
@xnikhil08 ,
Can I go ahead and merge this PR to feature/DHFPROD-3010 branch and enable PR #3025 for review ?

**Comment by srinathgit** [comment]
@xnikhil08  mentioned that the PR can be merged to feature branch

**Pull request merged**
