### PR TITLE
DHFPROD-9422: Error In Pagination Deleting Row In Last Pag

### PR DESCRIPTION
**Pull request by MSBrignoni**
### Description
Error In Pagination Deleting Row In Last Page

#### Checklist: 
```diff
- Note: do not change the below
```

- ##### Owner:

- [x] JIRA_ID included in all the commit messages
- [x] PR title is in the format JIRA_ID:Title
- [x] Rebase the branch with upstream
- [x] Squashed all commits into a single commit
- [x] Code passes ESLint tests
- n/a Added Tests
- n/a Ran cypress tests on firefox locally
  

- ##### Reviewer:

- [x] Reviewed Tests
- n/a Added to Release Wiki

### CODE REVIEW

**Comment by briantang** [comment]
Needs the fix in another location and one small change to the label. Coordinated with Martin - I will add it.

**Comment by briantang** [comment]
Pushed a fix for updating pagination state after new notifications are generated.

**Review by briantang — APPROVED** [review]

**Review by Sanjeevani19 — APPROVED** [review]

**Review by Sanjeevani19 — APPROVED** [review]
@briantang @MSBrignoni  I don't see any test coverage for this scenario, Do we plan to add test coverage in a different task ? If not let's make sure to add it to the manual wiki testing document

**Comment by briantang** [comment]
> @briantang @MSBrignoni I don't see any test coverage for this scenario, Do we plan to add test coverage in a different task ? If not let's make sure to add it to the manual wiki testing document

Yes generating over 10+ notifications to trigger pagination is not straightforward to set up in tests so this is a scenario where manual is needed imo.

**Pull request merged**
