### PR TITLE
DHFPROD-2322: Master docs across datasets

### PR DESCRIPTION
**Pull request by ryanjdew**

### CODE REVIEW

**Comment by aebadirad** [comment]
can I get a rebase please @ryanjdew

**Comment by ryanjdew** [comment]
@aebadirad rebased

**Comment by wooldridge** [comment]
@ryanjdew also, on this branch, when the mapping code retrieves a source document from the sjsSearch endpoint:
```
POST http://localhost:4200/api/search/sjsSearch
{
  "database": "data-hub-STAGING",
  "sourceQuery": "cts.collectionQuery([\"BedrockLoad\"])",
  "count": 1
}
```
it's getting back this (instead of something referencing a doc loaded from the BedrockLoad ingestion):
```
[
  {
    "uri": "/Users/mwooldri/projects/marklogic-data-hub/examples/new-project/src/main/hub-internal-config/security/users/flow-developer-user.json",
    "docs": {
      "envelope": {
        "headers": {},
        "triples": [],
        "instance": {
          "user-name": "%%mlFlowDeveloperUserName%%",
          "description": "A user that is used for reading and writing from MarkLogic Data Hub databases and for maintaining DHF modules",
          "password": "%%mlFlowDeveloperPassword%%",
          "role": [
            "%%mlFlowDeveloperRole%%",
            "%%mlFlowOperatorRole%%"
          ]
        },
        "attachments": null
      }
    }
  }
]
```

**Comment by wooldridge** [comment]
OK, I tried this branch a second time with a pristine environment and didn't see the problems I saw before. I tried it on my demo dataset and a simpler dataset, attaching the simpler one here:

[a-b.zip](https://github.com/marklogic/marklogic-data-hub/files/3119287/a-b.zip)

Everything worked fine. Thanks, @ryanjdew!

**Pull request merged**
