### PR TITLE
DHFPROD-6962: Only enable hubDhs for aws/azure spring profile

### PR DESCRIPTION
**Pull request by akshaysonvane**
#### Checklist: 
```diff
- Note: do not change the below
```

-  ##### Owner:

- [x] JIRA_ID included in all the commit messages
- [x] PR title is in the format JIRA_ID:Title
- [x] Rebase the branch with upstream
- [x] Squashed all commits into a single commit
- [N/A] Code passes ESLint tests
- [x] Added Tests
  

- ##### Reviewer:

- [x] Reviewed Tests

### CODE REVIEW

**Review by srinathgit — COMMENTED** [review]
1. Will the property 'hubUseLocalDefaults' be relevant after this change ? If not, can that and related code be removed ?
2. Should 'hubSsl' be removed from  in marklogic-data-hub-central/gradle.properties ?

**Comment by akshaysonvane** [comment]
> 1. Will the property 'hubUseLocalDefaults' be relevant after this change ? If not, can that and related code be removed ?
> 2. Should 'hubSsl' be removed from  in marklogic-data-hub-central/gradle.properties ?

yes, and yes. Removed both.

**Review by rjrudin — APPROVED** [review]
Looks good! I can QA it tomorrow morning

**Review by rjrudin — CHANGES_REQUESTED** [review]
Can you make one change - gradle.properties has a comment about "production" being the default profile, that needs to be updated to say that Spring Boot defaults to "default" for the profile.

**Comment by SameeraPriyathamTadikonda** [comment]
@akshaysonvane what values should I set if I'm pointing HC on local to ML on DHS.
hubDHS=true?

**Comment by akshaysonvane** [comment]
> Can you make one change - gradle.properties has a comment about "production" being the default profile, that needs to be updated to say that Spring Boot defaults to "default" for the profile.

Good catch, updated.

**Comment by rjrudin** [comment]
@SameeraPriyathamTadikonda  All you'd need is -PspringProfiles=aws, which selects application-aws.properties, which configures hubDhs=true.

**Comment by akshaysonvane** [comment]
> @akshaysonvane what values should I set if I'm pointing HC on local to ML on DHS.
> hubDHS=true?

yes, that's right.
Also, hubDhs enables hubSsl as well.
So based on the service type you may need to explicitly turn off hubSsl via `hubSsl=false`

**Review by rjrudin — APPROVED** [review]

**Review by srinathgit — APPROVED** [review]

**Review by SameeraPriyathamTadikonda — APPROVED** [review]

**Review by ryanjdew — APPROVED** [review]

**Pull request merged**
