### PR TITLE
DHFPROD-5932: Change collapse/expand toggle behavior in mapping step details.

### PR DESCRIPTION
**Pull request by timur-isangulov**
#### Checklist: 
```diff
- Note: do not change the below
```

-  ##### Owner:

- [x] JIRA_ID included in all the commit messages
- [x] PR title is in the format JIRA_ID:Title
- [x] Rebase the branch with upstream
- [x] Squashed all commits into a single commit
- [x] Added Tests
  

- ##### Reviewer:

- [ ] Reviewed Tests

### CODE REVIEW

**Review by xnikhil08 — CHANGES_REQUESTED** [review]
Button Clicks seems to work fine. Expand all button expands all the levels and collapse all does the opposite. However, looks like we need to handle the default/initial keys for the expand /collapse when the step details modal is opened. Its still opening up the modal sometimes with the default two levels in source table as well as entity table. Check the screencast below.
https://drive.google.com/file/d/1dQvLXqA_4bcPfRAGHjLhEbMwWCts0k7B/view

The issue with opening only one level for the entity tab looks like always existed I can reproduce it on develop without  my changes. Can you please open a separate jira ticket for it.

**Comment by xnikhil08** [comment]
@timur-isangulov - This ticket is marked for 5.3, but you are trying to merge into 5.4 develop. i think this change should go into develop.

**Comment by timur-isangulov** [comment]
> @timur-isangulov - This ticket is marked for 5.3, but you are trying to merge into 5.4 develop. i think this change should go into develop.

Thanks for noticing . I will close it and open a new pr. Thanks.

**Comment by timur-isangulov** [comment]
Opened a new pr for develop 5.3 https://github.com/marklogic/marklogic-data-hub/pull/4729

**Pull request closed without merging**
