### PR TITLE
DHFPROD-8322: Test URIs lists have unwanted heading

### PR DESCRIPTION
**Pull request by mrodrigu-marklogic**
### Description
Fixes unwanted table heading for test URIs.

image

#### Checklist: 
```diff
- Note: do not change the below
```

-  ##### Owner:

- [x] JIRA_ID included in all the commit messages
- [x] PR title is in the format JIRA_ID:Title
- [x] Rebase the branch with upstream
- [x] Squashed all commits into a single commit
- [x] Code passes ESLint tests
- [x] Added Tests
- [x] Run UI tests
  

- ##### Reviewer:

- [x] Reviewed Tests
- [x] Added Release Notes

### CODE REVIEW

**Review by AkshayBajajML — COMMENTED** [review]
Looks Good!!
Can we also get rid of unwanted heading when we open compare data table.
Screen Shot 2022-01-25 at 9 44 49 AM

**Comment by mrodrigu-marklogic** [comment]
@AkshayBajajML added a check in the E2E for the non visible headers as well
image

**Review by aniamy — APPROVED** [review]

**Comment by AkshayBajajML** [comment]
@mrodrigu-marklogic Can we please add info to release docs under bug fix for 5.7.0.
Link: https://wiki.marklogic.com/display/ENGINEERING/Releases

**Review by AkshayBajajML — APPROVED** [review]
Looks Good!!

**Comment by mrodrigu-marklogic** [comment]
good catch @AkshayBajajML, added to https://wiki.marklogic.com/display/ENGINEERING/Data+Hub+5.7.0

**Pull request merged**
