### PR TITLE
Feature/UI style updates

### PR DESCRIPTION
**Pull request by wooldridge**
Made updates to the Manage Flows and Edit Flow pages to make them more consistent (color, layout, typography) and to tighten up spacing where the pages could use it. 

I made changes that were OKed in conversations with @sbayatpur last week, namely:

- Remove "Edit Flow", replace with small link
- Move progress bar to step containers
- Updates to step summary info

I've started a style guide here that lays out recommendations with regard to look and feel:

https://wiki.marklogic.com/display/ENGINEERING/UI+Style+Guide

The changes in this PR follow those recommendations.

### CODE REVIEW

**Comment by ayuwono** [comment]
@wooldridge, it seems that when click on Run and cancel, the flow is still run

**Comment by brucean52** [comment]
@ayuwono The run stop bug is fixed in a PR I opened. Visually, it's looking good!

**Comment by ayuwono** [comment]
> @ayuwono The run stop bug is fixed in a PR I opened. Visually, it's looking good!

Yes I saw and tested that PR too yesterday. This one is when you click on Cancel button (the flow is not even run yet), but the flow is still running. If you fixed this too, that's cool

**Comment by ayuwono** [comment]
> > @ayuwono The run stop bug is fixed in a PR I opened. Visually, it's looking good!
> 
> Yes I saw and tested that PR too yesterday. This one is when you click on Cancel button (the flow is not even run yet), but the flow is still running. If you fixed this too, that's cool

Btw, I see this run cancel issue on develop, so I will just raise a separate issue on JIRA

**Comment by wooldridge** [comment]
@alexsmr, @brucean52 if this looks OK, can you review/approve?

Thanks for the help with testing, @ayuwono. The current output from the Jenkins system is confusing to me.

**Comment by wooldridge** [comment]
Thanks, all. I will merge as I also have the OK from @ayuwono.

**Pull request merged**
