### PR TITLE
DHFPROD-7562: Add SLED MLS demo as example project

### PR DESCRIPTION
**Pull request by ngodugu-marklogic**
### Description
Will be handling the addition of entities as part of DHFPROD-7836

#### Checklist: 
```diff
- Note: do not change the below
```

-  ##### Owner:

- [x] JIRA_ID included in all the commit messages
- [x] PR title is in the format JIRA_ID:Title
- [x] Rebase the branch with upstream
- [x] Squashed all commits into a single commit
- [x] Code passes ESLint tests

### CODE REVIEW

**Review by ryanjdew — APPROVED** [review]

**Review by AkshayBajajML — CHANGES_REQUESTED** [review]
Good work @ngodugu-marklogic; I was smoothly able to initialize and deploy the sample project; Documentation is really good.
Here are few observation.

- There was issue when I tried to run UI from non war file as discussed.
- I think you may need to replace "HarmonizeClaims" with "mapMMIS" in step 7 in Read me.
- Can we add running matching and merging both in respective order in step 18 in Read me.

I was able to verify 123 merged records at end.
image

**Review by ryanjdew — APPROVED** [review]

**Comment by AkshayBajajML** [comment]
I am seeing this error on ./gradlew install.
Screen Shot 2021-09-09 at 9 44 57 AM

**Comment by AkshayBajajML** [comment]
I am also seeing this same error on using -Ptesting=true 
image

**Review by AkshayBajajML — APPROVED** [review]
Looks Good!!

**Pull request merged**
