### PR TITLE
DHFPROD-6705: Filter for related entity types in Hub Central

### PR DESCRIPTION
**Pull request by briantang**
### Description
- Baseline implementation for filter for related entity types in mapping
- Placeholder values used for related entities until backend or mock data is added in DHFPROD-6706
- UI designs approved by @jbelonoj 

#### Checklist: 
```diff
- Note: do not change the below
```

-  ##### Owner:

- [x] JIRA_ID included in all the commit messages
- [x] PR title is in the format JIRA_ID:Title
- [x] Rebase the branch with upstream
- [x] Squashed all commits into a single commit
- [x] Code passes ESLint tests
- [x] Added Tests
  

- ##### Reviewer:

- [x] Reviewed Tests

### CODE REVIEW

**Review by timur-isangulov — APPROVED** [review]
Tested locally, looks good.

**Review by xnikhil08 — APPROVED** [review]
Looks good.

**Review by wooldridge — CHANGES_REQUESTED** [review]
Nice work. I'm seeing a layout issue when you shrink the browser window. The filter box doesn't shrink with the shrinking table/browser window (I see there's a static width of 895px set). Also, you quickly lose visibility of the settings icon. I also notice that the Values column header and the content below it are a bit disconnected (shrink at different rates as you resize). Could we at least fix the sizing issue for the filter box with this PR? Maybe everything can solved with a few CSS tweaks, or maybe look into the other issues in a separate bug ticket.

For starters, you might want to move the "Map related entities" label out of a paragraph tag and put the label and text box in side-by-side div's?

**Comment by briantang** [comment]
Thanks for the catch @wooldridge, just pushed and the above issues should be fixed now.

**Review by wooldridge — APPROVED** [review]
Looks good!

**Review by Sanjeevani19 — APPROVED** [review]

**Review by timur-isangulov — APPROVED** [review]

**Pull request merged**
