### PR TITLE
DHFPROD-3010: CSS style cleanup for mapping

### PR DESCRIPTION
**Pull request by wooldridge**
Give left and right tables a consistent look and feel.
Improve layout of buttons, headings.
Improve styling of source information on left side.
Remove zebra striping.
Display "Object" and "Array" for the those datatypes in Source table.

### CODE REVIEW

**Comment by bsrikan** [comment]
image

**Comment by wooldridge** [comment]
@bsrikan, I'm not seeing the cut-off text in the text boxes like in your screenshot. What browser environment are you using?

Screen Shot 2019-10-16 at 4 56 15 PM

**Comment by wooldridge** [comment]
@bsrikan, I've made a CSS change that might fix what you're seeing, can you check again?

**Comment by bsrikan** [comment]
@wooldridge I was using firefox v69. Will check again. Thanks for looking into it.

**Comment by bsrikan** [comment]
Still the same in firefox. I will let it pass.
Firefox v69:
image

Chrome v75:
image

**Comment by wooldridge** [comment]
@bsrikan, thanks for those screenshot details, that helps a lot, I will try to fix.

**Comment by bsrikan** [comment]
Current pixel values in FF and Chrome and they look OK
FF:
image

Chrome:
image

**Pull request merged**
