### PR TITLE
DHFPROD-8281: Matching Table Issues

### PR DESCRIPTION
**Pull request by MSBrignoni**
### Description

Matching Table Issues
#### Checklist: 
```diff
- Note: do not change the below
```

-  ##### Owner:

- [x] JIRA_ID included in all the commit messages
- [x] PR title is in the format JIRA_ID:Title
- [x] Rebase the branch with upstream
- [x] Squashed all commits into a single commit
- [x] Code passes ESLint tests
- [x] Added Tests
- [x] Run UI tests
  

- ##### Reviewer:

- [x] Reviewed Tests
- N/A Added to Release Wiki

### CODE REVIEW

**Comment by AkshayBajajML** [comment]
Can we align Synonym match type.
Screen Shot 2022-02-14 at 12 21 53 PM

**Comment by MSBrignoni** [comment]
> Can we align Synonym match type. Screen Shot 2022-02-14 at 12 21 53 PM

Done @AkshayBajajML , fixed others alignments with indentations, but let´s check with your resolution too how it works
image

**Review by AkshayBajajML — APPROVED** [review]
Looks Good now.

**Review by AkshayBajajML — CHANGES_REQUESTED** [review]
I still see Dash (-) selected when I select non-structured properties but it is not there for structured property. 
Screen Shot 2022-02-15 at 12 24 37 PM

**Comment by MSBrignoni** [comment]
> I still see Dash (-) selected when I select non-structured properties but it is not there for structured property. Screen Shot 2022-02-15 at 12 24 37 PM

Done @AkshayBajajML

**Review by yubiselmarklogic — APPROVED** [review]

**Pull request merged**
