### PR TITLE
DHFPROD-7969: Apply Main Panel Facets

### PR DESCRIPTION
**Pull request by briantang**
### Description

- Base Entities selections in the main panel now filter the graph, works on top of search text query as well
- UX reviewed by Jamie

#### Checklist: 
```diff
- Note: do not change the below
```

-  ##### Owner:

- [x] JIRA_ID included in all the commit messages
- [x] PR title is in the format JIRA_ID:Title
- [x] Rebase the branch with upstream
- [x] Squashed all commits into a single commit
- [x] Code passes ESLint tests
- [x] Added Tests
- [x] Run UI tests
  

- ##### Reviewer:

- [x] Reviewed Tests
- [x] Added Release Notes

### CODE REVIEW

**Review by aniamy — APPROVED** [review]

**Comment by briantang** [comment]
FYI @xnikhil08 , @aniamy . I don't see the issue that we discussed with faceting on top of the related entities. This PR is ready for review.

**Review by xnikhil08 — APPROVED** [review]

**Comment by aniamy** [comment]
@briantang The steps I do:
I'm using reference-entity-model. But I think it can also be done with e2e setup data.
1. Select BabyRegistry.  Related list is updated with Customer.
2. Graph shows nodes of BabyRegistry and Customer witht the edges correctly.
3. Go to the filters and select Collection: Customer. Apply facets.
4. You should only see the Customer nodes. Actual: I see no nodes.

**Comment by iveyMarklogic** [comment]
@briantang when I selected a base entity I still see the same list of facets. Is it necessary to update the list based on the selected entity? 
image

**Review by iveyMarklogic — CHANGES_REQUESTED** [review]
Does your story only include updating the chart view?, Table and Snippet views are not updating when you select a base entity.

image

**Comment by briantang** [comment]
> Does your story only include updating the chart view?, Table and Snippet views are not updating when you select a base entity.
> 
> image

@iveyMarklogic The table/snippet view will be handled in a separate PR with DHFPROD-7872.

**Comment by briantang** [comment]
@iveyMarklogic @aniamy , just checked, and all the above issues should be fixed with the Table View PR for story DHFPROD-7872.

**Review by iveyMarklogic — APPROVED** [review]

**Pull request merged**
