### PR TITLE
DHFPROD-10159: long names issues

### PR DESCRIPTION
**Pull request by littlecherro**
#### Checklist: 
```diff
- Note: do not change the below
```

- ##### Owner:

- [x] JIRA_ID included in all the commit messages
- [x] PR title is in the format JIRA_ID:Title
- [x] Rebase the branch with upstream
- [x] Squashed all commits into a single commit
- N/A Added Tests
- [x] Ran newly added/edited cypress tests on Firefox locally
  

- ##### Reviewer:

- N/A Reviewed Tests
- N/A Added to Release Wiki

### CODE REVIEW

**Comment by amejiaq** [comment]
@littlecherro looks good but could we add this scenarios ?
image
image

**Review by amejiaq — APPROVED** [review]

**Review by briantang — CHANGES_REQUESTED** [review]
Looks good.

For the Flow Name scenario on the Run page, there are two types of tooltips now. I think "Edit Flow" is more important. Is it possible to move that to the top? 

Screenshot 2023-05-26 at 1 11 53 AM

**Review by briantang — APPROVED** [review]
Looks good now. We should have RTL testing for the re-usable component but seems like this ticket has been large enough. I'll create a tech debt.

**Comment by briantang** [comment]
@littlecherro I think there's a consistent test failure in the modeling scenario e2e. Doesn't seem to be failing on the other PRs.

**Review by amejiaq — APPROVED** [review]

**Review by briantang — APPROVED** [review]

**Pull request merged**
