### PR TITLE
DHFPROD-2461: In Manage Flow page first flow's info gets replaced by second flow's info when running second

### PR DESCRIPTION
**Pull request by brucean52**
Currently running into a bug, when polling 2 different flow jobs, the latestJob object gets overwritten to with the last running flow job object. 

ex. FlowA was running first, then FlowB is started. FlowA gets overwritten with FlowB's latestJob information.

### CODE REVIEW

**Comment by akshaysonvane** [comment]
As per @aebadirad suggestion rebased with develop. Looking into the bug that @brucean52 is facing.

**Comment by aebadirad** [comment]
@ayuwono test failures are:
Failed: No element found using locator: By(css selector, div.facet-list div.facet-value span[title="SimpleJSONMapping"])
Failed: No element found using locator: By(css selector, .step-simplejsonmastering .step-committed a)

In DataHub.simpleJson.E2E Simple JSON.should create mapping/mastering step and run the flow

**Comment by ayuwono** [comment]
> @ayuwono test failures are:
> Failed: No element found using locator: By(css selector, div.facet-list div.facet-value span[title="SimpleJSONMapping"])
> Failed: No element found using locator: By(css selector, .step-simplejsonmastering .step-committed a)
> 
> In DataHub.simpleJson.E2E Simple JSON.should create mapping/mastering step and run the flow

The first one is it cannot find the facet name SimpleJSONMapping (but mastering flow is run fine)
The second one it says 0 documents committed for mastering step flow (but I can see the documents got merged)

I haven't seen these two before

**Comment by aebadirad** [comment]
UI tags/names may have changed, could you investigate and fix the tests? :/

**Comment by ayuwono** [comment]
> UI tags/names may have changed, could you investigate and fix the tests? :/

I don't think it's my tests, it's a bug and I can reproduce the failures manually on this branch

Collection from mapping step is not displayed on the browse data page
Screen Shot 2019-05-08 at 7 05 57 PM

After running mastering flow, the docs committed show 0 on the jobs detail page
Screen Shot 2019-05-08 at 7 07 41 PM

But the other flows work fine when I tested. I'll try to investigate it again

**Comment by ayuwono** [comment]
The only different when I got the failures is I ran those flows on the edit flow page

The other flows that I tested fine, I ran then from the manage flows page

**Comment by ayuwono** [comment]
There is a regression on this branch, logged a bug: https://project.marklogic.com/jira/browse/DHFPROD-2494

This scenario used to work on develop

**Comment by ryanjdew** [comment]
Testing on this branch, I'm seeing the issue with the flow data being replaced as resolved and I'm seeing the collections from the mapping step making it on the documents with Alex's latest commits.

**Comment by ayuwono** [comment]
Same here, I can see mapping collection again with the latest commit. I can see committed mastering docs. But I don't see merged document on mastering collection. I don't see mdd-merged collection either after running the mastering step. Did you see the same thing @ryanjdew?

**Comment by ryanjdew** [comment]
@ayuwono saw the same after I created a new mapping step. Created this PR to the branch to fix the collections for mastering: https://github.com/marklogic/marklogic-data-hub/pull/2471

**Comment by ayuwono** [comment]
I can't run ingestion flow now. Bootrun error:

2019-05-09 10:57:49.083 ERROR 75013 --- [pool-1-thread-1] c.m.hub.flow.impl.FlowRunnerImpl         : Unable to update the job document
10:57:49.083 [pool-1-thread-1] ERROR c.m.hub.flow.impl.FlowRunnerImpl - Unable to update the job document
2019-05-09 10:57:49.093 ERROR 75013 --- [pool-1-thread-1] c.m.hub.flow.impl.FlowRunnerImpl         : Local message: Could not read resource at resources/ml:jobs. Server Message: No job document found
10:57:49.093 [pool-1-thread-1] ERROR c.m.hub.flow.impl.FlowRunnerImpl - Local message: Could not read resource at resources/ml:jobs. Server Message: No job document found

**Comment by ryanjdew** [comment]
not seeing the "Unable to update the job document" error, on my end, with the latest in this branch.

**Comment by aebadirad** [comment]
@ayuwono should be fixed in latest, and we still keep hitting these 5 stale element/not clickables on the QS - does manual testing succeed?

**Pull request merged**
