### PR TITLE
DHFPROD-6947: Move the source navigation buttons in mapping UI to a s…

### PR DESCRIPTION
**Pull request by timur-isangulov**
…eparate component

#### Checklist: 
```diff
- Note: do not change the below
```

-  ##### Owner:

- [x] JIRA_ID included in all the commit messages
- [x] PR title is in the format JIRA_ID:Title
- [x] Rebase the branch with upstream
- [x] Squashed all commits into a single commit
- [x] Code passes ESLint tests
- [x] Added Tests
  

- ##### Reviewer:

- [x] Reviewed Tests

### CODE REVIEW

**Review by wooldridge — CHANGES_REQUESTED** [review]
This is great. If it isn't happening elsewhere, can we test buttons clicks, similar to what we do here? https://github.com/marklogic/marklogic-data-hub/blob/develop/marklogic-data-hub-central/ui/src/components/common/confirm-yes-no/confirm-yes-no.test.tsx#L25

Also check that the right index value is passed on a button click?

**Comment by timur-isangulov** [comment]
> This is great. If it isn't happening elsewhere, can we test buttons clicks, similar to what we do here? https://github.com/marklogic/marklogic-data-hub/blob/develop/marklogic-data-hub-central/ui/src/components/common/confirm-yes-no/confirm-yes-no.test.tsx#L25
> 
> Also check that the right index value is passed on a button click?

Added tests, can you please review again. Thanks.

**Review by wooldridge — CHANGES_REQUESTED** [review]
@timur-isangulov, thanks! Here's the test modified slightly to check the function arg as well:
```
  test("Verify handleSelection is called with correct index", () => {
    const handleSelectionMock = jest.fn();
    const {getByTestId} = render(<SourceNavigation currentIndex={1} startIndex={0} endIndex={2} handleSelection={handleSelectionMock} />);

    fireEvent.click(getByTestId("navigate-uris-left"));
    expect(handleSelectionMock).toHaveBeenCalledTimes(1);
    expect(handleSelectionMock).toHaveBeenLastCalledWith(0);

    fireEvent.click(getByTestId("navigate-uris-right"));
    expect(handleSelectionMock).toHaveBeenCalledTimes(2);
    expect(handleSelectionMock).toHaveBeenLastCalledWith(2);
  });
```

**Review by wooldridge — CHANGES_REQUESTED** [review]
I think we can streamline the logic more if we can assume the following constraint:

startIndex <= currentIndex <= endIndex

I made a PR to your branch with some suggested changes: https://github.com/timur-isangulov/marklogic-data-hub/pull/1

**Review by wooldridge — APPROVED** [review]

**Review by xnikhil08 — APPROVED** [review]
Looks good.

**Pull request merged**
