### PR TITLE
DHFPROD-4777: Adding ESLint into Data Hub Central UI project

### PR DESCRIPTION
**Pull request by saarimrahman**
### Description
This introduces the ability to run [ESLint](https://eslint.org/). From **marklogic-data-hub-central/ui**, running 
- `npm run lint` will detect style errors and enforce rules defined in ESLint config.
- `npm run lint -- --fix` will often fix style issues automatically. 

The changes included in this PR are a result of fixing linting issues surrounding spacing, semicolons, unused variables, and more. No additional tests were added as this is only adding linting to the project.

ESLint configuration is defined by **marklogic-data-hub-central/ui/.eslintrc.js**.
 

#### Checklist: 
```diff
- Note: do not change the below
```

-  ##### Owner:

- [x] JIRA_ID included in all the commit messages
- [x] PR title is in the format JIRA_ID:Title
- [x] Rebase the branch with upstream
- [x] Squashed all commits into a single commit
- N/A Added Tests
  

- ##### Reviewer:

- [x] Reviewed Tests

### CODE REVIEW

**Review by wooldridge — APPROVED** [review]
Nice work, looks good. Unit tests pass for me and I can run linting locally with no errors and some warnings. E2E passed in Jenkins.

**Comment by SameeraPriyathamTadikonda** [comment]
> Nice work, looks good. Unit tests pass for me and I can run linting locally with no errors and some warnings. E2E passed in Jenkins.

@wooldridge Should we run the task lint on all the PRs in Jenkins or will the PR owners run that before submitting the PR?

**Comment by wooldridge** [comment]
@SameeraPriyathamTadikonda, this PR was for getting ESLint into the system and working manually. I don't want to add any additional automation before we've reviewed this feature with the team, including reviewing the rules we want to enforce.

**Review by timur-isangulov — APPROVED** [review]

**Review by briantang — APPROVED** [review]
Looks good. Multiple file changes are from the Linting and shows it works properly

**Pull request merged**
