### PR TITLE
DHFPROD-7752: Matching/ruleset-multiple-modal

### PR DESCRIPTION
**Pull request by mrodrigu-marklogic**
#### Checklist: 
```diff
- Note: do not change the below
```

-  ##### Owner:

- [x] JIRA_ID included in all the commit messages
- [x] PR title is in the format JIRA_ID:Title
- [x] Rebase the branch with upstream
- [x] Squashed all commits into a single commit
- [x] Code passes ESLint tests
- [x] Added Tests
- [x] Run UI tests
  

- ##### Reviewer:

- [x] Reviewed Tests

### CODE REVIEW

**Comment by mrodrigu-marklogic** [comment]
@briantang @Sanjeevani19 you might notice there are still 2 RTL test cases I skipped in lieu of keeping the replacement tasks by @lucianaabc-ml blocked (namely Removing ConfigProvider and Clearing Ant components) we can file a new Bug (assigned to me)  to work on them, provided rest of the QA reviews still pass

image

**Review by briantang — CHANGES_REQUESTED** [review]
Screen Shot 2022-01-04 at 10 52 28 AM

@mrodrigu-marklogic Looks pretty close. Although I think something is off with the screenshot above when testing the "Customer" entity match step. Also, the header has an extra border radius in the "Name" column that is causing a little white triangle. I am not sure if the hover effect on the headers is desired as well - may be a question for UX.

**Comment by yubiselmarklogic** [comment]
When select the option Double Metaphone in the select, the table exceed the modal
image

**Comment by mrodrigu-marklogic** [comment]
It seems now it is looking a little better, we probably have to implement some hook in the future to control the indentation for the Match Type Details fields width
image

**Review by yubiselmarklogic — APPROVED** [review]

**Review by briantang — APPROVED** [review]
Looks good. Nested indentation is an issue but there is a separate ticket for that: https://project.marklogic.com/jira/browse/DHFPROD-8281

**Review by MSBrignoni — APPROVED** [review]

**Pull request merged**
