### PR TITLE
DHFPROD-6139: Exclude hub artifact and entity model collections on type ahead search in map step

### PR DESCRIPTION
**Pull request by rahulvudutala**
#### Checklist: 
```diff
- Note: do not change the below
```

-  ##### Owner:

- [x] JIRA_ID included in all the commit messages
- [x] PR title is in the format JIRA_ID:Title
- [x] Rebase the branch with upstream
- [x] Squashed all commits into a single commit
- [x] Added Tests
  

- ##### Reviewer:

- [ ] Reviewed Tests

### CODE REVIEW

**Review by briantang — APPROVED** [review]
Looks good. Tested with DHFPROD-5437 and is exactly what is needed.

**Comment by briantang** [comment]
@rahulvudutala Could this PR be changed towards the develop branch? It's needed for DHFPROD-5437 which is a 5.3 story.

**Comment by rahulvudutala** [comment]
Closing this PR. I will create a PR to the develop branch

**Review by rjrudin — CHANGES_REQUESTED** [review]
I started an internal conversation on why I think we shouldn't do this.

**Pull request closed without merging**
