### PR TITLE
DHFPROD-5326: Make mapping view step details page consistent with Smart Mastering step details pages

### PR DESCRIPTION
**Pull request by xnikhil08**
### Description
Lot of refactoring and code standardization in mapping step components. Below are some of the highlights.
1. Source to entity map component is now "mapping step detail" component which is now independent of mapping-card component.
2. Mapping step detail page now opens up within the curate tile instead of residing in a modal.
3. New route for mapping step detail "/tiles/curate/map".
4. Curation context is being used for state management within all mapping components.
5. All the relevant test cases have been adjusted.

#### Checklist: 
```diff
- Note: do not change the below
```

-  ##### Owner:

- [x] JIRA_ID included in all the commit messages
- [x] PR title is in the format JIRA_ID:Title
- [x] Rebase the branch with upstream
- [x] Squashed all commits into a single commit
- [x] Code passes ESLint tests
- [x] Added Tests
  

- ##### Reviewer:

- [x] Reviewed Tests

### CODE REVIEW

**Comment by timur-isangulov** [comment]
@xnikhil08, I noticed 4 scrolls on the page, the horizontal one probably is not needed. 
Screen Shot 2021-03-09 at 7 45 33 AM

**Review by timur-isangulov — CHANGES_REQUESTED** [review]
@xnikhil08, can you please fix the issue with the extra scrolls.

**Comment by xnikhil08** [comment]
> @xnikhil08, can you please fix the issue with the extra scrolls.

@timur-isangulov - Pushed a fix for the horizontal scroll. Another review ?

**Review by wooldridge — APPROVED** [review]
Epic job! Unit tests pass. I'm seeing all the mapping interactions work in the tile container.

**Review by timur-isangulov — APPROVED** [review]

**Pull request merged**
