### PR TITLE
DHFPROD-5722: Run cypress tests on PR

### PR DESCRIPTION
**Pull request by SameeraPriyathamTadikonda**
#### Checklist: 
```diff
- Note: do not change the below
```

-  ##### Owner:

- [x] JIRA_ID included in all the commit messages
- [x] PR title is in the format JIRA_ID:Title
- [x] Rebase the branch with upstream
- [x] Squashed all commits into a single commit
- [N/A ] Added Tests
  

- ##### Reviewer:

- [N/A ] Reviewed Tests

### CODE REVIEW

**Comment by SameeraPriyathamTadikonda** [comment]
@bsrikan @Sanjeevani19 @timur-isangulov E2E Failures

      Spec                                              Tests  Passing  Failing  Pending  Skipped  
┌────────────────────────────────────────────────────────────────────────────────────────────────┐
│ ✖  curation/load/defaultIngestion.spec      00:58        8        3        2        3        - │
│    .tsx                                                                                        │
├────────────────────────────────────────────────────────────────────────────────────────────────┤
│ ✔  explorer/scenarios.json.tsx              02:04       21       19        -        2        - │
├────────────────────────────────────────────────────────────────────────────────────────────────┤
│ ✖  explorer/scenarios.queries.tsx           02:50       13        4        9        -        - │
├────────────────────────────────────────────────────────────────────────────────────────────────┤
│ ✔  explorer/scenarios.table.tsx             00:07        2        2        -        -        - │
├────────────────────────────────────────────────────────────────────────────────────────────────┤
│ ✔  explorer/scenarios.xml.tsx               00:44       10       10        -        -        - ├────────────────────────────────────────────────────────────────────────────────────────────────┤
│ ✔  login/authorization.spec.tsx             00:26        9        9        -        -        - │
├────────────────────────────────────────────────────────────────────────────────────────────────┤
│ ✔  modeling/reader.spec.tsx                 00:09        1        1        -        -        - │
├────────────────────────────────────────────────────────────────────────────────────────────────┤
│ ✔  modeling/writer.spec.tsx                 02:34        6        6        -        -        - │
└────────────────────────────────────────────────────────────────────────────────────────────────┘
    ✖  2 of 8 failed (25%)                      09:55       70       54       11        5        -

**Comment by SameeraPriyathamTadikonda** [comment]
@Sanjeevani19 I'm not sure. I'm posting the results that are from the jenkins output. Looks like on the latest run it failed only 9 tests and all are from the save/managequeries
https://jenkins.marklogic.com/blue/organizations/jenkins/Datahub_CI/detail/PR-4404/10/tests
For Artifacts and videos :
https://jenkins.marklogic.com/blue/organizations/jenkins/Datahub_CI/detail/PR-4404/10/artifacts

**Comment by Sanjeevani19** [comment]
> @Sanjeevani19 I'm not sure. I'm posting the results that are from the jenkins output. Looks like on the latest run it failed only 9 tests and all are from the save/managequeries
> https://jenkins.marklogic.com/blue/organizations/jenkins/Datahub_CI/detail/PR-4404/10/tests
> For Artifacts and videos :
> https://jenkins.marklogic.com/blue/organizations/jenkins/Datahub_CI/detail/PR-4404/10/artifacts

Right these failures are due to multiple POST requests on the UI, spinner position caused these failures

**Comment by timur-isangulov** [comment]
> > @Sanjeevani19 I'm not sure. I'm posting the results that are from the jenkins output. Looks like on the latest run it failed only 9 tests and all are from the save/managequeries
> > https://jenkins.marklogic.com/blue/organizations/jenkins/Datahub_CI/detail/PR-4404/10/tests
> > For Artifacts and videos :
> > https://jenkins.marklogic.com/blue/organizations/jenkins/Datahub_CI/detail/PR-4404/10/artifacts
> 
> Right these failures are due to multiple POST requests on the UI, spinner position caused these failures

I just opened a pr with the fix for the spinner https://github.com/marklogic/marklogic-data-hub/pull/4410. Please review.

**Comment by SameeraPriyathamTadikonda** [comment]
Latest test result:
https://jenkins.marklogic.com/blue/organizations/jenkins/Datahub_CI/detail/PR-4404/11/tests

3more failures

**Comment by Sanjeevani19** [comment]
> Latest test result:
> https://jenkins.marklogic.com/blue/organizations/jenkins/Datahub_CI/detail/PR-4404/11/tests
> 
> 3more failures

@SameeraPriyathamTadikonda column selector test doesn't fail for me locally, is it on windows machine ?

**Comment by timur-isangulov** [comment]
> > Latest test result:
> > https://jenkins.marklogic.com/blue/organizations/jenkins/Datahub_CI/detail/PR-4404/11/tests
> > 3more failures
> 
> @SameeraPriyathamTadikonda column selector test doesn't fail for me locally, is it on windows machine ?

All tests pass for me on the latest develop on MAC. 
Screen Shot 2020-08-14 at 2 09 15 PM

**Comment by SameeraPriyathamTadikonda** [comment]
> > > Latest test result:
> > > https://jenkins.marklogic.com/blue/organizations/jenkins/Datahub_CI/detail/PR-4404/11/tests
> > > 3more failures
> > 
> > 
> > @SameeraPriyathamTadikonda column selector test doesn't fail for me locally, is it on windows machine ?
> 
> All tests pass for me on the latest develop on MAC.
> Screen Shot 2020-08-14 at 2 09 15 PM

Nope its on linux machine

**Comment by SameeraPriyathamTadikonda** [comment]
@Sanjeevani19 @bsrikan All the tests passed. Can I get approvals now?

**Pull request merged**
