### PR TITLE
DHFPROD-8534: ModelingReplaceRepeatedLogin

### PR DESCRIPTION
**Pull request by csilva-ml**
#### Checklist: 
```diff
- Note: do not change the below
```

-  ##### Owner:

- [x] JIRA_ID included in all the commit messages
- [x] PR title is in the format JIRA_ID:Title
- [x] Rebase the branch with upstream
- [x] Squashed all commits into a single commit
- [x] Code passes ESLint tests
- [x] Added Tests
  

- ##### Reviewer:

- [x] Reviewed Tests
- N/A Added to Release Wiki

### CODE REVIEW

**Review by briantang — COMMENTED** [review]
@csilva-ml Can we make sure to uncomment the test separations now that we are using local storage to preserve the sessions? (for example in writerScenario1.spec I see one that is still commented)

**Review by briantang — DISMISSED** [review]
Looks good now, thanks @csilva-ml

**Review by aniamy — APPROVED** [review]

**Comment by briantang** [comment]
One test is consistently failing. May need to be looked at and fixed @csilva-ml

**Comment by csilva-ml** [comment]
Hey @briantang It's working now :)

**Review by briantang — APPROVED** [review]

**Review by aniamy — APPROVED** [review]

**Pull request merged**
