### PR TITLE
Fix datahubCreatedByJob collation inconsistency (#3440)

### PR DESCRIPTION
**Pull request by crism**
Fixes intermittent deployment bug #3440

### CODE REVIEW

**Comment by rjrudin** [comment]
Let's not merge this yet - I posted on the internal JIRA ticket that the appropriate solution may be to adjust hub-entities.xqy when the search options are generated.

@crism If you have time, could you try that solution out - i.e. bring your own patched copy of hub-entities.xqy into your codebase, and then deploy your app and see if having constraints with the "en" collation avoids the error? 

Also, do you have steps that are guaranteed to produce the error every time?

**Comment by crism** [comment]
@rjrudin, it seems like a first-time `mlDeploy` or `mlRedeploy` will trigger the error, but after that, it’s uncertain. I’m not sure why it doesn’t crop up reliably.

I’ll try it the other way ’round in the patch. It seems to me that `hubCreatedByJob` is unlikely to be a linguistically-valued property, so root collation is appropriate, but your point about triggering reindexing for existing installations is well-taken.

**Comment by crism** [comment]
Part of the reproducibility problem has to do with reindexing. When the range index definition is different than previously, it triggers reindexing. Then the search options come in hot on its heels, and because indexing isn’t done, the index isn’t found, and so it fails. After waiting for reindexing, the next assertion isn’t different, doesn’t trigger reindexing, and succeeds.

**Comment by rjrudin** [comment]
Modifying the search options seems like the right choice, if the "en" collation is intended. If it is intended, we should have a comment documenting why it's intended, as it's guaranteed to raise eyebrows in the future. @rahulvudutala Can you provide that comment? Would be nice to include it in this PR.

**Comment by crism** [comment]
(It’s worth noting that this bug actually arises whether or not the index and usage are consistent… if it’s _different_ than previously installed, the rapidity of deployment will trigger an error. This is a broader problem probably worth looking into.)

**Comment by rjrudin** [comment]
Closing this, as the root cause isn't the mismatch between search options and the index, but rather that the search options are deployed before the index is built. That's a server issue we'll need to figure out.

**Pull request closed without merging**
