### PR TITLE
DHFPROD-8710: Save Step Settings Develop

### PR DESCRIPTION
**Pull request by MSBrignoni**
### Description
DHFPROD-8710: Save Step Settings Develop

#### Checklist: 
```diff
- Note: do not change the below
```

-  ##### Owner:

- [x] JIRA_ID included in all the commit messages
- [x] PR title is in the format JIRA_ID:Title
- [x] Rebase the branch with upstream
- [x] Squashed all commits into a single commit
- [x] Code passes ESLint tests
- [x] Added Tests
  

- ##### Reviewer:

- [x] Reviewed Tests
- [x] Added to Release Wiki

### CODE REVIEW

**Comment by csilva-ml** [comment]
e2e tests look good! I would only suggest removing all waitUntils since they are not needed :)

**Comment by MSBrignoni** [comment]
> e2e tests look good! I would only suggest removing all waitUntils since they are not needed :)

Thanks!, done.

**Review by briantang — DISMISSED** [review]
Looks good to me!

**Review by yubiselmarklogic — DISMISSED** [review]

**Comment by MSBrignoni** [comment]
Pushed again (conflict caused by new merges in develop).

**Review by yubiselmarklogic — DISMISSED** [review]

**Review by briantang — DISMISSED** [review]

**Review by xnikhil08 — CHANGES_REQUESTED** [review]
Added few comments in the similar PR for 5.7.2.

**Comment by MSBrignoni** [comment]
> Added few comments in the similar PR for 5.7.2.

Thanks @xnikhil08, I left the comments in the other branch!.

**Review by xnikhil08 — APPROVED** [review]

**Review by briantang — APPROVED** [review]

**Pull request merged**
