### PR TITLE
DHFPROD-8865: Customize concept icons and change color in Explore screen

### PR DESCRIPTION
**Pull request by yubiselmarklogic**
#### Checklist: 
```diff
- Note: do not change the below
```

- ##### Owner:

- [x] JIRA_ID included in all the commit messages
- [x] PR title is in the format JIRA_ID:Title
- [x] Rebase the branch with upstream
- [x] Squashed all commits into a single commit
- [x] Code passes ESLint tests
- [x] Added Tests
- [x] Ran cypress tests on firefox locally
  

- ##### Reviewer:

- [x] Reviewed Tests
- [x] Added to Release Wiki

### CODE REVIEW

**Comment by xnikhil08** [comment]
@yubiselmarklogic - The search capability is not working for the Concepts Name column in the data model settings table, within the modal.

**Comment by xnikhil08** [comment]
@yubiselmarklogic - Let's update the settings dropdown options label from "Entity Type settings" to "Data Model settings" since we have already made the changes within the modal.

image

**Review by xnikhil08 — CHANGES_REQUESTED** [review]
Looks good overall, except the changes suggested in previous comments.
Also, Saving the Concept Icon and Color config should also be done as part of this ticket. The only part which we had to mock so far was fetching the concept class Info to render in the table, but assuming we know the structure of the response we should be able to save the config for concepts within hubCentral.json file.

**Comment by yubiselmarklogic** [comment]
> @yubiselmarklogic - Let's update the settings dropdown options label from "Entity display settings" to "Data Model display settings" since we have already made the changes within the modal.
> 
> image

@xnikhil08  done

**Comment by yubiselmarklogic** [comment]
> Looks good overall, except the changes suggested in previous comments. Also, Saving the Concept Icon and Color config should also be done as part of this ticket. The only part which we had to mock so far was fetching the concept class Info to render in the table, but assuming we know the structure of the response we should be able to save the config for concepts within hubCentral.json file.

@xnikhil08 
In the video you can see that the hubCentralConfig file is saving the changes, It's needed to reflect that changes in the graph. The search feature in the table are not related in the acceptance criteria in the task. I followed the design and reusing the feature from the entity type table I was able to reproduce the search in the first level, but need a task for apply the search to all levels.
https://watch.screencastify.com/v/2hUxo7qfmL5MnScDBh48

**Review by xnikhil08 — APPROVED** [review]

**Comment by yubiselmarklogic** [comment]
> Looks good! could be possible to change the style of the first cell of the headers and remove the hover effect in the cells without ordering? image



> Looks good! could be possible to change the style of the first cell of the headers and remove the hover effect in the cells without ordering? image

@MSBrignoni  Fixed

**Review by MSBrignoni — APPROVED** [review]

**Review by xnikhil08 — APPROVED** [review]

**Pull request merged**
