### PR TITLE
DHFPROD-9677: Create Edit New List In Values To Ignore

### PR DESCRIPTION
**Pull request by MSBrignoni**
### Description
Create Edit New List In Values To Ignore

#### Checklist: 
```diff
- Note: do not change the below
```

- ##### Owner:

- [x] JIRA_ID included in all the commit messages
- [x] PR title is in the format JIRA_ID:Title
- [x] Rebase the branch with upstream
- [x] Squashed all commits into a single commit
- [x] Added Tests
- [x] Ran cypress tests on firefox locally
  

- ##### Reviewer:

- [x] Reviewed Tests
- n/a Added to Release Wiki

### CODE REVIEW

**Review by iveyMarklogic — COMMENTED** [review]
@MSBrignoni should we handle the validation of this ticket or do we have another ticket to handle that

image

**Comment by MSBrignoni** [comment]
> @MSBrignoni should we handle the validation of this ticket or do we have another ticket to handle that
> 
> image

Yes, here is the new ticket for this and other validations: https://project.marklogic.com/jira/browse/DHFPROD-9743

**Comment by amejiaq** [comment]
@MSBrignoni Hi, I found an unexpected behavior when I hover a tooltip.

Link for the video.


[802b86d6-feda-4be3-8e7f-a96acf2d3aec.webm](https://user-images.githubusercontent.com/116110652/205743055-0a621880-a652-4dd4-8b89-a987396e062d.webm)

**Comment by MSBrignoni** [comment]
> @MSBrignoni Hi, I found an unexpected behavior when I hover a tooltip.
> 
> Link for the video.
> 802b86d6-feda-4be3-8e7f-a96acf2d3aec.webm

Thanks @amejiaq , this will be fixed with the other tooltips in https://project.marklogic.com/jira/browse/DHFPROD-9709

**Review by amejiaq — APPROVED** [review]

**Review by iveyMarklogic — APPROVED** [review]

**Pull request merged**
