### PR TITLE
DHFPROD-6514:Fix 'targetEntityType' for match and merge steps

### PR DESCRIPTION
**Pull request by srinathgit**
### Description
Fix 'targetEntityType' for match and merge steps
#### Checklist: 
```diff
- Note: do not change the below
```

-  ##### Owner:

- [x] JIRA_ID included in all the commit messages
- [x] PR title is in the format JIRA_ID:Title
- [x] Rebase the branch with upstream
- [x] Squashed all commits into a single commit
- [x] Code passes ESLint tests
- [n/a ] Added Tests
  

- ##### Reviewer:

- [x] Reviewed Tests

### CODE REVIEW

**Review by ryanjdew — DISMISSED** [review]

**Review by Sanjeevani19 — APPROVED** [review]

**Review by wooldridge — DISMISSED** [review]

**Comment by wooldridge** [comment]
When I cherry pick this change on to the following PR branch: https://github.com/marklogic/marklogic-data-hub/pull/5102

The View links now work, they take the user to the Curate tab with the correct entity and step type open. Mission accomplished.

**Review by Sanjeevani19 — COMMENTED** [review]
@srinathgit There seems to be a e2e failure on the PR, Assuming this is not related to your PR , Please let me know @ngodugu-marklogic can look into the fix

**Comment by ngodugu-marklogic** [comment]
> @srinathgit There seems to be a e2e failure on the PR, Assuming this is not related to your PR , Please let me know @ngodugu-marklogic can look into the fix

This seems to be going fine on Develop branch

**Comment by ngodugu-marklogic** [comment]
> > @srinathgit There seems to be a e2e failure on the PR, Assuming this is not related to your PR , Please let me know @ngodugu-marklogic can look into the fix
> 
> This failure seems to be related to the PR changes as when we add the existing steps to a new flow and run the Match Step. The Match collection is not getting created and then when the test runs the Merge Step, the data is not getting displayed in the explore page. This test seems to be going fine in Develop branch. FYI @srinathgit

**Review by ryanjdew — APPROVED** [review]

**Comment by ryanjdew** [comment]
@Sanjeevani19 @srinathgit @ngodugu-marklogic I've updated this commit with a backend update that will ensure the entity title is used for the default collections and not the full entity type URI. That was causes the test failure.

**Review by Sanjeevani19 — APPROVED** [review]

**Review by ngodugu-marklogic — APPROVED** [review]

**Pull request merged**
