### PR TITLE
DHFPROD-4171: Fixed few issues raised in testing of TEST and CLEAR buttons

### PR DESCRIPTION
**Pull request by xnikhil08**
### Description
This PR only contains fixes for some issues. No tests required here as the unit tests are already being added as part of the story(4171) itself.

#### Checklist: 
```diff
- Note: do not change the below
```

-  ##### Owner:

- [x] JIRA_ID included in all the commit messages
- [x] PR title is in the format JIRA_ID:Title
- [x] Rebase the branch with upstream
- [x] Squashed all commits into a single commit
- [x] Added Tests
  

- ##### Reviewer:

- [x] Reviewed Tests

### CODE REVIEW

**Comment by bsrikan** [comment]
Fixes work for most part. But I am not OK with Value column width. Even after resizing, it doesnt seem to expand the truncated text.

image

**Comment by bsrikan** [comment]
@xnikhil08  can you pls rebase this PR with latest develop.

**Comment by wooldridge** [comment]
I'm still seeing the error above on Nikhil's PR branch, but I also don't see that branch changed since the force-push. How am I supposed to test this? @bsrikan @xnikhil08

**Comment by bsrikan** [comment]
Sorry about the confusion @wooldridge Added tests for DHFPROD-4171 and fixed the failing sort test.

**Comment by wooldridge** [comment]
I just checked out this PR branch in a fresh local environment and still get the same error as above. @srinathgit do you see that error? Are you doing the same thing that I'm doing? I'm obviously missing something here... @bsrikan @xnikhil08

**Comment by srinathgit** [comment]
The tests seems to have passed in regression

**Pull request merged**
