### PR TITLE
DHFPROD-8338: RadioGroupHoverInteraction

### PR DESCRIPTION
**Pull request by MSBrignoni**
### Description
Radio Group Hover Interaction

#### Checklist: 
```diff
- Note: do not change the below
```

-  ##### Owner:

- [x] JIRA_ID included in all the commit messages
- [x] PR title is in the format JIRA_ID:Title
- [x] Rebase the branch with upstream
- [x] Squashed all commits into a single commit
- [x] Code passes ESLint tests
- N/A Added Tests
- [x] Run UI tests
  

- ##### Reviewer:

- N/A Reviewed Tests
- N/A Added Release Notes

### CODE REVIEW

**Comment by MSBrignoni** [comment]
In the [Jira´s ticket](https://project.marklogic.com/jira/browse/DHFPROD-8338) there are some screenshot to show where the radio groups are, and in the video of the sprint 60.

**Comment by AkshayBajajML** [comment]
We are using #7FADE3 as default hover color for text and icons currently.
@jbelonoj would you suggest to keep it consistent for RadioGroup as well.(We are using white color now in this ticket)?

**Comment by MSBrignoni** [comment]
> We are using #7FADE3 as default hover color for text and icons currently. @jbelonoj would you suggest to keep it consistent for RadioGroup as well. Screencast: https://drive.google.com/file/d/1sdq6tDD4b8CjmNbcpPZLOWo_WBgKwJ6v/view?usp=sharing

@AkshayBajajML @jbelonoj in this new commit, I left the span radio buttons with #7f86b5 and the #7fade3 for the square icons, considering the [previous version](http://rh7v-10-dhe-2:8080/tiles/load), in the "explore state switcher" I left it consistent with the others squares.

**Review by lucianaabc-ml — DISMISSED** [review]

**Comment by MSBrignoni** [comment]
> > We are using #7FADE3 as default hover color for text and icons currently. @jbelonoj would you suggest to keep it consistent for RadioGroup as well. Screencast: https://drive.google.com/file/d/1sdq6tDD4b8CjmNbcpPZLOWo_WBgKwJ6v/view?usp=sharing
> 
> @AkshayBajajML @jbelonoj in this new commit, I left the span radio buttons with #7f86b5 and the #7fade3 for the square icons, considering the [previous version](http://rh7v-10-dhe-2:8080/tiles/load), in the "explore state switcher" I left it consistent with the others squares.

Guys, i talked with Jamie and shared my screen, it´s ok now.

**Review by AkshayBajajML — APPROVED** [review]

**Comment by ngodugu-marklogic** [comment]
@MSBrignoni Can you please make sure jsonTableViewValidations.spec.tsx is going fine. Seems like it failed consistently on all the runs.

**Comment by MSBrignoni** [comment]
> @MSBrignoni Can you please make sure jsonTableViewValidations.spec.tsx is going fine. Seems like it failed consistently on all the runs.

Yes @ngodugu-marklogic , added a parent() property to fix this.

**Review by yubiselmarklogic — APPROVED** [review]

**Review by lucianaabc-ml — APPROVED** [review]

**Pull request merged**
