### PR TITLE
DHFPROD-8397: Refactor to clean up properties use.

### PR DESCRIPTION
**Pull request by iveyMarklogic**
#### Checklist: 
```diff
- Note: do not change the below
```

-  ##### Owner:

- [x] JIRA_ID included in all the commit messages
- [x] PR title is in the format JIRA_ID:Title
- [x] Rebase the branch with upstream
- [x] Squashed all commits into a single commit
- [x] Code passes ESLint tests
- N/A Added Tests
- [x] Run UI tests
  

- ##### Reviewer:

- N/A Reviewed Tests
- N/A Added to Release Wiki

### CODE REVIEW

**Review by xnikhil08 — APPROVED** [review]
Looks great !
Just noticed few issues with the group node children disappearing when opening their associated right side panel. But that seems to be a regression as i see the similar behavior in the nightly instance. Will create a separate bug for that issue.
https://watch.screencastify.com/v/dy2ltSgfT41mQR2Ik2j3

Also, i still see the issue with the whole saved queries workflow, but since we have a separate bug for that too already, i will approve this ticket here.

**Review by xnikhil08 — CHANGES_REQUESTED** [review]
Looks like few UI tests failing in the PR. @iveyMarklogic, Can you take care of those ?

**Review by aniamy — DISMISSED** [review]

**Review by xnikhil08 — APPROVED** [review]

**Review by xnikhil08 — DISMISSED** [review]
@iveyMarklogic - Looks like the UI tests are still failing. Can you please look into those. ?

**Comment by briantang** [comment]
There seems to be a bug in a useEffect where the conditions are not passing. Converting to draft and looking into it...

**Comment by briantang** [comment]
Pushed a test fix and also reworked the routing state settings as discussed @iveyMarklogic

**Review by briantang — APPROVED** [review]
All tests passing!

**Review by AkshayBajajML — APPROVED** [review]

**Review by xnikhil08 — APPROVED** [review]

**Pull request merged**
