### PR TITLE
DHFPROD-6608: Move Possible Combinations box to the top

### PR DESCRIPTION
**Pull request by brucean52**
#### Checklist: 
```diff
- Note: do not change the below
```

-  ##### Owner:

- [x] JIRA_ID included in all the commit messages
- [x] PR title is in the format JIRA_ID:Title
- [x] Rebase the branch with upstream
- [x] Squashed all commits into a single commit
- [x] Code passes ESLint tests
- [N/A ] Added Tests
  

- ##### Reviewer:

- [ N/A] Reviewed Tests

### CODE REVIEW

**Review by briantang — APPROVED** [review]
Seeing possible combinations at the top now, looks good.

**Review by timur-isangulov — DISMISSED** [review]

**Review by Sanjeevani19 — COMMENTED** [review]
@brucean52 Looks like there is a e2e test failure, Please look into it

**Review by Sanjeevani19 — CHANGES_REQUESTED** [review]
@brucean52 Looks like there is a e2e test failure, Please look into it

**Review by Sanjeevani19 — DISMISSED** [review]

**Comment by SameeraPriyathamTadikonda** [comment]
cypress test failure on this one.
https://jenkins.marklogic.com/blue/organizations/jenkins/Datahub_CI/detail/PR-5193/18/tests

**Review by briantang — CHANGES_REQUESTED** [review]
The cypress failure appears to be related to the PR.

Matching -- can createedit a match step within the match tab of curate tile, can create match thresholdsrulesets, can delete match thresholdsrulesets (failed)

**Review by Sanjeevani19 — CHANGES_REQUESTED** [review]
@brucean52 e2e tests are still failing on the pipeline https://jenkins.marklogic.com/blue/organizations/jenkins/Datahub_CI/detail/PR-5193/25/pipeline

**Review by wooldridge — CHANGES_REQUESTED** [review]
I see the Possible Combinations box at the top now but we need to update the descriptive text since the scales are now "below" the box. @eltesoro-ml to confirm, should it be "Add thresholds and rulesets to below scales..."?

Screen Shot 2021-02-05 at 5 09 50 PM

**Comment by eltesoro-ml** [comment]
> I see the Possible Combinations box at the top now but we need to update the descriptive text since the scales are now "below" the box. @eltesoro-ml to confirm, should it be "Add thresholds and rulesets to below scales..."?
> 

**New text:**
Add thresholds and rulesets to the following sliders to determine which combinations of qualifying rulesets would meet each threshold.

**Comment by brucean52** [comment]
> > I see the Possible Combinations box at the top now but we need to update the descriptive text since the scales are now "below" the box. @eltesoro-ml to confirm, should it be "Add thresholds and rulesets to below scales..."?
> 
> 
> **New text:**
> Add thresholds and rulesets to the following sliders to determine which combinations of qualifying rulesets would meet each threshold.
> 
> 
> If possible, please replace the word "continuum" to "slider" to keep the terminology consistent.
> @wooldridge found it here:
> `const multiSliderTooltips = { priorityOrder: 'The length weights and source weights plotted on a continuum from low to high. Each weight indicates the importance of the length or source when merging documents.', timeStamp: 'Timestamp cannot be moved or deleted.', viewOnlyTooltip: 'Click the strategy name to change the priority order.' };`
> 
> Thank you!
@wooldridge  @ngodugu-marklogic @eltesoro-ml 

I've updated the tooltip text.

**Review by wooldridge — APPROVED** [review]

**Review by Sanjeevani19 — APPROVED** [review]

**Review by timur-isangulov — APPROVED** [review]

**Review by briantang — APPROVED** [review]

**Pull request merged**
