### PR TITLE
DHFPROD-6309: Add a tooltip for a disabled name field on edit step and edit flow

### PR DESCRIPTION
**Pull request by devinnicholson**
…d edit flow

#### Checklist: 
```diff
- Note: do not change the below
```

-  ##### Owner:

- [x] JIRA_ID included in all the commit messages
- [x] PR title is in the format JIRA_ID:Title
- [x] Rebase the branch with upstream
- [x] Squashed all commits into a single commit
- [x] Added Tests
  

- ##### Reviewer:

- [x] Reviewed Tests

### CODE REVIEW

**Review by wooldridge — CHANGES_REQUESTED** [review]
Nice work, @devinnicholson! There's a minor adjustment to be made to the name and description "?" icon tooltips. Because of idiosyncrasies with the Ant Design and tile components, we need to use placement "right" for the tooltip alignment to work. That's what I did in the following PR:

https://github.com/marklogic/marklogic-data-hub/pull/4968

Can you do the same for the match/merge name and description icons? Looks like those are the only ones that still have a problem, e.g.:

Screen Shot 2020-12-09 at 2 52 15 PM

**Review by wooldridge — CHANGES_REQUESTED** [review]
Test needed a little more work. Need to test with create-edit-load dialog in editing state. (First test has the dialog in new state due to an empty stepData property in the test data.) I've created a PR to your branch with a working test here:

https://github.com/devinnicholson/marklogic-data-hub/pull/1

**Review by wooldridge — APPROVED** [review]
Looks good, tests pass!

**Review by briantang — CHANGES_REQUESTED** [review]
Looks good, but I think the three commits may need to be squashed into one to keep consistent with PR protocols. Can you look into squashing those commits? @devinnicholson

**Review by briantang — DISMISSED** [review]

**Review by wooldridge — CHANGES_REQUESTED** [review]
@devinnicholson, looks like we've reverted to the older failing test? Updating the test file so that it has the changes here should fix:

https://github.com/devinnicholson/marklogic-data-hub/pull/1/files

Then squash and force-push.

**Review by wooldridge — CHANGES_REQUESTED** [review]

**Review by wooldridge — APPROVED** [review]

**Review by briantang — APPROVED** [review]

**Pull request merged**
