### PR TITLE
MLUI-134: mappings refactor and story

### PR DESCRIPTION
**Pull request by wooldridge**
Created mappings-ui shared component while refactoring the original mappings component.
Created story for the mappings-ui component.

### CODE REVIEW

**Comment by wooldridge** [comment]
@alexsmr, I've merged this PR branch with mlui-integration.

**Comment by alexsmr** [comment]
image
@wooldridge This test keeps failing due to the stuck model window. Can you please see deeper why e2e test cannot close it? It may be it is related to the refactoring we did.

**Comment by wooldridge** [comment]
@alexsmr, merged with latest from mlui-integration.

**Comment by alexsmr** [comment]
@wooldridge Mike can you fix the conflicts, please. Thanks.

**Pull request merged**
