### PR TITLE
DHFPROD-10486: BE:Handle Case When Mapping Context is Inapplicable

### PR DESCRIPTION
**Pull request by prolonMarkLogic**
#### Checklist: 
```diff
- Note: do not change the below
```

- ##### Owner:

- [x] JIRA_ID included in all the commit messages
- [x] PR title is in the format JIRA_ID:Title
- [x] Rebase the branch with upstream
- [x] Squashed all commits into a single commit
- [n/a] Added Tests
- [x] Ran newly added/edited cypress tests on Firefox locally
  

- ##### Reviewer:

- [x] Reviewed Tests
- [n/a] Added to Release Wiki

### CODE REVIEW

**Review by Sanjeevani19 — COMMENTED** [review]
@prolonMarkLogic I see that a couple of UI files have been modified; is this due to linting corrections?
Also, I note that the same error message is being duplicated in both the BE and UI files, referring to CONTEXT_URI_ERROR_MESSAGE. If the BE is already throwing an error, the UI can obtain that from the API, so why do we need to replicate the same message in two distinct files?

**Comment by prolonMarkLogic** [comment]
> @prolonMarkLogic I see that a couple of UI files have been modified; is this due to linting corrections? Also, I note that the same error message is being duplicated in both the BE and UI files, referring to CONTEXT_URI_ERROR_MESSAGE. If the BE is already throwing an error, the UI can obtain that from the API, so why do we need to replicate the same message in two distinct files?

Hello @Sanjeevani19, we made necessary changes to the UI to display different error scenarios in the tables, highlighting specific rows, but only when a specific error occurs. This involves comparing the error received from the backend in the FrontEnd, and the linter automatically adjusted various indentations.
image

**Review by briantang — CHANGES_REQUESTED** [review]
The updated error scenario and messaging looks good. But the changes to the table caused the dropdown menu to be hidden. In the screenshot, the "Map Related Entities" dropdown is open but you cannot see it anymore.

**Review by aniamy — APPROVED** [review]

**Review by briantang — APPROVED** [review]
Looks great now!

**Pull request merged**
