### PR TITLE
DHFPROD-8009: Modeling replacement

### PR DESCRIPTION
**Pull request by yubiselmarklogic**
#### Checklist: 
```diff
- Note: do not change the below
```

-  ##### Owner:

- [x] JIRA_ID included in all the commit messages
- [x] PR title is in the format JIRA_ID:Title
- [x] Rebase the branch with upstream
- [x] Squashed all commits into a single commit
- [x] Code passes ESLint tests
- [x] Added Tests
- [x] Run UI tests
  

- ##### Reviewer:

- [x] Reviewed Tests

### CODE REVIEW

**Review by iveyMarklogic — APPROVED** [review]

**Review by briantang — APPROVED** [review]

**Review by briantang — CHANGES_REQUESTED** [review]
@yubiselmarklogic This has merge conflicts. Also I am not seeing any text in the "Session Timeout" modal-status component. Can you check this? Not sure if it is due to your PR.

Screen Shot 2021-11-08 at 10 45 55 AM

**Comment by yubiselmarklogic** [comment]
@briantang I did the rebase and checked that message and now its working fine on my local, can you confirm that
image

**Review by MSBrignoni — APPROVED** [review]

**Review by iveyMarklogic — APPROVED** [review]

**Review by briantang — DISMISSED** [review]
Looks fixed now.

**Comment by briantang** [comment]
@yubiselmarklogic There may be one related e2e failure in writerScenario1.spec. It looks like that line that is failing can just be removed.

**Comment by yubiselmarklogic** [comment]
@briantang done

**Review by briantang — APPROVED** [review]

**Review by iveyMarklogic — APPROVED** [review]

**Pull request merged**
