### PR TITLE
WIP DHFPROD-2735: Porting changes from a feature branch to 5.x-develop: Need More Info for 5.x

### PR DESCRIPTION
**Pull request by bsrikan**

### CODE REVIEW

**Comment by bsrikan** [comment]
@aebadirad I have filed a bug DHFPROD-3069. This needs to be fixed for 2735 to get merged to any branch really. Not able to run a simple default mapping flow and get XDMP:CHILDNODEKIND error.

**Comment by SameeraPriyathamTadikonda** [comment]
Can we ignore these failures and merge?
https://jenkins.marklogic.com/blue/organizations/jenkins/Datahub_CI/detail/PR-2906/5/tests

**Comment by bsrikan** [comment]
I have reported a blocker bug for 2735. Have to wait till it is fixed.

**Comment by bsrikan** [comment]
Closing this as this is not required for 5.0.3

**Pull request closed without merging**
