### PR TITLE
DHFPROD-4856: Replacing usage of adminHubConfig

### PR DESCRIPTION
**Pull request by rjrudin**
#### Checklist: 
```diff
- Note: do not change the below
```

-  ##### Owner:

- [x] JIRA_ID included in all the commit messages
- [x] PR title is in the format JIRA_ID:Title
- [x] Rebase the branch with upstream
- [x] Squashed all commits into a single commit
- [x] Added Tests
  

- ##### Reviewer:

- [x] Reviewed Tests

### CODE REVIEW

**Review by akshaysonvane — APPROVED** [review]

**Comment by rjrudin** [comment]
Rebased

**Review by fsnow — DISMISSED** [review]

**Review by akshaysonvane — DISMISSED** [review]

**Review by srinathgit — APPROVED** [review]

**Comment by rjrudin** [comment]
Fixed compile errors, forgot to rebuild QS project

**Review by srinathgit — APPROVED** [review]

**Review by fsnow — DISMISSED** [review]

**Review by akshaysonvane — DISMISSED** [review]

**Review by anu3990 — DISMISSED** [review]

**Comment by rjrudin** [comment]
Rebased

**Review by fsnow — DISMISSED** [review]

**Review by akshaysonvane — DISMISSED** [review]

**Review by srinathgit — DISMISSED** [review]

**Comment by rjrudin** [comment]
Fixed test that depends on appConfig.cmaConfig.combineRequests being false, so modified that in HubTestBase.

**Review by akshaysonvane — DISMISSED** [review]

**Review by srinathgit — DISMISSED** [review]

**Comment by rjrudin** [comment]
Had to rebase again

**Review by bsrikan — APPROVED** [review]

**Review by akshaysonvane — APPROVED** [review]

**Pull request merged**
