### PR TITLE
DHFPROD-3108: Renamed new roles to data-hub-developer and data-hub-operator

### PR DESCRIPTION
**Pull request by rjrudin**
Used to be data-hub-app-admin and data-hub-user

### CODE REVIEW

**Comment by aebadirad** [comment]
We should probably rebase this so it passes tests

**Comment by rjrudin** [comment]
Rebased, though I'm 99.9% certain it has nothing to do with the failing FlowRunnerTest, as the roles that this impacts aren't actually being used anywhere yet.

**Comment by srinathgit** [comment]
I need this PR to be merged for DHFPROD-3617. There is a test (testRunFlow() – com.marklogic.hub.flow.FlowRunnerTest) that is failing. I will look into that

**Comment by srinathgit** [comment]
The tests are passing locally and the failure doesn't seem to be related to the changes in the PR. For now, I will work on develop rebased with this PR

**Comment by rjrudin** [comment]
@SameeraPriyathamTadikonda  Can we get this merged? I am confident the FlowRunnerTest failure is unrelated.

**Comment by SameeraPriyathamTadikonda** [comment]
Merging it manually as the test passes locally.

**Pull request merged**
