### PR TITLE
DHFPROD-2147: Redeploy button

### PR DESCRIPTION
**Pull request by wooldridge**
Make it work on Manage Flows page. Reuse deployService.redeployUserModules().

### CODE REVIEW

**Comment by wooldridge** [comment]
@ayuwono, are you able to test the functionality of this button? It hits the same endpoint as the Redeploy button on the old Flows page:

http://localhost:4200/#/flows-old

**Comment by ayuwono** [comment]
@wooldridge , I don't see anything going on the UI, but on the browser console I see:
Screen Shot 2019-04-15 at 7 41 58 PM

But, do you get this error on bootrun?
19:43:55.108 [SimpleAsyncTaskExecutor-4] ERROR o.s.a.i.SimpleAsyncUncaughtExceptionHandler - Unexpected exception occurred invoking async method: public void com.marklogic.hub.web.service.DataHubService.reinstallUserModules(com.marklogic.hub.HubConfig,com.marklogic.hub.web.listeners.DeployUserModulesListener,com.marklogic.hub.web.listeners.ValidateListener)
com.marklogic.hub.web.exception.DataHubException: Error in connecting to the Data Hub API with the following message: Local message: failed to apply resource at documents: Bad Request. Server Message: XDMP-CONFLICTINGUPDATES:

**Comment by wooldridge** [comment]
@ayuwono, thanks for testing. I don't see that error on bootrun, I'm just see this info after clicking the button:
```
2019-04-16 08:51:34.096  INFO 55197 --- [cTaskExecutor-2] c.m.h.d.commands.LoadUserModulesCommand  : Loading asset modules from dir: /Users/mwooldri/projects/marklogic-data-hub/examples/online-store/src/main/ml-modules
08:51:34.096 [SimpleAsyncTaskExecutor-2] INFO  c.m.h.d.c.LoadUserModulesCommand - Loading asset modules from dir: /Users/mwooldri/projects/marklogic-data-hub/examples/online-store/src/main/ml-modules
2019-04-16 08:51:34.100  INFO 55197 --- [cTaskExecutor-2] c.m.h.d.commands.LoadUserModulesCommand  : Loading all non-asset modules from dir: /Users/mwooldri/projects/marklogic-data-hub/examples/online-store/src/main/ml-modules
08:51:34.100 [SimpleAsyncTaskExecutor-2] INFO  c.m.h.d.c.LoadUserModulesCommand - Loading all non-asset modules from dir: /Users/mwooldri/projects/marklogic-data-hub/examples/online-store/src/main/ml-modules
2019-04-16 08:51:37.188  INFO 55197 --- [cTaskExecutor-2] c.marklogic.hub.util.PerformanceLogger   : PERFORMANCE: DataHubService.reinstallUserModules took 6.259367055s
08:51:37.188 [SimpleAsyncTaskExecutor-2] INFO  c.m.hub.util.PerformanceLogger - PERFORMANCE: DataHubService.reinstallUserModules took 6.259367055s
```

**Comment by ayuwono** [comment]
@wooldridge , I think it's because I have an existing entity?
Error in connecting to the Data Hub API with the following message: Local message: failed to apply resource at documents: Bad Request. Server Message: XDMP-CONFLICTINGUPDATES: xdmp:document-insert("/entities/Product.entity.json", document{object-node{"info":object-node{"title":text{"Product"}, "version":text{"..."}}, ...}}

Let me see with a clean install and new project

**Comment by aebadirad** [comment]
I wonder if this is in relation to having an existing 4.x entity and a new 5.x entity named the same, and we're deploying both, which we shouldn't be doing.

**Comment by ayuwono** [comment]
Okay, on clean install and new project directory, I don't get the error after redeploy. After creating an entity (on 5.x) and redeploy, there is no error either. I think I got that error because I had an entity created on 4.x.

**Comment by aebadirad** [comment]
This is fine to bring in, but tagging @ryanjdew about the dual 4.x/5.x deployment happening on 5.0

**Comment by ryanjdew** [comment]
@aebadirad @ayuwono The hubUpdate command moves the entities to the proper place. I'm not too concerned about the conflicting updates.

**Pull request merged**
