### PR TITLE
DHFPROD-4055: Fix rollback audit and merge blocks to work with new au…

### PR DESCRIPTION
**Pull request by ryanjdew**
…dit collections

### CODE REVIEW

**Comment by bsrikan** [comment]
Audit count is fixed, but blockFutureMerges still has issues.
Also after unmerge the original documents are getting the merged collection. This might be a cause for blockFutureMerges issue.

**Comment by ryanjdew** [comment]
Rebased and fixed the collections applied to documents when unmerged.

**Comment by bsrikan** [comment]
Rebased with latest develop and pushed gradle tests @ryanjdew

**Comment by SameeraPriyathamTadikonda** [comment]
Please rebase this PR. There are some conflicts.

**Pull request merged**
