### PR TITLE
DHFPROD-9259: Clean up Console Warnings - Notifications

### PR DESCRIPTION
**Pull request by senumulapally**
#### Checklist: 
```diff
- Note: do not change the below
```

- ##### Owner:

- [x] JIRA_ID included in all the commit messages
- [x] PR title is in the format JIRA_ID:Title
- [x] Rebase the branch with upstream
- [x] Squashed all commits into a single commit
- [x] Code passes ESLint tests
- [x] Ran cypress tests on firefox locally
  

- ##### Reviewer:

- [x] Reviewed Tests
- [x] Added to Release Wiki

### CODE REVIEW

**Review by littlecherro — CHANGES_REQUESTED** [review]
Hey, im still seeing red warnings when i open the notifications modal :( 

image
image
image

**Comment by amejiaq** [comment]
> Hey, im still seeing red warnings when i open the notifications modal :(
> 
> image image image

I believe those warnings are fixed in my warning tickets that are pending to merge

**Comment by littlecherro** [comment]
> > Hey, im still seeing red warnings when i open the notifications modal :(
> > image image image
> 
> I believe those warnings are fixed in my warning tickets that are pending to merge

@senumulapally 

@amejiaq I tested it on your open PRs branches, and the warnings are there too.

**Comment by senumulapally** [comment]
> your open PRs branches, and the warnings are there too.

@littlecherro I have fixed the issues and pushed the changes. @amejiaq I think it's better to keep the changes related to notifications-modal in this PR as this ticket is related to notifications.

**Review by briantang — APPROVED** [review]
Looks good!

**Comment by SameeraPriyathamTadikonda** [comment]
task list pending on this one

**Review by rahulvudutala — APPROVED** [review]

**Pull request merged**
