### PR TITLE
DHFPROD-1788 Bring in other models for uber model in trigger

### PR DESCRIPTION
**Pull request by ryanjdew**
Properly build uber model as part of the entity services trigger and remove an unused class from a previous approach I was exploring the TDE gradle command.

### CODE REVIEW

**Comment by bsrikan** [comment]
Verified the commits and they look good.

**Comment by aebadirad** [comment]
Give an approving review and we'll merge.

**Comment by aebadirad** [comment]
@ryanjdew can i get a rebase please?

**Comment by ryanjdew** [comment]
@aebadirad rebased

**Pull request merged**
