### PR TITLE
DHFPROD-2209: Fix to edit step dialog to render collection in dropdown

### PR DESCRIPTION
**Pull request by clockworked247**

### CODE REVIEW

**Comment by clockworked247** [comment]
build passes locally

**Comment by ayuwono** [comment]
@clockworked247 , just want to confirm if this will fix this issue: After creating a mapping step, then edit that mapping step, I can't see the options on source collection dropdown, hence the save button is disabled:

Screen Shot 2019-04-19 at 8 34 44 AM

**Comment by clockworked247** [comment]
@ayuwono I can't repro the problem.  See:  https://drive.google.com/file/d/1KXvTOgRMVSpsGlezovB3Cfk3lVqOnHyw/view

**Comment by clockworked247** [comment]
@wooldridge Good catch.  Fixed.

**Pull request merged**
