### PR TITLE
DHFPROD-7023: Retain state when navigating away and back to the Explo…

### PR DESCRIPTION
**Pull request by devinnicholson**
…re Tile

#### Checklist: 
```diff
- Note: do not change the below
```

-  ##### Owner:

- [x] JIRA_ID included in all the commit messages
- [x] PR title is in the format JIRA_ID:Title
- [x] Rebase the branch with upstream
- [x] Squashed all commits into a single commit
- [x] Code passes ESLint tests
- [x] Added Tests
  

- ##### Reviewer:

- [ ] Reviewed Tests

### CODE REVIEW

**Review by wooldridge — CHANGES_REQUESTED** [review]
@devinnicholson, not seeing search box text persisted in Explore, can we add that?

**Review by xnikhil08 — CHANGES_REQUESTED** [review]
Not sure if saving the currently applied facets is part of the story, but seems like something we should do. It's not happening currently.

**Review by Sanjeevani19 — CHANGES_REQUESTED** [review]
There are couple of issues I noticed on this PR
Query persistence 
1. Once the query is saved, the query should be highlighted in the dropdown with bold text
2. Edit the query and save it with new query name , it is not updated with latest name in the dropdown
3. Now shift between tiles, saved query is not persisted with facets
https://drive.google.com/file/d/1lwgzCki3xR7jZBFSNV3-ubFJ8wzSA9A_/view 


Clearing session and local storage
- If a user manually clears session and local storage and logs back in the explore screen keeps spinning without returning any results, this is highly unlikely but something that needs to be addressed
https://drive.google.com/file/d/1HBgaLfw7AXNImyraEpEcYQCEeUSx1T35/view

**Comment by devinnicholson** [comment]
> Not sure if saving the currently applied facets is part of the story, but seems like something we should do. It's not happening currently.

The reason the facet AC is crossed off in the PR is because there's a separate story (https://project.marklogic.com/jira/browse/DHFPROD-7363). This story is the foundation so I can find foundational bugs before building off it.

**Comment by devinnicholson** [comment]
> There are couple of issues I noticed on this PR
> Query persistence
> 
> 1. Once the query is saved, the query should be highlighted in the dropdown with bold text
> 2. Edit the query and save it with new query name , it is not updated with latest name in the dropdown
> 3. Now shift between tiles, saved query is not persisted with facets
>    https://drive.google.com/file/d/1lwgzCki3xR7jZBFSNV3-ubFJ8wzSA9A_/view
> 
> Clearing session and local storage
> 
> * If a user manually clears session and local storage and logs back in the explore screen keeps spinning without returning any results, this is highly unlikely but something that needs to be addressed
>   https://drive.google.com/file/d/1HBgaLfw7AXNImyraEpEcYQCEeUSx1T35/view

See above response in regards to facet persistence. Will fix the rest, thank you Sanjeevani.

**Comment by devinnicholson** [comment]
> @devinnicholson, not seeing search box text persisted in Explore, can we add that?

This addition was force pushed earlier, just so reviewers know to check that as well.

**Pull request closed without merging**
