### PR TITLE
DHFPROD-7950: Applying entity-specific facets

### PR DESCRIPTION
**Pull request by federicoRufrancosMarklogic**
### Description
This branch has also changes from the  story 7971. As I need them to complete the functionality, I brought those changes to here.

#### Checklist: 
```diff
- Note: do not change the below
```

-  ##### Owner:

- [X] JIRA_ID included in all the commit messages
- [X] PR title is in the format JIRA_ID:Title
- [X] Rebase the branch with upstream
- [X] Squashed all commits into a single commit
- [X] Code passes ESLint tests
- [X] Added Tests
- [X] Run UI tests
  

- ##### Reviewer:

- [ ] Reviewed Tests

### CODE REVIEW

**Review by Sanjeevani19 — COMMENTED** [review]
@federicoRufrancosMarklogic have a couple of conflicts on this PR, please rebase

**Comment by federicoRufrancosMarklogic** [comment]
@Sanjeevani19 conflicts resolved

**Review by xnikhil08 — CHANGES_REQUESTED** [review]
Clicking on an icon on the collapsed entity icon toolbar, once the entity specific sidebar is opened, navigates back to the HC homepage.
https://watch.screencastify.com/v/1CDASiXVNtyrgd5jqdQg

**Comment by federicoRufrancosMarklogic** [comment]
> Clicking on an icon on the collapsed entity icon toolbar, when the entity specific sidebar is opened, navigates back to the HC homepage. https://watch.screencastify.com/v/1CDASiXVNtyrgd5jqdQg

@xnikhil08 found the source of the bug!, pushed!

**Comment by xnikhil08** [comment]
Going back to the main panel, from entity specific side panel, updates the result set back to All entities, but the main panel still shows the selected base entity instead of All entities.
https://watch.screencastify.com/v/KKyQFmqtC8TqIWZ5bDCK

Also, the graph nodes becomes cluttered overlapping each other, which can be avoided by enabling the physics permanently for now.
At line 294 in graph-vis-explore.tsx component, just set **enabled: true**, under physics.

**Comment by xnikhil08** [comment]
> > Clicking on an icon on the collapsed entity icon toolbar, when the entity specific sidebar is opened, navigates back to the HC homepage. https://watch.screencastify.com/v/1CDASiXVNtyrgd5jqdQg
> 
> @xnikhil08 found the source of the bug!, pushed!

@federicoRufrancosMarklogic - Still seeing this.

**Comment by federicoRufrancosMarklogic** [comment]
@xnikhil08, could you check if you got Client on your model? Because of these entities are mocked, maybe you don't have client on your system and is causing this wrong redirection. Here is a video on my system how is working:
After Aniela's task is removed, will use the actual entities. I made some progress on data, Anile has my branch with the upgrade
https://watch.screencastify.com/v/5P7VvfPwhp7vMzR4tKMa

**Comment by federicoRufrancosMarklogic** [comment]
There is one particular test that still failing on Nightly.  
"Test '/Explore' left sidebar Searching text on related entities – Searching text on related entities"
On running it locally is going fine. What is suppose to to do is to open base entity select and pick Order entity. But seems that is not opening this select. With Camila improve the cypress getter to make click exactly over the arrow, but is not doing it.
image

**Review by Sanjeevani19 — COMMENTED** [review]
@csilva-ml Looks like there is a merge conflict, please rebase

**Comment by xnikhil08** [comment]
@csilva-ml - More merge conflicts here. Could you please rebase ?

**Comment by AkshayBajajML** [comment]
Changing it to draft for now.

**Pull request closed without merging**
