### PR TITLE
DHFPROD-7876: Default views for first-time user experience

### PR DESCRIPTION
**Pull request by AkshayBajajML**
#### Checklist: 
```diff
- Note: do not change the below
```

-  ##### Owner:

- [x] JIRA_ID included in all the commit messages
- [x] PR title is in the format JIRA_ID:Title
- [x] Rebase the branch with upstream
- [x] Squashed all commits into a single commit
- [x] Code passes ESLint tests
- [x] Added Tests  

- ##### Reviewer:

- [ ] Reviewed Tests
- [x] Added to Release Wiki

### CODE REVIEW

**Comment by AkshayBajajML** [comment]
Made updates to 5.7 release wiki

**Review by briantang — DISMISSED** [review]
1) Default view with instances in final - sidebar + view defaults me to final instances
2) Deleted entity instances in final - sidebar + view defaults me to staging instances
3) Deleted entity instances in staging - sidebar + view defaults me to All Data documents

**Review by xnikhil08 — APPROVED** [review]

**Comment by aniamy** [comment]
@xnikhil08 For this A/C
(Given) No entity instances exist (just raw data),
(Then) by default, the Card view is selected, the All Data toggle is selected, and the final toggle is selected.

In the scenario were I only used the load step the A/C is happening. I see "All data" and "Final". But since my data is in staging shouldn't it also check this case and automatically should Staging?
For a second I did not understand why my load step data wasn't showing.

**Comment by aniamy** [comment]
(And given) given they exist in the staging database
Pre-setting the data:
1. I loaded data.
2. I ran the Map step with target database Staging.
3. I logged out and cleaned my local storage
First time I logging as a first time experience:
1 logged in as a first time experience and went to explore.
2. Entities is selected. Final is selected but switches to Staging.
3. No data is shown.
Expected: Data from pre-setting should be shown.
Graph search call seems ok but backend is returning no data (To check if the issue is payload or backend)
There is no search call pointing to staging so when I switch to table/snippet view I see no data. (What was gotten from the final call probably)

If I stay in table view, move to another tile and come back, it looks like it tries to show data, but doesn't look good.

**Review by briantang — DISMISSED** [review]
Just pushed a conflict resolution for @AkshayBajajML. Tests passed on latest run, PR should be good to go now.

**Review by xnikhil08 — APPROVED** [review]

**Review by aniamy — DISMISSED** [review]

**Pull request closed without merging**
