### PR TITLE
DHFPROD-6383: Make applying facets in explorer more clear

### PR DESCRIPTION
**Pull request by timur-isangulov**
#### Checklist: 
```diff
- Note: do not change the below
```

-  ##### Owner:

- [x] JIRA_ID included in all the commit messages
- [x] PR title is in the format JIRA_ID:Title
- [x] Rebase the branch with upstream
- [x] Squashed all commits into a single commit
- [x] Code passes ESLint tests
- [x] Added Tests
  

- ##### Reviewer:

- [x] Reviewed Tests

### CODE REVIEW

**Review by wooldridge — CHANGES_REQUESTED** [review]
@timur-isangulov, as part of this PR could we update the CSS for the existing small apply/clear icons so that the pointer appears on mouseover (so they are consistent with other clickable icons)?
```
cursor: pointer;
```
Screen Shot 2021-01-19 at 11 32 04 AM

**Comment by timur-isangulov** [comment]
> @timur-isangulov, as part of this PR could we update the CSS for the existing small apply/clear icons so that the pointer appears on mouseover (so they are consistent with other clickable icons)?
> 
> ```
> cursor: pointer;
> ```
> 
> Screen Shot 2021-01-19 at 11 32 04 AM

Hi @wooldridge, thanks for reviewing, I added css changes.

**Review by wooldridge — APPROVED** [review]
Functionality and tests look good!

**Review by xnikhil08 — APPROVED** [review]
looks good.

**Pull request merged**
