### PR TITLE
DHFPROD-5711: Explore: Make Explore Results Area Keyboard Accessible

### PR DESCRIPTION
**Pull request by iveyMarklogic**
#### Checklist: 
```diff
- Note: do not change the below
```

- ##### Owner:

- [x] JIRA_ID included in all the commit messages
- [x] PR title is in the format JIRA_ID:Title
- [x] Rebase the branch with upstream
- [x] Squashed all commits into a single commit
- [x] Added Tests
- [x] Ran cypress tests on firefox locally
  

- ##### Reviewer:

- [x] Reviewed Tests
- [n/a] Added to Release Wiki

### CODE REVIEW

**Review by littlecherro — CHANGES_REQUESTED** [review]
Im unable to reach the merge button 

image

**Review by littlecherro — CHANGES_REQUESTED** [review]
this one too :(

image

**Comment by iveyMarklogic** [comment]
@littlecherro  The first comment was solved but the second one is a popover. @briantang  can we add this popover as part of the popovers ticket?

**Comment by briantang** [comment]
Correct, second one will be handled in the popovers ticket next sprint.

**Review by littlecherro — APPROVED** [review]

**Comment by briantang** [comment]
Screenshot 2023-01-25 at 9 26 57 AM

I can select the arrow using ENTER but not SPACE. Typically we allow both right?

Screenshot 2023-01-25 at 9 27 42 AM

For the row chevron, I can expand it with SPACE, but it also scrolls down the page. I have solved this in other tickets by using event.preventDefault(). Can we try that here?

**Review by MSBrignoni — APPROVED** [review]

**Pull request merged**
