### PR TITLE
DHFPROD-9775: Fix Git Security Vulnerabilities Group 5

### PR DESCRIPTION
**Pull request by MSBrignoni**
### Description
Fix Git Security Vulnerabilities Group 5. Change in package.json and package.lock.json.

#### Checklist: 
```diff
- Note: do not change the below
```

- ##### Owner:

- [x] JIRA_ID included in all the commit messages
- [x] PR title is in the format JIRA_ID:Title
- [x] Rebase the branch with upstream
- [x] Squashed all commits into a single commit
- [x] Added Tests
- [x] Ran cypress tests on firefox locally
  

- ##### Reviewer:

- [x] Reviewed Tests
- N/A Added to Release Wiki

### CODE REVIEW

**Comment by briantang** [comment]
Closing for now to revisit with https://project.marklogic.com/jira/browse/DHFPROD-9804

**Comment by briantang** [comment]
Latest changes are not running tests with the failure "/lib64/libstdc++.so.6: version `CXXABI_1.3.9' not found" due to needing GCC version 5.1.

See here: https://unix.stackexchange.com/a/726257

@SameeraPriyathamTadikonda is this something you can help with?

**Comment by SameeraPriyathamTadikonda** [comment]
Sure, let me try this out on one machine before we upgrade on all the machines. we need to make sure Marklogic server runs after the upgrade. Can we push this to a branch in the main repo. So, I could run using jenkins.

**Comment by briantang** [comment]
All tests passing now

**Review by littlecherro — APPROVED** [review]

**Review by briantang — APPROVED** [review]
Confirmed with @MSBrignoni that this looks good to be approved.

**Pull request merged**
