### PR TITLE
DHFPROD-9050: Additional matching performance updates

### PR DESCRIPTION
**Pull request by ryanjdew**
#### Checklist: 
```diff
- Note: do not change the below
```

- ##### Owner:

- [x] JIRA_ID included in all the commit messages
- [x] PR title is in the format JIRA_ID:Title
- [x] Rebase the branch with upstream
- [x] Squashed all commits into a single commit
- [x] Code passes ESLint tests
- [x] Added Tests
- N/A Ran cypress tests on firefox locally
  

- ##### Reviewer:

- [x] Reviewed Tests
- N/A Added to Release Wiki

### CODE REVIEW

**Review by Sanjeevani19 — COMMENTED** [review]
@ryanjdew Just trying to understand the changes in this PR, have a couple of questions related to that
1. What kind of performance improvements are we targeting with these code changes ? 
2. Do we anticipate any regressions that will need to be addressed after this PR is merged? ? cc @ngodugu-marklogic

**Comment by ryanjdew** [comment]
@Sanjeevani19 We're primarily targeting matching to be more inline with the XQuery version in terms of performance. There are a few low-impact performance changes to Java code in the PR as well that we flagged by Coverity.

I don't anticipate any regressions that will impact manual testing that we've done up to this point.

**Review by Sanjeevani19 — COMMENTED** [review]
@ryanjdew looks like a couple of core tests are failing http://jenkins1.marklogic.com/blue/organizations/jenkins/Datahub_CI/detail/PR-7326/1/tests, please look into it

**Review by Sanjeevani19 — COMMENTED** [review]
@ryanjdew  testMatchNotifications core test is failing on latest run http://jenkins1.marklogic.com/blue/organizations/jenkins/Datahub_CI/detail/PR-7326/15/tests, Please look into it

**Review by rahulvudutala — APPROVED** [review]

**Review by prolonMarkLogic — APPROVED** [review]

**Comment by ngodugu-marklogic** [comment]
@ryanjdew mergeNotification.spec.tsx and runFlow.spec.tsx seem to be related. There is an extra merge notification coming up when I run only two steps. Please find the video recording. And in runFlow there is a mismatch in the records, it is showing only record instead of two. Please refer the screenshots


Uploading Screen Recording 2022-11-04 at 11.31.25 AM.mov…

**Review by prolonMarkLogic — APPROVED** [review]

**Review by rahulvudutala — DISMISSED** [review]

**Comment by ryanjdew** [comment]
Addressed a fix that was applied to the JavaScript version of the synonym function but was missing in the XQuery version. That should resolve the e2e tests.

**Review by Sanjeevani19 — COMMENTED** [review]
@ryanjdew Looks like e2e tests are still failing on this PR http://jenkins1.marklogic.com/blue/organizations/jenkins/Datahub_CI/detail/PR-7326/23/tests, Could you please look into it ?

**Review by rahulvudutala — APPROVED** [review]

**Review by prolonMarkLogic — APPROVED** [review]

**Review by rahulvudutala — APPROVED** [review]

**Comment by ngodugu-marklogic** [comment]
The E2E tests look intermittent. We can merge this PR @Sanjeevani19

**Pull request merged**
