### PR TITLE
DHFPROD-4522:Cleanup/dhfprod 4522

### PR DESCRIPTION
**Pull request by bsrikan**
With this PR, trying to cleanup how tests are run for explorer.
1. Deleted hub project files. We will now be running a setup.sh script which will initialize a hub project to 5.3-SNAPSHOT, create indexes, deploy and then run flows via gradle. 
2. Changed the Cypress explorer tests to run on 8080. Its ok to run on 3000 during development, but in CI we should run it on 8080. Although, I understand from @SameeraPriyathamTadikonda  that we run these tests on docker, which runs the tests on 8443 an https port
3. cypress:run script now includes npm install, so we wont have to separately run npm install locally or in jenkins pipeline script
4. Brought in jest-junit reporters from explorer-ui . Updated the output report to be in a format that pipeline scripts can pick up and show in Jenkins
5. Changed a test title so it matches what is being tested. There are some e2e test failures. @timur-isangulov  hoping you can checkout changes in this PR and fix the failing tests
6. Moved the setup and teardown shell scripts under e2e from qa-project. Updated teardown script to use mladmin cleandata which runs much faster than mlUndeploy
7. Finally, upgraded Cypress version to 4.2.0

### CODE REVIEW

**Comment by bsrikan** [comment]
Changes in this PR would work for tests in Jenkins. For running locally, you would have to follow along in this order:

1. cd ~/one-ui
2. ./gradlew build -x test //This is required to build the war file
3. ./gradlew bootRun //This is required to bring the app up on 8080
4. In another terminal, cd ~/one-ui/ui/e2e
5. sh setup.sh //This will initialize a 5.3 DH, save the indexes configured in the entities, run mlDeploy as admin followed by running the flows as admin
6. npm run cypress:run // This will run npm install and run Cypress tests in a headless mode


To bring up QS, build it and run it on a port other than 8080.
Select qa-project, create flows/steps based on your test scenario to search on them in View/Browse screens
If you are adding a new test data to input directory make sure you create a new input.zip to include your test data. We have a gradle task to extract the zip in this project, so we dont have to commit input folder. Zip should do.

Pls let me know if you run into issues.

**Comment by timur-isangulov** [comment]
Pushed the fix. 
Screen Shot 2020-03-20 at 12 49 11 PM

**Comment by SameeraPriyathamTadikonda** [comment]
I saw two tests failing on Jenkins. Are those fixed?
https://jenkins.marklogic.com/blue/organizations/jenkins/Datahub_CI/detail/PR-3733/4/tests

**Comment by bsrikan** [comment]
This PR has duplicate commits. Will close and create a new one.

**Pull request closed without merging**
