### PR TITLE
DHFPROD-5727: Fixing the bug where 400 error occurs on refreshing the Detail page in Explore tile

### PR DESCRIPTION
**Pull request by xnikhil08**
### Description
This PR fixes the bug 5727 and involves few more enhancements to the explorer UI code. e2e test is added.

#### Checklist: 
```diff
- Note: do not change the below
```

-  ##### Owner:

- [x] JIRA_ID included in all the commit messages
- [x] PR title is in the format JIRA_ID:Title
- [x] Rebase the branch with upstream
- [x] Squashed all commits into a single commit
- [x] Added Tests
  

- ##### Reviewer:

- [x] Reviewed Tests

### CODE REVIEW

**Comment by xnikhil08** [comment]
> @xnikhil08 One e2e test fails in json scenario for table on browse documents page in scenarios.json file and the test is related to page reload (verify source view of the document is the name of the test suite)

@Sanjeevani19 - All e2e tests passed in the pipeline and my local. Can you confirm again?

**Comment by Sanjeevani19** [comment]
> > @xnikhil08 One e2e test fails in json scenario for table on browse documents page in scenarios.json file and the test is related to page reload (verify source view of the document is the name of the test suite)
> 
> @Sanjeevani19 - All e2e tests passed in the pipeline and my local. Can you confirm again?

@xnikhil08 https://jenkins.marklogic.com/blue/organizations/jenkins/Datahub_CI/detail/PR-4489/4/tests , In the tests tab it shows a failure

**Comment by xnikhil08** [comment]
> > > @xnikhil08 One e2e test fails in json scenario for table on browse documents page in scenarios.json file and the test is related to page reload (verify source view of the document is the name of the test suite)
> > 
> > 
> > @Sanjeevani19 - All e2e tests passed in the pipeline and my local. Can you confirm again?
> 
> @xnikhil08 https://jenkins.marklogic.com/blue/organizations/jenkins/Datahub_CI/detail/PR-4489/4/tests , In the tests tab it shows a failure

@Sanjeevani19 - Can you check again? It should work now.

**Comment by Sanjeevani19** [comment]
> > > > @xnikhil08 One e2e test fails in json scenario for table on browse documents page in scenarios.json file and the test is related to page reload (verify source view of the document is the name of the test suite)
> > > 
> > > 
> > > @Sanjeevani19 - All e2e tests passed in the pipeline and my local. Can you confirm again?
> > 
> > 
> > @xnikhil08 https://jenkins.marklogic.com/blue/organizations/jenkins/Datahub_CI/detail/PR-4489/4/tests , In the tests tab it shows a failure
> 
> @Sanjeevani19 - Can you check again? It should work now.

@xnikhil08 The test still seems to fail in the pipeline (https://jenkins.marklogic.com/blue/organizations/jenkins/Datahub_CI/detail/PR-4489/6/tests)

**Comment by xnikhil08** [comment]
> > > > > @xnikhil08 One e2e test fails in json scenario for table on browse documents page in scenarios.json file and the test is related to page reload (verify source view of the document is the name of the test suite)
> > > > 
> > > > 
> > > > @Sanjeevani19 - All e2e tests passed in the pipeline and my local. Can you confirm again?
> > > 
> > > 
> > > @xnikhil08 https://jenkins.marklogic.com/blue/organizations/jenkins/Datahub_CI/detail/PR-4489/4/tests , In the tests tab it shows a failure
> > 
> > 
> > @Sanjeevani19 - Can you check again? It should work now.
> 
> @xnikhil08 The test still seems to fail in the pipeline (https://jenkins.marklogic.com/blue/organizations/jenkins/Datahub_CI/detail/PR-4489/6/tests)

@Sanjeevani19 @brucean52 @bsrikan - I pushed a fix for those e2e tests, including mapping and modeling. Can you review again?

**Pull request merged**
