### PR TITLE
DHFPROD-1870: manage flow connected to the backend

### PR DESCRIPTION
**Pull request by alexsmr**
- manage flow connected to the backend
- pulled Mike's changes
- style fixes for the table, added links, etc.

### CODE REVIEW

**Comment by alexsmr** [comment]
@wooldridge pushed the changes along with the name refactorings, please review. Sasha.

**Comment by wooldridge** [comment]
I also made a component to display the color icons beneath the flow names:

step-icons

They changes are in the following commit:

https://github.com/wooldridge/marklogic-data-hub/commit/f1801c0de3d52564e3320f966de80da6e769da15

Can we add those or should I add those as a separate PR (that wouldn't be a problem)?

**Comment by wooldridge** [comment]
@alexsmr, I will merge this PR and add the color icons as a separate PR.

**Comment by wooldridge** [comment]
@alexsmr, looking good! Some comments:

- Arrange and label the buttons as specified in the wireframes here:

https://wiki.marklogic.com/display/ENGINEERING/Flow+UI+Design?preview=/102766514/102441533/Manage%20Flows%20v6%20(New%20Flow%20dialog%20open).png#FlowUIDesign-PageFlowDiagram

- The Description field is optional needs to be labeled that way.

- The dialog header/title area as it stands has a lot of padding and we'll want to settle on something more compact for all the dialog boxes. This worked for me in flow-settings-dialog.component.scss:

h1.mat-dialog-title {
  margin-top: -12px;
  margin-left: -4px;
  margin-bottom: 11px;
}

div.mat-dialog-content {
  padding: 10px 15px 20px 20px;
}

(We should figure out a way to set styles for those Material dialogs globally because we'll be using them a ton.)

- Batch Size has a default value of 100.

- Thread Count has a default value of 4. 

Default values and other information are here:

https://wiki.marklogic.com/display/ENGINEERING/Flow+UI+Design#FlowUIDesign-UIWireframes

**Pull request merged**
