### PR TITLE
DHFPROD-4863: fixed styling of saved query dropdown in explore

### PR DESCRIPTION
**Pull request by jyangML**
### Description
~The value prop is redundant (already covered by checkCurrentQueryChange) and is blocking the correct placeholder color from showing.~
#### Checklist: 
```diff
- Note: do not change the below
```

-  ##### Owner:

- [X] JIRA_ID included in all the commit messages
- [X] PR title is in the format JIRA_ID:Title
- [X] Rebase the branch with upstream
- [X] Squashed all commits into a single commit
- [X] Code passes ESLint tests

[NA] Added Tests
  

- ##### Reviewer:

[NA] Reviewed Tests

### CODE REVIEW

**Review by Sanjeevani19 — COMMENTED** [review]
@jyangML The expected functionality should be - When ever a query is saved or edited the query name should appear in the dropdown, https://drive.google.com/file/d/1oosh25_qd96tlTboButbS8uI7SabpigD/view,
@timur-isangulov correct me if I am wrong

**Comment by jyangML** [comment]
> 
> 
> @jyangML The expected functionality should be - When ever a query is saved or edited the query name should appear in the dropdown, https://drive.google.com/file/d/1oosh25_qd96tlTboButbS8uI7SabpigD/view,
> @timur-isangulov correct me if I am wrong

I reverted the old behavior.  Unfortunately, with how it's done, the styling code is going to be tacky.  The value prop overrides all placeholder styling, so it's going to have to be this

**Comment by Sanjeevani19** [comment]
> > @jyangML The expected functionality should be - When ever a query is saved or edited the query name should appear in the dropdown, https://drive.google.com/file/d/1oosh25_qd96tlTboButbS8uI7SabpigD/view,
> > @timur-isangulov correct me if I am wrong
> 
> I reverted the old behavior. Unfortunately, with how it's done, the styling code is going to be tacky. The value prop overrides all placeholder styling, so it's going to have to be this

@jyangML Please discuss this with Marilyn once, it shouldn't disturb the current functionality, I believe the e2e tests should also be modified if it has to be implemented like this

**Review by Sanjeevani19 — CHANGES_REQUESTED** [review]
@jyangML Please discuss this with Marilyn once, it shouldn't disturb the current functionality, I believe the e2e tests should also be modified if it has to be implemented like this, https://jenkins.marklogic.com/blue/organizations/jenkins/Datahub_CI/detail/PR-5531/1/tests

@jyangML Please confirm with Marilyn before fixing any tests, the tests are working as expected with the functionality requested before

**Comment by jyangML** [comment]
e2e failures look like intermittent failures.  They passed when I ran them locally.  The one rtl unit test that failed is also "intermittent"?  It passes on my local system as well.

**Comment by jyangML** [comment]
> 
> 
> @jyangML Please discuss this with Marilyn once, it shouldn't disturb the current functionality, I believe the e2e tests should also be modified if it has to be implemented like this, https://jenkins.marklogic.com/blue/organizations/jenkins/Datahub_CI/detail/PR-5531/1/tests
> 
> Please confirm with Marilyn before fixing any tests, the tests are working as expected with the functionality requested before

There were no functional changes to the UI.  Everything is styling/visuals only.

**Review by Sanjeevani19 — COMMENTED** [review]
@jyangML Looks good works as expected, just a small design enhancement as mentioned in the story when a query is selected these are the styles which should be applied
 Heading 2 (20px, #333333)

**Review by Sanjeevani19 — DISMISSED** [review]

**Comment by jyangML** [comment]
Confirmed with Marilyn.  Changes needed:

- remove the border of the select dropdown box
- horizontally align the query icons (save, discard, etc)
- reduce the spacing between the dropdown and the icons to 8px (preferred) or 16px

**Comment by jyangML** [comment]
Fixed up some comments in css files

**Review by briantang — CHANGES_REQUESTED** [review]
Seeing a couple linting errors. Can you run the fix on that? Should be straightforward indentation/spacing ones.

**Review by briantang — APPROVED** [review]

**Review by timur-isangulov — APPROVED** [review]

**Pull request merged**
