### PR TITLE
DHFPROD-4320: Show possible match combinations based on configuration

### PR DESCRIPTION
**Pull request by xnikhil08**
### Description
Adding possible match combinations for match step details page.

#### Checklist: 
```diff
- Note: do not change the below
```

-  ##### Owner:

- [x] JIRA_ID included in all the commit messages
- [x] PR title is in the format JIRA_ID:Title
- [x] Rebase the branch with upstream
- [x] Squashed all commits into a single commit
- [x] Added Tests
  

- ##### Reviewer:

- [x] Reviewed Tests

### CODE REVIEW

**Review by ryanjdew — APPROVED** [review]

**Comment by ryanjdew** [comment]
@xnikhil08 It looks like there is an e2e failure on adding a matching ruleset. https://jenkins.marklogic.com/blue/organizations/jenkins/Datahub_CI/detail/PR-4914/4/tests

**Comment by xnikhil08** [comment]
> @xnikhil08 It looks like there is an e2e failure on adding a matching ruleset. https://jenkins.marklogic.com/blue/organizations/jenkins/Datahub_CI/detail/PR-4914/4/tests

@ryanjdew -Fixed the failing test. Please review now.

**Review by Sanjeevani19 — COMMENTED** [review]
@xnikhil08 The possible match combinations window doesn't show the merge type along with the property name but the UI designs indicate that, Any design changes ?
Screen Shot 2020-11-30 at 6 20 33 PM

**Comment by xnikhil08** [comment]
> @xnikhil08 The possible match combinations window doesn't show the merge type along with the property name but the UI designs indicate that, Any design changes ?
> Screen Shot 2020-11-30 at 6 20 33 PM

@Sanjeevani19 - Can you review again ?

**Review by Sanjeevani19 — APPROVED** [review]

**Review by Sanjeevani19 — COMMENTED** [review]
@xnikhil08 looks like there is a merge conflict, Please resolve them

**Review by Sanjeevani19 — APPROVED** [review]

**Review by Sanjeevani19 — COMMENTED** [review]
@xnikhil08 Looks like there is one e2e failure related to matching

**Review by brucean52 — CHANGES_REQUESTED** [review]
an e2e test is consistently failing on the pipeline. Please look into it @xnikhil08

**Comment by xnikhil08** [comment]
@ryanjdew @brucean52 @Sanjeevani19 - Created another story (https://project.marklogic.com/jira/browse/DHFPROD-6312)to take care of the multi-slider component e2e issue to avoid keeping this PR from getting merged.

**Review by Sanjeevani19 — APPROVED** [review]

**Review by brucean52 — APPROVED** [review]

**Pull request merged**
